import test from 'node:test';
import assert from 'node:assert/strict';
import { simulate, javaHash, bucketIndex } from '../src/models.js';

test('Java string hash matches String.hashCode', () => {
  assert.equal(javaHash('hello'), 99162322);
  assert.equal(javaHash(''), 0);
  assert.equal(javaHash('Aa'), javaHash('BB'));
});
test('HashMap spreads the high bits and uses a power-of-two mask', () => {
  assert.equal(bucketIndex('hello', 16), 11);
});
test('Redis cache-aside gets repeated keys from cache', () => {
  const run = simulate('redis', { capacity: 3, requests: 6, cache: true, key: 'user:1001' });
  assert.equal(run.at(-1)?.metrics.hits, 3);
  assert.equal(run.at(-1)?.metrics.misses, 3);
});
test('Disabled cache always queries the database', () => {
  const run = simulate('redis', { capacity: 3, requests: 6, cache: false, key: 'user:1001' });
  assert.equal(run.at(-1)?.metrics.hits, 0);
  assert.equal(run.at(-1)?.metrics.misses, 6);
});
test('LRU eviction changes the hit rate', () => {
  assert.ok(simulate('redis', { capacity: 1, requests: 6, cache: true, key: 'k' }).at(-1)?.metrics.hits < 3);
});
test('ThreadPoolExecutor admits core workers, queue, max workers, then rejects', () => {
  const end = simulate('threadpool', { core: 2, max: 4, queue: 2, tasks: 8, policy: 'abort' }).at(-1);
  assert.equal(end?.metrics.workers, 4);
  assert.equal(end?.metrics.queued, 2);
  assert.equal(end?.metrics.rejected, 2);
});
test('CallerRunsPolicy does not count caller tasks as rejected', () => {
  const end = simulate('threadpool', { core: 1, max: 2, queue: 1, tasks: 5, policy: 'caller' }).at(-1);
  assert.equal(end?.metrics.caller, 2);
  assert.equal(end?.metrics.rejected, 0);
});
test('HashMap doubles capacity only when size exceeds threshold', () => {
  const run = simulate('hashmap', { capacity: 4, factor: 0.75, entries: 4 });
  assert.equal(run.at(-1)?.metrics.capacity, 8);
  assert.equal(run.at(-1)?.metrics.size, 4);
});
test('Kafka assigns each partition to exactly one active group consumer', () => {
  const end = simulate('kafka', { partitions: 3, consumers: 5, messages: 8 }).at(-1);
  assert.deepEqual(end?.assignments, [0, 1, 2]);
  assert.equal(end?.metrics.idle, 2);
  assert.equal(end?.metrics.consumed, 8);
});
test('MySQL indexed and full scans find the same row with different reads', () => {
  const index = simulate('mysql', { indexed: true, target: 42 }).at(-1);
  const scan = simulate('mysql', { indexed: false, target: 42 }).at(-1);
  assert.equal(index?.metrics.found, true);
  assert.equal(scan?.metrics.found, true);
  assert.ok(index?.metrics.reads < scan?.metrics.reads);
});
test('JVM generational model reclaims unreachable allocations', () => {
  const end = simulate('jvm', { eden: 4, allocations: 10, survival: 50 }).at(-1);
  assert.ok(end?.metrics.collections >= 2);
  assert.ok(end?.metrics.reclaimed > 0);
});
test('Unknown lab fails explicitly', () => {
  assert.throws(() => simulate('missing', {}), /Unknown lab/);
});
test('Every Redis frame reports a rate consistent with its displayed counts', () => {
  for (const frame of simulate('redis', { capacity: 3, requests: 6, cache: true, key: 'k' })) {
    const m = frame.metrics;
    assert.equal(m.rate, m.requests ? Math.round(m.hits / m.requests * 100) : 0);
  }
});
test('Kafka commits the next offset per partition and activates the offset node', () => {
  const run = simulate('kafka', { partitions: 3, consumers: 2, messages: 8 });
  assert.deepEqual(run.at(-1).offsets, [3, 3, 2]);
  assert.equal(run.at(-1).active, 'offset');
  assert.equal(run.filter(frame => frame.active === 'offset').length, 8);
});
test('Kafka ISR: acks=1 confirms on leader append and loses the un-replicated message on crash', () => {
  const end = simulate('kafka-replication', { acks: '1', replicas: 3, minIsr: 2, messages: 5, crashAfter: 3 }).at(-1);
  assert.equal(end?.metrics.sent, 5);
  assert.equal(end?.metrics.confirmed, 5);
  assert.equal(end?.metrics.lost, 1);
  assert.equal(end?.metrics.rejected, 0);
});
test('Kafka ISR: acks=all confirms only replicated messages and loses nothing on crash', () => {
  const end = simulate('kafka-replication', { acks: 'all', replicas: 3, minIsr: 2, messages: 5, crashAfter: 3 }).at(-1);
  assert.equal(end?.metrics.sent, 5);
  assert.equal(end?.metrics.confirmed, 4);
  assert.equal(end?.metrics.lost, 0);
  assert.equal(end?.metrics.rejected, 0);
});
test('Kafka ISR: ISR below min.insync.replicas rejects acks=all writes after crash', () => {
  const end = simulate('kafka-replication', { acks: 'all', replicas: 3, minIsr: 3, messages: 5, crashAfter: 3 }).at(-1);
  assert.equal(end?.metrics.sent, 3);
  assert.equal(end?.metrics.confirmed, 2);
  assert.equal(end?.metrics.rejected, 2);
  assert.equal(end?.metrics.lost, 0);
});
test('Kafka ISR: single-broker partition loses all writes and rejects the rest after crash', () => {
  const end = simulate('kafka-replication', { acks: '1', replicas: 1, minIsr: 1, messages: 5, crashAfter: 3 }).at(-1);
  assert.equal(end?.metrics.lost, 3);
  assert.equal(end?.metrics.rejected, 2);
  assert.equal(end?.isr.length, 0);
});
test('MySQL isolation: READ UNCOMMITTED sees dirty reads, non-repeatable reads and phantoms', () => {
  const end = simulate('mysql-isolation', { isolation: 'uncommitted' }).at(-1);
  assert.equal(end?.metrics.dirty, 1);
  assert.equal(end?.metrics.nonRepeatable, 1);
  assert.equal(end?.metrics.phantom, 1);
  assert.equal(end?.metrics.blocked, 0);
});
test('MySQL isolation: READ COMMITTED drops dirty reads but keeps non-repeatable reads and phantoms', () => {
  const end = simulate('mysql-isolation', { isolation: 'committed' }).at(-1);
  assert.equal(end?.metrics.dirty, 0);
  assert.equal(end?.metrics.nonRepeatable, 1);
  assert.equal(end?.metrics.phantom, 1);
  assert.equal(end?.metrics.blocked, 0);
});
test('MySQL isolation: REPEATABLE READ reuses one snapshot and blocks all three anomalies', () => {
  const end = simulate('mysql-isolation', { isolation: 'repeatable' }).at(-1);
  assert.equal(end?.metrics.dirty, 0);
  assert.equal(end?.metrics.nonRepeatable, 0);
  assert.equal(end?.metrics.phantom, 0);
  assert.equal(end?.metrics.blocked, 0);
  assert.equal(end?.items.txB.row, 100);
  assert.equal(end?.items.txB.count, 2);
});
test('MySQL isolation: SERIALIZABLE blocks the concurrent insert instead of phantom reads', () => {
  const end = simulate('mysql-isolation', { isolation: 'serializable' }).at(-1);
  assert.equal(end?.metrics.dirty, 0);
  assert.equal(end?.metrics.nonRepeatable, 0);
  assert.equal(end?.metrics.phantom, 0);
  assert.equal(end?.metrics.blocked, 1);
  assert.equal(end?.items.txC, 'COMMITTED');
  assert.equal(end?.items.table.committed, 3);
});
test('MySQL isolation: B reads the committed value under READ COMMITTED after A commits', () => {
  const run = simulate('mysql-isolation', { isolation: 'committed' });
  assert.equal(run.find(f => f.message.includes('不可重复读'))?.metrics.nonRepeatable, 1);
  assert.equal(run.at(-2)?.items.txB.row, 500);
});
test('RabbitMQ DIRECT routes only exact binding keys and drops the rest', () => {
  const end = simulate('rabbitmq-exchange', { exchange: 'direct' }).at(-1);
  assert.deepEqual(end?.items.q1, ['m1']);
  assert.deepEqual(end?.items.q2, ['m3']);
  assert.deepEqual(end?.items.void, ['m2', 'm4', 'm5']);
  assert.equal(end?.metrics.q1, 1);
  assert.equal(end?.metrics.q2, 1);
  assert.equal(end?.metrics.dropped, 3);
  assert.equal(end?.metrics.total, 2);
});
test('RabbitMQ TOPIC matches orders.* to QueueA and *.login to QueueB', () => {
  const end = simulate('rabbitmq-exchange', { exchange: 'topic' }).at(-1);
  assert.deepEqual(end?.items.q1, ['m1', 'm2']);
  assert.deepEqual(end?.items.q2, ['m3']);
  assert.deepEqual(end?.items.void, ['m4', 'm5']);
  assert.equal(end?.metrics.q1, 2);
  assert.equal(end?.metrics.q2, 1);
  assert.equal(end?.metrics.dropped, 2);
  assert.equal(end?.metrics.total, 3);
});
test('RabbitMQ FANOUT broadcasts every message to all bound queues ignoring keys', () => {
  const end = simulate('rabbitmq-exchange', { exchange: 'fanout' }).at(-1);
  assert.equal(end?.items.q1.length, 5);
  assert.equal(end?.items.q2.length, 5);
  assert.equal(end?.items.void.length, 0);
  assert.equal(end?.metrics.dropped, 0);
  assert.equal(end?.metrics.total, 10);
  assert.equal(end?.message.includes('FANOUT'), true);
});
test('RabbitMQ route messages animate producer then the matched queue or void node', () => {
  const run = simulate('rabbitmq-exchange', { exchange: 'topic' });
  assert.equal(run.length, 12);
  assert.equal(run[0]?.message.includes('TOPIC'), true);
  assert.equal(run.some(f => f.message.includes('命中 QueueA 的绑定「orders.*」')), true);
  assert.equal(run.some(f => f.message.includes('命中 QueueB 的绑定「*.login」')), true);
  assert.equal(run.filter(f => f.active === 'void').length, 2);
  assert.equal(run.at(-1)?.message.includes('未匹配丢弃 2'), true);
});
test('RabbitMQ manual ack retries failed messages up to maxRetry then dead-letters them', () => {
  const end = simulate('rabbitmq-ack', { autoAck: false, maxRetry: 3 }).at(-1);
  assert.equal(end?.metrics.delivered, 9);
  assert.equal(end?.metrics.acked, 3);
  assert.equal(end?.metrics.requeued, 4);
  assert.equal(end?.metrics.dead, 2);
  assert.deepEqual(end?.items.done, ['m1', 'm3', 'm5']);
  assert.deepEqual(end?.items.dead, ['m2', 'm4']);
  assert.deepEqual(end?.items.lost, []);
});
test('RabbitMQ autoAck confirms every delivery and loses failed messages silently', () => {
  const end = simulate('rabbitmq-ack', { autoAck: true }).at(-1);
  assert.equal(end?.metrics.delivered, 5);
  assert.equal(end?.metrics.acked, 5);
  assert.equal(end?.metrics.requeued, 0);
  assert.equal(end?.metrics.dead, 2);
  assert.deepEqual(end?.items.lost, ['m2', 'm4']);
  assert.deepEqual(end?.items.dead, []);
  assert.equal(end?.message.includes('已确认即丢失'), true);
});
test('RabbitMQ maxRetry=1 sends failed messages straight to the dead-letter queue', () => {
  const end = simulate('rabbitmq-ack', { autoAck: false, maxRetry: 1 }).at(-1);
  assert.equal(end?.metrics.requeued, 0);
  assert.equal(end?.metrics.dead, 2);
  assert.equal(end?.metrics.delivered, 5);
});
test('RabbitMQ ack frames animate requeue back to the queue and DLX forward to dead letters', () => {
  const run = simulate('rabbitmq-ack', { autoAck: false, maxRetry: 3 });
  assert.equal(run.length, 19);
  assert.equal(run.filter(f => f.active === 'queue').length >= 4, true);
  assert.equal(run.filter(f => f.active === 'dlx').length, 2);
  assert.equal(run.filter(f => f.active === 'dead').length, 2);
  assert.equal(run.some(f => f.message.includes('回到队首')), true);
});
test('RocketMQ tx: committed local transaction promotes the half message for consumers', () => {
  const end = simulate('rocketmq-tx', { scenario: 'commit' }).at(-1);
  assert.equal(end?.metrics.half, 1);
  assert.equal(end?.metrics.committed, 1);
  assert.equal(end?.metrics.rolledback, 0);
  assert.equal(end?.metrics.checks, 0);
  assert.deepEqual(end?.items.visible, ['m1']);
  assert.deepEqual(end?.items.gone, []);
  assert.equal(end?.message.includes('提交可见 1'), true);
});
test('RocketMQ tx: rollback deletes the half message and consumers never see it', () => {
  const end = simulate('rocketmq-tx', { scenario: 'rollback' }).at(-1);
  assert.equal(end?.metrics.committed, 0);
  assert.equal(end?.metrics.rolledback, 1);
  assert.deepEqual(end?.items.gone, ['m1']);
  assert.deepEqual(end?.items.visible, []);
  assert.equal(end?.message.includes('回滚丢弃 1'), true);
});
test('RocketMQ tx: a lost confirmation triggers checkBack that commits the half message', () => {
  const run = simulate('rocketmq-tx', { scenario: 'unknown' });
  const end = run.at(-1);
  assert.equal(end?.metrics.checks, 1);
  assert.equal(end?.metrics.committed, 1);
  assert.equal(end?.metrics.rolledback, 0);
  assert.deepEqual(end?.items.visible, ['m1']);
  assert.equal(run.some(f => f.message.includes('发起事务回查')), true);
  assert.equal(run.some(f => f.message.includes('回查结果 COMMIT')), true);
});
test('RocketMQ tx frames animate half queue, confirmation and consumer per scenario', () => {
  const commit = simulate('rocketmq-tx', { scenario: 'commit' });
  const rollback = simulate('rocketmq-tx', { scenario: 'rollback' });
  const unknown = simulate('rocketmq-tx', { scenario: 'unknown' });
  assert.equal(commit.length, 8);
  assert.equal(rollback.length, 8);
  assert.equal(unknown.length, 10);
  assert.equal(commit[2]?.active, 'half');
  assert.equal(commit[3]?.active, 'tx');
  assert.equal(commit.filter(f => f.active === 'consumer').length, 1);
  assert.equal(unknown.filter(f => f.active === 'half').length, 3);
  assert.equal(commit.at(-1)?.message.includes('运行结束'), true);
});
test('synchronized biased locking costs one CAS and re-entry is free for the same thread', () => {
  const run = simulate('sync-lock', { scenario: 'biased' });
  const end = run.at(-1);
  assert.equal(run.length, 7);
  assert.equal(end?.metrics.locks, 2);
  assert.equal(end?.metrics.spins, 0);
  assert.equal(end?.metrics.blocks, 0);
  assert.equal(end?.metrics.upgrades, 0);
  assert.equal(end?.items.state, 'biased');
  assert.equal(end?.items.owner, 'T1');
  assert.equal(run.some(f => f.message.includes('偏向锁命中')), true);
});
test('synchronized light-weight locking retries by spinning and never blocks', () => {
  const run = simulate('sync-lock', { scenario: 'light' });
  const end = run.at(-1);
  assert.equal(run.length, 10);
  assert.equal(end?.metrics.upgrades, 1);
  assert.equal(end?.metrics.spins, 2);
  assert.equal(end?.metrics.blocks, 0);
  assert.equal(end?.items.state, 'unlocked');
  assert.equal(run.some(f => f.items.state === 'light'), true);
  assert.equal(run.some(f => f.items.spinners.includes('T1')), true);
});
test('synchronized heavy contention inflates to a Monitor and parks contenders in EntryList', () => {
  const run = simulate('sync-lock', { scenario: 'heavy' });
  const end = run.at(-1);
  assert.equal(run.length, 10);
  assert.equal(end?.metrics.locks, 3);
  assert.equal(end?.metrics.spins, 8);
  assert.equal(end?.metrics.blocks, 2);
  assert.equal(end?.metrics.upgrades, 2);
  assert.deepEqual(end?.items.waiters, []);
  assert.equal(run.filter(f => f.active === 'monitor').length, 3);
  assert.equal(run.some(f => f.message.includes('锁膨胀')), true);
  assert.equal(run.some(f => f.message.includes('EntryList')), true);
});
test('synchronized frames drive Mark Word through the upgrade chain per scenario', () => {
  const light = simulate('sync-lock', { scenario: 'light' });
  const heavy = simulate('sync-lock', { scenario: 'heavy' });
  const lightStates = light.map(f => f.items.state);
  assert.deepEqual(lightStates.slice(0, 5), ['unlocked', 'biased', 'biased', 'unlocked', 'light']);
  const heavyFrame = heavy.find(f => f.items.state === 'heavy');
  assert.equal(heavyFrame?.message.includes('膨胀'), true);
  assert.equal(heavy.at(-2)?.items.state, 'unlocked');
});
test('AQS fair lock enqueues contenders and hands off in FIFO order', () => {
  const run = simulate('aqs-queue', { scenario: 'fair' });
  const end = run.at(-1);
  assert.equal(run.length, 10);
  assert.equal(end?.metrics.locks, 3);
  assert.equal(end?.metrics.reentries, 0);
  assert.equal(end?.metrics.parks, 2);
  assert.equal(end?.metrics.handoffs, 2);
  assert.equal(end?.items.state, 0);
  assert.deepEqual(end?.items.queue, []);
  assert.equal(run.some(f => f.items.queue.length === 2), true);
  assert.equal(run.some(f => f.message.includes('FIFO 顺序获锁')), true);
});
test('AQS reentrant acquire raises state to 2 and requires two unlocks to release', () => {
  const run = simulate('aqs-queue', { scenario: 'reentrant' });
  const end = run.at(-1);
  assert.equal(run.length, 9);
  assert.equal(end?.metrics.locks, 2);
  assert.equal(end?.metrics.reentries, 1);
  assert.equal(end?.metrics.parks, 1);
  assert.equal(end?.metrics.handoffs, 1);
  const reenter = run.find(f => f.items.state === 2);
  assert.equal(reenter?.items.owner, 'T1');
  assert.equal(reenter?.message.includes('可重入'), true);
  assert.deepEqual(reenter?.items.queue, ['T2']);
  assert.equal(run.some(f => f.message.includes('两次 unlock')), true);
});
test('AQS nonfair lock lets a new arrival cut in front of the queued thread', () => {
  const run = simulate('aqs-queue', { scenario: 'nonfair' });
  const end = run.at(-1);
  assert.equal(run.length, 9);
  assert.equal(end?.metrics.locks, 3);
  assert.equal(end?.metrics.reentries, 0);
  assert.equal(end?.metrics.parks, 1);
  assert.equal(end?.metrics.handoffs, 1);
  const sneak = run.find(f => f.items.owner === 'T3');
  assert.deepEqual(sneak?.items.queue, ['T2']);
  assert.equal(sneak?.message.includes('插队'), true);
});
test('AQS frames drive state and queue transitions that match each scenario', () => {
  const fair = simulate('aqs-queue', { scenario: 'fair' });
  const reentrant = simulate('aqs-queue', { scenario: 'reentrant' });
  const nonfair = simulate('aqs-queue', { scenario: 'nonfair' });
  const fairStates = fair.map(f => f.items.state);
  assert.deepEqual(fairStates.slice(0, 5), [0, 1, 1, 1, 0]);
  const reenterStates = reentrant.map(f => f.items.state);
  assert.deepEqual(reenterStates.slice(0, 4), [0, 1, 1, 2]);
  const nonfairFrame = nonfair.find(f => f.items.owner === 'T3');
  assert.equal(nonfairFrame?.items.state, 1);
  assert.deepEqual(nonfairFrame?.items.queue, ['T2']);
  assert.equal(nonfair.at(-1)?.items.state, 0);
  assert.equal(fair.at(-2)?.items.state, 0);
});
test('ZooKeeper leader crash triggers an election that converges on the freshest zxid', () => {
  const run = simulate('zookeeper-leader', { scenario: 'crash-recovery' });
  const end = run.at(-1);
  assert.equal(run.length, 8);
  assert.deepEqual(end?.items.states, ['DOWN', 'LEADING', 'FOLLOWING', 'FOLLOWING', 'FOLLOWING']);
  assert.equal(end?.metrics.elections, 1);
  assert.equal(end?.metrics.votes, 4);
  assert.equal(end?.metrics.handovers, 1);
  assert.equal(end?.metrics.synced, 3);
  assert.deepEqual(run[1]?.items.states, ['DOWN', 'LOOKING', 'LOOKING', 'LOOKING', 'LOOKING']);
  assert.equal(run.some(f => f.items.states[1] === 'LEADING'), true);
  assert.equal(run.some(f => f.message.includes('S2 得 4 票')), true);
  assert.equal(end?.message.includes('运行结束'), true);
});
test('ZooKeeper minority partition can never elect a leader, preventing split brain', () => {
  const run = simulate('zookeeper-leader', { scenario: 'partition' });
  const end = run.at(-1);
  assert.equal(run.length, 8);
  assert.deepEqual(end?.items.states, ['LEADING', 'FOLLOWING', 'FOLLOWING', 'FOLLOWING', 'FOLLOWING']);
  assert.equal(end?.metrics.elections, 1);
  assert.equal(end?.metrics.votes, 2);
  assert.equal(end?.metrics.handovers, 0);
  assert.equal(end?.metrics.synced, 2);
  assert.deepEqual(run[1]?.items.states, ['LEADING', 'FOLLOWING', 'FOLLOWING', 'LOOKING', 'LOOKING']);
  assert.equal(run.some(f => f.message.includes('2 票 < quorum')), true);
  assert.equal(run.some(f => f.items.states[0] === 'LEADING' && f.items.states[3] === 'LOOKING'), true);
  assert.equal(run.some(f => f.message.includes('脑裂')), true);
});
test('ZooKeeper follower crash does not trigger a leader election', () => {
  const run = simulate('zookeeper-leader', { scenario: 'follower-down' });
  const end = run.at(-1);
  assert.equal(run.length, 7);
  assert.deepEqual(end?.items.states, ['LEADING', 'FOLLOWING', 'FOLLOWING', 'FOLLOWING', 'FOLLOWING']);
  assert.equal(end?.metrics.elections, 0);
  assert.equal(end?.metrics.votes, 0);
  assert.equal(end?.metrics.handovers, 0);
  assert.equal(end?.metrics.synced, 1);
  assert.deepEqual(run[1]?.items.states, ['LEADING', 'FOLLOWING', 'DOWN', 'FOLLOWING', 'FOLLOWING']);
  assert.equal(run.some(f => f.message.includes('不触发选举')), true);
  assert.equal(run.at(-2)?.items.states[2], 'FOLLOWING');
});
test('ZooKeeper frames drive node roles through election, sync and recovery per scenario', () => {
  const crash = simulate('zookeeper-leader', { scenario: 'crash-recovery' });
  const partition = simulate('zookeeper-leader', { scenario: 'partition' });
  const follower = simulate('zookeeper-leader', { scenario: 'follower-down' });
  assert.deepEqual(crash.map(f => f.items.states[1]), ['FOLLOWING', 'LOOKING', 'LOOKING', 'LOOKING', 'LEADING', 'LEADING', 'LEADING', 'LEADING']);
  assert.deepEqual(partition.map(f => f.items.states[4]), ['FOLLOWING', 'LOOKING', 'LOOKING', 'LOOKING', 'LOOKING', 'LOOKING', 'FOLLOWING', 'FOLLOWING']);
  assert.deepEqual(follower.map(f => f.items.states[2]), ['FOLLOWING', 'DOWN', 'DOWN', 'DOWN', 'DOWN', 'FOLLOWING', 'FOLLOWING']);
});
test('ES builds the inverted index from 3 docs and match finds only postings hits', () => {
  const run = simulate('es-inverted', { scenario: 'match' });
  const end = run.at(-1);
  assert.equal(run.length, 8);
  assert.deepEqual(end?.metrics, { docs: 3, terms: 9, postings: 11, hits: 2 });
  const java = run.map(f => f.items.inverted.find(t => t.term === 'java')).filter(Boolean).at(-1);
  assert.deepEqual(java?.docs, ['m1', 'm2']);
  assert.equal(run.some(f => f.message.includes('postings [m1, m2]')), true);
  assert.equal(run[5]?.items.found.length, 2);
  assert.equal(end?.message.includes('运行结束'), true);
});
test('ES phrase query requires adjacent in-order terms while match unions terms', () => {
  const run = simulate('es-inverted', { scenario: 'phrase' });
  const end = run.at(-1);
  assert.equal(run.length, 6);
  assert.equal(end?.metrics.docs, 3);
  assert.equal(end?.metrics.terms, 9);
  assert.equal(end?.metrics.postings, 11);
  assert.equal(end?.metrics.hits, 1);
  const match = run.find(f => f.items.qmode === 'match' && f.items.query === 'java 后端');
  assert.deepEqual(match?.items.found, ['m1', 'm2', 'm3']);
  const phrase = run.find(f => f.items.qmode === 'match_phrase');
  assert.deepEqual(phrase?.items.found, ['m1']);
  assert.equal(run.some(f => f.message.includes('取并集')), true);
  assert.equal(run.some(f => f.message.includes('词序反转')), true);
});
test('ES update and delete remove orphaned terms from the inverted index', () => {
  const run = simulate('es-inverted', { scenario: 'update' });
  const end = run.at(-1);
  assert.equal(run.length, 7);
  assert.deepEqual(end?.metrics, { docs: 2, terms: 7, postings: 8, hits: 2 });
  const spring = run.find(f => f.items.query === 'spring');
  assert.deepEqual(spring?.items.found, []);
  assert.equal(spring?.metrics.hits, 0);
  const afterUpdate = run[3]?.items.inverted.map(t => t.term);
  assert.equal(afterUpdate?.includes('vertx'), true);
  assert.equal(afterUpdate?.includes('spring'), false);
  assert.equal(afterUpdate?.includes('服务'), false);
  const backend = run[3]?.items.inverted.find(t => t.term === '后端');
  assert.deepEqual(backend?.docs, ['m1']);
  assert.equal(run.some(f => f.message.includes('命中 0 篇')), true);
});
test('ES frames rebuild inverted terms as documents are indexed, updated and deleted', () => {
  const match = simulate('es-inverted', { scenario: 'match' });
  const update = simulate('es-inverted', { scenario: 'update' });
  const phrase = simulate('es-inverted', { scenario: 'phrase' });
  assert.equal(match[1]?.metrics.terms, 4);
  assert.equal(match[3]?.metrics.terms, 9);
  assert.equal(match[3]?.metrics.postings, 11);
  assert.equal(match[0]?.metrics.docs, 0);
  assert.equal(update[4]?.metrics.terms, 7);
  assert.equal(phrase[3]?.metrics.hits, 3);
  assert.equal(phrase[4]?.metrics.hits, 1);
});
test('Nacos register: two instances register and renew leases with heartbeats', () => {
  const run = simulate('nacos-registry', { scenario: 'register' });
  const end = run.at(-1);
  assert.equal(run.length, 8);
  assert.deepEqual(end?.metrics, { regs: 2, beats: 4, pushes: 0, removals: 0 });
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(run[0]?.items.instances.length, 0);
  const a = run[1]?.items.instances[0];
  assert.deepEqual(a, { id: 'A', addr: '10.0.0.11:8080', state: 'UP' });
  assert.equal(run[1]?.metrics.regs, 1);
  assert.equal(run[2]?.items.instances.length, 2);
  assert.equal(run[2]?.metrics.regs, 2);
  assert.equal(run[3]?.metrics.beats, 1);
  assert.equal(run[4]?.metrics.beats, 2);
  assert.equal(run[5]?.metrics.beats, 4);
  assert.equal(run[5]?.message.includes('双双续约'), true);
  assert.equal(run.at(-1)?.items.instances.every(i => i.state === 'UP'), true);
});
test('Nacos subscribe: consumer converges on scale-up via UDP push and long-poll fallback', () => {
  const run = simulate('nacos-registry', { scenario: 'subscribe' });
  const end = run.at(-1);
  assert.equal(run.length, 9);
  assert.deepEqual(end?.metrics, { regs: 1, beats: 1, pushes: 1, removals: 0 });
  assert.equal(end?.message.includes('C 的目录从 [A, B] 收敛到含 D'), true);
  const full = run[1]?.items.sub;
  assert.equal(full?.cache.join(','), 'A,B');
  assert.equal(full?.via, '全量拉取');
  assert.equal(run[2]?.message.includes('长轮询'), true);
  const regD = run[3]?.items.instances;
  assert.equal(regD?.length, 3);
  assert.equal(regD?.at(-1).id, 'D');
  assert.equal(run[3]?.metrics.regs, 1);
  const udp = run[4];
  assert.equal(udp?.items.notify, 'udp');
  assert.equal(udp?.items.sub.cache.join(','), 'A,B,D');
  assert.equal(udp?.items.sub.via, 'UDP 推送');
  assert.equal(udp?.metrics.pushes, 1);
  assert.equal(run[5]?.items.notify, 'longpoll');
  assert.equal(run[5]?.items.sub.via, '长轮询兜底');
  assert.equal(run[5]?.message.includes('互为兜底'), true);
  assert.equal(run[6]?.metrics.beats, 1);
  assert.deepEqual(run[7]?.items.req, { n: 37, to: 'D' });
});
test('Nacos deregister: graceful deregister removes instantly, crash waits for heartbeat expiry', () => {
  const run = simulate('nacos-registry', { scenario: 'deregister' });
  const end = run.at(-1);
  assert.equal(run.length, 8);
  assert.deepEqual(end?.metrics, { regs: 0, beats: 0, pushes: 0, removals: 2 });
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(run[1]?.items.instances.length, 1);
  assert.equal(run[1]?.items.instances[0].id, 'B');
  assert.equal(run[1]?.metrics.removals, 1);
  assert.equal(run[1]?.message.includes('deregister'), true);
  assert.equal(run[2]?.message.includes('kill -9'), true);
  assert.equal(run[2]?.items.instances[0].state, 'UP');
  assert.equal(run[3]?.message.includes('健康窗口设为 15s'), true);
  const down = run[4];
  assert.equal(down?.items.instances[0].state, 'DOWN');
  assert.equal(down?.message.includes('不健康'), true);
  assert.equal(run[5]?.items.instances.length, 0);
  assert.equal(run[5]?.metrics.removals, 2);
  assert.equal(run[6]?.message.includes('ephemeral=false'), true);
});
test('Nacos frames isolate per-scenario directory, subscriber view and end metrics', () => {
  const register = simulate('nacos-registry', { scenario: 'register' });
  const subscribe = simulate('nacos-registry', { scenario: 'subscribe' });
  const deregister = simulate('nacos-registry', { scenario: 'deregister' });
  assert.equal(register[0]?.items.instances.length, 0);
  assert.equal(subscribe[0]?.items.instances.length, 2);
  assert.equal(deregister[0]?.items.instances.length, 2);
  assert.equal(register[0]?.items.sub, null);
  assert.equal(subscribe[0]?.items.sub, null);
  assert.equal(subscribe.some(f => f.items.notify === 'udp'), true);
  assert.equal(register.some(f => f.items.notify !== null), false);
  assert.equal(deregister.some(f => f.items.notify !== null), false);
  assert.equal(deregister.some(f => f.items.sub !== null), false);
  assert.equal(register.some(f => f.items.req !== null), false);
  const a1 = subscribe[1]?.items.instances[0];
  const a2 = subscribe[2]?.items.instances[0];
  assert.notEqual(a1, a2);
  assert.deepEqual(a1, a2);
  assert.deepEqual(register.at(-1).metrics, { regs: 2, beats: 4, pushes: 0, removals: 0 });
  assert.deepEqual(subscribe.at(-1).metrics, { regs: 1, beats: 1, pushes: 1, removals: 0 });
  assert.deepEqual(deregister.at(-1).metrics, { regs: 0, beats: 0, pushes: 0, removals: 2 });
  assert.equal(register.at(-1).message.startsWith('运行结束'), true);
  assert.equal(subscribe.at(-1).message.startsWith('运行结束'), true);
  assert.equal(deregister.at(-1).message.startsWith('运行结束'), true);
});
test('Netty accept: boss accepts two connections and round-robins them to workers', () => {
  const run = simulate('netty-eventloop', { scenario: 'accept' });
  const end = run.at(-1);
  assert.equal(run.length, 10);
  assert.deepEqual(end?.metrics, { conns: 2, events: 2, regs: 2, tasks: 0 });
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(run[0]?.items.conns.length, 0);
  assert.equal(run[2]?.metrics.conns, 1);
  assert.deepEqual(run[2]?.items.conns[0], { id: 'conn-1', w: '—', state: 'idle' });
  assert.equal(run[3]?.items.conns[0].w, 'W1');
  assert.equal(run[3]?.metrics.regs, 1);
  assert.equal(run[3]?.message.includes('绑定'), true);
  assert.equal(run[4]?.items.conns[0].state, 'busy');
  assert.equal(run[4]?.items.cur, 'conn-1 读');
  assert.equal(run[4]?.metrics.events, 1);
  assert.equal(run[5]?.items.conns[0].state, 'idle');
  assert.equal(run[5]?.items.cur, null);
  assert.equal(run[6]?.items.conns.length, 2);
  assert.equal(run[6]?.metrics.conns, 2);
  assert.equal(run[6]?.message.includes('接入与 IO 在不同线程'), true);
  assert.equal(run[7]?.items.conns[1].w, 'W2');
  assert.equal(run[7]?.metrics.regs, 2);
  assert.equal(run[8]?.items.conns[1].state, 'busy');
  assert.equal(run[8]?.metrics.events, 2);
  assert.equal(run[8]?.message.includes('天然并行'), true);
  assert.equal(end?.items.conns.every(c => c.state === 'idle'), true);
  assert.equal(end?.items.cur, null);
});
test('Netty io loop: one worker serially drains three ready channels then runs an execute task', () => {
  const run = simulate('netty-eventloop', { scenario: 'io' });
  const end = run.at(-1);
  assert.equal(run.length, 9);
  assert.deepEqual(end?.metrics, { conns: 0, events: 4, regs: 0, tasks: 1 });
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(run[0]?.items.conns.length, 3);
  assert.equal(run[0]?.items.conns.every(c => c.w === 'W1'), true);
  assert.deepEqual(run[1]?.items.ready, ['conn-1', 'conn-2', 'conn-3']);
  assert.equal(run[1]?.message.includes('多路复用'), true);
  assert.equal(run[2]?.items.cur, 'conn-1 读');
  assert.equal(run[2]?.metrics.events, 1);
  assert.deepEqual(run[2]?.items.ready, ['conn-2', 'conn-3']);
  assert.equal(run[3]?.items.cur, 'conn-2 读');
  assert.equal(run[3]?.metrics.events, 2);
  assert.equal(run[3]?.message.includes('无需任何锁'), true);
  assert.equal(run[4]?.items.cur, 'conn-3 读');
  assert.equal(run[4]?.metrics.events, 3);
  assert.equal(run[4]?.items.ready.length, 0);
  assert.equal(run[5]?.items.task, '心跳写 → conn-1');
  assert.equal(run[5]?.metrics.tasks, 1);
  assert.equal(run[5]?.message.includes('execute'), true);
  assert.equal(run[6]?.items.task, null);
  assert.equal(run[6]?.message.includes('搬'), true);
  assert.equal(run[7]?.items.cur, 'conn-2 读');
  assert.equal(run[7]?.metrics.events, 4);
  assert.equal(end?.items.conns.every(c => c.state === 'idle'), true);
  assert.equal(end?.items.task, null);
  assert.equal(end?.items.cur, null);
});
test('Netty slow handler: one blocking call stalls the shared worker until offloaded to the pool', () => {
  const run = simulate('netty-eventloop', { scenario: 'slow' });
  const end = run.at(-1);
  assert.equal(run.length, 10);
  assert.deepEqual(end?.metrics, { conns: 0, events: 3, regs: 0, tasks: 2 });
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(run[0]?.items.conns.length, 2);
  assert.equal(run[0]?.items.conns.every(c => c.w === 'W1'), true);
  assert.equal(run[1]?.items.conns[0].state, 'blocked');
  assert.equal(run[1]?.metrics.events, 1);
  assert.equal(run[1]?.message.includes('卡死'), true);
  assert.deepEqual(run[2]?.items.ready, ['conn-2']);
  assert.equal(run[2]?.message.includes('排队'), true);
  assert.equal(run[3]?.items.conns[0].state, 'idle');
  assert.equal(run[3]?.items.cur, 'conn-2 读');
  assert.equal(run[3]?.metrics.events, 2);
  assert.equal(run[3]?.message.includes('拖慢'), true);
  assert.equal(run[4]?.items.conns[1].state, 'idle');
  assert.equal(run[5]?.items.pool, 1);
  assert.equal(run[5]?.metrics.tasks, 1);
  assert.equal(run[5]?.message.includes('业务线程池'), true);
  assert.equal(run[6]?.items.pool, 2);
  assert.equal(run[6]?.metrics.tasks, 2);
  assert.equal(run[6]?.message.includes('派活'), true);
  assert.equal(run[7]?.items.cur, 'conn-2 读');
  assert.equal(run[7]?.metrics.events, 3);
  assert.equal(run[7]?.message.includes('零排队'), true);
  assert.equal(run[8]?.items.pool, 1);
  assert.equal(run[8]?.message.includes('回投'), true);
  assert.equal(end?.items.conns.every(c => c.state === 'idle'), true);
  assert.equal(end?.items.cur, null);
});
test('Netty frames isolate per-scenario topology, queues and end metrics', () => {
  const accept = simulate('netty-eventloop', { scenario: 'accept' });
  const io = simulate('netty-eventloop', { scenario: 'io' });
  const slow = simulate('netty-eventloop', { scenario: 'slow' });
  assert.equal(accept[0]?.items.conns.length, 0);
  assert.equal(io[0]?.items.conns.length, 3);
  assert.equal(slow[0]?.items.conns.length, 2);
  assert.equal(io[0]?.items.conns.every(c => c.w === 'W1'), true);
  assert.equal(accept.some(f => f.items.task !== null), false);
  assert.equal(accept.some(f => f.items.ready.length > 0), false);
  assert.equal(accept.some(f => f.items.pool > 0), false);
  assert.equal(io.some(f => f.items.pool > 0), false);
  assert.equal(slow.some(f => f.items.task !== null), false);
  const c1 = io[5]?.items.conns[0];
  const c2 = io[6]?.items.conns[0];
  assert.notEqual(c1, c2);
  assert.deepEqual(c1, c2);
  assert.deepEqual(accept.at(-1).metrics, { conns: 2, events: 2, regs: 2, tasks: 0 });
  assert.deepEqual(io.at(-1).metrics, { conns: 0, events: 4, regs: 0, tasks: 1 });
  assert.deepEqual(slow.at(-1).metrics, { conns: 0, events: 3, regs: 0, tasks: 2 });
  assert.equal(accept.at(-1).message.startsWith('运行结束'), true);
  assert.equal(io.at(-1).message.startsWith('运行结束'), true);
  assert.equal(slow.at(-1).message.startsWith('运行结束'), true);
});
test('Nacos config publish: clients bootstrap with a full pull and fingerprint check skips refresh', () => {
  const run = simulate('nacos-config', { scenario: 'publish' });
  const end = run.at(-1);
  assert.equal(run.length, 7);
  assert.deepEqual(end?.metrics, { pulls: 3, pushes: 0, refreshes: 0, rollbacks: 0 });
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(run[0]?.items.clients.length, 0);
  assert.deepEqual(run[0]?.items.configs[0], { ns: 'dev', ver: 3, md5: '9f2c', ok: true });
  const a0 = run[1]?.items.clients[0];
  assert.equal(a0?.state, 'starting');
  assert.equal(a0?.cache, null);
  assert.equal(run[1]?.metrics.pulls, 0);
  const a1 = run[2]?.items.clients[0];
  assert.equal(a1?.state, 'ready');
  assert.equal(a1?.cache, 3);
  assert.equal(a1?.md5, '9f2c');
  assert.equal(run[2]?.metrics.pulls, 1);
  assert.equal(run[4]?.items.clients.length, 2);
  assert.equal(run[4]?.metrics.pulls, 2);
  assert.equal(run[5]?.metrics.pulls, 3);
  assert.deepEqual(run[5]?.items.clients[0], a1);
  assert.equal(run[5]?.message.includes('未变更'), true);
});
test('Nacos config update: publishes flow to clients via UDP push and long-poll fallback without restart', () => {
  const run = simulate('nacos-config', { scenario: 'update' });
  const end = run.at(-1);
  assert.equal(run.length, 8);
  assert.deepEqual(end?.metrics, { pulls: 4, pushes: 2, refreshes: 4, rollbacks: 0 });
  assert.equal(end?.message.includes('两次发布四次刷新'), true);
  assert.equal(run[0]?.items.clients.length, 2);
  assert.equal(run[0]?.items.clients.every(c => c.cache === 3), true);
  assert.equal(run[1]?.items.configs[0].ver, 4);
  assert.equal(run[1]?.items.configs[0].md5, 'a1b2');
  assert.equal(run[1]?.metrics.pushes, 1);
  assert.equal(run[2]?.items.notify, 'udp');
  assert.equal(run[2]?.items.clients[0].cache, 4);
  assert.equal(run[2]?.metrics.pulls, 1);
  assert.equal(run[2]?.metrics.refreshes, 1);
  assert.equal(run[2]?.message.includes('秒级'), true);
  assert.equal(run[3]?.items.notify, 'poll');
  assert.equal(run[3]?.items.clients[1].cache, 4);
  assert.equal(run[3]?.metrics.pulls, 2);
  assert.equal(run[3]?.metrics.refreshes, 2);
  assert.equal(run[3]?.message.includes('丢包'), true);
  assert.equal(run[4]?.items.configs[0].ver, 5);
  assert.equal(run[4]?.metrics.pushes, 2);
  assert.equal(run[5]?.items.clients[0].cache, 5);
  assert.equal(run[5]?.metrics.refreshes, 3);
  assert.equal(run[6]?.items.clients[1].cache, 5);
  assert.equal(run[6]?.metrics.pulls, 4);
  assert.equal(run[6]?.metrics.refreshes, 4);
});
test('Nacos config namespace: bad publish hits only dev, rollback restores D while prod never flinches', () => {
  const run = simulate('nacos-config', { scenario: 'namespace' });
  const end = run.at(-1);
  assert.equal(run.length, 8);
  assert.deepEqual(end?.metrics, { pulls: 4, pushes: 2, refreshes: 2, rollbacks: 1 });
  assert.equal(end?.message.includes('毫发无伤'), true);
  assert.equal(run[0]?.items.configs.length, 2);
  assert.equal(run[0]?.items.configs[0].ns, 'dev');
  assert.equal(run[0]?.items.configs[0].ver, 4);
  assert.equal(run[0]?.items.configs[1].ns, 'prod');
  assert.equal(run[1]?.items.clients[0].ns, 'dev');
  assert.equal(run[1]?.items.clients[0].md5, 'd4e5');
  assert.equal(run[2]?.items.clients[1].ns, 'prod');
  assert.equal(run[2]?.items.clients[1].md5, 'p3q4');
  assert.equal(run[2]?.message.includes('prod-db'), true);
  assert.equal(run[3]?.items.configs[0].ok, false);
  assert.equal(run[3]?.items.configs[0].ver, 5);
  assert.equal(run[3]?.metrics.pushes, 1);
  assert.equal(run[4]?.items.clients[0].state, 'error');
  assert.equal(run[4]?.items.clients[0].md5, 'e6f7');
  assert.equal(run[4]?.metrics.refreshes, 1);
  assert.equal(run[4]?.message.includes('报错'), true);
  assert.equal(run[5]?.items.rollback, '← 撤销 v5');
  assert.equal(run[5]?.items.configs[0].ok, true);
  assert.equal(run[5]?.metrics.rollbacks, 1);
  assert.equal(run[5]?.metrics.pushes, 2);
  assert.equal(run[5]?.message.includes('一键回滚'), true);
  assert.equal(run[6]?.items.clients[0].state, 'ready');
  assert.equal(run[6]?.items.clients[0].md5, 'd4e5');
  assert.equal(run[6]?.metrics.refreshes, 2);
});
test('Nacos config frames isolate per-scenario topology, channels and end metrics', () => {
  const publish = simulate('nacos-config', { scenario: 'publish' });
  const update = simulate('nacos-config', { scenario: 'update' });
  const namespace = simulate('nacos-config', { scenario: 'namespace' });
  assert.equal(publish[0]?.items.configs.length, 1);
  assert.equal(update[0]?.items.configs.length, 1);
  assert.equal(namespace[0]?.items.configs.length, 2);
  assert.equal(publish[0]?.items.clients.length, 0);
  assert.equal(update[0]?.items.clients.length, 2);
  assert.equal(namespace[0]?.items.clients.length, 0);
  assert.equal(update[0]?.items.clients.every(c => c.ns === 'dev'), true);
  assert.equal(namespace[1]?.items.clients[0].ns, 'dev');
  assert.equal(namespace[2]?.items.clients[1].ns, 'prod');
  assert.equal(publish.some(f => f.items.notify !== null), false);
  assert.equal(update.some(f => f.items.notify === 'udp'), true);
  assert.equal(update.some(f => f.items.notify === 'poll'), true);
  assert.equal(namespace.some(f => f.items.notify === 'poll'), false);
  assert.equal(namespace.some(f => f.items.notify === 'udp'), true);
  assert.equal(publish.some(f => f.items.rollback !== null), false);
  assert.equal(update.some(f => f.items.rollback !== null), false);
  assert.equal(namespace.some(f => f.items.rollback !== null), true);
  const u0 = update[0]?.items.clients[0];
  const u1 = update[1]?.items.clients[0];
  assert.notEqual(u0, u1);
  assert.deepEqual(u0, u1);
  const d1 = namespace[1]?.items.clients[0];
  const d2 = namespace[2]?.items.clients[0];
  assert.notEqual(d1, d2);
  assert.deepEqual(d1, d2);
  assert.deepEqual(publish.at(-1).metrics, { pulls: 3, pushes: 0, refreshes: 0, rollbacks: 0 });
  assert.deepEqual(update.at(-1).metrics, { pulls: 4, pushes: 2, refreshes: 4, rollbacks: 0 });
  assert.deepEqual(namespace.at(-1).metrics, { pulls: 4, pushes: 2, refreshes: 2, rollbacks: 1 });
  assert.equal(publish.at(-1).message.startsWith('运行结束'), true);
  assert.equal(update.at(-1).message.startsWith('运行结束'), true);
  assert.equal(namespace.at(-1).message.startsWith('运行结束'), true);
});
test('MySQL replication chain: events travel binlog → relay log → SQL replay and lag catches up', () => {
  const run = simulate('mysql-replication', { scenario: 'chain' });
  const end = run.at(-1);
  assert.equal(run.length, 8);
  assert.deepEqual(end?.metrics, { writes: 2, copies: 2, acks: 0, failovers: 0 });
  assert.equal(end?.message.startsWith('运行结束'), true);
  assert.equal(end?.message.includes('异步链路全通'), true);
  assert.equal(run[0]?.items.events.length, 0);
  assert.equal(run[0]?.items.mode, 'async');
  assert.equal(run[1]?.items.events.length, 1);
  assert.equal(run[1]?.items.events[0].s, 'm');
  assert.equal(run[1]?.metrics.writes, 1);
  assert.equal(run[1]?.message.includes('不等待复制'), true);
  assert.equal(run[2]?.items.events[0].s, 'r');
  assert.equal(run[2]?.message.includes('relay log'), true);
  assert.equal(run[3]?.items.events[0].s, 'a');
  assert.equal(run[3]?.metrics.copies, 1);
  assert.equal(run[3]?.message.includes('串行回放'), true);
  assert.equal(run[5]?.items.events.length, 2);
  assert.equal(run[5]?.items.lag, 2);
  assert.equal(run[5]?.message.includes('追不上'), true);
  assert.equal(run[6]?.items.lag, 0);
  assert.equal(run[6]?.items.events.every(e => e.s === 'a'), true);
  assert.equal(run[6]?.metrics.copies, 2);
  assert.equal(run[6]?.message.includes('追平'), true);
  assert.equal(run[6]?.items.ack, null);
  assert.equal(run[6]?.items.route, null);
});
test('MySQL replication semisync: ack before commit, timeout degrades to async, failover promotes slave', () => {
  const run = simulate('mysql-replication', { scenario: 'semisync' });
  const end = run.at(-1);
  assert.equal(run.length, 9);
  assert.deepEqual(end?.metrics, { writes: 3, copies: 1, acks: 1, failovers: 1 });
  assert.equal(end?.message.startsWith('运行结束'), true);
  assert.equal(end?.message.includes('降级窗口丢一笔'), true);
  assert.equal(run[0]?.items.mode, 'semisync');
  assert.equal(run[0]?.message.includes('至少一个从库回 ack'), true);
  assert.equal(run[1]?.metrics.writes, 1);
  assert.equal(run[1]?.items.events[0].s, 'm');
  assert.equal(run[1]?.message.includes('挂起'), true);
  assert.equal(run[2]?.metrics.acks, 1);
  assert.equal(run[2]?.items.ack, 'e1 ✓ S');
  assert.equal(run[2]?.items.events[0].s, 'r');
  assert.equal(run[2]?.message.includes('提交成功'), true);
  assert.equal(run[3]?.metrics.copies, 1);
  assert.equal(run[3]?.items.events[0].s, 'a');
  assert.equal(run[3]?.items.ack, null);
  assert.equal(run[4]?.items.mode, 'degraded');
  assert.equal(run[4]?.metrics.writes, 2);
  assert.equal(run[4]?.items.events[1].s, 'm');
  assert.equal(run[4]?.message.includes('降级为异步'), true);
  assert.equal(run[5]?.items.events[1].s, 'x');
  assert.equal(run[5]?.message.includes('损失窗口'), true);
  assert.equal(run[6]?.items.master, 'S↑');
  assert.equal(run[6]?.items.mode, 'async');
  assert.equal(run[6]?.metrics.failovers, 1);
  assert.equal(run[6]?.message.includes('提升为新主'), true);
  assert.equal(run[7]?.metrics.writes, 3);
  assert.equal(run[7]?.items.events[2].s, 'm');
  assert.equal(run[7]?.message.includes('S↑ 开始积累'), true);
});
test('MySQL replication split: stale read routed to slave, critical read forced to master, catch-up', () => {
  const run = simulate('mysql-replication', { scenario: 'split' });
  const end = run.at(-1);
  assert.equal(run.length, 7);
  assert.deepEqual(end?.metrics, { writes: 2, copies: 2, acks: 0, failovers: 0 });
  assert.equal(end?.message.startsWith('运行结束'), true);
  assert.equal(end?.message.includes('黄金准则'), true);
  assert.equal(run[0]?.items.route, null);
  assert.equal(run[1]?.metrics.writes, 1);
  assert.equal(run[1]?.items.events[0].s, 'm');
  assert.equal(run[1]?.message.includes('写路由到 M'), true);
  assert.equal(run[2]?.items.route, 'slave');
  assert.equal(run[2]?.message.includes('空空如也'), true);
  assert.equal(run[3]?.metrics.copies, 1);
  assert.equal(run[3]?.items.events[0].s, 'a');
  assert.equal(run[3]?.items.route, 'slave');
  assert.equal(run[3]?.message.includes('订单出现了'), true);
  assert.equal(run[4]?.metrics.writes, 2);
  assert.equal(run[4]?.items.route, 'master');
  assert.equal(run[4]?.items.events[1].s, 'm');
  assert.equal(run[4]?.message.includes('强制路由主库'), true);
  assert.equal(run[5]?.metrics.copies, 2);
  assert.equal(run[5]?.items.events[1].s, 'a');
  assert.equal(run[5]?.items.route, 'slave');
  assert.equal(run[5]?.message.includes('分流效果'), true);
});
test('MySQL replication frames isolate per-scenario topology, channels and end metrics', () => {
  const chain = simulate('mysql-replication', { scenario: 'chain' });
  const semi = simulate('mysql-replication', { scenario: 'semisync' });
  const split = simulate('mysql-replication', { scenario: 'split' });
  assert.equal(chain[0]?.items.mode, 'async');
  assert.equal(semi[0]?.items.mode, 'semisync');
  assert.equal(split[0]?.items.mode, 'async');
  assert.equal(chain.some(f => f.items.ack !== null), false);
  assert.equal(chain.some(f => f.items.route !== null), false);
  assert.equal(chain.some(f => f.items.lag > 0), true);
  assert.equal(semi.some(f => f.items.ack !== null), true);
  assert.equal(semi.some(f => f.items.lag > 0), false);
  assert.equal(semi.some(f => f.items.route !== null), false);
  assert.equal(split.some(f => f.items.route !== null), true);
  assert.equal(split.some(f => f.items.ack !== null), false);
  assert.equal(split.some(f => f.items.master !== 'M'), false);
  assert.equal(split.some(f => f.items.lag > 0), false);
  const c1 = chain[3]?.items.events[0];
  const c2 = chain[4]?.items.events[0];
  assert.notEqual(c1, c2);
  assert.deepEqual(c1, c2);
  const s1 = semi[4]?.items.events[1];
  const s2 = semi[5]?.items.events[1];
  assert.notEqual(s1, s2);
  assert.equal(s2.s, 'x');
  assert.deepEqual(chain.at(-1).metrics, { writes: 2, copies: 2, acks: 0, failovers: 0 });
  assert.deepEqual(semi.at(-1).metrics, { writes: 3, copies: 1, acks: 1, failovers: 1 });
  assert.deepEqual(split.at(-1).metrics, { writes: 2, copies: 2, acks: 0, failovers: 0 });
  assert.equal(chain.at(-1).message.startsWith('运行结束'), true);
  assert.equal(semi.at(-1).message.startsWith('运行结束'), true);
  assert.equal(split.at(-1).message.startsWith('运行结束'), true);
});
test('volatile visibility: plain field hides the write until volatile is added', () => {
  const run = simulate('volatile-jmm', { scenario: 'visible' });
  const end = run.at(-1);
  assert.equal(run.length, 9);
  assert.deepEqual(end?.metrics, { reads: 5, writes: 1, lost: 2, barriers: 1 });
  const writeFrame = run[3];
  assert.equal(writeFrame?.items.t1seen, 'true');
  assert.equal(writeFrame?.items.value, 'false');
  assert.equal(writeFrame?.metrics.writes, 0);
  const fix = run[6];
  assert.equal(fix?.items.volatile, true);
  assert.equal(fix?.items.value, 'true');
  assert.equal(fix?.metrics.barriers, 1);
  const exit = run[7];
  assert.equal(exit?.items.running, false);
  assert.equal(exit?.items.t2seen, 'true');
  assert.equal(end?.message.includes('happens-before'), true);
});
test('volatile reordering: DCL leaks a half-initialized instance without volatile', () => {
  const run = simulate('volatile-jmm', { scenario: 'order' });
  const end = run.at(-1);
  assert.equal(run.length, 10);
  assert.deepEqual(end?.metrics, { reads: 3, writes: 2, lost: 1, barriers: 1 });
  assert.equal(run[0]?.items.value, 'null');
  const leak = run[3];
  assert.equal(leak?.items.value, '半初始化');
  assert.equal(leak?.metrics.writes, 1);
  assert.equal(run[4]?.items.t2seen, '半初始化');
  assert.equal(run[4]?.metrics.lost, 1);
  assert.equal(run[5]?.items.volatile, true);
  const republish = run[7];
  assert.equal(republish?.items.value, '就绪');
  assert.equal(republish?.metrics.writes, 2);
  assert.equal(run.some(f => f.message.includes('StoreStore')), true);
});
test('volatile atomicity: two increments on volatile count lose one update until atomized', () => {
  const run = simulate('volatile-jmm', { scenario: 'atomic' });
  const end = run.at(-1);
  assert.equal(run.length, 8);
  assert.deepEqual(end?.metrics, { reads: 3, writes: 3, lost: 1, barriers: 1 });
  assert.equal(end?.items.value, 2);
  assert.equal(end?.message.includes('原子化后终值 2'), true);
  const overwrite = run[4];
  assert.equal(overwrite?.items.value, 1);
  assert.equal(overwrite?.metrics.lost, 1);
  assert.equal(run[4]?.message.includes('覆盖了 T1 的更新'), true);
  assert.equal(run[5]?.items.t2seen, '读到 1');
  assert.equal(run[5]?.metrics.reads, 3);
  const atomized = run[6];
  assert.equal(atomized?.items.atomized, true);
  assert.equal(atomized?.items.value, 2);
  assert.equal(atomized?.metrics.barriers, 1);
});
test('volatile frames track per-scenario shared state views and distinct end metrics', () => {
  const visible = simulate('volatile-jmm', { scenario: 'visible' });
  const order = simulate('volatile-jmm', { scenario: 'order' });
  const atomic = simulate('volatile-jmm', { scenario: 'atomic' });
  assert.equal(visible[0]?.metrics.reads, 0);
  assert.equal(visible[0]?.items.kind, 'flag');
  assert.equal(order[0]?.items.kind, 'instance');
  assert.equal(atomic[0]?.items.kind, 'count');
  assert.equal(atomic[0]?.items.volatile, true);
  assert.equal(order[1]?.metrics.reads, 1);
  assert.equal(atomic[1]?.items.t1seen, '读到 0');
  assert.equal(visible.at(-1).metrics.lost, 2);
  assert.equal(order.at(-1).metrics.writes, 2);
  assert.equal(atomic.at(-1).metrics.writes, 3);
  assert.deepEqual(visible.at(-1).metrics, { reads: 5, writes: 1, lost: 2, barriers: 1 });
  assert.deepEqual(order.at(-1).metrics, { reads: 3, writes: 2, lost: 1, barriers: 1 });
  assert.deepEqual(atomic.at(-1).metrics, { reads: 3, writes: 3, lost: 1, barriers: 1 });
  assert.equal(order.some(f => f.message.includes('半初始化')), true);
  assert.equal(atomic.some(f => f.message.includes('read-modify-write')), true);
});

test('ES sharding route: hash routing scatters docs across 3 primary shards then syncs replicas', () => {
  const run = simulate('es-sharding', { scenario: 'route' });
  const end = run.at(-1);
  assert.equal(run.length, 8);
  assert.deepEqual(end?.metrics, { docs: 3, syncs: 3, promotes: 0, moves: 0 });
  assert.deepEqual(end?.items.nodes, ['up', 'up', 'up']);
  assert.equal(end?.items.docs.length, 3);
  assert.deepEqual(end?.items.docs.map(d => [d.shard, d.s]), [['P2', 's'], ['P0', 's'], ['P1', 's']]);
  assert.equal(end?.message.startsWith('运行结束'), true);
  assert.equal(end?.message.includes('hash % N'), true);
  const f1 = run[1];
  assert.equal(f1?.metrics.docs, 1);
  assert.equal(f1?.items.docs[0]?.shard, 'P2');
  assert.equal(f1?.items.docs[0]?.s, 'm');
  assert.equal(f1?.items.nodes[0], 'up');
  const f2 = run[2];
  assert.equal(f2?.items.docs[0]?.s, 's');
  assert.equal(f2?.metrics.syncs, 1);
  const f5 = run[5];
  assert.equal(f5?.metrics.docs, 3);
  assert.equal(f5?.items.docs[2]?.shard, 'P1');
  assert.equal(f5?.items.docs[2]?.s, 'm');
});

test('ES sharding failover: replica promotes after node down, cluster self-heals', () => {
  const run = simulate('es-sharding', { scenario: 'failover' });
  const end = run.at(-1);
  assert.equal(run.length, 7);
  assert.deepEqual(end?.metrics, { docs: 1, syncs: 2, promotes: 1, moves: 0 });
  assert.equal(end?.items.nodes[1], 'up');
  assert.equal(end?.items.promotes.length, 1);
  assert.equal(end?.items.promotes[0], 'R1 → P1');
  assert.equal(end?.message.startsWith('运行结束'), true);
  assert.equal(end?.message.includes('分片级高可用'), true);
  assert.equal(run[2]?.message.includes('零丢失'), true);
  const down = run[1];
  assert.equal(down?.items.nodes[1], 'down');
  assert.equal(down?.metrics.promotes, 0);
  assert.equal(down?.message.includes('变 red'), true);
  const promoted = run[2];
  assert.equal(promoted?.metrics.promotes, 1);
  assert.equal(promoted?.items.primaries[1], 'P1↑@N1');
  assert.equal(promoted?.message.includes('自动提升为新主'), true);
  const heal = run[3];
  assert.equal(heal?.metrics.syncs, 1);
  assert.equal(heal?.message.includes('回到 green'), true);
  const resume = run[4];
  assert.equal(resume?.metrics.docs, 1);
  assert.equal(resume?.items.docs[0]?.shard, 'P1↑');
  assert.equal(resume?.items.docs[0]?.s, 'm');
  const back = run[5];
  assert.equal(back?.items.nodes[1], 'up');
  assert.equal(back?.metrics.syncs, 2);
});

test('ES sharding scale: shard count is locked, reindex expands, quorum blocks split brain', () => {
  const run = simulate('es-sharding', { scenario: 'scale' });
  const end = run.at(-1);
  assert.equal(run.length, 7);
  assert.deepEqual(end?.metrics, { docs: 0, syncs: 0, promotes: 0, moves: 2 });
  assert.deepEqual(end?.items.nodes, ['up', 'up', 'up']);
  assert.equal(end?.items.moving, null);
  assert.equal(end?.items.primaries[0], 'orders-v2 · 5 主分片');
  assert.equal(end?.message.startsWith('运行结束'), true);
  assert.equal(end?.message.includes('400'), true);
  const rejected = run[1];
  assert.equal(rejected?.message.includes('400'), true);
  assert.equal(rejected?.message.includes('路由哈希'), true);
  assert.equal(rejected?.metrics.moves, 0);
  const migrating = run[2];
  assert.equal(migrating?.metrics.moves, 1);
  assert.equal(migrating?.items.moving, 'orders → orders-v2');
  const aliased = run[3];
  assert.equal(aliased?.metrics.moves, 2);
  assert.equal(aliased?.items.moving, null);
  assert.equal(aliased?.items.primaries[0], 'orders-v2 · 5 主分片');
  const split = run[4];
  assert.equal(split?.items.nodes[1], 'split');
  assert.equal(split?.message.includes('quorum'), true);
  assert.equal(split?.message.includes('脑裂'), true);
  const recovered = run[5];
  assert.equal(recovered?.items.nodes[1], 'up');
});

test('ES sharding frames isolate per-scenario state views', () => {
  const route = simulate('es-sharding', { scenario: 'route' });
  const failover = simulate('es-sharding', { scenario: 'failover' });
  const scale = simulate('es-sharding', { scenario: 'scale' });
  assert.equal(route[0]?.items.promotes.length, 0);
  assert.equal(route[0]?.items.moving, null);
  assert.equal(failover[0]?.items.nodes[0], 'up');
  assert.equal(failover[0]?.items.docs.length, 0);
  assert.equal(scale[0]?.items.nodes[1], 'up');
  assert.equal(route[6]?.items.docs[2]?.s, 's');
  assert.equal(route[7]?.items.docs[2]?.s, 's');
  assert.notEqual(route[6]?.items.docs[2], route[7]?.items.docs[2]);
  assert.deepEqual(route[6]?.items.docs[2], route[7]?.items.docs[2]);
  const f0 = failover[0];
  const f1 = failover[1];
  assert.notEqual(f0?.items.nodes, f1?.items.nodes);
  assert.deepEqual(f0?.items.nodes, ['up', 'up', 'up']);
  assert.deepEqual(f1?.items.nodes, ['up', 'down', 'up']);
  assert.equal(failover.some(f => f.items.promotes.length > 0), true);
  assert.equal(route.some(f => f.items.promotes.length > 0), false);
  assert.equal(scale.some(f => f.items.moving !== null), true);
  assert.equal(route.some(f => f.items.moving !== null), false);
  assert.equal(failover.some(f => f.items.moving !== null), false);
  assert.equal(route.at(-1).metrics.moves, 0);
  assert.equal(failover.at(-1).metrics.promotes, 1);
  assert.equal(scale.at(-1).metrics.moves, 2);
  assert.equal(failover[2]?.items.primaries.join(' · ').includes('P1↑@N1'), true);
  assert.equal(route[0]?.items.primaries.join(' · '), 'P0@N1 · P1@N2 · P2@N3');
});
test('RocketMQ ordered: same order stays in q0, per-queue serial consume', () => {
  const run = simulate('rocketmq-ordered', { scenario: 'ordered' });
  assert.equal(run.length, 8);
  assert.equal(run[0]?.message.includes('分区有序'), true);
  assert.equal(run[1]?.items.q0.join(), 'O1 创建');
  assert.equal(run[1]?.metrics.sent, 1);
  assert.equal(run[1]?.metrics.queued, 1);
  assert.equal(run[2]?.items.q0.join(), 'O1 创建,O1 支付');
  assert.equal(run[3]?.items.q1.join(), 'O2 创建');
  assert.equal(run[3]?.metrics.queued, 3);
  assert.equal(run[4]?.items.done.join(), 'O1 创建');
  assert.equal(run[5]?.items.done.join(), 'O1 创建,O1 支付');
  assert.equal(run[6]?.items.done.join(), 'O1 创建,O1 支付,O2 创建');
  assert.deepEqual(run[6]?.metrics, { sent: 3, consumed: 3, retries: 0, queued: 0 });
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(end?.message.includes('分区'), true);
  assert.deepEqual(end?.metrics, { sent: 3, consumed: 3, retries: 0, queued: 0 });
  assert.equal(end?.items.q0.length, 0);
  assert.equal(end?.items.q1.length, 0);
});
test('RocketMQ ordered resend: failed message suspends queue and retries in place', () => {
  const run = simulate('rocketmq-ordered', { scenario: 'resend' });
  assert.equal(run.length, 10);
  assert.equal(run[3]?.items.done.join(), 'O1 创建,O1 支付');
  assert.equal(run[4]?.items.q0.join(), 'O1 出库');
  assert.equal(run[5]?.items.retrying, 'O1 出库');
  assert.equal(run[5]?.metrics.retries, 1);
  assert.equal(run[5]?.items.q0.length, 0);
  assert.equal(run[5]?.message.includes('SUSPEND'), true);
  assert.equal(run[6]?.items.retrying, 'O1 出库');
  assert.equal(run[6]?.metrics.retries, 2);
  assert.equal(run[6]?.message.includes('完成'), true);
  assert.equal(run[7]?.items.retrying, null);
  assert.equal(run[7]?.items.done.join(), 'O1 创建,O1 支付,O1 出库');
  assert.equal(run[7]?.metrics.consumed, 3);
  assert.equal(run[8]?.items.done.join(), 'O1 创建,O1 支付,O1 出库,O1 完成');
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.deepEqual(end?.metrics, { sent: 4, consumed: 4, retries: 2, queued: 0 });
  assert.equal(run.some(f => f.items.done.includes('O1 完成') && !f.items.done.includes('O1 出库')), false);
});
test('RocketMQ ordered delay: message waits in SCHEDULE_TOPIC then transfers to queue', () => {
  const run = simulate('rocketmq-ordered', { scenario: 'delay' });
  assert.equal(run.length, 6);
  assert.equal(run[0]?.message.includes('SCHEDULE_TOPIC'), true);
  assert.equal(run[1]?.items.delayed.length, 1);
  assert.equal(run[1]?.items.delayed[0]?.lvl, 5);
  assert.equal(run[1]?.items.q1.length, 0);
  assert.equal(run[1]?.metrics.queued, 1);
  assert.equal(run[2]?.items.delayed.length, 1);
  assert.equal(run[3]?.items.delayed.length, 0);
  assert.equal(run[3]?.items.q1.join(), '超时关闭 #3001');
  assert.equal(run[4]?.items.done.join(), '超时关闭 #3001');
  assert.equal(run[4]?.metrics.consumed, 1);
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.deepEqual(end?.metrics, { sent: 1, consumed: 1, retries: 0, queued: 0 });
});
test('RocketMQ ordered: scenarios isolate queue state and default to ordered', () => {
  const ordered = simulate('rocketmq-ordered', { scenario: 'ordered' });
  const resend = simulate('rocketmq-ordered', { scenario: 'resend' });
  const delay = simulate('rocketmq-ordered', { scenario: 'delay' });
  assert.equal(ordered.some(f => f.items.retrying !== null), false);
  assert.equal(ordered.some(f => f.items.delayed.length > 0), false);
  assert.equal(resend.some(f => f.items.delayed.length > 0), false);
  assert.equal(delay.some(f => f.items.q0.length > 0), false);
  assert.equal(delay.some(f => f.items.retrying !== null), false);
  assert.equal(delay.some(f => f.items.q1.length > 0 && f.items.delayed.length > 0), false);
  assert.equal(simulate('rocketmq-ordered', {}).length, simulate('rocketmq-ordered', { scenario: 'ordered' }).length);
  assert.equal(ordered[0]?.items.done.length, 0);
  assert.equal(resend.at(-1)?.items.done.length, 4);
  assert.equal(delay.at(-1)?.items.done.length, 1);
});
test('JUC countdown: latch waits for all 3 jobs then releases main thread', () => {
  const run = simulate('juc-coordination', { scenario: 'countdown' });
  assert.equal(run.length, 7);
  assert.equal(run[0]?.items.coord.txt, 'CountDownLatch = 3');
  assert.equal(run[1]?.items.jobs.every(j => j.st === 'run'), true);
  assert.deepEqual(run[1]?.metrics, { submitted: 3, arrived: 0, released: 0, waiting: 1 });
  assert.equal(run[1]?.items.coord.txt, 'await 阻塞 · 门闩剩 3');
  assert.equal(run[2]?.items.jobs[0].st, 'done');
  assert.equal(run[2]?.items.coord.txt, '门闩剩 2');
  assert.equal(run[3]?.items.jobs[1].st, 'done');
  assert.equal(run[3]?.items.coord.txt, '门闩剩 1');
  assert.equal(run[4]?.items.jobs[2].st, 'done');
  assert.equal(run[4]?.metrics.arrived, 3);
  assert.equal(run[4]?.items.coord.st, 'open');
  assert.equal(run[4]?.message.includes('countDown'), true);
  assert.equal(run[5]?.metrics.released, 1);
  assert.equal(run[5]?.items.coord.txt, '三份数据齐 · 已合并渲染');
  assert.equal(run[5]?.message.includes('await(timeout)'), true);
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(end?.message.includes('一次性'), true);
  assert.deepEqual(end?.metrics, { submitted: 3, arrived: 3, released: 1, waiting: 1 });
});
test('JUC barrier: threads wait for each other and the last arrival opens the round', () => {
  const run = simulate('juc-coordination', { scenario: 'barrier' });
  assert.equal(run.length, 7);
  assert.equal(run[1]?.items.coord.txt, '阶段一 · 各自统计中');
  assert.equal(run[2]?.items.jobs[0].st, 'wait');
  assert.equal(run[2]?.metrics.waiting, 1);
  assert.equal(run[2]?.items.coord.txt, '已到 1/3 · A 等待');
  assert.equal(run[3]?.items.jobs[1].st, 'wait');
  assert.equal(run[3]?.items.coord.txt, '已到 2/3 · A/B 等待');
  assert.equal(run[4]?.items.jobs[0].st, 'run');
  assert.equal(run[4]?.items.jobs[1].st, 'run');
  assert.equal(run[4]?.items.jobs[2].st, 'run');
  assert.equal(run[4]?.metrics.arrived, 3);
  assert.equal(run[4]?.metrics.released, 3);
  assert.equal(run[4]?.items.coord.txt, '到齐 3/3 · 放行阶段二');
  assert.equal(run[4]?.message.includes('最后到达者触发'), true);
  assert.equal(run[5]?.items.jobs.every(j => j.st === 'done'), true);
  assert.equal(run[5]?.items.coord.txt, '屏障复位 0/3 · 可循环');
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(end?.message.includes('BrokenBarrierException'), true);
  assert.deepEqual(end?.metrics, { submitted: 3, arrived: 3, released: 3, waiting: 2 });
});
test('JUC semaphore: permits cap concurrency and release wakes queued thread', () => {
  const run = simulate('juc-coordination', { scenario: 'semaphore' });
  assert.equal(run.length, 7);
  assert.equal(run[0]?.items.coord.txt, 'Semaphore(2) · 许可 2/2');
  assert.equal(run[1]?.items.jobs[0].st, 'run');
  assert.equal(run[1]?.items.jobs[2].st, 'wait');
  assert.equal(run[1]?.metrics.waiting, 1);
  assert.equal(run[1]?.items.coord.txt, '许可 0/2 · 丙排队');
  assert.equal(run[0]?.message.includes('不绑定持有者'), true);
  assert.equal(run[2]?.metrics.released, 1);
  assert.equal(run[2]?.items.jobs[0].st, 'done');
  assert.equal(run[2]?.items.coord.txt, '许可 1/2 · 唤醒丙');
  assert.equal(run[3]?.items.jobs[2].st, 'run');
  assert.equal(run[3]?.metrics.arrived, 3);
  assert.equal(run[3]?.items.coord.txt, '许可 0/2 · 乙丙执行中');
  assert.equal(run[4]?.metrics.released, 2);
  assert.equal(run[5]?.metrics.released, 3);
  assert.equal(run[5]?.items.coord.txt, '许可 2/2 · 全部归还');
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(end?.message.includes('流量闸门'), true);
  assert.deepEqual(end?.metrics, { submitted: 3, arrived: 3, released: 3, waiting: 1 });
});
test('JUC tools: scenarios isolate state and default to countdown', () => {
  const countdown = simulate('juc-coordination', { scenario: 'countdown' });
  const barrier = simulate('juc-coordination', { scenario: 'barrier' });
  const semaphore = simulate('juc-coordination', { scenario: 'semaphore' });
  assert.equal(simulate('juc-coordination', {}).length, countdown.length);
  assert.equal(countdown.some(f => f.items.jobs.some(j => j.st === 'wait')), false);
  assert.equal(countdown[2]?.items.jobs[0].label, '① 拉用户');
  assert.equal(barrier.some(f => f.items.coord.txt.includes('许可')), false);
  assert.equal(countdown.some(f => f.items.coord.txt.includes('许可')), false);
  assert.equal(barrier.at(-1)?.items.jobs.every(j => j.st === 'done'), true);
  assert.equal(semaphore.at(-1)?.items.jobs.every(j => j.st === 'done'), true);
  assert.equal(barrier[2]?.items.jobs[0].label, 'A 分片');
  assert.equal(semaphore[1]?.items.jobs[2].label, '丙');
});
test('MySQL WAL: commit persists redo first, dirty page flushes later', () => {
  const run = simulate('mysql-crash', { scenario: 'wal' });
  assert.equal(run.length, 8);
  assert.equal(run[0]?.items.pages[0].st, 'clean');
  assert.equal(run[1]?.items.pages[0].st, 'dirty');
  assert.deepEqual(run[1]?.items.undos[0], { t: 'T1', v: 1000 });
  assert.equal(run[2]?.items.redos[0].st, 'committed');
  assert.equal(run[2]?.metrics.committed, 1);
  assert.equal(run[2]?.items.undos.length, 0);
  assert.equal(run[2]?.message.includes('fsync'), true);
  assert.equal(run[3]?.message.includes('commit ok'), true);
  assert.equal(run[3]?.message.includes('分裂'), true);
  assert.equal(run[5]?.metrics.committed, 2);
  assert.equal(run[6]?.metrics.committed, 3);
  assert.equal(run[6]?.items.redos.length, 3);
  assert.equal(run[6]?.items.redos.every(r => r.st === 'committed'), true);
  assert.equal(run[7]?.items.pages[0].st, 'clean');
  assert.equal(run[7]?.metrics.flushed, 1);
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(end?.message.includes('checkpoint'), true);
  assert.deepEqual(end?.metrics, { committed: 3, flushed: 1, replayed: 0, rolledback: 0 });
});
test('MySQL crash: redo replay recovers committed-but-unflushed transactions', () => {
  const run = simulate('mysql-crash', { scenario: 'crash' });
  assert.equal(run.length, 8);
  assert.equal(run[1]?.metrics.committed, 1);
  assert.equal(run[2]?.items.pages[0].st, 'clean');
  assert.equal(run[2]?.metrics.flushed, 1);
  assert.equal(run[4]?.metrics.committed, 3);
  assert.equal(run[5]?.items.state, 'down');
  assert.equal(run[5]?.message.includes('kill -9'), true);
  assert.equal(run[6]?.items.state, 'recovering');
  assert.equal(run[6]?.items.pages[0].st, 'dirty');
  assert.equal(run[6]?.metrics.replayed, 2);
  assert.equal(run[6]?.message.includes('checkpoint'), true);
  assert.equal(run[6]?.message.includes('重放'), true);
  const end = run.at(-1);
  assert.equal(end?.items.state, 'ok');
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(end?.message.includes('零丢失'), true);
  assert.deepEqual(end?.metrics, { committed: 3, flushed: 1, replayed: 2, rolledback: 0 });
});
test('MySQL two-phase commit: xid in binlog decides commit vs rollback after crash', () => {
  const run = simulate('mysql-crash', { scenario: 'twophase' });
  assert.equal(run.length, 11);
  assert.equal(run[0]?.message.includes('两阶段'), true);
  assert.equal(run[1]?.items.redos[0].st, 'prepared');
  assert.deepEqual(run[1]?.items.undos[0], { t: 'T1', v: 1000 });
  assert.deepEqual(run[2]?.items.binlogs, [{ t: 'T1' }]);
  assert.equal(run[3]?.items.redos[0].st, 'committed');
  assert.equal(run[3]?.metrics.committed, 1);
  assert.equal(run[3]?.items.undos.length, 0);
  assert.equal(run[4]?.items.redos[1].t, 'T2');
  assert.equal(run[4]?.items.redos[1].st, 'prepared');
  assert.equal(run[5]?.items.state, 'down');
  assert.equal(run[5]?.message.includes('xid=2'), true);
  assert.equal(run[6]?.metrics.rolledback, 1);
  assert.equal(run[6]?.items.redos.some(r => r.t === 'T2'), false);
  assert.equal(run[6]?.items.state, 'running');
  assert.deepEqual(run[7]?.items.binlogs.map(b => b.t), ['T1', 'T3']);
  assert.equal(run[7]?.items.redos[1].st, 'prepared');
  assert.equal(run[8]?.items.state, 'down');
  assert.equal(run[8]?.message.includes('xid=3'), true);
  assert.equal(run[9]?.metrics.replayed, 1);
  assert.equal(run[9]?.metrics.committed, 2);
  assert.equal(run[9]?.items.redos[1].st, 'committed');
  assert.equal(run[9]?.items.state, 'ok');
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(end?.message.includes('主从不分裂'), true);
  assert.deepEqual(end?.metrics, { committed: 2, flushed: 0, replayed: 1, rolledback: 1 });
});
test('MySQL crash: scenarios isolate state and default to wal', () => {
  const wal = simulate('mysql-crash', { scenario: 'wal' });
  const crash = simulate('mysql-crash', { scenario: 'crash' });
  const twophase = simulate('mysql-crash', { scenario: 'twophase' });
  assert.equal(simulate('mysql-crash', {}).length, wal.length);
  assert.equal(wal.some(f => f.items.state === 'down' || f.items.state === 'recovering'), false);
  assert.equal(wal.some(f => f.items.binlogs.length > 0), false);
  assert.equal(wal.some(f => f.items.redos.some(r => r.st === 'discard')), false);
  assert.equal(crash.some(f => f.items.binlogs.length > 0), false);
  assert.equal(crash.some(f => f.items.undos.length > 0), false);
  assert.equal(twophase.some(f => f.metrics.flushed > 0), false);
  assert.equal(twophase[5]?.items.pages[0].st, 'dirty');
  assert.equal(crash[0]?.items.pages[0].st, 'clean');
  assert.equal(twophase.at(-1)?.items.redos.length, 2);
  assert.equal(twophase.at(-1)?.items.redos.every(r => r.st === 'committed'), true);
});
test('CHM put: empty slots CAS direct insert, collision serialized on single bin lock', () => {
  const run = simulate('concurrent-hashmap', { scenario: 'put' });
  assert.equal(run.length, 6);
  assert.equal(run[0]?.items.slots.length, 8);
  assert.equal(run[0]?.items.slots.every(s => s.keys.length === 0 && s.fwd === false), true);
  assert.equal(run[0]?.items.threads.length, 4);
  assert.equal(run[1]?.metrics.inserted, 1);
  assert.deepEqual(run[1]?.items.slots[3].keys, ['k1']);
  assert.equal(run[1]?.message.includes('CAS'), true);
  assert.equal(run[2]?.metrics.conflicts, 2);
  assert.deepEqual(run[2]?.items.slots[3].keys, ['k1', 'k2']);
  assert.equal(run[2]?.items.threads.find(t => t.id === 'T3').st, 'wait');
  assert.equal(run[2]?.message.includes('bin'), true);
  assert.equal(run[3]?.items.threads.find(t => t.id === 'T4').st, 'done');
  assert.deepEqual(run[3]?.items.slots[5].keys, ['k4']);
  assert.equal(run[3]?.message.includes('并行'), true);
  assert.equal(run[4]?.items.threads.find(t => t.id === 'T3').st, 'done');
  assert.deepEqual(run[4]?.items.slots[3].keys, ['k1', 'k2', 'k3']);
  assert.equal(run[4]?.message.includes('唤醒'), true);
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(end?.message.includes('锁粒度'), true);
  assert.deepEqual(end?.metrics, { inserted: 4, conflicts: 2, migrated: 0, spread: 0 });
});
test('CHM resize: slots migrate with fwd placeholders, readers/writers follow to new table', () => {
  const run = simulate('concurrent-hashmap', { scenario: 'resize' });
  assert.equal(run.length, 8);
  assert.equal(run[0]?.items.slots.reduce((n, s) => n + s.keys.length, 0), 6);
  assert.deepEqual(run[0]?.items.slots[2].keys, ['B', 'C']);
  assert.equal(run[0]?.message.includes('阈值'), true);
  assert.equal(run[1]?.items.newSlots.length, 16);
  assert.equal(run[1]?.items.threads.find(t => t.id === 'T1').st, 'run');
  assert.equal(run[2]?.items.slots.filter(s => s.fwd).length, 3);
  assert.deepEqual(run[2]?.items.newSlots[6].keys, ['F']);
  assert.deepEqual(run[2]?.items.newSlots[5].keys, ['E']);
  assert.equal(run[3]?.items.slots.filter(s => s.fwd).length, 5);
  assert.deepEqual(run[3]?.items.newSlots[10].keys, ['C']);
  assert.equal(run[3]?.message.includes('高位'), true);
  assert.equal(run[4]?.items.slots.filter(s => s.fwd).length, 8);
  assert.equal(run[5]?.metrics.inserted, 1);
  assert.deepEqual(run[5]?.items.newSlots[4].keys, ['G']);
  assert.equal(run[5]?.message.includes('fwd'), true);
  assert.deepEqual(run[6]?.items.newSlots[12].keys, ['H']);
  assert.equal(run[6]?.metrics.inserted, 2);
  const end = run.at(-1);
  assert.equal(end?.items.slots.every(s => s.fwd), true);
  assert.equal(end?.items.newSlots.filter(n => n.keys.length).length, 8);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(end?.message.includes('高位移位'), true);
  assert.deepEqual(end?.metrics, { inserted: 2, conflicts: 0, migrated: 8, spread: 0 });
});
test('CHM weak count: CAS collisions spread into CounterCell, size() snapshot lags then converges', () => {
  const run = simulate('concurrent-hashmap', { scenario: 'count' });
  assert.equal(run.length, 7);
  assert.equal(run[0]?.items.counter.base, 0);
  assert.equal(run[0]?.items.counter.cells.length, 0);
  assert.equal(run[1]?.items.counter.base, 1);
  assert.deepEqual(run[1]?.items.counter.cells, [1]);
  assert.equal(run[1]?.metrics.conflicts, 1);
  assert.equal(run[1]?.metrics.spread, 1);
  assert.deepEqual(run[1]?.items.slots[1].keys, ['k1']);
  assert.deepEqual(run[1]?.items.slots[3].keys, ['k2']);
  assert.equal(run[2]?.items.counter.base, 2);
  assert.equal(run[2]?.metrics.inserted, 3);
  assert.equal(run[2]?.message.includes('闲置'), true);
  assert.equal(run[3]?.items.counter.base, 3);
  assert.deepEqual(run[3]?.items.counter.cells, [1, 1]);
  assert.equal(run[3]?.metrics.inserted, 5);
  assert.equal(run[3]?.metrics.spread, 2);
  assert.equal(run[4]?.items.counter.last, 5);
  assert.equal(run[4]?.metrics.inserted, 6);
  assert.deepEqual(run[4]?.items.slots[6].keys, ['k6']);
  assert.equal(run[4]?.message.includes('弱一致'), true);
  assert.equal(run[5]?.items.counter.base, 4);
  assert.equal(run[5]?.items.counter.last, 6);
  assert.equal(run[5]?.message.includes('收敛'), true);
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(end?.message.includes('LongAdder'), true);
  assert.deepEqual(end?.metrics, { inserted: 6, conflicts: 2, migrated: 0, spread: 2 });
});
test('CHM: scenarios isolate state and default to put', () => {
  const put = simulate('concurrent-hashmap', { scenario: 'put' });
  const resize = simulate('concurrent-hashmap', { scenario: 'resize' });
  const count = simulate('concurrent-hashmap', { scenario: 'count' });
  assert.equal(simulate('concurrent-hashmap', {}).length, put.length);
  assert.equal(simulate('concurrent-hashmap', {}).at(-1)?.metrics.inserted, 4);
  assert.equal(put.some(f => f.items.newSlots !== null), false);
  assert.equal(put.some(f => f.items.counter.cells.length > 0), false);
  assert.equal(put.some(f => f.items.counter.last !== null), false);
  assert.equal(resize.some(f => f.items.counter.cells.length > 0), false);
  assert.equal(resize.some(f => f.items.counter.last !== null), false);
  assert.equal(count.some(f => f.items.slots.some(s => s.fwd)), false);
  assert.equal(count.some(f => f.items.newSlots !== null), false);
  assert.equal(count[3]?.items.counter.last, null);
  assert.equal(count.filter(f => f.items.counter.last !== null).length, 3);
});
test('mysql-lock row: X lock mutual exclusion, later tx waits in queue, MVCC read passes', () => {
  const run = simulate('mysql-lock', { scenario: 'row' });
  assert.equal(run.length, 8);
  assert.equal(run[0]?.items.threads.length, 3);
  assert.equal(run[0]?.items.locks.length, 0);
  assert.deepEqual(run[0]?.items.wait, []);
  assert.equal(run[1]?.metrics.locked, 1);
  assert.equal(run[1]?.items.locks.find(l => l.name === '行 1').holder, 'T1');
  assert.equal(run[1]?.items.locks.find(l => l.name === '行 1').kind, 'X');
  assert.equal(run[2]?.metrics.blocked, 1);
  assert.deepEqual(run[2]?.items.wait, ['T2']);
  assert.equal(run[2]?.items.threads.find(t => t.id === 'T2').st, 'wait');
  assert.equal(run[2]?.message.includes('等待队列'), true);
  assert.equal(run[3]?.items.threads.find(t => t.id === 'T3').st, 'done');
  assert.equal(run[3]?.items.locks.find(l => l.name === '行 1').holder, 'T1');
  assert.equal(run[3]?.message.includes('快照读'), true);
  assert.equal(run[4]?.items.locks.find(l => l.name === '行 1').holder, null);
  assert.equal(run[4]?.message.includes('唤醒'), true);
  assert.equal(run[5]?.metrics.locked, 2);
  assert.deepEqual(run[5]?.items.wait, []);
  assert.equal(run[5]?.items.locks.find(l => l.name === '行 1').holder, 'T2');
  assert.equal(run[6]?.items.locks.find(l => l.name === '行 1').holder, null);
  assert.equal(run[6]?.items.threads.find(t => t.id === 'T2').st, 'done');
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(end?.message.includes('互斥面'), true);
  assert.deepEqual(end?.metrics, { locked: 2, blocked: 1, deadlocks: 0, aborted: 0 });
});
test('mysql-lock gap: next-key blocks insert into gap under RR, insert succeeds after commit', () => {
  const run = simulate('mysql-lock', { scenario: 'gap' });
  assert.equal(run.length, 8);
  assert.equal(run[0]?.items.threads.length, 2);
  assert.equal(run[1]?.metrics.locked, 1);
  assert.equal(run[1]?.items.locks.filter(l => l.holder === 'T1').length, 3);
  assert.equal(run[1]?.items.locks.some(l => l.kind === 'GAP'), true);
  assert.equal(run[1]?.message.includes('next-key'), true);
  assert.equal(run[2]?.metrics.blocked, 1);
  assert.deepEqual(run[2]?.items.wait, ['T2']);
  assert.equal(run[2]?.items.threads.find(t => t.id === 'T2').st, 'wait');
  assert.equal(run[2]?.message.includes('插入意向'), true);
  assert.equal(run[3]?.message.includes('幻读'), true);
  assert.equal(run[4]?.items.locks.every(l => l.holder === null), true);
  assert.equal(run[4]?.message.includes('唤醒'), true);
  assert.equal(run[5]?.metrics.locked, 2);
  assert.equal(run[5]?.items.locks.find(l => l.name === '行 3').holder, 'T2');
  assert.deepEqual(run[5]?.items.wait, []);
  assert.equal(run[6]?.items.locks.find(l => l.name === '行 3').holder, null);
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(end?.message.includes('间隙锁'), true);
  assert.deepEqual(end?.metrics, { locked: 2, blocked: 1, deadlocks: 0, aborted: 0 });
});
test('mysql-lock deadlock: circular wait detected, T2 victim rolled back, whole-tx retry', () => {
  const run = simulate('mysql-lock', { scenario: 'deadlock' });
  assert.equal(run.length, 10);
  assert.equal(run[0]?.items.threads.length, 2);
  assert.equal(run[1]?.metrics.locked, 1);
  assert.equal(run[1]?.items.locks.find(l => l.name === '行 1').holder, 'T1');
  assert.equal(run[2]?.metrics.locked, 2);
  assert.equal(run[2]?.items.locks.find(l => l.name === '行 2').holder, 'T2');
  assert.equal(run[3]?.metrics.blocked, 1);
  assert.deepEqual(run[3]?.items.wait, ['T1']);
  assert.equal(run[4]?.metrics.blocked, 2);
  assert.deepEqual(run[4]?.items.wait, ['T1', 'T2']);
  assert.equal(run[4]?.message.includes('成环'), true);
  assert.equal(run[5]?.metrics.deadlocks, 1);
  assert.equal(run[5]?.message.includes('四条件'), true);
  assert.equal(run[6]?.metrics.aborted, 1);
  assert.equal(run[6]?.items.victim, 'T2');
  assert.equal(run[6]?.items.locks.find(l => l.name === '行 2').holder, null);
  assert.equal(run[6]?.items.threads.find(t => t.id === 'T2').st, 'idle');
  assert.equal(run[6]?.message.includes('1213'), true);
  assert.equal(run[7]?.metrics.locked, 3);
  assert.deepEqual(run[7]?.items.wait, []);
  assert.equal(run[7]?.items.locks.find(l => l.name === '行 2').holder, 'T1');
  assert.equal(run[8]?.metrics.locked, 4);
  assert.equal(run[8]?.items.locks.find(l => l.name === '行 1').holder, 'T2');
  assert.equal(run[8]?.message.includes('整个事务'), true);
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(end?.message.includes('固定顺序'), true);
  assert.equal(end?.items.victim, null);
  assert.deepEqual(end?.metrics, { locked: 4, blocked: 2, deadlocks: 1, aborted: 1 });
});
test('mysql-lock: scenarios isolate state and default to row', () => {
  const row = simulate('mysql-lock', { scenario: 'row' });
  const gap = simulate('mysql-lock', { scenario: 'gap' });
  const deadlock = simulate('mysql-lock', { scenario: 'deadlock' });
  assert.equal(simulate('mysql-lock', {}).length, row.length);
  assert.deepEqual(simulate('mysql-lock', {}).at(-1)?.metrics, { locked: 2, blocked: 1, deadlocks: 0, aborted: 0 });
  assert.equal(row.some(f => f.items.locks.some(l => l.kind === 'GAP')), false);
  assert.equal(row.some(f => f.items.victim !== null), false);
  assert.equal(gap.some(f => f.metrics.deadlocks > 0), false);
  assert.equal(gap.some(f => f.items.victim !== null), false);
  assert.equal(deadlock.some(f => f.items.locks.some(l => l.kind === 'GAP')), false);
  assert.equal(deadlock.some(f => f.items.locks.length > 2), false);
  assert.equal(deadlock.at(-1)?.items.locks.length, 2);
  assert.equal(deadlock.filter(f => f.items.victim !== null).length, 1);
  assert.equal(deadlock.at(-1)?.items.locks.every(l => l.holder === null), true);
});
test('kafka-eos idempotent: PID+seq window dedupes retry, rejects out-of-order, calibrates', () => {
  const run = simulate('kafka-eos', { scenario: 'idempotent' });
  assert.equal(run.length, 8);
  assert.equal(run[0]?.items.producer.pid, 7);
  assert.equal(run[0]?.items.lastSeq, 3);
  assert.equal(run[0]?.items.coordinator, null);
  assert.equal(run[0]?.items.lso, null);
  assert.deepEqual(run[0]?.items.parts.P1, []);
  assert.equal(run[1]?.metrics.sent, 1);
  assert.equal(run[1]?.metrics.stored, 1);
  assert.equal(run[1]?.metrics.committed, 1);
  assert.equal(run[1]?.items.lastSeq, 4);
  assert.deepEqual(run[1]?.items.parts.P0.map(e => e.t), ['pay-101']);
  assert.equal(run[1]?.items.parts.P0[0].st, 'ok');
  assert.equal(run[2]?.metrics.sent, 2);
  assert.equal(run[2]?.metrics.blocked, 1);
  assert.equal(run[2]?.items.parts.P0.length, 1);
  assert.equal(run[2]?.items.flash.kind, 'dup');
  assert.equal(run[2]?.message.includes('判重复'), true);
  assert.equal(run[3]?.metrics.sent, 4);
  assert.equal(run[3]?.items.flash, null);
  assert.equal(run[3]?.message.includes('在途'), true);
  assert.equal(run[4]?.metrics.blocked, 2);
  assert.equal(run[4]?.items.flash.kind, 'gap');
  assert.equal(run[4]?.items.parts.P0.length, 1);
  assert.equal(run[4]?.message.includes('OutOfOrder'), true);
  assert.equal(run[5]?.metrics.stored, 2);
  assert.equal(run[5]?.items.lastSeq, 5);
  assert.equal(run[5]?.items.parts.P0.at(-1).t, 'pay-102');
  assert.equal(run[5]?.items.flash.kind, 'calib');
  assert.equal(run[5]?.message.includes('校准'), true);
  assert.equal(run[6]?.metrics.committed, 3);
  assert.equal(run[6]?.items.lastSeq, 6);
  assert.equal(run[6]?.items.parts.P0.length, 3);
  assert.equal(run[6]?.items.flash.kind, 'calib');
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(end?.message.includes('at-least-once'), true);
  assert.equal(end?.items.flash, null);
  assert.equal(end?.items.producer.st, 'done');
  assert.deepEqual(end?.metrics, { sent: 5, stored: 3, committed: 3, blocked: 2 });
});
test('kafka-eos transaction: two-phase commit + abort marker isolation via LSO', () => {
  const run = simulate('kafka-eos', { scenario: 'transaction' });
  assert.equal(run.length, 9);
  assert.equal(run[0]?.items.producer.pid, 21);
  assert.equal(run[0]?.items.lastSeq, 0);
  assert.deepEqual(run[0]?.items.lso, { P0: 2, P1: 2 });
  assert.deepEqual(run[0]?.items.coordinator, { st: 'idle', txn: null, epoch: 1, holder: 'P' });
  assert.equal(run[1]?.items.coordinator.txn, 'T1');
  assert.equal(run[1]?.items.coordinator.st, 'active');
  assert.equal(run[2]?.metrics.sent, 1);
  assert.equal(run[2]?.metrics.stored, 1);
  assert.equal(run[2]?.items.parts.P0[0].st, 'pend');
  assert.equal(run[2]?.message.includes('未提交段'), true);
  assert.equal(run[3]?.items.parts.P1[0].st, 'pend');
  assert.equal(run[3]?.message.includes('原子性'), true);
  assert.equal(run[4]?.metrics.committed, 2);
  assert.equal(run[4]?.items.parts.P0[0].st, 'ok');
  assert.equal(run[4]?.items.parts.P1[0].st, 'ok');
  assert.deepEqual(run[4]?.items.lso, { P0: 3, P1: 3 });
  assert.equal(run[4]?.items.flash.kind, 'marker');
  assert.equal(run[4]?.message.includes('PREPARE'), true);
  assert.equal(run[5]?.metrics.sent, 3);
  assert.equal(run[5]?.items.coordinator.txn, 'T2');
  assert.equal(run[5]?.items.flash, null);
  assert.equal(run[6]?.metrics.blocked, 1);
  assert.equal(run[6]?.items.parts.P0[1].st, 'abort');
  assert.deepEqual(run[6]?.items.lso, { P0: 4, P1: 3 });
  assert.equal(run[6]?.items.flash.kind, 'abort');
  assert.equal(run[6]?.message.includes('物理还在'), true);
  assert.equal(run[6]?.message.includes('marker 圈禁'), true);
  assert.equal(run[7]?.items.flash, null);
  assert.equal(run[7]?.items.parts.P0[1].st, 'abort');
  assert.equal(run[7]?.message.includes('仿佛从未发生过'), true);
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(end?.message.includes('零感知'), true);
  assert.equal(end?.items.flash, null);
  assert.equal(end?.items.producer.st, 'done');
  assert.deepEqual(end?.metrics, { sent: 3, stored: 3, committed: 2, blocked: 1 });
});
test('kafka-eos fencing: epoch bump fences zombie instance, stale commit rejected', () => {
  const run = simulate('kafka-eos', { scenario: 'fencing' });
  assert.equal(run.length, 9);
  assert.equal(run[0]?.items.producer.epoch, 1);
  assert.deepEqual(run[0]?.items.coordinator, { st: 'idle', txn: null, epoch: 1, holder: 'A' });
  assert.deepEqual(run[0]?.items.lso, { P0: 1, P1: 1 });
  assert.equal(run[1]?.items.parts.P0[0].by, 'A');
  assert.equal(run[1]?.items.parts.P0[0].st, 'pend');
  assert.equal(run[1]?.items.coordinator.txn, 'T1');
  assert.equal(run[2]?.items.producer.st, 'down');
  assert.equal(run[2]?.message.includes('悬为 pending'), true);
  assert.equal(run[3]?.items.producer.epoch, 2);
  assert.equal(run[3]?.items.coordinator.epoch, 2);
  assert.equal(run[3]?.items.coordinator.holder, 'B');
  assert.equal(run[3]?.message.includes('InitPid'), true);
  assert.equal(run[4]?.metrics.blocked, 1);
  assert.equal(run[4]?.items.parts.P0[0].st, 'abort');
  assert.equal(run[4]?.items.flash.kind, 'abort');
  assert.equal(run[4]?.message.includes('作废'), true);
  assert.equal(run[5]?.metrics.sent, 3);
  assert.equal(run[5]?.metrics.stored, 3);
  assert.equal(run[5]?.items.parts.P0[1].by, 'B');
  assert.equal(run[5]?.items.parts.P0[1].st, 'pend');
  assert.equal(run[5]?.items.parts.P1[0].by, 'B');
  assert.equal(run[5]?.items.flash, null);
  assert.equal(run[6]?.metrics.committed, 2);
  assert.equal(run[6]?.items.parts.P0[1].st, 'ok');
  assert.equal(run[6]?.items.parts.P1[0].st, 'ok');
  assert.deepEqual(run[6]?.items.lso, { P0: 3, P1: 2 });
  assert.equal(run[6]?.items.flash.kind, 'marker');
  assert.equal(run[7]?.metrics.blocked, 2);
  assert.equal(run[7]?.items.flash.kind, 'fence');
  assert.equal(run[7]?.message.includes('FencedInstanceEpochException'), true);
  assert.equal(run[7]?.message.includes('代数校验'), true);
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(end?.message.includes('四层'), true);
  assert.equal(end?.message.includes('read_committed'), true);
  assert.equal(end?.items.flash, null);
  assert.equal(end?.items.producer.st, 'done');
  assert.equal(end?.items.producer.epoch, 2);
  assert.equal(end?.items.coordinator.epoch, 2);
  assert.equal(end?.items.coordinator.holder, 'B');
  assert.deepEqual(end?.metrics, { sent: 3, stored: 3, committed: 2, blocked: 2 });
});
test('kafka-eos: scenarios isolate state and default to idempotent', () => {
  const idem = simulate('kafka-eos', { scenario: 'idempotent' });
  const txn = simulate('kafka-eos', { scenario: 'transaction' });
  const fence = simulate('kafka-eos', { scenario: 'fencing' });
  assert.equal(simulate('kafka-eos', {}).length, idem.length);
  assert.deepEqual(simulate('kafka-eos', {}).at(-1)?.metrics, { sent: 5, stored: 3, committed: 3, blocked: 2 });
  assert.equal(idem.some(f => f.items.coordinator !== null), false);
  assert.equal(idem.some(f => f.items.lso !== null), false);
  assert.equal(idem.some(f => f.items.parts.P1.length > 0), false);
  assert.equal(idem.some(f => f.items.flash && f.items.flash.kind === 'marker'), false);
  assert.equal(idem.some(f => f.items.flash && f.items.flash.kind === 'abort'), false);
  assert.equal(idem.some(f => f.items.flash && f.items.flash.kind === 'fence'), false);
  assert.equal(idem.filter(f => f.items.flash && f.items.flash.kind === 'dup').length, 1);
  assert.equal(idem.filter(f => f.items.flash && f.items.flash.kind === 'gap').length, 1);
  assert.equal(idem.filter(f => f.items.flash && f.items.flash.kind === 'calib').length, 2);
  assert.equal(txn.some(f => f.items.lastSeq > 0), false);
  assert.equal(txn.some(f => f.items.flash && f.items.flash.kind === 'fence'), false);
  assert.equal(txn.some(f => f.items.flash && f.items.flash.kind === 'dup'), false);
  assert.equal(txn.some(f => f.items.flash && f.items.flash.kind === 'gap'), false);
  assert.equal(txn.filter(f => f.items.flash && f.items.flash.kind === 'marker').length, 1);
  assert.equal(txn.filter(f => f.items.flash && f.items.flash.kind === 'abort').length, 1);
  assert.equal(fence.some(f => f.items.flash && f.items.flash.kind === 'dup'), false);
  assert.equal(fence.some(f => f.items.flash && f.items.flash.kind === 'gap'), false);
  assert.equal(fence.filter(f => f.items.flash && f.items.flash.kind === 'fence').length, 1);
  assert.equal(fence.filter(f => f.items.flash && f.items.flash.kind === 'abort').length, 1);
  assert.equal(fence.at(-1)?.items.coordinator.epoch, 2);
  assert.equal(fence.at(-1)?.items.coordinator.holder, 'B');
  assert.equal(txn.at(-1)?.items.coordinator.epoch, 1);
});
test('es-write: nrt scenario walks buffer → refresh → searchable segments', () => {
  const run = simulate('es-write', { scenario: 'nrt' });
  assert.equal(run.length, 10);
  assert.equal(run[0]?.items.state, 'idle');
  assert.equal(run[0]?.message.includes('近实时'), true);
  assert.equal(run[1]?.metrics.docs, 1);
  assert.deepEqual(run[1]?.items.buffer, ['w1']);
  assert.equal(run[1]?.items.tlog[0].fs, true);
  assert.deepEqual(run[3]?.items.buffer, ['w1', 'w2', 'w3']);
  assert.equal(run[4]?.items.search.hits.length, 0);
  assert.equal(run[4]?.items.flash.kind, 'miss');
  assert.equal(run[5]?.metrics.refreshs, 1);
  assert.deepEqual(run[5]?.items.segs, [{ id: 'seg-A', docs: ['w1', 'w2', 'w3'], mem: true, del: [] }]);
  assert.equal(run[5]?.items.buffer.length, 0);
  assert.equal(run[5]?.items.search, null);
  assert.equal(run[5]?.items.flash.kind, 'refresh');
  assert.deepEqual(run[6]?.items.search.hits, ['w1', 'w2', 'w3']);
  assert.equal(run[7]?.metrics.docs, 4);
  assert.deepEqual(run[7]?.items.buffer, ['w4']);
  assert.equal(run[8]?.metrics.refreshs, 2);
  assert.equal(run[8]?.items.segs.length, 2);
  assert.equal(run[8]?.items.segs[1].docs[0], 'w4');
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.deepEqual(end?.metrics, { docs: 4, refreshs: 2, merges: 0, replayed: 0 });
  assert.deepEqual(end?.items.search.hits, ['w1', 'w2', 'w3', 'w4']);
  assert.equal(end?.items.flash, null);
});
test('es-write: crash scenario loses only the un-fsynced tail', () => {
  const run = simulate('es-write', { scenario: 'crash' });
  assert.equal(run.length, 10);
  assert.equal(run[0]?.items.state, 'ok');
  assert.equal(run[0]?.message.includes('崩溃恢复'), true);
  assert.equal(run[3]?.metrics.docs, 3);
  assert.equal(run[4]?.metrics.refreshs, 1);
  assert.deepEqual(run[4]?.items.segs[0].docs, ['w1', 'w2', 'w3']);
  assert.equal(run[4]?.items.segs[0].mem, true);
  assert.equal(run[5]?.metrics.docs, 5);
  assert.deepEqual(run[5]?.items.buffer, ['w4', 'w5']);
  assert.equal(run[5]?.items.tlog[3].fs, false);
  assert.equal(run[5]?.items.tlog[4].fs, false);
  assert.equal(run[6]?.items.state, 'down');
  assert.deepEqual(run[6]?.items.buffer, []);
  assert.deepEqual(run[6]?.items.segs, []);
  assert.equal(run[6]?.items.tlog.length, 3);
  assert.equal(run[6]?.items.tlog.every(l => l.fs), true);
  assert.deepEqual(run[6]?.items.lost, ['w4', 'w5']);
  assert.equal(run[6]?.items.flash.kind, 'crash');
  assert.equal(run[7]?.items.state, 'recovering');
  assert.equal(run[7]?.metrics.replayed, 3);
  assert.deepEqual(run[7]?.items.segs[0].docs, ['w1', 'w2', 'w3']);
  assert.equal(run[7]?.items.flash.kind, 'replay');
  assert.equal(run[8]?.items.state, 'ok');
  assert.deepEqual(run[8]?.items.search.hits, ['w1', 'w2', 'w3']);
  assert.equal(run[8]?.items.flash.kind, 'lost');
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.equal(end?.message.includes('durability'), true);
  assert.deepEqual(end?.metrics, { docs: 5, refreshs: 1, merges: 0, replayed: 3 });
  assert.deepEqual(end?.items.lost, ['w4', 'w5']);
  assert.equal(end?.items.flash, null);
});
test('es-write: merge scenario clears tombstones only at merge', () => {
  const run = simulate('es-write', { scenario: 'merge' });
  assert.equal(run.length, 12);
  assert.equal(run[0]?.message.includes('段合并'), true);
  assert.equal(run[4]?.metrics.docs, 4);
  assert.equal(run[4]?.metrics.refreshs, 4);
  assert.equal(run[4]?.items.segs.length, 4);
  assert.deepEqual(run[5]?.items.search.hits, ['w1', 'w2', 'w3', 'w4']);
  assert.equal(run[6]?.metrics.merges, 1);
  assert.equal(run[6]?.items.segs.length, 2);
  assert.equal(run[6]?.items.segs[0].mem, false);
  assert.deepEqual(run[6]?.items.segs[0].docs, ['w1', 'w2', 'w3']);
  assert.equal(run[6]?.items.flash.kind, 'merge');
  assert.equal(run[7]?.metrics.docs, 5);
  assert.deepEqual(run[7]?.items.buffer, ['w2′']);
  assert.deepEqual(run[7]?.items.segs.find(s => s.id === 'seg-A').del, ['w2']);
  assert.equal(run[7]?.items.search, null);
  assert.equal(run[8]?.metrics.refreshs, 5);
  assert.equal(run[8]?.items.segs.length, 3);
  assert.equal(run[8]?.items.flash.kind, 'refresh');
  assert.deepEqual(run[9]?.items.segs.find(s => s.id === 'seg-A').del, ['w2', 'w3']);
  assert.equal(run[9]?.items.flash.kind, 'del');
  assert.equal(run[10]?.metrics.merges, 2);
  assert.equal(run[10]?.items.segs.length, 1);
  assert.deepEqual(run[10]?.items.segs[0].docs, ['w1', 'w2′', 'w4']);
  assert.equal(run[10]?.items.segs[0].del.length, 0);
  assert.equal(run[10]?.items.flash.kind, 'merge');
  const end = run.at(-1);
  assert.equal(end?.message.includes('运行结束'), true);
  assert.deepEqual(end?.metrics, { docs: 5, refreshs: 5, merges: 2, replayed: 0 });
  assert.deepEqual(end?.items.search.hits, ['w1', 'w2′', 'w4']);
  assert.equal(end?.items.flash, null);
});
test('es-write: scenarios isolate state and default to nrt', () => {
  const nrt = simulate('es-write', {});
  const crash = simulate('es-write', { scenario: 'crash' });
  const merge = simulate('es-write', { scenario: 'merge' });
  assert.equal(nrt.length, simulate('es-write', { scenario: 'nrt' }).length);
  assert.deepEqual(nrt.at(-1)?.metrics, { docs: 4, refreshs: 2, merges: 0, replayed: 0 });
  assert.equal(nrt.some(f => f.items.state === 'down' || f.items.state === 'recovering'), false);
  assert.equal(nrt.some(f => f.items.lost.length > 0), false);
  assert.equal(crash.filter(f => f.items.state === 'down').length, 1);
  assert.equal(crash.some(f => f.metrics.merges > 0), false);
  assert.equal(crash.at(-1)?.items.lost.length, 2);
  assert.equal(merge.some(f => f.metrics.replayed > 0), false);
  assert.equal(merge.some(f => f.items.state === 'down' || f.items.state === 'recovering'), false);
  assert.equal(merge.some(f => f.items.lost.length > 0), false);
  assert.equal(nrt.filter(f => f.items.flash && f.items.flash.kind === 'refresh').length, 2);
  assert.equal(crash.filter(f => f.items.flash && f.items.flash.kind === 'refresh').length, 1);
  assert.equal(merge.filter(f => f.items.flash && f.items.flash.kind === 'refresh').length, 1);
  assert.equal(nrt.filter(f => f.items.flash && f.items.flash.kind === 'miss').length, 1);
  assert.equal(crash.filter(f => f.items.flash && f.items.flash.kind === 'crash').length, 1);
  assert.equal(crash.filter(f => f.items.flash && f.items.flash.kind === 'replay').length, 1);
  assert.equal(crash.filter(f => f.items.flash && f.items.flash.kind === 'lost').length, 1);
  assert.equal(merge.filter(f => f.items.flash && f.items.flash.kind === 'merge').length, 2);
  assert.equal(merge.filter(f => f.items.flash && f.items.flash.kind === 'del').length, 1);
  assert.equal(nrt.some(f => f.items.flash && f.items.flash.kind === 'crash'), false);
  assert.equal(nrt.some(f => f.items.flash && f.items.flash.kind === 'del'), false);
  assert.equal(crash.some(f => f.items.flash && f.items.flash.kind === 'del'), false);
});
