import { redisLabs } from './redisCatalog.js';
import { jvmLabs } from './jvmCatalog.js';

export const labs = [
  {
    id: 'hashmap', group: 'Java 核心', title: 'HashMap 存储与扩容', short: 'HashMap', icon: 'Boxes', tag: '集合框架', number: '01',
    summary: '从一个 key 出发，观察哈希寻址、碰撞与扩容的全过程。',
    defaults: { capacity: 4, factor: 0.75, entries: 6 },
    fields: [
      { key: 'capacity', label: '初始容量', type: 'select', options: [[4, '4'], [8, '8'], [16, '16']] },
      { key: 'factor', label: '负载因子', type: 'select', options: [[0.5, '0.50'], [0.75, '0.75'], [1, '1.00']] },
      { key: 'entries', label: '插入数量', min: 1, max: 12, unit: '个' },
    ],
    metrics: [['size', '元素数量', ''], ['capacity', '当前容量', ''], ['threshold', '扩容阈值', ''], ['resizes', '扩容次数', '次']],
    nodes: [['key', '输入键值', 'String key', 'Braces', 'blue'], ['hash', '哈希扰动', 'hash ^ (hash >>> 16)', 'Binary', 'yellow'], ['buckets', '数组与链表', 'Node<K, V>[] table', 'Boxes', 'green'], ['resize', '容量扩展', 'newCap = oldCap << 1', 'Expand', 'pink']],
    edges: [['key', 'hash', 'hashCode()'], ['hash', 'buckets', '(n - 1) & hash'], ['buckets', 'resize', 'size > threshold']],
    code: ['Map<String, Integer> map = new HashMap<>();', 'int h = key.hashCode() ^ (key.hashCode() >>> 16);', 'int index = (table.length - 1) & h;', 'if (++size > threshold) resize();'],
    theory: [['寻址公式', 'index = (n − 1) & hash', '容量为 2 的幂，使位运算均匀映射到桶。'], ['扩容时机', 'size > capacity × loadFactor', '插入新元素后超过阈值才触发扩容。'], ['碰撞不是覆盖', 'Aa.hashCode() = BB.hashCode()', '哈希相同的不同 key 仍通过 equals 区分。']],
    boundary: '以 JDK 8+ 的字符串键为例，演示数组、碰撞和扩容；未模拟红黑树树化。初始容量按已分配 table 展示。',
    source: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/HashMap.html',
  },
  {
    id: 'threadpool', group: 'Java 核心', title: '线程池任务调度', short: '线程池', icon: 'Workflow', tag: '并发编程', number: '02',
    summary: '一个任务提交之后，究竟会创建线程、进入队列，还是被拒绝？',
    defaults: { core: 2, max: 4, queue: 3, tasks: 10, policy: 'abort' },
    fields: [
      { key: 'core', label: '核心线程数', min: 1, max: 4, unit: '个' },
      { key: 'max', label: '最大线程数', min: 1, max: 6, unit: '个' },
      { key: 'queue', label: '队列容量', min: 1, max: 6, unit: '个' },
      { key: 'tasks', label: '提交任务数', min: 1, max: 16, unit: '个' },
      { key: 'policy', label: '拒绝策略', type: 'select', options: [['abort', 'AbortPolicy'], ['caller', 'CallerRunsPolicy']] },
    ],
    metrics: [['submitted', '已提交', ''], ['workers', '工作线程', ''], ['queued', '排队任务', ''], ['rejected', '被拒绝', '']],
    nodes: [['submit', '任务提交', 'execute(Runnable)', 'Send', 'blue'], ['queue', '阻塞队列', 'ArrayBlockingQueue', 'ListOrdered', 'yellow'], ['workers', '工作线程', 'Worker threads', 'Cpu', 'green'], ['reject', '饱和策略', 'RejectedExecutionHandler', 'ShieldAlert', 'pink']],
    edges: [['submit', 'workers', '① 核心线程'], ['submit', 'queue', '② 入队'], ['queue', 'workers', '③ 扩展线程'], ['queue', 'reject', '④ 饱和']],
    code: ['executor.execute(task);', 'if (workers < corePoolSize) addWorker(task, true);', 'else if (workQueue.offer(task)) return;', 'else if (workers < maximumPoolSize) addWorker(task, false);', 'else handler.rejectedExecution(task, executor);'],
    theory: [['接收顺序', '核心线程 → 队列 → 最大线程', '先入队，再扩展非核心线程，而非直接扩到最大值。'], ['拒绝条件', '队列已满 && workers = max', 'AbortPolicy 抛出 RejectedExecutionException。'], ['反压策略', 'CallerRunsPolicy', '调用线程执行任务，可能减缓继续提交的速率。']],
    boundary: '展示任务在工作线程持续忙碌时的接收顺序，不模拟任务结束、线程回收与真实并发时序。CallerRuns 任务按顺序完成。',
    source: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/ThreadPoolExecutor.html',
  },
  {
    id: 'sync-lock', group: 'Java 核心', title: 'synchronized 锁升级与 Monitor', short: 'synchronized 锁升级', icon: 'Monitor', tag: '并发编程', number: '03',
    summary: '同一把锁，无竞争走偏向、短临界区走轻量级自旋、激烈竞争才膨胀成重量级 Monitor——跟随 Mark Word 看锁如何升级。',
    defaults: { scenario: 'biased' },
    fields: [{ key: 'scenario', label: '竞争场景', type: 'select', options: [['biased', '① 无竞争 → 偏向锁'], ['light', '② 交替竞争 → 轻量级锁'], ['heavy', '③ 激烈竞争 → 重量级锁']] }],
    metrics: [['locks', '加锁成功', '次'], ['spins', '自旋等待', '次'], ['blocks', '阻塞挂起', '次'], ['upgrades', '升级次数', '次']],
    nodes: [['thread', '竞争线程', 'T1 · T2 · T3 竞争同锁', 'Cpu', 'blue'], ['mark', '对象头 Mark Word', '无锁 / 偏向 / 轻量 / 重量', 'Braces', 'yellow'], ['entry', '临界区', 'synchronized 方法体', 'Workflow', 'green'], ['monitor', '重量级 Monitor', 'Owner · EntryList', 'Monitor', 'pink'], ['block', 'EntryList 队列', 'park 挂起等待唤醒', 'ListOrdered', 'yellow']],
    edges: [['thread', 'mark', '竞争进入'], ['mark', 'entry', '获锁成功'], ['mark', 'monitor', '自旋失败膨胀'], ['monitor', 'block', '线程 park'], ['monitor', 'entry', '唤醒移交锁']],
    code: ['public synchronized void critical() { /* 临界区 */ }', '// 偏向锁：首线程 CAS 把自身线程 id 写入 Mark Word 偏向位，之后同线程重入零成本', '// 轻量级锁：线程栈建 Lock Record 拷贝 Mark Word，CAS 替换为指向锁记录的指针', '// 自旋超过阈值仍未成功 → 锁膨胀：Mark Word 改为指向 ObjectMonitor', '// 重量级锁：未获锁线程 park 挂起进入 EntryList，持锁线程释放后由 Monitor 唤醒', '// 锁释放：恢复 Mark Word，唤醒下一个等待线程'],
    theory: [['偏向锁', 'Mark Word 记录首线程 id', '首线程 CAS 一次即长期持有，同线程反复进入零开销；出现竞争才撤销偏向——适合单线程重复访问。'], ['轻量级锁', 'Lock Record + CAS 自旋', '线程栈里建锁记录拷贝原 Mark Word，再用 CAS 换成锁记录指针；失败先短暂自旋，假定临界区很快结束。'], ['重量级锁', 'ObjectMonitor 与 EntryList', '自旋超过阈值就膨胀：Mark Word 指向 ObjectMonitor，未获锁线程 park 进 EntryList，由 Monitor 负责唤醒——高竞争下让出 CPU 更划算。']],
    goals: ['看懂 Mark Word 三种锁状态的迁移条件：无竞争、短临界区交替、激烈竞争', '能说出自旋与阻塞的选择依据：临界区长短与竞争强度', '知道偏向撤销与锁膨胀各在什么时机触发'],
    challenge: { task: '固定同一把锁与临界区，用三个竞争场景各运行一次：① T1 单线程反复进入 ② T1 持锁期间 T2 进入且临界区短 ③ T1 长时间持锁、T2/T3 持续竞争。期望：① 只做一次 CAS 全程偏向锁，零自旋零阻塞 ② 偏向撤销后以轻量级锁运行，自旋成功无阻塞 ③ 自旋超阈值膨胀为重量级锁，T2/T3 park 进 EntryList 逐个被唤醒。', hint: '注意 Mark Word 状态 token 的颜色变化（黄偏向 → 绿轻量 → 粉重量）；重量级场景先看自旋计数再看出阻塞。', success: '能画出 偏向 → 轻量级 → 重量级 的升级链，并说明每步的触发条件与代价。', requirements: [{ id: 'biased', label: '① 无竞争 · 偏向锁', when: { scenario: 'biased' } }, { id: 'light', label: '② 交替竞争 · 轻量级锁', when: { scenario: 'light' } }, { id: 'heavy', label: '③ 激烈竞争 · 重量级锁', when: { scenario: 'heavy' } }] },
    quiz: [
      { prompt: '偏向锁最适合下列哪种使用场景？', choices: ['多个线程激烈竞争同一把锁', '同一个线程反复进入临界区、几乎没有竞争', '临界区里抛出异常的锁'], answer: 1, explanation: '偏向锁把锁记到首线程，之后重入零成本；一旦其他线程竞争就要撤销，所以只适合低竞争场景。' },
      { prompt: '轻量级锁 CAS 加锁失败时，线程会怎么做？', choices: ['立即 park 挂起进入阻塞队列', '先原地自旋重试 CAS，等待持锁线程尽快释放', '直接抛出异常'], answer: 1, explanation: '轻量级锁假定临界区很短，失败先短暂自旋；自旋超过阈值才膨胀为重量级锁并阻塞。' },
    ],
    boundary: '教学脚本按固定事件推进，忽略偏向撤销的安全点时机、批量重偏向/批量撤销、锁消除与锁粗化、自适应自旋参数以及各 JDK 版本的实现差异（JDK 15+ 已默认禁用偏向锁，本模型按 JDK 6-14 的行为演示），不能作为生产调优依据。',
    source: 'https://docs.oracle.com/javase/tutorial/essential/concurrency/locksync.html',
  },
  {
    id: 'aqs-queue', group: 'Java 核心', title: 'ReentrantLock 与 AQS 队列', short: 'ReentrantLock 与 AQS', icon: 'ListOrdered', tag: '并发编程', number: '04',
    summary: '拿不到锁的线程去哪里排队？看 state 计数与 CLH 等待队列如何完成获取、重入与唤醒。',
    defaults: { scenario: 'fair' },
    fields: [{ key: 'scenario', label: '获取模式', type: 'select', options: [['fair', '① 公平模式 · FIFO 排队'], ['reentrant', '② 可重入 · state 计数'], ['nonfair', '③ 非公平 · 释放瞬间插队']] }],
    metrics: [['locks', '获取成功', '次'], ['reentries', '重入加锁', '次'], ['parks', '排队挂起', '次'], ['handoffs', '唤醒移交', '次']],
    nodes: [['thread', '竞争线程', 'T1 · T2 · T3 调用 lock()', 'Cpu', 'blue'], ['cas', 'CAS 尝试', 'compareAndSet(0, 1)', 'Braces', 'yellow'], ['state', '同步状态', 'state: 0 空闲 · 1 占用 · N 重入', 'Database', 'green'], ['queue', 'CLH 等待队列', 'head ↔ tail 双向链表', 'ListOrdered', 'pink'], ['park', '线程挂起', 'parkAndCheckInterrupt', 'Monitor', 'pink']],
    edges: [['thread', 'cas', 'lock() 进入'], ['cas', 'state', 'CAS 成功置 1'], ['cas', 'queue', '获取失败入队'], ['queue', 'park', 'park 挂起等待'], ['queue', 'state', '队首被唤醒重抢']],
    code: ['lock.lock();', 'if (state == 0 && compareAndSet(0, 1)) { owner = currentThread; }', 'else if (owner == currentThread) { state++; /* 可重入 */ }', 'else enqueue(node); parkAndCheckInterrupt();', 'lock.unlock();', 'if (state == 1) { state = 0; unparkSuccessor(head.next); }'],
    theory: [['同步状态 state', '0 空闲 · 1 占用 · N 重入', 'state=0 表示无锁；首次获取 CAS 0→1；同一线程可重入使 state 递增，每次 unlock 递减，归零才真正释放锁。'], ['CLH 等待队列', '获取失败的线程排队', 'AQS 用双向链表排队，节点内线程 park 挂起省 CPU；释放时 unpark 队首后继，由它重新竞争。'], ['公平与非公平', 'FIFO 与插队的取舍', 'FairSync 只有自己是队首才获取；NonfairSync 在入队前先直接 CAS 抢一次，吞吐更高，但可能让队首线程饿得久一点。']],
    goals: ['说出 state 的含义：0 空闲、1 被占用、N 表示同一线程重入 N 次', '画出获取失败的线程进入 CLH 队列并 park 挂起的完整链路', '对比公平锁 FIFO 与非公平锁释放瞬间插队的行为差异与代价'],
    challenge: { task: '固定同一把锁，用三个获取模式各运行一次：① T1 持锁期间 T2/T3 先后到达排队，释放后按 FIFO 依次获锁 ② T1 持锁期间自己再次 lock，state 从 1 涨到 2，观察释放两次才归零 ③ T1 持锁、T2 已入队等待，T1 释放瞬间新线程 T3 直接 CAS 插队成功。期望：① 唤醒移交 2 次且顺序 T2→T3 ② 重入加锁 1 次、state 出现过 2 ③ 排队挂起只有 1（T2），T3 未排队就拿到锁。', hint: '看 CLH 队列 token 的变化与 state 读数：公平场景队列从头到尾逐个清空；重入场景 state 出现 2 且 owner 始终是 T1；非公平场景 T3 获锁时 T2 仍在队列里。', success: '能解释 state 计数的释放规则，并说清公平队列与非公平插队在获取顺序上的差别。', requirements: [{ id: 'fair', label: '① 公平模式 · FIFO 排队', when: { scenario: 'fair' } }, { id: 'reentrant', label: '② 可重入 · state 计数', when: { scenario: 'reentrant' } }, { id: 'nonfair', label: '③ 非公平 · 释放瞬间插队', when: { scenario: 'nonfair' } }] },
    quiz: [
      { prompt: 'ReentrantLock 中 state=2 表示什么？', choices: ['两个不同线程各持锁一次', '同一线程重入了两次，需要释放两次', 'CLH 队列里有两个等待线程'], answer: 1, explanation: 'state 记录持有次数：只有持锁线程自己能重入，state 递增；每次 unlock 递减，归零才真正释放锁。' },
      { prompt: '公平锁 FairSync 的获取条件是什么？', choices: ['线程必须已经是 CLH 队首（或队列为空）才能获取', '任何新线程都可以直接 CAS 插队', '等待线程 park 后由 JVM 随机唤醒'], answer: 0, explanation: '公平锁在入队前先检查 hasQueuedPredecessors：队列非空且自己不是队首就乖乖入队，保证先到先得。' },
    ],
    boundary: '以 lock()/unlock() 的离散事件演示 state 与 CLH 队列的核心语义；忽略中断、超时、Condition、读写锁分离与节点 waitStatus 细节，非公平模式只演示释放瞬间的单次插队，未模拟线程取消与队列清理。',
    source: 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/locks/AbstractQueuedSynchronizer.html',
  },
  {
    id: 'volatile-jmm', group: 'Java 核心', title: 'volatile 与内存可见性', short: 'volatile 与 JMM', icon: 'ShieldAlert', tag: '并发编程', number: '14',
    summary: '一个线程的写入另一个线程何时能看到？volatile 保证可见性与禁止重排，却管不了 i++ 的原子性——三个场景逐一演示 JMM 三条经典语义。',
    defaults: { scenario: 'visible' },
    fields: [{ key: 'scenario', label: '并发问题场景', type: 'select', options: [['visible', '① 可见性 · 普通字段 vs volatile'], ['order', '② 指令重排 · 双重检查锁'], ['atomic', '③ 原子性 · volatile 的局限']] }],
    metrics: [['reads', '线程读', '次'], ['writes', '写回主存', '次'], ['lost', '丢失更新', '次'], ['barriers', '屏障生效', '次']],
    nodes: [['shared', '主存共享变量', 'flag · instance · count', 'Database', 'green'], ['cache', '线程缓存', 'L1 缓存行 · 寄存器', 'Cpu', 'yellow'], ['t1', '线程 T1', '写入者 · 发布者', 'Send', 'blue'], ['t2', '线程 T2', '读取者 · 使用者', 'Monitor', 'pink'], ['volatile', 'volatile 语义', '可见性 · 禁止重排', 'ShieldAlert', 'yellow'], ['atomic', '原子化修复', 'synchronized · CAS', 'Braces', 'green']],
    edges: [['t1', 'cache', '① 写入本地副本'], ['cache', 'shared', '② 回写主存'], ['shared', 'cache', '③ 缓存行失效重读'], ['cache', 't2', '④ T2 读到副本'], ['volatile', 'shared', '⑤ 屏障约束读写'], ['t2', 'atomic', '⑥ 复合操作需原子化']],
    code: ['boolean flag = false;  // 非 volatile', '// T2: while (!flag) { /* 轮询本地缓存副本 */ }', '// T1: flag = true;  // 仅写 CPU 缓存，未同步主存', 'volatile boolean flag;  // 加 volatile', '// volatile 写 → 立即回写主存并广播失效其他核心的缓存行', '// volatile 读 → 穿透缓存读主存最新值，建立 happens-before'],
    theory: [['可见性', 'volatile 写-读建立 happens-before', '普通字段的写先落在线程私有缓存/寄存器，其他线程可能长期读旧值（JIT 甚至把循环读提升到循环外）。volatile 写在发布后立即回写主存并使其他核心缓存行失效，读方下次必得最新值。'], ['禁止重排', 'volatile 读写插屏障', 'JMM 保证 volatile 写之前的普通写不会重排到它之后（StoreStore），volatile 读之后的普通读不会重排到它之前——双重检查锁（DCL）靠它保证先构造后发布，防止半初始化对象泄漏。'], ['原子性局限', 'volatile 不管复合操作', 'volatile 只保证读写本身原子与可见，count++ 这类 read-modify-write 仍会交错丢更新：两个线程各加一次可能终值只 +1。要原子得用 synchronized 或 AtomicInteger（CAS）。']],
    goals: ['用普通字段 vs volatile 解释可见性：写方回写主存、读方缓存行失效重读', '说出 volatile 如何禁止重排（StoreStore 屏障）与双重检查锁的正确写法', '知道 volatile 的边界：不保证 i++ 原子，需 synchronized / CAS 才能原子化'],
    challenge: { task: '固定同一幕并发脚本，用三个场景各运行一次：① T1 发布 flag=true，T2 循环等待退出——先普通字段后加 volatile ② 双重检查锁中 T1 发布 instance，T2 检空后直接使用——先普通字段（重排泄漏半初始化对象）后加 volatile ③ T1/T2 对 volatile count 各自增一次——先裸 volatile（丢更新）后用原子操作。期望：① 丢失 2 次、写回 1 次、屏障 1 次，T2 最终退出循环 ② T2 用到半初始化对象 1 次，volatile 后顺序固定 ③ 裸自增终值 1、丢 1 次更新，原子化后终值 2。', hint: '看主存与 T1/T2 视角 token：非 volatile 时 T1 已写而主存不变；加 volatile 后 token 变绿且值同步；atomic 场景关注 count 终值与丢失计数。', success: '能区分可见性、重排与原子性三类问题，并说出 volatile 各管哪一样、管不了哪一样。', requirements: [{ id: 'visible', label: '① 可见性 · 普通字段 vs volatile', when: { scenario: 'visible' } }, { id: 'order', label: '② 指令重排 · 双重检查锁', when: { scenario: 'order' } }, { id: 'atomic', label: '③ 原子性 · volatile 的局限', when: { scenario: 'atomic' } }] },
    quiz: [
      { prompt: '两个线程共享一个普通 boolean flag，T1 把它置 true，T2 循环 while (!flag) 等待——最常见的问题是？', choices: ['T2 编译报错，循环无法通过检查', 'T2 可能永远看不到 true：写留在 T1 的缓存/寄存器里，读方缓存行未失效', 'flag 只能由 T1 修改，其他线程无权读取'], answer: 1, explanation: '非 volatile 字段的读写可停留在线程私有缓存；JIT 甚至把循环读提升出循环。加 volatile 后写回主存并失效读方缓存，读方才能及时看到。' },
      { prompt: 'volatile 为什么能修正双重检查锁（DCL）？', choices: ['它把 synchronized 块变成了无锁代码', 'volatile 写插入 StoreStore 屏障，保证对象构造先于引用发布，防止读到半初始化实例', '它让 instance 字段只能被一个线程写入'], answer: 1, explanation: 'new 的分配-构造-写引用三步可能被重排为“先写引用后构造”；volatile 禁止该重排，读到引用时对象必已构造完整。' },
      { prompt: '两个线程各执行一次 volatile int count++，终值可能只是 1，原因是？', choices: ['volatile 的读不是原子的', 'count++ 是读-改-写三步，volatile 不保证复合操作原子，两步写会互相覆盖', 'volatile 字段不允许自增'], answer: 1, explanation: 'volatile 只保证单次读写原子且可见；count++ 会拆成 read / add / store，两个线程同时读 0 后各自写 1，一次更新被覆盖丢失。' },
    ],
    boundary: '以离散事件演示 JMM 三条语义（可见性 / 禁止重排 / 原子性）的定性行为：缓存一致性按失效-回写简化，未模拟 MESI 具体状态机、Store Buffer、JIT 真实优化策略、锁升级与 CAS 内部实现，不构成性能结论。',
    source: 'https://docs.oracle.com/javase/specs/jls/se21/html/jls-17.html',
  },
  ...jvmLabs,
  ...redisLabs,
  {
    id: 'mysql', group: '数据与缓存', title: 'MySQL 索引查询', short: 'MySQL 索引查询', icon: 'Network', tag: '数据库原理', number: '05',
    summary: '对比索引定位与全表扫描，观察 B+ 树叶子页和记录的访问路径。',
    defaults: { indexed: true, target: 42 },
    fields: [{ key: 'target', label: '查询 ID', min: 1, max: 64, unit: '' }, { key: 'indexed', label: '使用主键索引', type: 'toggle' }],
    metrics: [['reads', '访问页数', '页'], ['scanned', '检查记录', '行'], ['target', '目标 ID', ''], ['found', '查询结果', '']],
    nodes: [['query', 'SQL 查询', 'WHERE id = ?', 'CodeXml', 'blue'], ['index', 'B+ 树根页', '17 | 33 | 49', 'Network', 'yellow'], ['leaf', '叶子数据页', 'Clustered index', 'Table2', 'green'], ['result', '查询结果', 'Row data', 'FileCheck2', 'pink']],
    edges: [['query', 'index', '索引定位'], ['index', 'leaf', '定位叶子页'], ['leaf', 'result', '返回记录']],
    code: ['SELECT * FROM users WHERE id = ?;', '// B+ tree: search root page', '// Clustered leaf: locate the row within the page', '// Full scan: examine records page by page', '// Return the matching row'],
    theory: [['聚簇索引', '叶子节点保存完整记录', '按主键查询无需额外回表。'], ['页内查找', '有序记录定位', '演示固定两层索引与每页 16 条记录。'], ['成本比较', '逻辑页访问 ≠ 物理磁盘 I/O', '实际读取成本还受 Buffer Pool 和优化器影响。']],
    boundary: '固定 64 行、两层树与每页 16 行的教学模型，统计逻辑页访问及检查记录数，不是 MySQL EXPLAIN 或实际磁盘 I/O。',
    source: 'https://dev.mysql.com/doc/refman/8.4/en/innodb-index-types.html',
  },
  {
    id: 'mysql-isolation', group: '数据与缓存', title: 'MySQL 事务与隔离级别', short: 'MySQL 事务与隔离', icon: 'Table2', tag: '数据库原理', number: '06',
    summary: '运行同一幕并发脚本，切换隔离级别观察脏读、不可重复读、幻读与锁等待的消长。',
    defaults: { isolation: 'repeatable' },
    fields: [{ key: 'isolation', label: '隔离级别', type: 'select', options: [['uncommitted', '读未提交 READ UNCOMMITTED'], ['committed', '读已提交 READ COMMITTED'], ['repeatable', '可重复读 REPEATABLE READ'], ['serializable', '串行化 SERIALIZABLE']] }],
    metrics: [['dirty', '脏读', ''], ['nonRepeatable', '不可重复读', ''], ['phantom', '幻读', ''], ['blocked', '锁等待', '']],
    nodes: [['txb', '读事务 B', 'SELECT 一致性读', 'Monitor', 'blue'], ['txa', '写事务 A', 'UPDATE → COMMIT', 'Send', 'green'], ['row', '数据行 id=1', 'balance: 100 → 500', 'Database', 'yellow'], ['undo', 'MVCC 快照', 'ReadView · 版本链', 'Layers', 'pink']],
    edges: [['txb', 'row', '① 读行 / 范围'], ['txa', 'row', '② 写 500'], ['undo', 'row', '③ 版本可见性'], ['txb', 'undo', '快照 / 新读']],
    code: ['BEGIN; -- 读事务 B：一致性读起点', 'SELECT balance FROM users WHERE id = 1; -- 基线 100', 'UPDATE users SET balance = 500; -- A 未提交写', 'SELECT balance FROM users WHERE id = 1; -- 未提交值可见吗', 'COMMIT; -- A 提交', 'SELECT balance ...; -- 同事务再读：新快照还是旧快照', 'SELECT COUNT(*) WHERE age BETWEEN 20 AND 30; -- 范围读', 'INSERT (age 25); -- 事务 C：SERIALIZABLE 下阻塞', 'COMMIT; -- B 提交，读锁释放'],
    theory: [['隔离级别', '四级一致性与并发度递进', '读未提交 → 读已提交 → 可重复读 → 串行化：越严格异常越少，代价是并发度与阻塞。'], ['快照读', 'ReadView 决定可见版本', 'READ COMMITTED 每语句新建快照；REPEATABLE READ 复用事务首个快照，两次读值一致。'], ['幻读的锁解法', '读锁 / 间隙锁', 'SERIALIZABLE 范围读加锁阻止并发插入；InnoDB 用 next-key 锁在 RR 下近似消除幻读。']],
    goals: ['用四个隔离级别解释脏读、不可重复读、幻读的消长', '区分语句级快照与事务级快照的读一致性差异', '知道 SERIALIZABLE 以读锁与阻塞换取完全一致'],
    challenge: { task: '固定同一幕脚本，用四个隔离级别各运行一次。期望：读未提交三类异常全出现；读已提交只剩不可重复读与幻读；可重复读全部消除；串行化无异常但出现一次锁等待。', hint: '切换隔离级别后点击重新演示，观察第 3、5、8 帧消息与底部异常计数。', success: '能解释为什么级别越高异常越少，以及串行化为什么用阻塞代替异常。', requirements: [{ id: 'uncommitted', label: '读未提交 READ UNCOMMITTED', when: { isolation: 'uncommitted' } }, { id: 'committed', label: '读已提交 READ COMMITTED', when: { isolation: 'committed' } }, { id: 'repeatable', label: '可重复读 REPEATABLE READ', when: { isolation: 'repeatable' } }, { id: 'serializable', label: '串行化 SERIALIZABLE', when: { isolation: 'serializable' } }] },
    quiz: [
      { prompt: '哪个隔离级别允许读到其他事务尚未提交的修改？', choices: ['读已提交 READ COMMITTED', '读未提交 READ UNCOMMITTED', '可重复读 REPEATABLE READ'], answer: 1, explanation: 'READ UNCOMMITTED 不做隔离，直接读最新版本，因此产生脏读。' },
      { prompt: '可重复读下两次读同一行值仍一致，靠什么实现？', choices: ['每条语句重新查库', '事务首个一致性快照（MVCC ReadView）', '把该行锁住直到事务结束'], answer: 1, explanation: 'REPEATABLE READ 复用事务开始后首个 ReadView，快照内读不到之后提交的修改。' },
    ],
    boundary: '以两个并发事务的离散事件演示 MVCC 快照读语义：REPEATABLE READ 采用事务级首个快照，SERIALIZABLE 额外演示范围读锁阻塞插入；标准 SQL 中 RR 仍允许幻读，本模型按 InnoDB 风格快照读（含近似消除幻读）简化；未模拟 next-key 锁细节、死锁检测与回滚。',
    source: 'https://dev.mysql.com/doc/refman/8.4/en/innodb-transaction-isolation-levels.html',
  },
  {
    id: 'es-inverted', group: '数据与缓存', title: 'Elasticsearch 分词与倒排索引', short: 'ES 倒排索引', icon: 'Search', tag: '搜索引擎', number: '13',
    summary: '写入的文档怎么变成词项表？match 与 match_phrase 的差距在哪？更新与删除又是如何维护倒排索引的——跟着 term → postings 走一遍。',
    defaults: { scenario: 'match' },
    fields: [{ key: 'scenario', label: '索引操作场景', type: 'select', options: [['match', '① match 查询 · 倒排构建'], ['phrase', '② match_phrase · 位置与词序'], ['update', '③ 文档更新删除 · 倒排维护']] }],
    metrics: [['docs', '文档总数', '篇'], ['terms', '词项', '个'], ['postings', '定位记录', '处'], ['hits', '查询命中', '篇']],
    nodes: [['doc', '文档写入', 'POST /blog/_doc', 'FileCheck2', 'blue'], ['analyzer', '分词分析', 'standard 分析器', 'Braces', 'yellow'], ['token', '词项流', 'java · 后端 · 缓存', 'Binary', 'yellow'], ['inverted', '倒排索引', 'term → postings', 'Search', 'green'], ['query', '查询 DSL', 'match / match_phrase', 'Search', 'pink'], ['result', '命中排序', 'BM25 相关度', 'ListOrdered', 'green']],
    edges: [['doc', 'analyzer', '原文切词'], ['analyzer', 'token', '词项输出'], ['token', 'inverted', '挂接 postings'], ['query', 'inverted', '词项定位'], ['inverted', 'result', '命中打分']],
    code: ['PUT /blog/_doc/m1 { "text": "java 后端 中间件 缓存" }', '// analyzer 分词 → java / 后端 / 中间件 / 缓存', 'GET /blog/_search { "query": { "match": { "text": "java 后端" } } }', 'GET /blog/_search { "query": { "match_phrase": { "text": "java 后端" } } }', '// 倒排表：java → [m1, m2] · 后端 → [m1, m3]', '// UPDATE = 旧文档标记删除 + 新版本重新索引'],
    theory: [['分词与分析', '写入与查询走同一 analyzer', '文本先切成词项（term）再入倒排；中文需要 ik 等专用分词器。查询串也做同样分析，两侧词项一致才能命中。'], ['倒排索引', 'term → 文档列表 postings', '每个词项记录出现过它的文档与位置；查询只读相关词项的列表，不必扫描全库——这是 ES 远快于 SQL 模糊匹配（%x%）的根本原因。'], ['match 与 match_phrase', '词项并集 vs 位置连续', 'match 把查询拆词后取并集，按相关度排序；match_phrase 还要求词项按顺序相邻出现（利用 position），做短语精确匹配。'], ['更新与删除', '段不可变，先删后建', 'Lucene 段不可修改：更新 = 旧文档标记删除 + 写入新版本，旧词项从倒排移除；删除同理，合并段时再物理清理。']],
    goals: ['解释倒排索引为何让 ES 免于全库扫描：查询只读相关词项的 postings', '说出 match 与 match_phrase 在匹配语义上的差异及 position 的作用', '知道文档更新删除如何影响倒排词项（先删后建、词项消失）'],
    challenge: { task: '固定 3 篇文档（m1 java 后端 中间件 缓存 · m2 java 框架 spring 并发 · m3 后端 服务 分布式），用三个场景各运行一次：① 写入后 match 查询 "java" ② 对 "java 后端" 分别跑 match 与 match_phrase ③ 把 m2 更新为 java 框架 vertx 异步、删除 m3，再查询已移除的词项 spring。期望：① 词项 9 · 定位 11 · 命中 2 ② match 命中 3 篇而 phrase 只有 m1（位置相邻）命中 1 ③ 更新删除后词项 7 · 定位 8 · 文档 2，spring 查询命中 0。', hint: '看词项 token 与 mono 统计行：写入帧词项逐个增加；phrase 场景对比两次查询的命中数；更新场景注意 spring/服务 等词项从列表消失。', success: '能解释倒排查询为什么快、match_phrase 为什么更严，以及更新删除后词项如何被移除。', requirements: [{ id: 'match', label: '① match 查询 · 倒排构建', when: { scenario: 'match' } }, { id: 'phrase', label: '② match_phrase · 位置与词序', when: { scenario: 'phrase' } }, { id: 'update', label: '③ 更新删除 · 倒排维护', when: { scenario: 'update' } }] },
    quiz: [
      { prompt: '倒排索引的核心思想是什么？', choices: ['把文档按原文顺序整篇存储，查询时逐篇扫描', '为每个词项维护出现过它的文档列表，查询只定位相关词项', '为每篇文档计算与其他文档的相似度并预存'], answer: 1, explanation: '倒排索引以词项为键、文档列表为值：查询 "java" 只读 java 一个词项的 postings，而不是扫全库。' },
      { prompt: 'match_phrase 与 match 在匹配语义上的关键区别是什么？', choices: ['match_phrase 不做分词，直接整串比较', 'match_phrase 要求词项在文档中按顺序相邻出现（利用 position）', 'match_phrase 只返回第一篇命中文档'], answer: 1, explanation: 'match 拆词取并集，词项散落各篇也能命中；match_phrase 用 position 校验词项连续且顺序一致，才能做短语精确匹配。' },
    ],
    boundary: '固定 3 篇教学文档，分词按整词切分（未模拟 standard/ik 的真实切词细节与停用词）；相关度只讲词频与命中篇数，未模拟 BM25 的 IDF 公式与 explain；segment 合并只作文字说明；未模拟分词器自定义、查询 bool 组合、高亮与聚合。',
    source: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-overview.html',
  },
  {
    id: 'kafka', group: '消息中间件', title: 'Kafka 分区与消费组', short: 'Kafka 分区消费', icon: 'Waypoints', tag: '消息队列', number: '07',
    summary: '观察消息写入分区、消费组分配和 offset 推进之间的关系。',
    defaults: { partitions: 3, consumers: 2, messages: 9 },
    fields: [{ key: 'partitions', label: 'Topic 分区数', min: 1, max: 6, unit: '个' }, { key: 'consumers', label: '消费组成员数', min: 1, max: 6, unit: '个' }, { key: 'messages', label: '发送消息数', min: 1, max: 15, unit: '条' }],
    metrics: [['produced', '已生产', ''], ['consumed', '已消费', ''], ['lag', '消息积压', ''], ['idle', '空闲消费者', '']],
    nodes: [['producer', '生产者', 'KafkaProducer', 'Send', 'blue'], ['broker', 'Topic 分区', 'orders.events', 'Layers', 'yellow'], ['consumer', '消费组', 'order-service-group', 'Workflow', 'green'], ['offset', '消费位点', '__consumer_offsets', 'LocateFixed', 'pink']],
    edges: [['producer', 'broker', 'send()'], ['broker', 'consumer', 'poll()'], ['consumer', 'offset', 'commit offset']],
    code: ['// One partition has one owner in the consumer group', 'producer.send(new ProducerRecord<>(topic, partition, key, value));', 'for (var record : consumer.poll(timeout)) process(record);', 'consumer.commitSync(nextOffsetsByPartition);'],
    theory: [['组内分配', '一个分区 → 一个活跃消费者', '同一个消费组内，分区不会被多个成员同时消费。'], ['并行度上限', 'min(partitions, consumers)', '消费者数超过分区数时，多余成员空闲。'], ['消费位点', 'offset = 下一条待消费位置', '顺序保证仅限单个分区，不是 Topic 全局有序。']],
    boundary: '消息显式轮询写入分区，消费组按轮询分配。先生产再消费，不模拟副本、故障、再均衡或事务；不是默认生产者分区器。',
    source: 'https://kafka.apache.org/documentation/#intro_consumers',
  },
  {
    id: 'kafka-replication', group: '消息中间件', title: 'Kafka 副本与 ISR', short: 'Kafka 副本与 ISR', icon: 'Layers', tag: '消息队列', number: '08',
    summary: '调整 acks 与 min.insync.replicas，观察 Leader 崩溃前后确认、复制与丢失的关系。',
    defaults: { acks: 'all', replicas: 3, minIsr: 2, messages: 5, crashAfter: 3 },
    fields: [
      { key: 'acks', label: 'acks 确认要求', type: 'select', options: [['0', 'acks=0 发送即返回'], ['1', 'acks=1 仅 Leader 确认'], ['all', 'acks=all 全 ISR 确认']] },
      { key: 'replicas', label: '副本总数', min: 1, max: 3, unit: '个' },
      { key: 'minIsr', label: 'min.insync.replicas', min: 1, max: 3, unit: '个' },
      { key: 'messages', label: '消息条数', min: 1, max: 8, unit: '条' },
      { key: 'crashAfter', label: 'Leader 故障时机', min: 0, max: 8, unit: '（0=不故障）' },
    ],
    metrics: [['sent', '已发送', ''], ['confirmed', '已确认', ''], ['lost', '确认后丢失', ''], ['rejected', '拒绝写入', '']],
    nodes: [['producer', '生产者', 'producer.send()', 'Send', 'blue'], ['leader', 'Leader 副本', 'append 日志', 'Server', 'green'], ['follower', 'ISR 副本', '同步复制', 'Layers', 'yellow'], ['commit', '提交确认', 'ISR 全量确认', 'FileCheck2', 'pink'], ['reject', '拒绝写入', 'NotEnoughReplicas', 'ShieldAlert', 'pink']],
    edges: [['producer', 'leader', '写入'], ['leader', 'follower', '复制'], ['follower', 'commit', '全量同步'], ['leader', 'commit', 'acks=1 确认'], ['producer', 'reject', 'ISR 不足']],
    code: ['producer.send(new ProducerRecord<>(topic, value), callback);', 'leader.append(record); // 只落盘在本副本', 'for (Replica r : inSyncReplicas) r.replicate(record);', 'if (inSyncReplicas.size() < minInsyncReplicas)', '    throw new NotEnoughReplicasException();', 'acknowledge(record); // 满足 acks 要求才回执'],
    theory: [['确认语义', 'acks=0 / 1 / all', 'acks=1 只保证写入 Leader；acks=all 要求 ISR 中全部同步副本都复制成功才回执。'], ['ISR 与选举', 'in-sync replicas 才有资格', 'Leader 崩溃后从 ISR 中选择新 Leader，只有 ISR 副本持有的数据被承认。'], ['min.insync.replicas', '写入可用性下限', 'ISR 低于该值时 acks=all 写入被拒绝：宁可暂不可写，也不给低安全确认。']],
    goals: ['解释 acks=0/1/all 各自的确认时机与丢失窗口', '说明 Leader 崩溃时哪些消息会丢失、哪些不会', '理解 min.insync.replicas 在可用性与持久性之间的取舍'],
    challenge: { task: '保持 3 副本、5 条消息、第 3 条后 Leader 故障，分别用 acks=1 与 acks=all 运行，对比确认数、丢失与后续写入；再把 acks=all 配 min.insync.replicas=3 运行，观察写入何时被拒绝。', hint: 'acks=all 时故障前的每一条都已复制到 ISR 全部副本，已确认的消息不丢。', success: '能用模型中的确认、丢失、拒绝三个指标解释三个配置的差异。', requirements: [{ id: 'ack1', label: 'acks=1 · 3 副本 · 故障@3', when: { acks: '1', replicas: 3, minIsr: 2, messages: 5, crashAfter: 3 } }, { id: 'ackall', label: 'acks=all · 3 副本 · 故障@3', when: { acks: 'all', replicas: 3, minIsr: 2, messages: 5, crashAfter: 3 } }, { id: 'strict', label: 'acks=all · minIsr=3 · 故障@3', when: { acks: 'all', replicas: 3, minIsr: 3, messages: 5, crashAfter: 3 } }] },
    quiz: [
      { prompt: 'acks=all 时，Leader 把消息写进自己的日志就立即确认吗？', choices: ['会，Leader 写入即可确认', '不会，要等 ISR 中全部同步副本复制成功', '会，但只等一个副本'], answer: 1, explanation: 'acks=all 要求 ISR 内所有同步副本都复制完成，Leader 单机写入不满足确认条件。' },
      { prompt: 'min.insync.replicas 的主要作用是什么？', choices: ['提升生产吞吐量', '设置消息保留时长', '规定 acks=all 下可接受写入所需的最小 ISR 副本数，不足时拒绝写入'], answer: 2, explanation: 'ISR 低于该阈值时 acks=all 写入被拒绝，用短暂不可写换取「能确认就不丢」的保证。' },
    ],
    boundary: '复制为逐条即时完成的教学抽象，ISR 只在 Leader 崩溃时收缩；未模拟副本长期落后被移出 ISR、HW/LEO 推进、follower 故障与真实网络时序，不能作为生产参数依据。',
    source: 'https://kafka.apache.org/documentation/#design_ha',
  },
  {
    id: 'rabbitmq-exchange', group: '消息中间件', title: 'RabbitMQ 交换机与路由', short: 'RabbitMQ 路由', icon: 'Route', tag: '消息队列', number: '09',
    summary: '同一条消息在直连、主题与扇出交换机下，如何按绑定规则进入队列或被丢弃？',
    defaults: { exchange: 'topic' },
    fields: [{ key: 'exchange', label: '交换机类型', type: 'select', options: [['direct', '直连 DIRECT'], ['topic', '主题 TOPIC'], ['fanout', '扇出 FANOUT']] }],
    metrics: [['q1', '订单队列', '条'], ['q2', '用户队列', '条'], ['dropped', '未匹配丢弃', '条'], ['total', '总投递', '次']],
    nodes: [['producer', '生产者', 'basicPublish(rk)', 'Send', 'blue'], ['exchange', '交换机', 'orders.ex', 'Route', 'yellow'], ['q1', '订单队列', 'QueueA', 'Table2', 'green'], ['q2', '用户队列', 'QueueB', 'Table2', 'green'], ['void', '黑洞', '无匹配丢弃', 'X', 'pink']],
    edges: [['producer', 'exchange', 'publish 消息'], ['exchange', 'q1', '命中绑定'], ['exchange', 'q2', '命中绑定'], ['exchange', 'void', '无队列匹配']],
    code: ['String type = "topic"; // direct | topic | fanout', 'channel.exchangeDeclare("orders.ex", BuiltinExchangeType.of(type));', 'channel.queueBind(queueA, "orders.ex", "orders.*"); // 绑定模式随类型变化', 'channel.basicPublish("orders.ex", routingKey, null, body);', '// 交换机匹配绑定：命中 → 入队；无命中 → 丢弃'],
    theory: [['三种交换机', 'direct / topic / fanout', 'direct 精确匹配绑定 key；topic 用 *（一个词段）与 #（任意多段）匹配；fanout 忽略 key 向所有绑定队列广播。'], ['绑定与路由键', 'queue.bind(exchange, routingKey)', '交换机只认绑定关系：队列预先声明关心的 key 或模式，消息按 routingKey 分拣入队。'], ['无法路由的消息', '默认在交换机处丢弃', '没有队列绑定命中时消息被静默丢弃，生产环境可用 alternate-exchange 兜底，避免丢失。']],
    goals: ['区分 direct、topic、fanout 三种交换机的匹配语义', '能根据绑定模式预判一条 routingKey 进入哪个队列', '知道未匹配消息会被交换机丢弃而非阻塞等待'],
    challenge: { task: '固定 5 条消息与两个队列，分别用直连、主题、扇出各运行一次。期望：DIRECT 只有 key 精确命中绑定的消息入队；TOPIC 中 orders.* 收两类订单事件、*.login 收登录事件；FANOUT 无视 key，双队列各收 5 条。', hint: '逐条观察「命中 / 丢弃」消息：direct 只有 orders.created 与 user.login 有主；topic 模式下 * 只匹配一个词段；fanout 全部广播。', success: '能解释为何同一条消息在三种交换机下的去向不同，以及无法路由的消息为何被丢弃。', requirements: [{ id: 'direct', label: '直连 DIRECT', when: { exchange: 'direct' } }, { id: 'topic', label: '主题 TOPIC', when: { exchange: 'topic' } }, { id: 'fanout', label: '扇出 FANOUT', when: { exchange: 'fanout' } }] },
    quiz: [
      { prompt: 'TOPIC 交换机上 QueueA 绑定 orders.*，下面哪个 routingKey 能命中 QueueA？', choices: ['orders', 'orders.paid', 'orders.paid.done'], answer: 1, explanation: '* 恰好匹配一个词段：orders.paid 两段命中；orders 缺段、orders.paid.done 多段都不命中。' },
      { prompt: '一条消息的 routingKey 没有命中任何队列的绑定，RabbitMQ 会怎么处理？', choices: ['阻塞在交换机等待匹配', '自动回退给生产者并报错', '直接丢弃这条消息'], answer: 2, explanation: '交换机无法路由的消息默认被直接丢弃；需要兜底时应配置 alternate-exchange 或死信策略。' },
    ],
    boundary: '固定 5 条消息与 2 个队列的教学模型，按 direct/topic/fanout 演示绑定匹配与丢弃；未模拟消息体、队列持久化、ack、死信交换机与 alternate-exchange，也未真实创建 RabbitMQ 资源。',
    source: 'https://www.rabbitmq.com/docs/exchanges',
  },
  {
    id: 'rabbitmq-ack', group: '消息中间件', title: 'RabbitMQ 消费确认与死信队列', short: 'RabbitMQ ack 与死信', icon: 'Recycle', tag: '消息队列', number: '10',
    summary: '同一幕消息，自动确认与手动确认下失败消息的两种结局：静默丢失，还是重试后进入死信队列？',
    defaults: { autoAck: false, maxRetry: 3 },
    fields: [{ key: 'autoAck', label: '自动确认 autoAck', type: 'toggle' }, { key: 'maxRetry', label: '失败重试上限', min: 1, max: 4, unit: '次' }],
    metrics: [['delivered', '消息投递', '次'], ['acked', '确认成功', '条'], ['requeued', '重回队列', '次'], ['dead', '未成功消息', '条']],
    nodes: [['producer', '生产者', 'basicPublish × 5', 'Send', 'blue'], ['queue', '业务队列', 'orders.work', 'ListOrdered', 'yellow'], ['consumer', '消费者', 'autoAck / manual', 'Workflow', 'green'], ['dlx', '死信交换机', 'dlx.orders', 'Layers', 'pink'], ['dead', '死信队列', 'orders.dlx', 'Table2', 'yellow']],
    edges: [['producer', 'queue', '入队'], ['queue', 'consumer', '投递'], ['consumer', 'queue', 'nack 回队'], ['consumer', 'dlx', '拒绝不重回'], ['dlx', 'dead', 'DLX 转发']],
    code: ['channel.basicConsume("orders.work", autoAck, consumer); // false = 手动确认', 'boolean ok = process(delivery);', 'if (ok) channel.basicAck(tag, false); // 成功后显式确认', 'else channel.basicNack(tag, false, retryLeft > 0); // requeue 或拒收', '// 被拒收且不重回队列的消息，由 DLX 转发进死信队列'],
    theory: [['自动确认的陷阱', 'autoAck=true 投递即确认', 'broker 立即删除消息；应用处理失败也来不及补救，异常消息静默丢失。'], ['手动确认与重试', 'basicNack(requeue=true)', '失败消息回到队列等待再投递，可能再次发给同一消费者——消费方需要幂等。'], ['死信队列 DLX', '拒绝不重回 / TTL 过期 / 队列超限', '死信交换机把「救不回」的消息转存到死信队列，由补偿任务或人工兜底处理。']],
    goals: ['对比 autoAck 与手动 ack 下失败消息的两种结局', '解释 nack(requeue=true) 重试与超过上限后拒收进死信的机制', '知道死信队列是兜底出口，重试逻辑要控制次数并考虑幂等'],
    challenge: { task: '同一幕 5 条消息（m2、m4 处理必然失败）：分别用 自动确认 与 手动确认（重试上限 3 与 1）运行。期望：autoAck 全部确认、无回队，失败消息已确认即丢失；手动确认下失败消息回队重试，回队次数 = 上限 − 1，超限后经 DLX 进入死信队列。', hint: '对比「确认成功」：autoAck 为 5 是把失败也算确认了；手动模式为 3。观察回队帧与死信帧的节点高亮。', success: '能解释为什么失败消息在 autoAck 下丢失、手动模式下却可以重试并落到死信队列。', requirements: [{ id: 'manual3', label: '手动 ack · 上限 3', when: { autoAck: false, maxRetry: 3 } }, { id: 'manual1', label: '手动 ack · 上限 1', when: { autoAck: false, maxRetry: 1 } }, { id: 'auto', label: '自动确认 autoAck', when: { autoAck: true } }] },
    quiz: [
      { prompt: '消费者调用 basicNack(tag, false, true)（requeue=true）后，这条消息会怎样？', choices: ['被 broker 立即删除', '回到队列等待再次投递，可能又被同一消费者收到', '只发给其他消费者，绝不再投递给当前消费者'], answer: 1, explanation: 'requeue=true 时消息回到队列等待再次投递，同一消费者仍可能再次收到，所以消费逻辑要幂等。' },
      { prompt: '一条消息在哪种情况下会被送进死信队列（DLX）？', choices: ['消费者拒绝且 requeue=false（或 TTL 过期、队列超限）', '消息体超过 1MB', '消费者处理成功并 basicAck 之后'], answer: 0, explanation: 'DLX 的触发是消息「救不回」：显式拒收不重回、TTL 过期或队列达到长度上限时转存死信队列。' },
    ],
    boundary: '固定 5 条消息与 2 条必然失败消息的教学模型，回队消息立即再次投递（单消费者），未模拟多消费者竞争、prefetch 与公平分发、TTL 与队列超限、持久化及真实 RabbitMQ 环境。autoAck 下的丢失与死信同样计入「未成功消息」。',
    source: 'https://www.rabbitmq.com/docs/dlx',
  },
  {
    id: 'rocketmq-tx', group: '消息中间件', title: 'RocketMQ 事务消息与最终一致', short: 'RocketMQ 事务消息', icon: 'RefreshCw', tag: '消息队列', number: '11',
    summary: '半消息先入 Broker、本地事务后执行——Commit 让消息转正可见，Rollback 让消息消失，谁都没表态就靠回查兜底。',
    defaults: { scenario: 'commit' },
    fields: [{ key: 'scenario', label: '本地事务结局', type: 'select', options: [['commit', '① 事务成功 → Commit 转正'], ['rollback', '② 业务失败 → Rollback 丢弃'], ['unknown', '③ 确认丢失 → Broker 回查']] }],
    metrics: [['half', '半消息', '条'], ['committed', '提交可见', '条'], ['rolledback', '回滚丢弃', '条'], ['checks', '回查次数', '次']],
    nodes: [['producer', '事务生产者', 'sendMessageInTransaction', 'Send', 'blue'], ['half', '半消息队列', 'PREPARED 暂存', 'Server', 'yellow'], ['tx', '本地事务', '订单落库 + 状态', 'Database', 'green'], ['commit', '消息确认', 'Commit / Rollback', 'FileCheck2', 'pink'], ['consumer', '消费者', '只收已提交消息', 'Workflow', 'green']],
    edges: [['producer', 'half', '发送半消息'], ['half', 'tx', '事务回调'], ['tx', 'commit', '结果确认'], ['commit', 'consumer', '转正可见']],
    code: ['TransactionMQProducer producer = new TransactionMQProducer("tx-group");', 'producer.sendMessageInTransaction(msg, (m, arg) -> executeLocalTx()); // 先发半消息', '// 本地事务：订单落库，并把事务状态写入业务库中的事务状态表', 'if (state == LocalTransactionState.COMMIT) sendCommit(m); else sendRollback(m);', '// 迟迟收不到确认 → Broker 回调 checkLocalTransaction(msg) 回查状态表', 'consumer.poll(); // 只消费 Commit 转正后的普通消息'],
    theory: [['半消息', 'PREPARED 暂存、对外不可见', '事务消息先以半消息进入 Broker 暂存，等收到 Commit 才转成消费者可见的普通消息。'], ['事务状态表', 'executeLocalTx 落库并记状态', '本地事务与状态记录在同一个业务事务里写库；Commit/Rollback 由业务方向 Broker 回告。'], ['回查兜底', 'checkLocalTransaction(msg)', 'Broker 长时间等不到确认时主动回查业务方的本地事务表，按真实结果转正或删除——保证最终一致。']],
    goals: ['讲清事务消息的推进：半消息暂存 → 本地事务 → Commit/Rollback', '说明回查机制如何兜底「确认消息丢失」的极端场景', '理解事务消息实现的是最终一致而非强一致，事务状态表是关键'],
    challenge: { task: '固定同一幕消息 m1（订单创建），用三个场景各运行一次：① 本地事务成功 ② 本地事务回滚 ③ Commit 确认丢失。期望：① 收到 Commit 后半消息转正，消费者收到 m1；② Rollback 后半消息被删除，消费者一无所获；③ Broker 等不到确认触发回查，查出已提交后消息仍转正可见。', hint: '看 strip：半消息（黄）→ 提交可见（绿 ✓）或 回滚丢弃（粉 ✗）；场景三在第 4-6 帧出现回查流程。', success: '能讲出半消息、Commit/Rollback 与回查三者如何配合，以及为什么它达成的是最终一致。', requirements: [{ id: 'commit', label: '① 事务成功 Commit', when: { scenario: 'commit' } }, { id: 'rollback', label: '② 业务失败 Rollback', when: { scenario: 'rollback' } }, { id: 'unknown', label: '③ 确认丢失·回查', when: { scenario: 'unknown' } }] },
    quiz: [
      { prompt: '半消息在什么时候才会被消费者看到？', choices: ['生产者一发送即可见', 'Broker 收到 Commit 确认、转成普通消息之后', '本地事务一执行完就可见'], answer: 1, explanation: '半消息以 PREPARED 状态暂存、对消费者不可见，只有收到 Commit 转正后才可被拉取。' },
      { prompt: 'Broker 迟迟收不到事务确认时会怎么做？', choices: ['把半消息永久留着', '直接丢弃半消息', '回调 checkLocalTransaction 回查本地事务状态，按结果 Commit 或 Rollback'], answer: 2, explanation: '事务确认可能因进程崩溃、网络异常丢失，Broker 通过回查业务方的事务状态表来推进，避免消息永远悬空。' },
    ],
    boundary: '固定单条消息的教学简化，事件按固定顺序推进；回查只演示「查得已提交 → 转正」一条结局，未模拟回查多次重试与超限判死、事务状态表的具体落库实现、多分支回查结果、以及本地消息表 / 2PC 等替代方案，不能替代真实 RocketMQ 参数依据。',
    source: 'https://rocketmq.apache.org/docs/featureBehavior/04transactionmessage',
  },
  {
    id: 'zookeeper-leader', group: '分布式协调', title: 'ZooKeeper Leader 选举与防脑裂', short: 'ZooKeeper 选举', icon: 'Server', tag: '分布式协调', number: '12',
    summary: 'Leader 宕机谁接班？从 LOOKING 状态出发，看 (zxid, myid) 投票如何过半收敛，以及少数派为什么永远选不出新 Leader——脑裂被机制禁止。',
    defaults: { scenario: 'crash-recovery' },
    fields: [{ key: 'scenario', label: '集群故障场景', type: 'select', options: [['crash-recovery', '① Leader 宕机 · 崩溃恢复'], ['partition', '② 网络分区 · 防脑裂'], ['follower-down', '③ Follower 宕机 · 无需选举']] }],
    metrics: [['elections', '触发选举', '次'], ['votes', '参与投票', '台'], ['handovers', 'Leader 交接', '次'], ['synced', '数据同步', '台']],
    nodes: [['cluster', 'ZK 集群', '5 节点 · quorum = 3', 'Server', 'blue'], ['fault', '故障与分区', '宕机 · 网络隔离', 'CircleAlert', 'pink'], ['looking', '选举状态', 'LOOKING · 广播 (zxid, myid)', 'Activity', 'yellow'], ['ballot', '投票收敛', 'zxid 大者胜 · 过半即停', 'FileCheck2', 'yellow'], ['leading', '新主节点', 'LEADING · 写提案与确认', 'Cpu', 'green'], ['sync', '数据同步', 'FOLLOWING 追平 zxid', 'RefreshCw', 'green']],
    edges: [['cluster', 'fault', '节点失联'], ['fault', 'looking', '进入选举'], ['looking', 'ballot', '投票广播'], ['ballot', 'leading', '过半当选'], ['leading', 'sync', 'zxid 对齐']],
    code: ['// 角色：LOOKING（选举中）· LEADING（主）· FOLLOWING（从）', '// 触发重选：Leader 失联且剩余节点过半，或本节点重启后重新加入', '// 投票：广播自己的 (zxid, myid)——先比 zxid（数据新者胜），平局比 myid', '// 收敛：收到更大票值即改投；某票数 ≥ n/2 + 1 即当选 Leader', '// 新 Leader 把缺失事务同步给 FOLLOWING（ZAB 崩溃恢复）', '// 防脑裂：少数派不足 quorum，任何时刻最多存在一个 Leader'],
    theory: [['过半与 quorum', 'quorum = n / 2 + 1', '5 节点集群任何决议要 3 台确认；任意两个多数派必有交集，所以「两个分区各选出一个 Leader」在数学上不可能——这正是防脑裂的根本保证。'], ['投票优先级', '(zxid, myid) 字典序', 'zxid 是事务序号：数据最新者当选才不会丢失已提交更新；zxid 相同再比 myid 打破平局。'], ['角色与触发', 'LOOKING → LEADING / FOLLOWING', '只有 Leader 失联、或一侧人数不足法定多数才重选；Follower 单点故障不触发选举，恢复后同步追平即可重新服务。']],
    goals: ['用 quorum = 3/5 解释多数派与少数派为何不可能同时选出两个 Leader', '按 (zxid, myid) 比较规则推演 Leader 宕机后哪个节点会当选', '区分触发选举（Leader 失联）与不触发选举（Follower 宕机）的故障'],
    challenge: { task: '固定 5 节点集群（quorum=3，Leader S1），用三个场景各运行一次：① S1 宕机，S2-S5 重新选举 ② 网络分区把 S4/S5 隔离在少数派一侧 ③ Follower S3 宕机后恢复。期望：① S2 以 4 票过半当选并完成 3 台同步，Leader 交接 1 次 ② 少数派发起选举但只有 2 票、选不出 Leader，S1 全程零交接，恢复后 S4/S5 同步 2 台 ③ 全程零选举零交接，只有 S3 同步 1 台。', hint: '看节点 token 颜色：绿=主、灰=从、黄=选（LOOKING）、粉=宕。三个场景的 交接/同步 计数是核心对比点：只有 Leader 失联才交接。', success: '能解释为什么少数派侧永远选不出 Leader（quorum 防脑裂），并说出 Follower 宕机与 Leader 宕机的处理差异。', requirements: [{ id: 'crash', label: '① Leader 宕机 · 崩溃恢复', when: { scenario: 'crash-recovery' } }, { id: 'partition', label: '② 网络分区 · 防脑裂', when: { scenario: 'partition' } }, { id: 'follower', label: '③ Follower 宕机 · 无需选举', when: { scenario: 'follower-down' } }] },
    quiz: [
      { prompt: '5 节点 ZooKeeper 集群中，选出 Leader 最少需要几张选票？', choices: ['2 张', '3 张', '5 张'], answer: 1, explanation: 'quorum = 5/2 + 1 = 3：拿到过半（3 张）选票才有效。过半要求保证任意时刻最多只有一个 Leader。' },
      { prompt: '投票比较 (zxid=8, myid=2) 与 (zxid=9, myid=1)，谁会当选？', choices: ['(8, 2)——myid 更大', '(9, 1)——先比 zxid，数据更新者优先', 'zxid 大的和 myid 大的随机竞争'], answer: 1, explanation: '比较规则是先比 zxid 再比 myid：zxid=9 数据更新，让数据最新者当 Leader 才不会丢失已提交的更新。' },
    ],
    boundary: '固定 5 节点集群与三个预设故障场景的教学模型，一轮投票即收敛；未模拟 ZAB 的 epoch 计数与多次票选风暴、节点重启时的数据追赶细节、observer、动态 quorum，以及真实网络中的选票超时与重试；zxid 编号为教学示意。',
    source: 'https://zookeeper.apache.org/doc/current/zookeeperInternals.html#sc_leaderElection',
  },
  {
    id: 'nacos-registry', group: '分布式协调', title: 'Nacos 服务注册与发现', short: 'Nacos 注册中心', icon: 'Activity', tag: '微服务治理', number: '15',
    summary: '一个服务怎么让别的服务找到自己？注册、心跳、订阅三件事：实例上线登记目录、5 秒心跳续约租约、消费者靠全量拉取 + UDP/长轮询双通道感知每一次上下线。',
    defaults: { scenario: 'register' },
    fields: [{ key: 'scenario', label: '注册中心场景', type: 'select', options: [['register', '① 注册与心跳 · 实例上线'], ['subscribe', '② 订阅与推送 · 扩缩容感知'], ['deregister', '③ 下线与剔除 · 心跳超时']] }],
    metrics: [['regs', '服务注册', '次'], ['beats', '心跳续约', '次'], ['pushes', '变更推送', '次'], ['removals', '摘除实例', '次']],
    nodes: [['provider', '服务提供者', 'order-service · 实例 A / B / D', 'Server', 'green'], ['registry', 'Nacos Server', '注册表 · 实例写入', 'Database', 'blue'], ['catalog', '服务目录', '实例列表 · 健康状态', 'Table2', 'yellow'], ['beat', '心跳租约', '每 5s 续约 · 超时判定', 'Activity', 'yellow'], ['consumer', '服务消费者', '订阅 · 本地缓存 · 调用', 'Monitor', 'pink'], ['notify', '变更通知', 'UDP 推送 · 30s 长轮询', 'Send', 'green']],
    edges: [['provider', 'registry', '注册 / 注销实例'], ['registry', 'catalog', '登记入服务目录'], ['beat', 'registry', '5s 心跳续约'], ['catalog', 'consumer', '订阅 · 全量拉取'], ['registry', 'notify', '实例变更事件'], ['notify', 'consumer', 'UDP 推送 / 长轮询']],
    code: ['// 服务端：Map<service, List<Instance>> 注册表，实例带健康状态与租约', '// 启动注册（ephemeral=true 临时实例，默认）：携带 service、ip、port', 'nacos.register({ service: "order-service", ip, port, ephemeral: true });', '// 心跳线程：每 5 秒发一次 beat，服务端刷新 lastBeat = 租约续期', 'setInterval(sendBeat, 5000); // 15s 无心跳 → 不健康；30s 仍未恢复 → 剔除', '// 消费者订阅：先全量拉取打底，再挂 UDP 监听 + 30s 长轮询请求', 'nacos.subscribe("order-service", onNotify); // 变更秒级到达', '// 优雅下线：显式 deregister 立即摘除；kill -9 无此调用 → 只能等超时'],
    theory: [['注册表与租约', '服务名 → 实例列表', '实例启动时注册并携带 IP:Port 等元数据；临时实例（ephemeral）靠每 5s 心跳续约证明存活，服务端只把健康的实例交给调用方。'], ['变更通知双通道', 'UDP 推送 + 30s 长轮询', 'UDP 快但会丢包；长轮询请求挂在服务端，无变更时 30s 返回空并重新挂起——任一通道先到，消费者都能在秒级拿到新目录，无需自建轮询。'], ['健康判定与剔除', '15s 不健康 · 30s 剔除', '超过 15s 未收到心跳先标记不健康（从负载池摘除但目录保留）；临时实例再超时即被自动剔除；持久实例（ephemeral=false）不自动摘除，须运维显式删除。']],
    goals: ['用「注册 → 5s 心跳续约」解释临时实例如何上线并维持健康状态', '说明消费者启动全量拉取后，UDP 推送与 30s 长轮询如何互为兜底感知上下线', '对比优雅下线（即时注销）、进程崩溃（15s 判不健康 → 30s 自动剔除）与持久实例的离开方式差异'],
    challenge: { task: '固定 order-service 与实例拓扑，用三个场景各运行一次：① 实例 A、B 先后注册并连续心跳 ② 消费者 C 订阅后新实例 D 扩容，观察 C 的收敛路径 ③ A 优雅下线、B 进程崩溃。期望：① 注册 2 · 心跳 4，零推送零摘除 ② 推送 1 · 心跳 1：C 缓存先 [A,B] 后含 D，且看到 UDP 推送与长轮询兜底两种通知徽章 ③ 摘除 2：A 即时消失、B 经历「不健康 → 剔除」直至目录清空，全程零心跳（无幸存实例）。', hint: '看目录 token 颜色与 C 缓存徽章：绿=健康、黄=心跳超时不健康、空=目录清空；「UDP 推送 / 长轮询兜底」徽章展示双通道。三个场景的 推送/摘除 计数是核心对比：只有实例离开目录才产生摘除。', success: '能解释 ephemeral 注册靠 5s 心跳续约、消费者用「全量拉取打底 + UDP/长轮询双通道」感知变更，并说出崩溃下线与优雅下线、持久实例的处置差异。', requirements: [{ id: 'register', label: '① 注册与心跳 · 实例上线', when: { scenario: 'register' } }, { id: 'subscribe', label: '② 订阅与推送 · 扩缩容感知', when: { scenario: 'subscribe' } }, { id: 'deregister', label: '③ 下线与剔除 · 心跳超时', when: { scenario: 'deregister' } }] },
    quiz: [
      { prompt: '临时实例（ephemeral）的心跳中断后，Nacos 如何处置它？', choices: ['检测到即从目录删除', '15s 无心跳先标记不健康，再超时自动剔除', '永久保留并持续告警'], answer: 1, explanation: '短暂抖动不该误杀实例：先给 15s 健康判定窗口标记不健康并摘出负载池，仍不恢复才自动剔除——这就是租约机制的容错设计。' },
      { prompt: '消费者启动订阅服务时，首先拿到实例列表的方式是？', choices: ['空列表，被动等推送', '服务端全量返回当前实例列表打底，之后靠 UDP 推送 / 长轮询增量更新', '随机返回一个实例'], answer: 1, explanation: '订阅先全量拉取一次，让本地缓存立即可用；后续的实例上下线才走 UDP 推送与长轮询双通道增量收敛。' },
      { prompt: 'UDP 推送与 30s 长轮询是什么关系？', choices: ['长轮询已取代 UDP，推送纯属历史遗留', '两条互斥通道，消费者只选其一', '互为兜底：UDP 秒级通知，报文丢失时挂起的长轮询也会带回变更'], answer: 2, explanation: 'UDP 快但不可靠，长轮询可靠但稍慢（最长挂 30s，有变更即时应答）。两条通道并发工作，保证变更必然被消费者感知。' },
    ],
    boundary: '以单服务单命名空间的教学模型演示注册表核心语义；心跳间隔、健康判定与剔除时限采用简化固定值（真实 Nacos 可配且按实际参数执行）；未模拟 1.x 的 Distro/AP 与 CP 模式差异、服务端健康检查主动探测、UDP 合并去重、2.x gRPC 长连接演进、集群节点间注册表同步与 Nacos-Sync 多集群场景。',
    source: 'https://nacos.io/',
  },
  {
    id: 'netty-eventloop', group: 'Java 核心', title: 'Netty 事件循环与线程模型', short: 'Netty 线程模型', icon: 'Network', tag: '网络编程', number: '16',
    summary: '百万连接真靠百万线程？Netty 用主从 Reactor 两拨线程吃下全部：boss 只接客、连接轮询分发后绑定固定 worker 单线程串行处理——绑线程换来无锁，execute 任务队列收编跨线程访问；再看一个慢 handler 如何堵死整条事件循环，业务线程池如何拆弹。',
    defaults: { scenario: 'accept' },
    fields: [{ key: 'scenario', label: '线程模型场景', type: 'select', options: [['accept', '① 主从 Reactor · boss 接入与分发'], ['io', '② 串行无锁 · 一轮 select 多连接'], ['slow', '③ 阻塞传染 · 业务线程池卸载']] }],
    metrics: [['conns', '接入连接', '条'], ['events', '处理事件', '次'], ['regs', '线程绑定', '次'], ['tasks', '提交任务', '次']],
    nodes: [['client', '客户端', '连接发起 · 请求读写', 'Monitor', 'pink'], ['boss', 'Boss EventLoop', '主 Reactor · 只处理 OP_ACCEPT', 'Server', 'blue'], ['worker', 'Worker EventLoop', '从 Reactor · 事件串行处理', 'Cpu', 'green'], ['channel', 'Channel 连接', '绑定固定线程 · 事件不外流', 'Waypoints', 'yellow'], ['pipeline', 'ChannelPipeline', 'decode → handle → encode', 'ListOrdered', 'green'], ['pool', '业务线程池', '阻塞任务卸载 · 慢活不进 IO', 'Workflow', 'yellow']],
    edges: [['client', 'boss', '三次握手 → 就绪队列'], ['boss', 'worker', 'accept 后轮询注册'], ['worker', 'channel', '读写事件 · 串行无锁'], ['channel', 'pipeline', '事件流经 Handler 链'], ['pipeline', 'pool', '阻塞业务提交卸载'], ['pool', 'worker', '完成回调回投']],
    code: ['// 线程模型：bossGroup 只 accept，workerGroup 负责连接上的全部 IO', 'EventLoopGroup boss = new NioEventLoopGroup(1);    // 主 Reactor：接入专用', 'EventLoopGroup worker = new NioEventLoopGroup(2);  // 每线程持 1 个 Selector', 'b.group(boss, worker).childHandler(pipeline);      // accept 后轮询注册到 worker', '// Channel 固定绑定一个 EventLoop：读写与任务单线程串行 → 无锁', 'channel.eventLoop().execute(() -> channel.write(msg)); // 跨线程投递任务', '// 阻塞陷阱：handler 阻塞调用占住整个 worker，其他连接排队等', 'pool.submit(() -> slowBiz());  // 卸载到业务线程池，IO 线程快进快出'],
    theory: [['主从 Reactor', 'boss 只接入 · worker 管 IO', 'boss 单线程只轮询 OP_ACCEPT：select 命中后 accept 出新连接、按轮询注册给某个 worker，使命即完成。连接的读写事件此后只与它绑定的 worker 相关——接入与 IO 分离，新连接洪峰不会挤占既有连接的 IO 线程。'], ['Channel 绑定线程', '同一连接 · 同一线程 · 无锁', '每个 channel 固定归属一个 EventLoop：它的读写事件与用户任务全部在该线程串行执行，任何时刻只有一个线程碰它的状态——线程封闭换来无锁。跨线程要操作 channel？唯一正确姿势是 eventLoop().execute() 投递任务。'], ['阻塞的传染性', '慢 handler 堵死整个 worker', 'handler 在 IO 线程上跑：一个 100ms 的阻塞调用会让共享该 worker 的所有连接一起等待——一个慢接口拖垮整个服务。修复：把阻塞业务提交独立业务线程池，IO 线程快进快出，完成结果经回调回投 channel 线程。']],
    goals: ['用 boss/worker 两组线程画出主从 Reactor：接入、分发、串行处理三段分工如何各司其职', '解释 channel 固定绑定 EventLoop 为何换来无锁串行，并说出跨线程操作 channel 的唯一入口', '推演一个慢 handler 如何拖慢同 worker 的其他连接，并说出用业务线程池卸载的修复路径'],
    challenge: { task: '固定线程拓扑（boss 1 线程、worker 2 线程 W1/W2），用三个场景各运行一次：① 客户端 A、C 先后连接并发起请求 ② conn-1~3 同挂 W1，一轮就绪三连发并穿插心跳任务 ③ conn-1 带慢 handler，先阻塞后卸载修复。期望：① 接入 2 · 事件 2 · 绑定 2，零任务：A 分发到 W1、C 轮到 W2，各事件只在自己的 worker 上处理 ② 事件 4 · 任务 1：一次 select 循环内三连接串行无锁处理完，心跳写经 eventLoop.execute 回投 ③ 任务 2 · 事件 3：修复前 conn-2 被拖慢一个阻塞周期（就绪排队），修复后请求零延迟、慢活全在业务池。', hint: '看条带 token：绿=空闲或处理完成、黄=事件处理中或就绪排队、粉=handler 阻塞占线程；「处理中 / 就绪 [..] / 任务 / 业务池 ×N」徽章展示线程内的串行顺序。对比慢场景第 2-3 帧 conn-2 的黄色排队与第 7 帧的即时处理。', success: '能画出主从 Reactor 的接入/分发/处理三段分工，解释「channel 绑定 EventLoop → 单线程串行 → 无锁」与 execute 投递规则，并说出慢 handler 如何传染同 worker 连接、业务线程池如何卸载。', requirements: [{ id: 'accept', label: '① 主从接入 · boss 分发', when: { scenario: 'accept' } }, { id: 'io', label: '② 串行无锁 · 多连接复用', when: { scenario: 'io' } }, { id: 'slow', label: '③ 阻塞传染 · 线程池卸载', when: { scenario: 'slow' } }] },
    quiz: [
      { prompt: '一个 handler 里做了 100ms 的阻塞调用，谁会被拖累？', choices: ['只有发起请求的那一条连接', '共享同一 worker 的所有连接', 'boss 与全部 worker 一起等待'], answer: 1, explanation: 'handler 跑在连接所属的 worker 线程上：该线程串行服务它名下的所有 channel，阻塞期间这些连接的就绪事件全部排队——这就是 Netty 禁止在 IO 线程做阻塞调用的原因。' },
      { prompt: '业务线程想给某个 channel 写数据，正确的姿势是？', choices: ['channel.eventLoop().execute(...) 把写操作投递到连接所属线程执行', '直接修改该 channel handler 内的业务状态（无锁模型=谁都能碰）', '把连接迁移到一个更空闲的 worker 再写'], answer: 0, explanation: '线程封闭意味着只有 EventLoop 线程能碰 channel 的状态：跨线程操作一律经 execute 投递，任务回到连接所属线程串行执行——安全且不加锁。' },
      { prompt: 'boss EventLoop 与 worker EventLoop 的分工是？', choices: ['boss 与 worker 都处理读写，靠多线程抢占', 'worker 负责 accept 新连接，boss 处理连接上的读写', 'boss 只 accept 并分发注册，worker 处理连接上的全部 IO'], answer: 2, explanation: '主从分离：boss 从就绪队列取出新连接、轮询注册给某个 worker 即完成使命；连接的读写事件全部在其绑定的 worker 线程上发生——接入与 IO 互不拖累。' },
    ],
    boundary: '固定 boss=1、worker=2 与预设事件序列的教学模型；未模拟 NIO 的 OP_WRITE 与半包粘包、ChannelOutboundBuffer 背压与高低水位、MPSC 任务队列与唤醒优化、FastThreadLocal、EventExecutorGroup 的 childHandler 卸载写法、epoll/kqueue 原生传输与零拷贝、以及真实调度下 select 返回数量的不确定性；阻塞与卸载事件按固定顺序推进。',
    source: 'https://netty.io/wiki/thread-model.html',
  },
  {
    id: 'nacos-config', group: '分布式协调', title: 'Nacos 配置中心与动态刷新', short: 'Nacos 配置中心', icon: 'SlidersHorizontal', tag: '微服务治理', number: '17',
    summary: '配置也要管环境、管版本、管回滚：namespace 把 dev/prod 隔成两堵墙，dataId 精确寻址每一份配置；客户端启动全量拉取打底、运行期靠 MD5 指纹识别变更，UDP 秒级推送与 30s 长轮询互为兜底——发布即生效、无需重启，发布错了还能一键回滚。',
    defaults: { scenario: 'publish' },
    fields: [{ key: 'scenario', label: '配置中心场景', type: 'select', options: [['publish', '① 启动拉取 · 全量打底与本地缓存'], ['update', '② 动态刷新 · 发布即生效'], ['namespace', '③ 环境隔离 · 误发布与回滚']] }],
    metrics: [['pulls', '配置拉取', '次'], ['pushes', '变更推送', '次'], ['refreshes', '动态刷新', '次'], ['rollbacks', '回滚配置', '次']],
    nodes: [['app', '应用服务', 'order-service · 启动读取配置', 'Server', 'green'], ['client', '配置客户端', '本地缓存 · MD5 校验', 'Monitor', 'pink'], ['server', 'Nacos Server', '配置存储 · 版本管理', 'Database', 'blue'], ['config', '配置文件', 'dataId · group · namespace', 'FileCheck2', 'yellow'], ['listener', '变更监听', '30s 长轮询 · UDP 通知', 'Activity', 'yellow'], ['rollback', '版本历史', '发布归档 · 一键回滚', 'RotateCcw', 'green']],
    edges: [['app', 'client', '启动注入 · 读取缓存'], ['client', 'server', '全量拉取 · 长轮询挂起'], ['server', 'config', 'dataId 存取 · 版本 +1'], ['server', 'listener', '变更事件发布'], ['listener', 'client', 'UDP 推送 / 轮询应答'], ['server', 'rollback', '历史归档 · 回滚恢复']],
    code: ['// 配置寻址：namespace（环境隔离）· group（租户/业务线）· dataId（常带文件名后缀）', 'Config config = nacos.getConfig("order-service.yaml", "DEFAULT_GROUP", "dev");', '// 启动全量拉取打底，内容与 MD5 指纹一起落本地缓存；运行期靠指纹识别变更', 'String md5 = digest(remote);  // 与本地指纹一致 → 配置没变，不触发刷新', '// 动态监听：30s 长轮询请求挂服务端，无变更超时返回并自动重挂', 'config.addListener(dataId, listener);  // 服务端发布即推送，秒级生效', '// 发布即版本 +1，历史全保留；灰度先发小流量实例验证', 'nacos.publishConfig(dataId, group, content);  // 出问题随时回滚', '// 回滚 = 把上一版本再发布一次：走同样的推送通道，客户端自动恢复'],
    theory: [['三维寻址与隔离', 'namespace · group · dataId', '一份代码进不同环境，靠 namespace 拿到各自的配置：dev/prod 里同名的 dataId 互不可见、各推各的监听者；group 再按租户/业务线细分。配置像文件路径一样精确可寻址，只是它在远端、能动态改。'], ['拉取与 MD5 指纹', '全量打底 · 指纹比对', '启动时全量拉取一次落本地缓存，服务端连内容带 MD5 一起返回；之后所有「变没变」的判断都交给指纹比对——指纹相同就不刷新，避免无谓重建 bean。'], ['变更双通道与回滚', 'UDP 秒级 · 轮询兜底 · 回滚=再发布', '客户端始终挂一条长轮询，配置一变即时应答；UDP 丢了还有轮询兜底，变更必然收敛。发布错了不用慌：历史版本一键回滚，本质是把上一版再发布一次，走同样的推送通道，客户端自动恢复，全程零重启。']],
    goals: ['用「namespace 隔离 + dataId 寻址」解释同一份代码如何在不同环境拿到各自的配置', '说出启动拉取打底后，MD5 指纹与 UDP/长轮询双通道在运行期各自扮演什么角色', '推演「误发布 → 客户端秒级生效出错 → 一键回滚自愈」的完整链路与隔离保障'],
    challenge: { task: '固定 order-service 与 dev/prod 命名空间拓扑，用三个场景各运行一次：① 客户端 A、B 先后启动拉取同一 dataId 并落本地缓存 ② 开发连续发布 v4、v5 两次变更，A、B 各自感知刷新 ③ dev 误发布错误配置后一键回滚，prod 全程不受影响。期望：① 拉取 3 · 零推送零刷新零回滚：两次启动拉取 + 一次带指纹校验的无变更确认 ② 推送 2 · 刷新 4 · 拉取 4：变更 1 中 A 走 UDP 秒级刷新、B 靠长轮询兜底追平（看到两种通知徽章），变更 2 双双 UDP 刷新，缓存最终都到 v5 ③ 回滚 1 · 推送 2 · 刷新 2 · 拉取 4：D 经历「误配置生效报错 → 回滚恢复自愈」两次刷新，prod 的 P 全程零推送零刷新。', hint: '看客户端 token 的版本号与颜色：黄=启动或刷新中、粉=错误配置生效、绿=就绪；「UDP 推送 / 长轮询兜底」徽章区分通知通道；配置 token 变粉 = 错误配置已发布，回滚后回到上一版。三个场景的 推送/刷新 计数是核心：只有服务端发布变更才产生推送。', success: '能说出 namespace 如何隔离环境、MD5 指纹如何识别变更、UDP 与长轮询如何互补兜底，并描述误发布到回滚链路中服务端与客户端各自的动作。', requirements: [{ id: 'publish', label: '① 启动拉取 · 本地缓存打底', when: { scenario: 'publish' } }, { id: 'update', label: '② 动态刷新 · 发布即生效', when: { scenario: 'update' } }, { id: 'namespace', label: '③ 环境隔离 · 误发布与回滚', when: { scenario: 'namespace' } }] },
    quiz: [
      { prompt: '开发环境发布了一份错误配置，生产环境的应用会受影响吗？', choices: ['会——所有环境共用同一份配置', '不会——dev 与 prod 的 namespace 相互独立，发布只推送自己命名空间下的监听客户端', '看运气——取决于哪个环境先拉取'], answer: 1, explanation: '配置寻址是 namespace:group:dataId 三维：namespace 天然隔离环境，dev 的发布只写入并推送给 dev 命名空间下的客户端，生产毫发无伤。' },
      { prompt: '客户端如何判断服务端配置「变了」、需要刷新？', choices: ['比对 MD5 指纹：服务端返回内容指纹，与本地一致就不刷新', '每次长轮询超时重挂都重建全部 bean', '服务端主动断开连接表示配置失效'], answer: 0, explanation: '启动拉取打底后，运行期一切变更判断都靠指纹：长轮询/UDP 只负责告诉客户端「可能有变更」，客户端重拉后凭指纹差异决定要不要刷新——指纹相同就不动，避免无谓重建。' },
      { prompt: '配置发布错了，最快的恢复手段是？', choices: ['服务端回滚到上一版本，客户端经推送通道自动恢复', '逐台重启应用让它们重新拉取旧配置', '只能把错误值手动改回来再发布一次'], answer: 0, explanation: 'Nacos 保留全部历史版本：一键回滚本质是「把上一版本再发布一次」，走同样的推送通道、触发同样的刷新——客户端零人工介入自动自愈。' },
    ],
    boundary: '固定 dev/prod 两个命名空间与单个 dataId 的教学模型；未模拟 group 细分租户、配置加密与权限体系、beta 灰度与标签路由、Spring Cloud @RefreshScope 与 bootstrap 阶段拉取时序、2.x gRPC 长连接、配置导入导出与监听器线程模型、本地磁盘快照在服务端长期不可达时的降级细节；发布与回滚事件按固定顺序推进，版本号与 MD5 为教学示意。',
    source: 'https://nacos.io/',
  },
  {
    id: 'mysql-replication', group: '数据与缓存', title: 'MySQL 主从复制与读写分离', short: 'MySQL 主从复制', icon: 'Copy', tag: '数据库原理', number: '18',
    summary: '主库提交先落 binlog，从库 IO 线程接力到 relay log、SQL 线程串行回放——异步留出延迟窗口，半同步用 ack 压窗口，读写分离再把延迟问题摆到路由层：默认读从库卸压，写后即读与关键读强制回主库。',
    defaults: { scenario: 'chain' },
    fields: [{ key: 'scenario', label: '复制场景', type: 'select', options: [['chain', '① 异步复制 · binlog → relay log 全链路'], ['semisync', '② 半同步 · ack 确认与故障切换'], ['split', '③ 读写分离 · 主写从读与读陈旧']] }],
    metrics: [['writes', '主库写入', '次'], ['copies', '从库回放', '次'], ['acks', '半同步确认', '次'], ['failovers', '主从切换', '次']],
    nodes: [['writer', '写入应用', 'order-service · 写 SQL', 'Send', 'blue'], ['master', '主库 Master', 'binlog 记录 · 对外确认', 'Database', 'green'], ['binlog', 'binlog', 'ROW 格式变更日志', 'FileCheck2', 'yellow'], ['relay', 'relay log', '从库中转 · 待回放', 'Layers', 'yellow'], ['slave', '从库 Slave', 'IO 拉取 · SQL 回放', 'Server', 'pink'], ['reader', '读应用', 'SELECT · 路由主或从', 'Search', 'blue']],
    edges: [['writer', 'master', '写 INSERT / UPDATE'], ['master', 'binlog', '提交即记 binlog'], ['binlog', 'relay', 'dump / IO 线程接力'], ['relay', 'slave', 'SQL 线程回放'], ['reader', 'slave', '默认读从库'], ['reader', 'master', '强一致读主库']],
    code: ['-- 主库：ROW 格式 binlog 是复制的源头', '[mysqld] log-bin=mysql-bin  binlog_format=ROW  server-id=1', '-- 从库：指定主库与 binlog 位点，再启动复制双线程', 'CHANGE MASTER TO MASTER_HOST="M", MASTER_LOG_FILE="mysql-bin.000003", MASTER_LOG_POS=104;', 'START SLAVE;  -- IO 线程拉 binlog → relay log；SQL 线程串行回放', 'SHOW SLAVE STATUS\\G  -- 关注 Seconds_Behind_Master 复制延迟', '-- 半同步：提交前至少一个从库确认收到 binlog；ack 超时自动降级异步', 'SET GLOBAL rpl_semi_sync_master_enabled = 1;  -- rpl_semi_sync_master_timeout 默认 10s', '-- 读写分离路由：默认读从库；写后即读 / 支付回调等关键读强制走主库', '@Hint(read=master) SELECT status FROM orders WHERE id = ?;'],
    theory: [['三段接力', 'binlog → relay log → SQL 回放', '主库提交先写 binlog（ROW 格式逐行记录变更）；从库 IO 线程把 binlog 拉到本地 relay log，SQL 线程再串行回放——拉取与回放解耦，单线程回放保证提交顺序与主库一致。'], ['异步的延迟窗口', '提交零等待 · Seconds_Behind_Master', '异步复制下主库提交成功即返回，从库何时追上全看网络与回放速度：大事务（ROW 格式十万行 = 十万条事件）会瞬间拉开延迟。延迟不伤害主库，但读从库会读到旧数据。'], ['半同步与读写分离', 'ack 压窗口 · 路由定新旧', '半同步让主库提交前至少等一个从库确认收到 binlog，把「主库以为成功但从库完全没有」的丢失窗口压到超时降级期。读写分离再把延迟问题摆到路由层：默认读从库卸压，写后即读与关键读强制回主库。']],
    goals: ['画出 binlog → relay log → SQL 线程回放的三段复制接力，说出异步延迟窗口从哪来', '解释半同步 ack 如何压缩丢失窗口，以及 ack 超时降级与故障切换的完整流程', '给出读写分离下读路由的默认与例外：什么读走从库、什么读必须强制走主库'],
    challenge: { task: '固定 M（主）+ S（从）+ 读写 Proxy 拓扑，三个场景各运行一次：① 应用提交 T1、T2 两笔事务，跟踪 binlog → relay log → SQL 回放的全程接力与延迟追平 ② 半同步下先走一笔正常 ack 事务，再从库宕机触发降级、主库宕机后提升从库恢复业务 ③ 下单后立刻查订单列表（写后即读翻车），支付回调强制走主库读，主从各自追平。期望：① 写入 2 · 回放 2 · 零确认零切换：看事件 token 从粉（binlog）→ 黄（relay）→ 绿（回放）走完全程 ② 写入 3 · 回放 1 · 确认 1 · 切换 1：看到 ack 徽章、模式 token 变「降级异步」、主库变 S↑ ③ 写入 2 · 回放 2 · 零确认零切换：观察 route token 在「读从库 → 读主库 → 读从库」间切换。', hint: '看 strip 事件 token 颜色：粉=在主库 binlog（在途或中断）、黄=到 relay log 待回放、绿=已回放主从一致；lag token 出现即延迟窗口；route token 显示本次读走主还是从；半同步场景看 ack 徽章与模式 token（半同步 → 降级异步 → 新主续写）。', success: '能画出 binlog → relay log → SQL 回放的三段接力并解释延迟窗口来源；能说出半同步 ack 与超时降级如何压缩丢失窗口；能给出写后即读与关键读的正确路由策略。', requirements: [{ id: 'chain', label: '① 异步复制 · 接力全链路', when: { scenario: 'chain' } }, { id: 'semisync', label: '② 半同步 · 确认与切换', when: { scenario: 'semisync' } }, { id: 'split', label: '③ 读写分离 · 主写从读', when: { scenario: 'split' } }] },
    quiz: [
      { prompt: '异步复制下，主库刚提交的事务，从库立刻能读到吗？', choices: ['能——主从数据实时同步，提交即双写', '不一定——存在延迟窗口：binlog 传输与 SQL 回放完成前，读从库会读到旧数据', '读不到——从库只能复制延迟一天前的数据'], answer: 1, explanation: '异步复制主库提交零等待，从库靠 IO 拉取 + SQL 回放追赶：窗口内读从库是旧数据。延迟是常态而非故障，所以读路由才要讲究策略。' },
      { prompt: '半同步复制下从库迟迟不回 ack，主库会怎样？', choices: ['无限期阻塞，直到从库恢复为止', '放弃该事务并回滚', '等待超时后降级为异步继续提交，保证主库可用'], answer: 2, explanation: '半同步是折中：默认等一个从库确认收到 binlog 才提交成功；从库失联超过 rpl_semi_sync_master_timeout 就降级异步——宁可暂时牺牲一致性，也不能让主库写不进去，丢失窗口因此只存在于降级期。' },
      { prompt: '读写分离下，「支付回调需读取订单状态再决定是否发货」，这笔读应该怎么路由？', choices: ['强制走主库——读最新已提交数据，避免按旧状态做出错误发货决策', '照常走从库——读压力必须均匀分摊', '随机路由主从——负载均衡说了算'], answer: 0, explanation: '读决定写的关键路径不能容忍复制延迟：写后即读与强一致读一律强制主库，普通列表与报表读才走从库卸压。' },
    ],
    boundary: '固定 M/S 双节点与预设事务序列的教学模型；未模拟 binlog 三种格式的差异细节与 DDL 特殊处理、GTID 自动定位、半同步多副本参数与 wait point 差异、并行复制（MTS）回放、级联/多源/环形拓扑、MHA/Orchestrator 自动切换与 VIP 漂移、基于位点的断点续传与 relay log 损坏恢复、半同步在读写分离下的级联配置；延迟秒数与事务命名均为教学示意。',
    source: 'https://dev.mysql.com/doc/refman/8.0/en/replication.html',
  },
  {
    id: 'es-sharding', group: '数据与缓存', title: 'ES 分片与集群高可用', short: 'ES 分片集群', icon: 'Network', tag: '搜索引擎', number: '19',
    summary: '文档靠 hash(routing) % 主分片数落位，主分片数建索引时定死、扩容只能 reindex；主分片所在节点宕机，副本自动提升接管；节点分裂时过半 quorum 让少数派自动认怂——green / yellow / red 三个颜色就是集群的体检报告。',
    defaults: { scenario: 'route' },
    fields: [{ key: 'scenario', label: '集群场景', type: 'select', options: [['route', '① 分片路由 · hash % 3 落位'], ['failover', '② 副本提升 · 故障转移'], ['scale', '③ 扩容 reindex · 脑裂防护']] }],
    metrics: [['docs', '文档写入', '篇'], ['syncs', '副本同步', '次'], ['promotes', '主分片提升', '次'], ['moves', '迁移批次', '次']],
    nodes: [['app', '写入应用', 'POST /orders/_doc', 'Send', 'blue'], ['coord', '协调节点', '算路由 · 广播合并', 'Route', 'blue'], ['primary', '主分片', 'P0 / P1 / P2 接收写入', 'Database', 'green'], ['replica', '副本分片', 'R0 / R1 / R2 随时接管', 'Server', 'pink'], ['idx', '索引 orders', '主分片数创建即定', 'Layers', 'yellow'], ['cluster', '集群', 'green / yellow / red', 'Activity', 'green']],
    edges: [['app', 'coord', '写入 / 查询'], ['coord', 'primary', 'hash(routing) % 3'], ['primary', 'replica', '副本同步'], ['replica', 'primary', '故障时提升'], ['idx', 'cluster', '分片状态上报'], ['primary', 'idx', '文档归属分片']],
    code: ['PUT /orders/_doc/1001                  // 路由：hash(_id) % 3 → 写入 P2', 'GET /_cat/shards/orders                 // 看 3 主 3 副如何散布在节点上', 'PUT /orders/_settings { "number_of_shards": 5 }  // 400！主分片数一经创建不可修改', '// 横向扩容正道：新索引 + reindex + 别名切换（短暂只读窗口）', 'POST /_reindex { "source": { "index": "orders" }, "dest": { "index": "orders-v2" } }', 'GET /_cluster/health                    // green 主副齐 / yellow 缺副本 / red 缺主', '// 脑裂防护：过半 quorum 才有资格当主', 'discovery.zen.minimum_master_nodes: 2   // 3 个 master 节点 → 至少 2 票'],
    theory: [['分片路由', 'hash(routing) % 主分片数', '写入与查询都先算路由：同一 _id 的文档永远落到同一个主分片，更新与读取只打一个分片；主分片数决定「桶」的数量，所以在建索引时就要按峰值流量估算好。'], ['副本与颜色', 'green / yellow / red', '每个主分片带 1+ 副本（分布在别的节点）。主分片丢 = red（读写受阻）；副本不足 = yellow（能读写但容灾降级）；全齐 = green。主节点宕机后，含最新数据的副本自动提升为新主，秒级到分钟级自愈。'], ['扩容与脑裂', 'reindex · 过半 quorum', '主分片数不可动态调大（改了路由哈希就全错位）——扩容量只能建新索引 reindex 搬数据再切别名。脑裂靠过半票数防：3 个 master 节点要求至少 2 票才允许选主，被分区孤立的单节点凑不齐 quorum 就自动降级，杜绝双主。']],
    goals: ['用 hash(routing) % 主分片数解释文档落位，说出为什么主分片数一经创建不可修改', '描述主分片所在节点宕机后的完整自愈流程：副本提升 → 补副本 → 恢复 green', '说出横向扩容的标准动作（新索引 + reindex + 别名切换）与过半 quorum 如何阻止脑裂'],
    challenge: { task: '固定 3 数据节点拓扑（N1: P0+R1 · N2: P1+R2 · N3: P2+R0），三个场景各运行一次：① 依次写入 #1001/#1002/#1003 三篇文档并各自完成副本同步 ② 宕掉 N2 观察 P1 主分片失联、R1 副本提升为新主、补副本后恢复 green、期间写入一笔恢复业务、N2 回归追平 ③ 演示对 orders 调大主分片数被 400 拒绝，改用 orders-v2 + reindex 扩容，再让 N2 与集群网络分区、观察它因凑不齐过半 quorum 而自动降级、恢复后重新归队。期望：① 写入 3 · 同步 3 · 零提升零迁移：三篇散落 P2/P0/P1 且全部完成主副同步 ② 写入 1 · 同步 2 · 提升 1 · 零迁移：看到 N2 变 DOWN、提升徽章、集群从 red 回到 green ③ 写入 0 · 同步 0 · 零提升 · 迁移 2：先看到 400 拒绝，再看 N2 变 SPLIT（孤岛降级）后恢复 UP。', hint: '看节点 token 颜色与 mono 主分片分配行：N2 变粉即宕机、变黄即分区；「提升」徽章出现代表副本接管；主分片分配行里 P1@N2 变为 P1↑@N1 即转移完成；scale 场景的 400 报错帧与 reindex 迁移 token 是关键确认点。', success: '能解释文档路由为什么永远打同一主分片、主分片数为何建索引时定死；能说清副本提升与集群颜色自愈的全过程；能说出扩容走 reindex、过半 quorum 防脑裂的机理。', requirements: [{ id: 'route', label: '① 分片路由 · hash 落位', when: { scenario: 'route' } }, { id: 'failover', label: '② 副本提升 · 故障转移', when: { scenario: 'failover' } }, { id: 'scale', label: '③ 扩容 reindex · 脑裂防护', when: { scenario: 'scale' } }] },
    quiz: [
      { prompt: '一篇文档写进 ES 后落在哪个主分片，由什么决定？', choices: ['协调节点随机挑一个负载最低的主分片', 'routing 值取哈希后再对主分片数取模——同一文档永远落同一分片', '按文档 _id 的字典序从小到大依次填充分片'], answer: 1, explanation: '路由规则是 hash(routing) % 主分片数：同一 routing 的文档恒定落在同一主分片，更新与查询只打一个分片。也因此主分片数一旦创建就不能改——改了取模结果全变，数据等于全部错位。' },
      { prompt: '主分片所在节点宕机，集群如何恢复可用？', choices: ['数据直接丢失，必须人工从备份恢复', '该分片的最新副本自动提升为新主分片，随后自动补建副本、颜色回到 green', '整个索引下线，直到宕机节点重新上线', '该分片永久降级为只读'], answer: 1, explanation: '副本不是冷备份而是随时可接管的活副本：主分片失联后，含最新数据的副本自动提升为新主，集群从 red 短暂变 yellow（缺副本），自动补建副本后回到 green——秒级到分钟级自愈，数据零丢失。' },
      { prompt: '索引建成后才发现主分片数不够、需要扩容，正确做法是？', choices: ['直接调大 number_of_shards 设置，分片自动分裂', '停掉索引后重建，旧数据废弃', '建一个更多主分片的新索引，reindex 搬数据，别名切换后删旧索引'], answer: 2, explanation: '主分片数被路由哈希锁死，不能原地改；扩容正道是建新索引（按峰值流量定分片数）→ reindex 后台搬数据 → 别名原子切换 → 删旧索引，业务只经历短暂只读窗口。' },
    ],
    boundary: '固定 3 节点 + 3 主分片的教学拓扑，路由哈希与文档标号为示意（未模拟真实 Murmur3 路由、自定义 routing 参数与 shard_size）；未模拟分片分配策略（磁盘水印/节点 awareness）、translog/flush 与副本同步内部机制、zen/fang 一致性协议的交互细节、集群 reroute 手工迁移、滚动升级与重启顺序、ILM 生命周期；集群颜色变化与提升耗时按教学节奏推进，副本同步次数为教学计数。',
    source: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/scalability.html',
  },
  {
    id: 'rocketmq-ordered', group: '消息中间件', title: 'RocketMQ 顺序消息与延迟消息', short: 'RocketMQ 顺序延迟', icon: 'ListOrdered', tag: '消息队列', number: '20',
    summary: '全局顺序的代价是单队列吞吐，分区有序才是正解：MessageQueueSelector 把同一订单钉在同一队列，消费端单线程串行、失败挂起重试；延迟消息则靠 18 个固定级别 + SCHEDULE_TOPIC 定时转投，到点才现身。',
    defaults: { scenario: 'ordered' },
    fields: [{ key: 'scenario', label: '投递场景', type: 'select', options: [['ordered', '① 分区有序 · 同订单同队列'], ['resend', '② 消费失败 · 挂起重试'], ['delay', '③ 延迟消息 · 定时转投']] }],
    metrics: [['sent', '消息发送', '条'], ['consumed', '消费完成', '条'], ['retries', '失败重试', '次'], ['queued', '队列积压', '条']],
    nodes: [['producer', '顺序生产者', '按业务 key 发消息', 'Send', 'blue'], ['selector', 'MessageQueueSelector', 'orderId hash → 队列', 'Route', 'yellow'], ['q0', '队列 q0', '同订单消息排队', 'ListOrdered', 'yellow'], ['q1', '队列 q1', '另一订单排队', 'ListOrdered', 'yellow'], ['consumer', '顺序消费者', '单队列单线程串行', 'Cpu', 'green'], ['schedule', '定时调度', 'SCHEDULE_TOPIC 转投', 'Clock', 'pink']],
    edges: [['producer', 'selector', '声明队列选择器'], ['selector', 'q0', 'O1 全步骤落 q0'], ['selector', 'q1', 'O2 全步骤落 q1'], ['q0', 'consumer', '串行消费'], ['q1', 'consumer', '串行消费'], ['producer', 'schedule', '延迟级别消息']],
    code: ['// 顺序消息：同一订单的全部步骤必须进入同一队列（MessageQueueSelector）', 'SendResult r = producer.send(msg, (m, queueList) -> {', '  long oid = ((Order) m.getProperty("orderId")).id;', '  return queueList.get((int) (oid % queueList.size())); }, orderId);', '// 消费端：注册 MessageListenerOrderly —— 队列内单线程串行、失败自动挂起重试', 'consumer.registerMessageListener(new MessageListenerOrderly() {', '  public ConsumeOrderlyStatus consumeMessage(...) {', '    return doBusiness(msg) ? SUCCESS : SUSPEND_CURRENT_QUEUE_A_MOMENT;', '  } });', '// 延迟消息：delayTimeLevel 固定 18 档（1s/5s/10s/30s/1m/2m/…/1h/2h）', 'msg.setDelayTimeLevel(5);   // 第 5 档 = 1 分钟（不允许自定义秒数）', '// 实现：消息先进 SCHEDULE_TOPIC_XXXX 对应级别队列，定时调度到点转投业务 topic'],
    theory: [['全局 vs 分区有序', '顺序粒度 = 队列', '全局严格有序 = 所有消息挤一个队列，吞吐被压到单队列上限。RocketMQ 的模型是分区（队列）有序：同一个业务 key（如订单号）的消息恒入同一队列，该队列内单线程消费即保序——不同订单交错完全允许。'], ['顺序消费失败', 'SUSPEND_CURRENT_QUEUE_A_MOMENT', '并发消费失败可跳过（offset 继续推），顺序消费不行：跳过的步骤会让后续消息建立在缺失前提上。MessageListenerOrderly 失败后挂起当前队列、原地重试，直到成功或人工介入——宁可慢，不可乱。'], ['延迟消息', '18 级固定档位 + 定时转投', '延迟不是让消费者 sleep，而是 Broker 端延时投递：消息按 delayTimeLevel 先落 SCHEDULE_TOPIC_XXXX 的对应级别队列，定时线程到点后把消息转投到业务 topic 的真实队列，消费者在指定时刻后才看到它。级别固定 18 档（1s～2h），不允许任意秒数。']],
    goals: ['区分全局有序与分区有序，说出 MessageQueueSelector 保证同一订单同队列的原理', '解释顺序消费失败为何必须挂起当前队列重试而不是跳过，以及它与并发消费重试的区别', '说出延迟消息的实现路径：18 级档位 → SCHEDULE_TOPIC 落位 → 定时转投业务队列'],
    challenge: { task: '固定订单 O1（创建→支付）与参照订单 O2，三个场景各运行一次：① O1 两步经 MessageQueueSelector 全部落 q0，消费端逐条串行消费 ② q0 预排 O1 四步（创建→支付→出库→完成），让「出库」连续失败两次后第三次成功，观察队列挂起与恢复 ③ 发送「订单超时关闭」delayTimeLevel=5，跟踪它从 SCHEDULE_TOPIC 等待到定时转投再到被消费。期望：① 发送 3 · 消费 3 · 零重试零积压：q0 内 O1 按创建→支付序出队，q1 的 O2 交错无妨 ② 发送 4 · 消费 4 · 重试 2 · 零积压：出库失败帧出现重试 token、后续「完成」未被提前消费 ③ 发送 1 · 消费 1 · 零重试：延迟消息 token 先黄（调度等待）后绿（转投消费）。', hint: '看队列 token：同订单步骤是否恒在同一队列内排队；失败帧出现「重试」粉 token 并停在队列头；延迟场景看消息从「调度等待」转「投递消费」的落点变化。', success: '能说出为什么同一订单的消息必须同队列串行消费、跨订单可以并行；能解释顺序消费失败挂起重试的必要性；能画出延迟消息 SCHEDULE_TOPIC 定时转投的完整路径。', requirements: [{ id: 'ordered', label: '① 分区有序 · 同订单同队列', when: { scenario: 'ordered' } }, { id: 'resend', label: '② 失败挂起 · 顺序重试', when: { scenario: 'resend' } }, { id: 'delay', label: '③ 延迟级别 · 定时转投', when: { scenario: 'delay' } }] },
    quiz: [
      { prompt: 'RocketMQ 中要保证同一订单的多条消息严格按序处理，正确做法是？', choices: ['所有消息都发到同一个 topic，靠消费者多线程抢消息时自行排序', '同一订单号经 MessageQueueSelector 恒落同一队列，该队列单线程串行消费', '为每个订单单独建一个 topic'], answer: 1, explanation: '全局顺序要把吞吐压到单队列，所以 RocketMQ 给的是分区（队列）有序：订单号 hash 选队列让同一订单的消息永远排进同一队列，队列内单线程消费即严格保序，不同订单并行互不阻塞。' },
      { prompt: '顺序消费中某条消息处理失败，消费者应该怎么做？', choices: ['跳过失败消息，先把后面的消息消费掉避免阻塞', '挂起当前队列的重试，失败消息原地重试直到成功或人工介入', '把失败消息改发到别的队列并行重试'], answer: 1, explanation: '顺序语义下跳过的步骤会污染后续消息的前提（支付先于创建就是事故），所以 MessageListenerOrderly 失败返回 SUSPEND_CURRENT_QUEUE_A_MOMENT：队列被挂起、失败消息原地重试，成功后才继续后续消息——宁可慢，不可乱。' },
      { prompt: '延迟消息 delayTimeLevel=5，Broker 是如何实现「到点才可见」的？', choices: ['消息先入 SCHEDULE_TOPIC_XXXX 对应级别队列，定时调度到点转投业务 topic，消费端届时才拉到', '消息直接进业务队列，由消费端收到后自己 sleep 到点再处理', 'delayTimeLevel 是精确秒数，Broker 按秒定时唤醒精确投递'], answer: 0, explanation: '延迟投递在 Broker 端完成：消息按 18 个固定级别（1s～2h）落入 SCHEDULE_TOPIC 的对应队列，定时线程扫描到点后把消息转投业务 topic——消费者只是「晚些时候才看到」，消费逻辑与普通消息完全一致。' },
    ],
    boundary: '固定 q0/q1 双队列与预设订单步骤的教学模型；未模拟 hash 取模与队列数量的实际对应、MessageQueueSelector 的具体参数形态（queueList 遍历时机）、顺序消费的消费进度/offset 提交细节、重试间隔与 SUSPEND 时长的真实语义、maxReconsumeTimes 顺序消费超限处理、延迟消息的时间轮与多级队列内部实现、事务消息与延迟消息的互斥限制、定时消息（任意时刻）与延迟消息的差异；失败次数与延迟档位为教学示意。',
    source: 'https://rocketmq.apache.org/docs/featureBehavior/03ordermessage',
  },
  {
    id: 'juc-coordination', group: 'Java 核心', title: 'CountDownLatch / CyclicBarrier / Semaphore', short: 'JUC 同步三件套', icon: 'Users', tag: '并发工具', number: '21',
    summary: '三个线程协作工具各管一种「对齐」：CountDownLatch 等 N 件事齐了一次性放行，CyclicBarrier 让 N 个线程互相等齐且可循环复用，Semaphore 用许可数把并发流量闸在 N 以内。',
    defaults: { scenario: 'countdown' },
    fields: [{ key: 'scenario', label: '协作场景', type: 'select', options: [['countdown', '① CountDownLatch · 等齐再合并'], ['barrier', '② CyclicBarrier · 互相等齐'], ['semaphore', '③ Semaphore · 许可限流']] }],
    metrics: [['submitted', '发起执行者', '个'], ['arrived', '到达协调点', '次'], ['released', '闸门放行', '次'], ['waiting', '真实阻塞', '人次']],
    nodes: [['main', '主线程', '编排 · 等待 / 发起', 'Monitor', 'blue'], ['pool', '线程池', '并行执行者', 'Boxes', 'yellow'], ['w1', '执行者 ①', '子任务 / 线程', 'Cpu', 'yellow'], ['w2', '执行者 ②', '子任务 / 线程', 'Cpu', 'yellow'], ['w3', '执行者 ③', '子任务 / 线程', 'Cpu', 'yellow'], ['coord', '协调器', 'Latch / Barrier / Semaphore', 'Waypoints', 'pink']],
    edges: [['main', 'pool', '提交并行任务'], ['pool', 'w1', '分配'], ['pool', 'w2', '分配'], ['pool', 'w3', '分配'], ['w1', 'coord', '到达'], ['coord', 'main', '放行 / 唤醒']],
    code: ['// CountDownLatch：主线程等 N 个子任务全部 countDown 后才放行（一次性）', 'CountDownLatch latch = new CountDownLatch(3);', 'executor.submit(() -> { User u = fetchUser(); latch.countDown(); });', 'executor.submit(() -> { Product p = fetchProduct(); latch.countDown(); });', 'latch.await(5, TimeUnit.SECONDS); // 挂起等待；超时兜底防永久阻塞', '// CyclicBarrier：N 个线程互相等齐，最后到达者触发打开；放行后自动复位可复用', 'CyclicBarrier barrier = new CyclicBarrier(3);', 'int phase = barrier.await(); // 先到者阻塞，最后一个到齐的线程返回并触发放行', '// Semaphore：acquire 拿许可进临界区，release 归还；不区分持有者，谁都能放', 'Semaphore sem = new Semaphore(2);', 'sem.acquire(); try { writeAuditLog(); } finally { sem.release(); }'],
    theory: [['CountDownLatch', 'await 等计数归零', '主线程 await 挂起等待，N 个子任务完成后各自 countDown，计数归零瞬间唤醒主线程——「等 N 件事齐」的一次性闸门。归零后不可复用；任务异常导致 countDown 不执行会让主线程永久阻塞，生产必须用 await(timeout)。'], ['CyclicBarrier', '线程互相等 · 可循环', 'N 个线程执行完阶段一后各自 await 在屏障前，先到者阻塞等待，最后一个到达者触发屏障打开，所有人同时进入阶段二；放行后屏障自动复位（cyclic），下一轮流程可重复使用。破坏或中断会抛 BrokenBarrierException。'], ['Semaphore', '许可计数 · 限流闸门', '构造时给 N 张许可：acquire 成功（许可-1）才能进临界区，release（许可+1）归还——控制同时进入资源的并发数（连接池、限流）。它不记录谁持有：任何线程都能 release，与锁的「持有者独占」本质不同。']],
    goals: ['区分三种协调语义：等 N 件事齐（Latch）、N 个线程互相等齐且可复用（Barrier）、许可限流（Semaphore）', '说清 CountDownLatch 一次性与 CyclicBarrier 可循环复用的差异，以及 await 阻塞与超时兜底', '理解 Semaphore 的 acquire/release 计数模型：谁都能放、不区分持有者，用于控制并发度而非互斥'],
    challenge: { task: '三个场景各运行一次：① 3 个子任务（用户/商品/库存）并行拉取，主线程 await 等齐后一次性合并 ② 3 个线程分片处理两阶段任务，观察「先到者阻塞、最后到达者触发放行」③ 3 个线程争抢 2 张许可，观察丙排队直到甲 release 才进场。期望：① 门闩 3→2→1→0、await 放行 1 次、三份数据齐后合并 ② A、B 先到真实阻塞（已到 1/3→2/3）、C 最后到达触发打开、三线程齐进阶段二 ③ 甲/乙直通（许可 0/2）、丙 pink 排队、甲 release 后丙才获得许可进场。', hint: '看协调器 token 的数字变化（门闩剩 N/3、屏障已到 N/3、许可剩 N/2）与执行者状态：黄=执行中、粉=等待/排队、绿=完成。', success: '能说出三件套各自解决哪种协作问题（等齐一次性 / 互相等可复用 / 并发限流），并解释为何 Semaphore 不区分持有者、CountDownLatch 必须配超时兜底。', requirements: [{ id: 'countdown', label: '① Latch 等齐合并', when: { scenario: 'countdown' } }, { id: 'barrier', label: '② Barrier 互相等齐', when: { scenario: 'barrier' } }, { id: 'semaphore', label: '③ Semaphore 许可限流', when: { scenario: 'semaphore' } }] },
    quiz: [
      { prompt: 'CountDownLatch(3) 中，主线程 latch.await() 什么时候返回？', choices: ['3 秒后自动超时返回', '3 个子任务各执行一次 countDown、计数归零时', '主线程自己调用三次 countDown 之后'], answer: 1, explanation: 'await 挂起主线程直到计数器归零——每个子任务完成时 countDown() 减一，三份数据齐备的瞬间主线程被唤醒。它是「等 N 件事齐」的一次性闸门。' },
      { prompt: 'CyclicBarrier 与 CountDownLatch 的本质区别是？', choices: ['Barrier 等外部事件，Latch 是线程互相等', 'Latch 一次性、归零即终局；Barrier 由最后到达者触发打开、放行后自动复位可循环复用，且是线程间互相等齐', 'Barrier 最多只能协调两个线程'], answer: 1, explanation: 'CountDownLatch 通常是主线程等子任务「报数」，归零后不可复用；CyclicBarrier 是 N 个对等线程互相等齐后一起放行，屏障复位后下一轮流程可继续使用（cyclic 由此得名）。' },
      { prompt: 'Semaphore(2) 场景下，第三个线程调用 acquire() 会怎样？', choices: ['立即抛异常拒绝执行', '直接获得许可继续执行', '阻塞排队，直到有线程 release 归还许可后才被唤醒'], answer: 2, explanation: '许可耗尽时 acquire 阻塞进入等待队列，前面某个线程执行完 release() 归还许可后，队首等待者被唤醒拿到许可进场。Semaphore 用许可数把并发流量闸在固定水位内。' },
    ],
    boundary: '固定 3 个执行者的教学模型；未模拟 await(timeout) 超时分支与中断异常、CyclicBarrier 的 BrokenBarrierException（线程中断/超时致屏障破坏）、Semaphore 公平/非公平队列与 AQS 内部实现（见 ReentrantLock 与 AQS 课）、release 超额与 tryAcquire 非阻塞路径、多阶段复杂流水线、以及实际业务中的线程池饱和与任务失败补偿策略；时间为教学示意。',
    source: 'https://docs.oracle.com/javase/tutorial/essential/concurrency/sync.html',
  },
  {
    id: 'mysql-crash', group: '数据与缓存', title: 'InnoDB 事务日志与崩溃恢复', short: 'InnoDB 日志与恢复', icon: 'DatabaseZap', tag: '存储引擎', number: '22',
    summary: '提交成功 ≠ 数据页已落盘：WAL 让 redo 日志先行 fsync、数据页留在 Buffer Pool 慢慢刷；实例崩溃后靠 checkpoint + redo 重放找回已提交事务、undo 回滚抹掉未提交事务；redo 与 binlog 之间用两阶段提交对齐崩溃窗口，xid 判定补提交还是回滚。',
    defaults: { scenario: 'wal' },
    fields: [{ key: 'scenario', label: '实验场景', type: 'select', options: [['wal', '① WAL 先行 · 提交与刷脏'], ['crash', '② 崩溃恢复 · redo 重放'], ['twophase', '③ 两阶段提交 · 崩溃窗口']] }],
    metrics: [['committed', '已提交事务', '个'], ['flushed', '脏页刷盘', '页'], ['replayed', '重放补齐', '次'], ['rolledback', '回滚清理', '个']],
    nodes: [['app', '应用', '事务提交 / 崩溃', 'Monitor', 'blue'], ['bp', 'Buffer Pool', '缓存页 → 脏页', 'Boxes', 'yellow'], ['redo', 'redo log', 'WAL 顺序写', 'Layers', 'pink'], ['data', '数据文件', '数据页落盘', 'Table2', 'green'], ['undo', 'undo log', '回滚映像', 'Recycle', 'yellow'], ['binlog', 'binlog', '归档与复制', 'FileCheck2', 'blue']],
    edges: [['app', 'bp', '改写缓存页'], ['bp', 'redo', 'WAL：先落日志'], ['bp', 'data', '后台刷盘'], ['app', 'undo', '记录回滚映像'], ['app', 'binlog', '归档写入'], ['redo', 'bp', '恢复重放']],
    code: ['-- WAL：先写日志、后落数据页 —— 数据页可以延迟批量刷，日志必须先行持久化', 'BEGIN; UPDATE t SET bal = bal - 100 WHERE id = 1;   -- ① 改 Buffer Pool 页 5 → 脏页', 'COMMIT;   -- ② 提交瞬间 redo log fsync 落盘 → 返回 commit ok（数据页可能还在内存！）', '-- ③ 后台刷脏线程把脏页异步写盘 → checkpoint 前移；崩溃时落后部分靠 redo 找回', '-- 崩溃恢复：从 checkpoint LSN 起重放 redo（已提交找回）→ 按 undo 回滚（未提交抹掉）', '-- 两阶段提交：redo prepare → binlog fsync → redo commit，三个崩溃窗口用 xid 对齐', '-- 恢复判定：binlog 有该 xid → 补 commit；binlog 没有 → undo 回滚 —— 主从不分裂'],
    theory: [['WAL 先行', '日志顺序写 · 数据页延迟刷', '直接改磁盘数据页是随机写，事务提交若等页落盘会慢一个数量级。WAL 反着来：提交时只把 redo log 顺序写盘（fsync），数据页先留在 Buffer Pool 标记为脏页、由后台线程批量刷。代价是磁盘页可能滞后于已提交事务——但 redo 里总有完整记录，崩溃后可以重放，这就是「提交保证与页落盘解耦」的根源。'], ['崩溃恢复', 'checkpoint + redo 重放 + undo 回滚', '启动恢复：从最近 checkpoint 记录的 LSN 开始顺序重放 redo（roll-forward），把已提交但未刷盘的事务找回——提交时 redo 已 fsync，所以已提交事务零丢失；随后扫描未提交事务，按 undo 里的回滚映像把修改抹掉（roll-back）。先向前重放、再向后回滚，把崩溃瞬间的中间态校正到一致。'], ['两阶段提交', 'prepare → binlog → commit', 'redo（InnoDB 崩溃恢复）与 binlog（Server 归档 + 从库复制）是两个独立文件。若主库提交了而从库没收到对应记录，主从就分裂。两阶段提交拆三步：redo 写 prepare → binlog 落盘 → redo 写 commit。崩溃在中间时靠 xid 判定：binlog 里有该事务 → 补 commit（从库已有，主库必须也提交）；binlog 里没有 → 回滚（从库没有，主库不该有）。']],
    goals: ['解释 WAL 为什么「先写日志后落数据页」：提交成功的保证是 redo fsync，数据页可延迟批量刷盘', '说出崩溃恢复的两步：redo 重放找回已提交事务（roll-forward）、undo 回滚清掉未提交事务（roll-back），checkpoint 决定重放起点', '画出两阶段提交三步（redo prepare → binlog fsync → redo commit）并说清崩溃窗口如何用 xid 判定补提交还是回滚'],
    challenge: { task: '三个场景各运行一次：① 事务 T1~T3 依次提交，观察 redo 先 fsync、脏页滞后刷盘，理解「commit ok 时页可能还在内存」② T2、T3 的脏页尚未落盘时实例崩溃，启动恢复观察 checkpoint 起点 + redo 重放找回已提交数据 ③ 观察事务在 prepare/binlog/commit 三个时点崩溃的恢复动作。期望：① 提交 3 · 刷盘 1 · 零重放零回滚 ② 提交 3 · 崩溃前刷盘 1 · 重放 2 · 零丢失（T2、T3 找回）③ 提交 2 · 重放补齐 1 · 回滚 1——binlog 有 xid 的补 commit、没有的回滚。', hint: '看日志 token 颜色：redo 条目黄→绿表示已 fsync；数据页 token 黄=脏页未落盘、绿=已刷盘；崩溃帧出现红粉 token，恢复帧看「重放 / 回滚」动作与数字。', success: '能解释为何提交成功但页未落盘也不丢数据（WAL + redo 重放）；能区分 redo 与 binlog 的职责；能画出两阶段提交的三个时点并说出崩溃窗口的 xid 判定规则。', requirements: [{ id: 'wal', label: '① WAL 先行 · 提交与刷脏', when: { scenario: 'wal' } }, { id: 'crash', label: '② 崩溃恢复 · redo 重放', when: { scenario: 'crash' } }, { id: 'twophase', label: '③ 两阶段提交 · 崩溃窗口', when: { scenario: 'twophase' } }] },
    quiz: [
      { prompt: '事务提交成功（客户端已收到 commit ok）后实例立刻崩溃，重启后这条已提交数据会丢吗？', choices: ['会丢：数据页还没刷到磁盘，内存里的修改随崩溃消失', '不会丢：提交时 redo log 已 fsync 落盘，启动恢复会重放 redo 找回它', '取决于运气：赶上后台刷盘就不丢，没赶上就丢'], answer: 1, explanation: 'WAL 的保证就在这：commit ok 只承诺 redo 已 fsync，不承诺数据页已落盘。页没刷没关系——redo 里保存着页级修改记录，崩溃恢复从 checkpoint 起重放 redo，把这条已提交事务的修改找回来，所以已提交事务零丢失。' },
      { prompt: 'redo log 与 binlog 的本质区别是？', choices: ['redo 是 InnoDB 崩溃恢复用的物理日志（页级重做、循环覆盖）；binlog 是 Server 层归档与复制用的逻辑日志（追加保存、记录完整历史）', '两者记录内容完全一样，只是存放在不同目录', 'redo 记录 SQL 语句用于主从复制，binlog 记录字节级修改用于崩溃恢复'], answer: 0, explanation: 'redo 属于 InnoDB 存储引擎，记的是「页 5 的偏移 X 被改成什么」这类物理修改，按 LSN 循环覆盖，只服务崩溃恢复；binlog 属于 Server 层，记的是逻辑变更（行级/语句级），追加保存全量历史，服务归档、闪回与主从复制。' },
      { prompt: '两阶段提交中，实例在「redo prepare 已写、binlog 已落盘、redo commit 未写」时崩溃，恢复时该事务怎么处理？', choices: ['直接回滚：只要 redo commit 没写就说明没提交成功', '状态不一致无法自动处理，只能人工介入', '检查 binlog：该事务的 xid 已存在则补写 redo commit 让其提交——从库可能已收到，主库必须也提交'], answer: 2, explanation: 'binlog 落盘意味着从库可能已经执行了这条事务；若主库回滚，主从就分裂。所以恢复器以 binlog 为准：xid 已在 binlog 中 → 补一个 redo commit 让事务完成提交；xid 不在 → 说明从库没收到，回滚它。prepare → binlog → commit 的三步把崩溃窗口压缩到可判定。' },
    ],
    boundary: '固定 3 个事务与单数据页的教学模型；未模拟 redo log buffer 攒批与组提交（group commit）、log file 循环覆盖与 archive 日志、真实 LSN/页号偏移的物理格式、checkpoint 的 fuzzy 机制、多页并行刷盘、doublewrite buffer、binlog 的 statement/row 格式差异、XA 分布式事务（跨库/跨资源管理器）、崩溃恢复的并行回滚与 purge 流程；LSN 数值与刷盘节奏为教学示意。',
    source: 'https://dev.mysql.com/doc/refman/8.0/en/innodb-redo-log.html',
  },
  {
    id: 'concurrent-hashmap', group: 'Java 核心', title: 'ConcurrentHashMap 并发写入与扩容', short: 'ConcurrentHashMap', icon: 'Box', tag: '并发容器', number: '23',
    summary: '写并发不靠全表锁：空槽 CAS 直插、冲突才 synchronized 锁住单个 bin；扩容时已迁槽位放 ForwardingNode，读写自动跟随新表；计数用 baseCount + CounterCell 分流——看 JDK8 如何把并发度从 1 放大到桶数。',
    defaults: { scenario: 'put' },
    fields: [{ key: 'scenario', label: '实验场景', type: 'select', options: [['put', '① 并发写入 · CAS 与 bin 锁'], ['resize', '② 并发扩容 · fwd 迁移'], ['count', '③ 弱一致计数 · 分流']] }],
    metrics: [['inserted', '写入成功', '次'], ['conflicts', '撞槽 / 排队', '次'], ['migrated', '槽位迁移', '个'], ['spread', '计数分流', '次']],
    nodes: [['t1', '线程①', '写入者 put(k1)', 'Cpu', 'yellow'], ['t2', '线程②', '写入者 put(k2)', 'Cpu', 'yellow'], ['t3', '线程③', '写入者 put(k3)', 'Cpu', 'yellow'], ['t4', '线程④', '写入者 put(k4)', 'Cpu', 'yellow'], ['table', 'Node[] table', '桶数组 · 链表 bin', 'Table2', 'green'], ['sync', 'bin 协调器', 'bin 锁 / fwd / 计数', 'Waypoints', 'pink']],
    edges: [['t1', 'table', 'hash 定位槽位'], ['t2', 'table', 'hash 定位槽位'], ['t3', 'table', 'hash 定位槽位'], ['t4', 'table', 'hash 定位槽位'], ['table', 'sync', '写冲突上锁'], ['sync', 'table', '锁内串行写']],
    code: ['// JDK8 ConcurrentHashMap：锁粒度从「整表」细化到「单个 bin」——并发度≈桶数而非 1', 'V put(K key, V value) {', '    int i = spread(key.hashCode()) & (table.length - 1);   // hash 扰动后定位槽位', '    if (tabAt(table, i) == null && casTabAt(table, i, null, new Node<>(key, value)))', '        return;   // 快路径：槽位为空，CAS 无锁直插', '    synchronized (tabAt(table, i)) { /* 慢路径：锁住 bin 头节点，链尾追加 */ }', '    // 对比 Hashtable 的 synchronized(this)：一次只放行一个写线程；CHM 只锁一个 bin', '}', '// 并发扩容：槽位迁移完原地放 ForwardingNode(fwd)，读写线程遇 fwd 自动转新表继续', '// 计数：baseCount 用 CAS；高并发撞车时增量分流进 CounterCell[]（LongAdder 思想）', '// size() = baseCount + ΣCounterCell —— 求和瞬间仍有写入，所以是弱一致的近似值'],
    theory: [['锁粒度进化', 'CAS 空槽直插 · 冲突锁单 bin', 'JDK8 的 put 分两档：槽位为空 → CAS 原子直插，全程无锁（快路径）；槽位被占 → synchronized 锁住该 bin 的头节点做链尾追加（慢路径）。锁不落在整张表上：写不同槽的两个线程完全并行——并发度≈桶数。对比 Hashtable / Collections.synchronizedMap 的 this 全表锁（任意写都互斥）与 JDK7 的 Segment 分段锁（16 段粗粒度），JDK8 把锁粒度压到了最小并发单元。'], ['并发扩容', 'fwd 占位 · 读写跟随新表', 'size 达到 0.75×capacity 触发扩容到 2 倍：新表先建好，旧表槽位从尾向前逐个迁移（transferIndex 协作指针递减取槽），每个 key 按 hash 高位 0/1 落入新表原槽或原槽+旧容量——一条链就地拆成两段。每迁完一个槽，旧位置放入 ForwardingNode（fwd 占位）。此后任何线程访问该槽：写操作沿 fwd 转入新表执行、读操作同样跟随——已迁槽绝不再被写旧表，扩容期间插入不丢也不重复。'], ['弱一致计数', 'baseCount CAS · CounterCell 分流', '全局计数 baseCount 用 CAS 自增，低并发时一次成功。多个线程同时自增撞车时，失败者不无限自旋，而是把增量写进自己散列的 CounterCell 槽，size() 以 baseCount + ΣCounterCell 求和。求和瞬间新 put 的计数可能还没落位，所以 size() 是弱一致近似值；迭代器同样弱一致、不抛 ConcurrentModificationException。这与 LongAdder / Striped64 是同一套思想：把单一热点计数打散成多个可并行累加的单元。']],
    goals: ['说清 JDK8 锁粒度：空槽 CAS 无锁直插、冲突 synchronized 只锁 bin 头节点；与 Hashtable 全表锁相比并发度为什么≈桶数', '解释并发扩容的 ForwardingNode 机制：槽迁移完成后放 fwd 占位，读写线程遇 fwd 自动转入新表，扩容期间插入不丢不重复', '说明 size() 为什么是弱一致近似值：baseCount CAS + CounterCell 分流（LongAdder 思想），求和与写入并发进行'],
    challenge: { task: '三个场景各运行一次：① T1 空槽 CAS 直插 k1 后，T2、T3 同写槽 3：CAS 双双失败，T2 抢到 bin 锁链尾追加 k2，T3 阻塞排队；T4 此刻写槽 5 空槽直插成功——不同槽互不阻塞 ② 8 槽表已存 6 个 key 将满，下一次 put 触发扩容：观察旧槽逐个迁移并留 fwd 占位、槽 2 的链 B/C 按 hash 高位拆到新表槽 2 与槽 10、迁移中的 put 遇 fwd 自动转新表 ③ 写入者把 baseCount 撞出两次 CAS 失败，失败增量写进 CounterCell，size() 求和快照错过并发中的第 6 次写入。期望：① 写入 4 · 冲突 2 · T3 真实排队后获锁追加 k3、链长 3 ② 迁移 8 · 写入 2 · 全部旧槽变 fwd ③ 写入 6 · 冲突 2 · 分流 2 · size 快照先滞后后收敛。', hint: '看槽位 token：绿=key 已落位、黄=链式追加/正在写、粉=fwd 占位或排队等待；mono 指标行看 写入/冲突/迁移/分流 四个计数；场景② 关注 fwd 与新表槽位出现，场景③ 关注 base 与 cells 数字。', success: '能解释 JDK8 CHM 的锁粒度设计（空槽 CAS + 冲突锁单 bin）与 Hashtable 的本质差异；能说清扩容中 ForwardingNode 的作用（占位 + 读写跟随新表）；能解释 size() 弱一致的原因与 CounterCell 分流思想。', requirements: [{ id: 'put', label: '① 并发写入 · CAS 与 bin 锁', when: { scenario: 'put' } }, { id: 'resize', label: '② 并发扩容 · fwd 迁移', when: { scenario: 'resize' } }, { id: 'count', label: '③ 弱一致计数 · 分流', when: { scenario: 'count' } }] },
    quiz: [
      { prompt: '两个线程同时 put 到两个不同的空槽位，会发生什么？', choices: ['两个线程必须排队：put 存在全局互斥', '各自 CAS 直插成功，完全并行、互不等待', '先到者赢，后到者自旋等待同一把锁'], answer: 1, explanation: '空槽位走 CAS 快路径：每个线程只对自己的目标槽做一次 compare-and-swap，锁不落地、互不接触——写不同 bin 的线程天然并行，这正是「并发度≈桶数」的来源。' },
      { prompt: '扩容迁移完成后，旧表中已迁移槽位里留下的是什么？', choices: ['ForwardingNode（fwd）：任何读写遇它都会自动转去新表的对应槽位继续', 'null——槽位直接清空，旧表整表废弃', '原链表的深拷贝副本，供读线程回退使用'], answer: 0, explanation: 'fwd 是迁移完成的标记：写线程遇 fwd 不会把数据写进旧表（会丢），而是沿它转入新表执行；读线程同样跟随。占位 + 路由两件事由一个节点完成，扩容期间并发读写才不丢不重。' },
      { prompt: '高并发下 CHM 的 size() 为什么可能不是最新精确值？', choices: ['size() 内部持悲观锁，执行期间禁止一切写入', 'CAS 撞车的线程把增量写进 CounterCell[]；size() 求和瞬间新的写入仍在发生，读到的快照天然滞后', 'CHM 内部固定每 1000 次写入才刷新一次计数'], answer: 1, explanation: 'size() = baseCount + ΣCounterCell 只是「读快照 + 求和」：求和进行时新 put 的计数可能还没落到 base 或 cell 上，所以结果弱一致——这是用分散计数换并发度的必然代价，LongAdder 同理。' },
    ],
    boundary: '固定 8/16 槽与 4 个写入者的教学模型，hash 简化为预置槽位映射（真实为 spread 扰动 + (n-1) 掩码寻址）；未模拟链表树化与退化（见 HashMap 课）、bin 锁的锁膨胀与节点首尾插入细节、扩容的 helpTransfer 多线程协作搬运与位点竞争、CounterCell 的扩容上限与 sum 两次上限重试、LongAdder/Striped64 的 probe 冲突迁移、JDK7 分段锁结构、映射计数 mappingCount 的 long 语义；槽位与数字为教学示意。',
    source: 'https://docs.oracle.com/javase/tutorial/essential/concurrency/collections.html',
  },
  {
    id: 'mysql-lock', group: '数据与缓存', title: 'InnoDB 行锁 · 间隙锁 · 死锁', short: 'InnoDB 锁与死锁', tag: '锁机制', number: '24',
    summary: 'InnoDB 的锁落在「行」上而不是整张表：同写一行时后到者进锁等待队列阻塞排队，普通 SELECT 走 MVCC 快照读不撞锁；RR 隔离级别用间隙锁把行与行之间还不存在的空隙也罩住，幻读从入口被堵死；两个事务互相等对方手里的锁会成环，死锁检测器挑 undo 代价最小的 victim 回滚——应用要做的是捕获 1213 后重试整个事务。',
    defaults: { scenario: 'row' },
    fields: [{ key: 'scenario', label: '实验场景', type: 'select', options: [['row', '① 行锁互斥 · 等待队列'], ['gap', '② 间隙锁 · 防幻读'], ['deadlock', '③ 死锁环 · 检测与回滚']] }],
    metrics: [['locked', '加锁成功', '次'], ['blocked', '锁等待', '次'], ['deadlocks', '死锁环', '次'], ['aborted', '回滚事务', '个']],
    nodes: [['t1', '事务 T1', 'UPDATE / 加锁读', 'Cpu', 'yellow'], ['t2', '事务 T2', 'UPDATE / INSERT', 'Cpu', 'yellow'], ['t3', '事务 T3', 'SELECT · 快照读', 'Cpu', 'yellow'], ['lock', '锁管理器', '行锁 / 间隙锁', 'Lock', 'green'], ['db', 'InnoDB', '事务 · MVCC · 隔离级别', 'Database', 'blue'], ['detector', '死锁检测器', '等待图 · victim', 'Activity', 'pink']],
    edges: [['t1', 'lock', '申请行锁'], ['t2', 'lock', '申请行锁'], ['t3', 'lock', '快照读不加锁'], ['lock', 'db', '持锁执行 DML'], ['lock', 'detector', '等待图供检测']],
    code: ['-- InnoDB 锁粒度是「行」：UPDATE / DELETE / SELECT ... FOR UPDATE 才会申请行锁', 'BEGIN;', 'UPDATE products SET stock = stock - 1 WHERE id = 1;   -- 在行 1 上加 X（排他）锁', '-- 另一事务再 UPDATE 同一行：X 与 X 不兼容 → 进入锁等待队列阻塞（innodb_lock_wait_timeout 默认 50s）', '-- 普通 SELECT 不加锁：MVCC 快照读从 X 锁旁边零等待穿过', 'SELECT * FROM products WHERE id BETWEEN 2 AND 5 FOR UPDATE;   -- RR：记录锁 + 间隙锁 = next-key', '-- 间隙锁罩住「还不存在的行」：别的事务向该空隙 INSERT 会被阻塞 → 幻读被堵死', '-- 死锁：两事务各持一把锁、互相等对方手里那把 → 等待图成环（互斥/持有并等待/不可剥夺/循环等待）', '-- 检测器发现环 → 回滚 undo 代价最小的 victim → 应用收到 Error 1213 → 重试整个事务', '-- 预防：所有事务按固定顺序加锁（先小 id 后大 id），环无从形成'],
    theory: [['行锁互斥', 'X 锁不兼容 · 等待队列', 'UPDATE/DELETE/FOR UPDATE 对目标行申请 X 锁：行空闲直接授予；被他人持有则冲突——后到者不是报错，而是进入锁等待队列阻塞，直到持有者提交/回滚释放，或被 innodb_lock_wait_timeout（默认 50s）超时踢出（Error 1205）。锁粒度是行不是表：写不同行互不干扰，普通 SELECT 走 MVCC 快照读、连锁都不申请，因此读写天然并行。'], ['间隙锁 · next-key', '罩住不存在的行 · 防幻读', 'RR（可重复读）隔离级别下，范围加锁会把扫描区间里「行 + 空隙」一起锁住：行上挂 X 记录锁，行与行之间的空隙挂 GAP 间隙锁，合称 next-key lock。插入者要先声明「插入意向锁」——与间隙锁不兼容 → 向被锁空隙的 INSERT 排队等待。幻读正是「读的范围里被插进新行」：间隙锁锁住还不存在的行，把幻读堵在入口；RC 隔离级别没有间隙锁，可幻读但并发更高。'], ['死锁与检测', '四条件 · victim 回滚 · 重试', '死锁 = 互斥 + 持有并等待 + 不可剥夺 + 循环等待同时成立。最典型成因是加锁顺序互反：T1 拿行 1 等行 2、T2 拿行 2 等行 1。InnoDB 的应对不是干等超时：后台检测器周期扫描锁等待构成的等待图（wait-for graph），发现环即挑 undo 代价最小（已做修改最少）的事务作 victim 回滚、释放其全部锁，另一方立即继续——victim 收到 Error 1213，应用必须捕获后重试整个事务；根治手段是统一加锁顺序 + 缩短事务。']],
    goals: ['解释行锁互斥：X 锁冲突时后到者进锁等待队列阻塞（innodb_lock_wait_timeout 超时才报错），普通 SELECT 走 MVCC 快照读不撞锁', '说清间隙锁与 next-key lock 为何能防幻读：行锁管已存在的行、间隙锁管还不存在的行，插入意向锁与间隙锁互斥', '复述死锁四条件与 InnoDB 的应对：检测器找等待环 → 回滚 undo 代价最小的 victim → 应用捕获 1213 后重试整个事务'],
    challenge: { task: '三个场景各运行一次：① T1 UPDATE 行 1 后 T2 对同一行 UPDATE——X 与 X 不兼容，观察 T2 进锁等待队列、T3 的普通 SELECT 零等待穿过、T1 提交后 T2 被唤醒完成 ② RR 下 T1 对 id BETWEEN 2 AND 5 加锁读：行 2、行 5 挂 X 记录锁、中间空隙挂 GAP 间隙锁，T2 向空隙 INSERT id=3 被阻塞，T1 提交后才插入成功 ③ T1 先锁行 1 再要行 2、T2 先锁行 2 再要行 1——循环等待成环，检测器回滚 undo 代价小的 T2（Error 1213），T1 走完提交，应用重试整个 T2 事务。期望：① 加锁 2 · 等待 1 · T2 真实排队后获锁、T3 从未被阻塞 ② 加锁 2 · 等待 1 · T2 排队直到 T1 提交 ③ 加锁 4 · 等待 2 · 死锁环 1 · 回滚 1——T2 标为 victim 回滚、行 2 让给 T1、重试后两事务都完成。', hint: '看锁 token：绿=行 X 锁被持有、黄=间隙锁 GAP、粉=等待队列与 victim 回滚标记；mono 指标行看 加锁/等待/死锁环/回滚 四个计数；场景③ 关注 detector 帧出现的「环」判定与 victim 挑选。', success: '能解释行锁互斥与锁等待队列（什么操作会撞锁、普通读为什么不撞）；能说清 RR 下间隙锁如何防幻读（插入被堵、RC 没有间隙锁）；能讲出死锁四条件、检测器为什么选 undo 最小的 victim、应用为何要重试整个事务。', requirements: [{ id: 'row', label: '① 行锁互斥 · 等待队列', when: { scenario: 'row' } }, { id: 'gap', label: '② 间隙锁 · 防幻读', when: { scenario: 'gap' } }, { id: 'deadlock', label: '③ 死锁环 · 检测与回滚', when: { scenario: 'deadlock' } }] },
    quiz: [
      { prompt: '两个事务先后对同一行执行 UPDATE，后到的事务会怎样？', choices: ['立即报错：MySQL 检测到行锁冲突直接拒绝', '进入锁等待队列阻塞：持有者提交/回滚释放锁后被唤醒继续，超过 innodb_lock_wait_timeout（默认 50s）才抛 1205 错误', '自动降级为快照读：先不加锁把数据返回给应用'], answer: 1, explanation: '行锁冲突走「等待」而非「失败」：后到者挂进锁等待队列，持有者释放锁后按序被唤醒。只有排队超过 innodb_lock_wait_timeout（默认 50 秒）才抛 1205 超时错误——期间普通快照读不受影响。' },
      { prompt: '形成死锁必须满足的条件是？', choices: ['互斥 + 持有并等待 + 不可剥夺 + 循环等待，四个同时满足', '只要两个事务同时对同一行加锁就必然死锁', '只要锁等待超过 innodb_lock_wait_timeout 就必然死锁'], answer: 0, explanation: '死锁是四条件的组合产物：行锁本身互斥（①）；每个事务都攥着已拿到的锁去等对方手里的（②③：持有并等待、不可剥夺）；等待关系连成环（④）。少一个环就断——比如所有事务按同一顺序加锁，循环等待不可能出现，这就是「固定加锁顺序防死锁」的原理。' },
      { prompt: 'InnoDB 死锁检测器发现等待环后如何处置？', choices: ['回滚持有锁最多的事务，把损失压到最小', '两个事务全部回滚，彻底消除不一致', '回滚 undo 代价最小（已做修改最少）的 victim 并释放其锁，让另一事务继续；victim 收到 1213 后重试整个事务'], answer: 2, explanation: '死锁不罚双方：检测器比较 undo 大小，挑代价最小的那个做 victim 回滚，其锁全部释放、另一事务立刻能走完——回滚方收到 Error 1213。事务在引擎侧已整个失败，应用必须捕获 1213 重试「整个事务」而非从断点续跑，否则已做的修改会丢。' },
    ],
    boundary: '固定行 1/2/5 与单个间隙的教学模型；未模拟完整锁矩阵（S/IX/SIX/自增锁）与锁升级、插入意向锁的排队细则、next-key 的边界细节（左开右闭、(5,∞) 上界区间、唯一索引等值命中退化为记录锁）、innodb_lock_wait_timeout 与 lock_wait_timeout 的真实语义、死锁检测器扫描周期与 victim 权重细节（事务 id/undo 大小）、RC/READ UNCOMMITTED 下间隙锁差异与 binlog 格式联动、performance_schema.data_locks 锁监控查询、多行多事务死锁的复杂度；行号与锁对象为教学示意。',
    source: 'https://dev.mysql.com/doc/refman/8.0/en/innodb-locking.html',
  },
  {
    id: 'kafka-eos', group: '消息中间件', title: 'Kafka 幂等与事务 · 精确一次', short: 'Kafka 幂等与事务', icon: 'ShieldCheck', tag: '消息可靠性', number: '25',
    summary: 'Kafka 的 exactly-once 由四层拼成：幂等 producer 用 (PID, 序列号) 窗口把「重试的重复」拦在 Broker 门外；跨分区原子交给事务——coordinator 两阶段拍板、各分区写 commit/abort marker、read_committed 消费者用 LSO 把关；旧实例复活想再提交，被递增的 epoch 代数直接驱逐。',
    defaults: { scenario: 'idempotent' },
    fields: [{ key: 'scenario', label: '实验场景', type: 'select', options: [['idempotent', '① 幂等去重 · PID+序列号'], ['transaction', '② 事务 · 跨分区原子'], ['fencing', '③ 僵尸驱逐 · epoch 代数']] }],
    metrics: [['sent', '发送批次', '次'], ['stored', '落盘批次', '次'], ['committed', '生效批次', '次'], ['blocked', '机制拦截', '次']],
    nodes: [['producer', '生产者', 'PID · seq · epoch', 'Send', 'blue'], ['check', '精确一次校验', '序列窗口 · epoch 代数', 'ShieldAlert', 'yellow'], ['broker', 'Broker 分区', '追加日志 · LSO', 'Server', 'green'], ['coord', '事务协调器', '__transaction_state', 'Waypoints', 'pink'], ['consumer', '消费者', 'read_committed', 'Monitor', 'blue']],
    edges: [['producer', 'check', '携带 PID·seq / epoch'], ['check', 'broker', '校验后追加'], ['producer', 'coord', 'begin / commit / abort'], ['coord', 'broker', '两阶段 marker'], ['broker', 'consumer', 'LSO 内可见'], ['coord', 'producer', 'InitPid / fence']],
    code: ['// 幂等：批次头携带 (PID, 序列号)，Broker 按 (PID, 分区) 记住最近已确认的序列号', 'properties.put(ProducerConfig.ENABLE_IDEMPOTENCE_CONFIG, true);', 'send(new ProducerRecord<>("pay", v));   // 带 pid=7, seq=4 → 4 == lastSeq+1 连续 → 追加', '// ack 丢失触发重试、重发同一批 (7,4)：seq ≤ 窗口 → 判重复，不回写只回 ack —— 不会扣两次款', '// 事务：transactional.id 向事务协调器注册（__transaction_state 分区的 leader 兼任）', 'producer.initTransactions();', 'producer.beginTransaction();', 'producer.send(new ProducerRecord<>("order", v));   // 写 P0：未拍板，read_committed 不可见（LSO 把关）', 'producer.commitTransaction();   // 两阶段：PREPARE 拍板 → 各分区写 commit marker → LSO 越过，跨分区同时生效', '// 旧实例复活：同 transactional.id 的新实例注册使 epoch+1，旧 epoch 的 commit 抛 FencedInstanceEpochException'],
    theory: [['幂等去重', '(PID, seq) · 序列号窗口', '开启 enable.idempotence 后，每个批次携带 PID（producer id）与单调递增的序列号；Broker 为每个 (PID, 分区) 维护最近已确认的序列号窗口。校验两条：seq ≤ 窗口 → 重复——不重复追加、只回 ack（重试因此安全，at-least-once 的重复被压掉）；seq > 窗口+1 → 乱序——拒绝并抛 OutOfOrderSequenceException，producer 拉取窗口校准后重发。代价只有批次头的两个字段，换来单分区的不重不漏不乱。'], ['事务与隔离', '两阶段拍板 · marker · LSO', '跨分区原子靠事务：事务 producer 以 transactional.id 向 coordinator（__transaction_state 分区 leader）注册并拿到 PID。commit 走两阶段：coordinator 记录 PREPARE 拍板（不可反悔）→ 各分区 leader 写 commit/abort marker → 分区里消息按 marker 圈定归属。未拍板数据物理已追加但被 LSO（last stable offset）挡在闸内：read_committed 消费者只读 LSO 内，abort 段读到 marker 即跳过——提交跨分区同时可见，作废对消费者零感知（物理不删、逻辑回滚）。'], ['僵尸驱逐', 'epoch 代数 · fencing', '新实例以同一 transactional.id 注册（InitPid）时，coordinator 保留 PID 但把 epoch 代数 +1。旧实例网络分区恢复后仍持旧 epoch 提交请求 → 代数校验失败：抛 FencedInstanceEpochException，客户端只能自毁退出。epoch 与 ZK 分布式锁的 fencing token 同思想：用单调递增的代数标记「持有权已经换代」，复活者抢不回笔——双写被挡在协议层。']],
    goals: ['解释幂等去重的窗口机制：seq ≤ 窗口判重复不重写、seq 跳号拒绝 + 校准重发，重试从「风险」变成「常规操作」', '说清事务的原子与隔离：两阶段拍板（PREPARE → 各分区 marker）+ LSO 闸门，read_committed 下提交跨分区同时可见、abort 数据被 marker 圈禁过滤', '讲透 epoch fencing：新实例注册代数 +1、旧代数请求被驱逐（FencedInstanceEpochException），并理解精确一次 = 幂等 + 事务 + read_committed + 下游幂等四层'],
    challenge: { task: '三个场景各运行一次：① 发 pay-101(seq4) 成功后 ack 丢失触发重发——窗口判重复拦截；随后管道并发 s5/s6，观察 pay-103(seq6) 抢跑被跳号拒绝、pay-102 落盘后 producer 校准重发 ② 事务 T1 写 P0 订单-301 + P1 账务-301 未提交期间 LSO 不动（read_committed 不可见），commit 两阶段后双分区同时放行；对照事务 T2 写发券-302 后 abort——marker 圈禁、读取端跳过 ③ 实例 A 事务 T1 写到一半崩溃（ord-501 悬在 P0），实例 B 同 transactional.id 接管（epoch 1→2）后先作废 T1 残留、再重放并提交自己的 T2；网络分区恢复后僵尸 A 复活想 commit T1——epoch 落后被驱逐。期望：① 发送 5 · 落盘 3 · 生效 3 · 拦截 2（重复 1 + 跳号 1）② 发送 3 · 落盘 3 · 生效 2 · 拦截 1（T2 作废圈禁）③ 发送 3 · 落盘 3 · 生效 2 · 拦截 2（T1 残留作废 + 僵尸驱逐）——最终只有 B 的一版 501 生效。', hint: '看 producer token 的 pid/seq/epoch 与状态（黄=发送/重放、粉=拦截或崩溃、绿=完成）；分区 token 绿=生效、黄=待拍板、粉=圈禁；粉字拦截 token 显示 dup/gap/fence 原因；mono 行看 发送/落盘/生效/拦截 四计数；场景③ 关注 coordinator 的 epoch 代数变化。', success: '能解释 PID+seq 窗口为何让重试不再产生重复（判重不回写）；能说清事务的 PREPARE→marker→LSO 流程与 read_committed 的隔离效果；能讲出 epoch 如何驱逐复活的旧实例（FencedInstanceEpochException），并拼出精确一次的四层结构。', requirements: [{ id: 'idempotent', label: '① 幂等去重 · PID+序列号', when: { scenario: 'idempotent' } }, { id: 'transaction', label: '② 事务 · 跨分区原子', when: { scenario: 'transaction' } }, { id: 'fencing', label: '③ 僵尸驱逐 · epoch 代数', when: { scenario: 'fencing' } }] },
    quiz: [
      { prompt: '幂等 producer 发送 pay-101 成功但 ack 丢失，重发同一批（同 PID、同序列号），Broker 会怎么做？', choices: ['无法识别，再次追加——重试导致重复消息', '按序列号窗口判重复：不重复追加、直接回 ack，消息只落盘一次', '要求生产者换一个新的 PID 才能继续发送'], answer: 1, explanation: 'Broker 为 (PID, 分区) 记住已确认序列号：重发批的 seq 已在窗口内 → 判为重复，不再追加、只回 ack 让发送端以为成功——扣款只发生一次。这就是幂等把 at-least-once 的重试重复压掉的原理。' },
      { prompt: 'Kafka 事务提交时，消息何时对 read_committed 消费者可见？', choices: ['begin 后立即可见：事务消息与普通消息无差别', '数据落盘即可见：物理追加成功就代表提交成功', '两阶段完成后才可见：coordinator 记 PREPARE 拍板 → 各分区写 commit marker → LSO 越过，未拍板数据一直被 LSO 挡着'], answer: 2, explanation: '事务数据物理追加后仍处于未提交段，LSO 不放行：read_committed 消费者只能读到 LSO 以内的已拍板数据。commit 两阶段（PREPARE → 各分区 commit marker）完成后 LSO 越过，跨分区消息才同时可见——abort 段则被 marker 圈禁、读取端跳过。' },
      { prompt: '实例 A 崩溃后，新实例 B 以同一 transactional.id 注册并提交了事务；随后网络分区恢复、僵尸 A 复活想继续提交旧事务，会发生什么？', choices: ['正常提交，两条相同业务数据并存，靠消费者去重', 'coordinator 发现 A 的 epoch 落后于当前代数 → 拒绝并抛 FencedInstanceEpochException，A 只能退出——复活者抢不回笔', 'B 会让出事务所有权，把提交权交还给先注册的 A'], answer: 1, explanation: 'B 注册时 coordinator 把 epoch 从 1 递增到 2；A 的旧请求带 epoch=1、代数落后 → 被 fencing 拒绝。旧实例唯一的下场是收到 FencedInstanceEpochException 自毁退出——网络分区复活的旧 Leader 无法再提交，双写被挡在协议层。' },
    ],
    boundary: '单 producer、双分区、数据即时到达的教学模型；未模拟真实的分批发送与序列号按批次（base seq/num records）推进、Broker 端序列号窗口的具体实现与 OutOfOrderSequenceException 后的连接重置细节、__transaction_state 分区与 coordinator 故障转移、transaction.timeout.ms 对 pending 事务的独立超时回滚、事务与消费 offset 提交的原子集成（consume-transform-produce）、read_uncommitted 消费路径、abort 段跨控制批次边界的读取端实现、Kafka 的 max.in.flight/retries 与幂等的联动约束、下游写库的幂等配合；LSO/序列号与事件节奏为教学示意。',
    source: 'https://kafka.apache.org/documentation/#semantics',
  },
  {
    id: 'es-write', group: '数据与缓存', title: 'ES 写入路径 · 近实时与段合并', short: 'ES 写入路径', icon: 'Save', tag: '搜索引擎', number: '26',
    summary: 'ES 的写入是一条「缓冲 + 日志」流水线：文档先落内存 buffer 与 translog，确认写入后对搜索不可见；refresh（默认 1s）把 buffer 快照成内存段才可搜——这就是近实时。段只增不改：更新与删除都是打 tombstone 标记，空间要等后台 merge 把段合并时才真正释放；崩溃恢复则靠 translog 回放，durability 决定 ack 的含金量。',
    defaults: { scenario: 'nrt' },
    fields: [{ key: 'scenario', label: '实验场景', type: 'select', options: [['nrt', '① 近实时 · 写入与可搜'], ['crash', '② 崩溃恢复 · translog 兜底'], ['merge', '③ 段合并 · 空间释放']] }],
    metrics: [['docs', '确认写入', '笔'], ['refreshs', 'refresh', '次'], ['merges', '段合并', '次'], ['replayed', '日志回放', '笔']],
    nodes: [['client', '客户端', '写入 · 搜索', 'Send', 'blue'], ['buffer', '内存缓冲', 'indexing buffer · 待 refresh', 'MemoryStick', 'green'], ['translog', '预写日志', 'fsync · 崩溃兜底', 'FileCheck2', 'yellow'], ['segs', '内存段', 'refresh 生成 · 可搜索', 'Layers', 'pink'], ['disk', '磁盘段', 'flush · 已落盘', 'Database', 'blue'], ['search', '搜索端', '跨段归并查询', 'Search', 'green']],
    edges: [['client', 'buffer', '写入缓冲'], ['client', 'translog', 'fsync 日志'], ['buffer', 'segs', 'refresh 成段'], ['translog', 'segs', '崩溃回放'], ['segs', 'disk', 'flush 落盘'], ['segs', 'search', '内存段可搜'], ['disk', 'search', '磁盘段可搜']],
    code: ['// 写入：先进内存 buffer + translog（预写日志），durability 决定 ack 语义', 'PUT orders/_doc/w1 { "title": "订单-101" }   // request：ack 前 translog fsync → 已确认就不会丢', 'GET orders/_search?q=title:订单   // refresh 前 → 0 命中：buffer 中的数据不可搜', 'PUT orders/_refresh              // 手动刷新：buffer 快照成内存段，段即刻可搜（默认 refresh_interval=1s）', 'PUT orders/_settings { "index": { "translog.durability": "async" } }  // async：每 5s 批量 fsync，崩溃最多丢一个批窗口', '// 崩溃恢复：commit point + 磁盘段 + translog 回放（request 模式已 fsync 的日志一笔不丢）', 'PUT orders/_doc/w2 { ... }        // 更新：新版本写新段，旧版本在旧段打删除标记（tombstone）', 'DELETE orders/_doc/w3              // 删除：段内打 tombstone，搜索即过滤，空间待段合并释放', 'POST orders/_forcemerge?max_num_segments=1   // 合并小段并真正丢弃 tombstone 文档（后台 merge 自动进行）'],
    theory: [
      ['缓冲与近实时', 'buffer + refresh · 段', '写入先落两处：内存 indexing buffer（暂存）与 translog（预写日志，durability=request 时 ack 前先 fsync）。buffer 中的文档对搜索不可见——能不能搜取决于「段」，不取决于 buffer。refresh（默认 1s）把 buffer 快照变成内存段（位于 OS page cache）并清空 buffer，段即刻可搜：这就是近实时，写入确认与可搜之间隔一次 refresh。refresh 不落盘：内存段可搜但崩溃即失，数据安全靠 translog 而不是段。'],
      ['崩溃恢复', 'translog · fsync · durability', '段文件要 flush（commit）才 fsync 落盘并清空 translog。崩溃恢复三件套：commit point（记录已落盘段）+ 磁盘段 + translog 回放——把已 fsync 的日志逐条重放、重建可搜状态。durability 决定 ack 语义：request = 每笔请求 fsync 一次，ack 即磁盘、崩溃零丢失；async = 每 sync_interval（默认 5s）批量 fsync 一次，崩溃最多丢一个批窗口内已 ack 的尾巴——吞吐与丢失窗口的取舍。'],
      ['段与合并', '只增不改 · tombstone · merge', '段是倒排索引的最小文件单位，一旦生成就只读、永不就地修改。更新 = 新版本写进新段 + 给旧版本打删除标记；删除 = 直接打删除标记（tombstone）：搜索端立即过滤，但字节还占在段里。小段越积越多，查询要归并的段越多——后台 merge 线程把多个小段归并为大段，只有合并时才真正丢弃 tombstone 文档、释放空间。段只增不改、合并是唯一的「删除执行者」，这是理解 ES 空间回收与查询性能的关键。'],
    ],
    goals: ['写出「确认写入 → refresh 可搜」的近实时链路：buffer + translog 双写、refresh 成段即清 buffer、默认 1 秒内可见，并解释为何 buffer 不可搜而段可搜', '说清崩溃恢复的兜底机制：commit point + 磁盘段 + translog 回放，durability=request 零丢失、async 丢批窗口尾巴（ack 语义的差异）', '解释段生命周期：更新与删除都只打 tombstone、空间在 merge 时才释放、段数增长如何拖慢查询'],
    challenge: { task: '三个场景各运行一次：① 依次写 w1/w2/w3 后立即搜索（buffer 不可搜 0 命中）→ refresh #1 生成 seg-A 命中 3 → 再写 w4 搜索仍只见 w1-3 → refresh #2 生成 seg-B ② durability=request 写 w1-3 并 refresh 一次后，把 translog 切 async 再写 w4/w5（ack 即回但未 fsync），随后实例崩溃重启 ③ 连写 w1-4 每笔立即 refresh 攒 4 个小段 → 搜索跨 4 段 → merge #1 归并 3 段 → 更新 w2→w2′ 并删除 w3（tombstone）→ merge #2 收成单段。期望：① 确认写入 4 · refresh 2 · 合并 0 · 回放 0 ② 确认写入 5 · refresh 1 · 合并 0 · 回放 3（w1-3 找回、async 尾巴 w4/w5 丢失）③ 确认写入 5 · refresh 5 · 合并 2 · 回放 0（最终 1 段仅 w1/w2′/w4，tombstone 空间被释放）。', hint: '看条带 token：buf=黄待 refresh（搜索不可见）、log 绿 ✓=已 fsync 而黄=未 fsync、段 token 黄=内存可搜未落盘、绿=磁盘已落盘；✗ 前缀 = tombstone 或丢失；粉字 flash 显示 miss/崩溃/丢失/删除，黄绿 flash 显示 refresh/回放/合并。三个场景的 刷新/合并/回放 计数是核心对比。', success: '能画出 buffer → refresh → 内存段 → flush 磁盘段的写入流水线并解释「近实时」为什么是 1s 量级；能说清 durability=request 与 async 在崩溃时的差异（ack 语义）；能解释删除与更新的空间为什么必须等段合并才释放。', requirements: [{ id: 'nrt', label: '① 近实时 · 写后 1s 可搜', when: { scenario: 'nrt' } }, { id: 'crash', label: '② 崩溃恢复 · translog 回放', when: { scenario: 'crash' } }, { id: 'merge', label: '③ 段合并 · tombstone 释放', when: { scenario: 'merge' } }] },
    quiz: [
      { prompt: '向 ES 写入一条文档并收到 ack 后，它默认多久能被搜索到？', choices: ['写入确认后立即能搜：ack 与可搜同步', '约 1 秒后：下一次 refresh 把 buffer 快照成内存段才进倒排（refresh_interval 默认 1s）', '必须等 fsync 落盘到磁盘段才能搜'], answer: 1, explanation: '写入 = buffer + translog，buffer 对搜索不可见；refresh（默认 1s）把 buffer 生成内存段（OS cache 中）才可搜——「近实时」指的就是这段默认 ≤1s 的可见延迟。可搜与落盘无关：内存段可搜，落盘要等 flush。' },
      { prompt: 'translog 的 durability 分别设为 request 与 async 时，实例崩溃的差异是？', choices: ['request：每笔请求 ack 前 fsync，崩溃零丢失；async：周期批量 fsync，崩溃会丢一个批窗口内已 ack 的数据', 'request 反而更危险：频繁 fsync 会损坏日志', '两者一样：崩溃都靠段文件恢复，与 translog 无关'], answer: 0, explanation: 'durability 决定 ack 的含金量：request 模式 ack 前日志已 fsync，崩溃可从 translog 回放、一笔不丢；async 模式每 sync_interval（默认 5s）批量 fsync，崩溃时窗口内已 ack 但未 fsync 的数据随内存消失——拿吞吐换丢失窗口。' },
      { prompt: '删除一条文档后，它的磁盘空间何时真正释放？', choices: ['删除请求执行时立即释放', '下一次 refresh 时释放', '包含它的段被 merge 合并时才真正丢弃 tombstone、释放空间'], answer: 2, explanation: '删除 = 在段里打 tombstone 删除标记：搜索端立即过滤，但字节仍占着段。段只增不改，唯一的重写时机是后台 merge——合并时 tombstone 文档才被真正丢弃，空间此时才释放。所以大量更新删除后段不收缩，要靠 merge（或 forcemerge）收空间。' },
    ],
    boundary: '单主分片、单文档粒度写入的教学模型；未模拟 Lucene 段文件与倒排内部结构、refresh 的 CPU 成本、tiered merge 的分层阈值与并发策略、translog 的滚动与大小上限、flush/commit 的触发条件、durability=async 的精确批窗口与副本同步的写多数派、段内删除对评分与查询开销的精确影响、force_merge 在只读索引上的限制、bulk 批量请求与多副本场景；buffer/translog/段状态与事件节奏为教学示意。',
    source: 'https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-translog.html',
  },
];
export const groups = ['Java 核心', 'JVM 专题', 'Redis 专题', '数据与缓存', '消息中间件', '分布式协调'];
export const getLab = id => labs.find(lab => lab.id === id) || labs.find(lab => lab.id === 'redis');
