const quiz = (prompt, choices, answer, explanation) => ({ prompt, choices, answer, explanation });
const lesson = config => ({ group: 'JVM 专题', module: 'JVM', milestone: 'foundation', ...config });

export const jvmLabs = [
  lesson({
    id: 'jvm-bytecode', title: 'Class 文件与字节码执行', short: '01 · 字节码执行', icon: 'CodeXml', tag: '执行引擎', number: 'J01', phase: '字节码与类加载',
    summary: '跟随 add 方法的 iload、iadd 与 ireturn，观察局部变量表和操作数栈。',
    defaults: { left: 7, right: 5 },
    fields: [{ key: 'left', label: '参数 a', min: -10, max: 20, unit: '' }, { key: 'right', label: '参数 b', min: -10, max: 20, unit: '' }],
    metrics: [['pc', '程序计数', ''], ['stackDepth', '栈深度', ''], ['localVariables', '局部变量', ''], ['result', '返回结果', '']],
    nodes: [['classfile', 'Class 文件', 'method bytecode', 'FileCheck2', 'blue'], ['locals', '局部变量表', 'slot 0 / slot 1', 'Table2', 'green'], ['stack', '操作数栈', 'operand stack', 'Layers', 'yellow'], ['return', '方法返回', 'ireturn', 'CornerDownLeft', 'pink']],
    edges: [['classfile', 'locals', '读取指令'], ['locals', 'stack', 'load / store'], ['stack', 'return', 'return value']],
    code: [
      '// JVM 字节码演示：add 方法的 iload → iadd → ireturn 指令流，并用 ASM 打印真实 Class 文件指令',
      '// 运行：javac -cp "lib/*" BytecodeDemo.java && java -cp "build;lib/*" BytecodeDemo   （JDK 17）',
      '// 依赖：org.ow2.asm:asm:9.7 / org.ow2.asm:asm-util:9.7（读取并反汇编 Class 文件）',
      'import java.io.IOException;',
      'import java.io.InputStream;',
      'import java.io.PrintWriter;',
      'import java.nio.charset.StandardCharsets;',
      'import org.objectweb.asm.ClassReader;',
      'import org.objectweb.asm.util.TraceClassVisitor;',
      '',
      'public class BytecodeDemo {',
      '',
      '    /** 演示方法：编译后的字节码为 iload_0 → iload_1 → iadd → ireturn。 */',
      '    private static int add(int a, int b) {',
      '        // iload_0：把局部变量槽 0 的 a 压入操作数栈',
      '        // iload_1：把局部变量槽 1 的 b 压入操作数栈',
      '        // iadd：弹出栈顶两个 int，把和压回栈顶',
      '        return a + b; // ireturn：返回栈顶整数并结束当前栈帧',
      '    }',
      '',
      '    /** 用 ASM 读取本类 Class 文件，逐条打印真实字节码指令（等价 javap -c -p）。 */',
      '    private static void printBytecode() throws IOException {',
      '        try (InputStream classBytes = BytecodeDemo.class.getResourceAsStream("BytecodeDemo.class")) {',
      '            if (classBytes == null) {',
      '                System.out.println("未找到 BytecodeDemo.class，请先 javac 编译再运行。");',
      '                return;',
      '            }',
      '            PrintWriter writer = new PrintWriter(System.out, true, StandardCharsets.UTF_8);',
      '            new ClassReader(classBytes).accept(new TraceClassVisitor(writer), 0);',
      '            writer.flush();',
      '        }',
      '    }',
      '',
      '    public static void main(String[] args) throws IOException {',
      '        System.out.printf("add(7, 5)   = %d%n", add(7, 5));',
      '        System.out.printf("add(-3, 8)  = %d%n", add(-3, 8));',
      '        System.out.println("--- 真实 Class 文件字节码（main 与 add 的指令流）---");',
      '        printBytecode();',
      '    }',
      '}',
    ],
    theory: [['栈帧', '每次方法调用创建一个栈帧', '局部变量表、操作数栈和返回信息属于当前调用。'], ['基于栈执行', 'iload → iadd → ireturn', '指令通过压栈和出栈传递中间值，而不是直接命名 CPU 寄存器。'], ['类型化指令', 'iadd 只处理 int 类值', 'long、float、double 等类型使用不同指令族。']],
    goals: ['读懂简单方法的局部变量槽位和操作数栈变化', '解释 iadd 为什么先弹出两个操作数', '区分 Java 源码、Class 字节码与机器码'],
    challenge: { task: '分别运行 7+5 与 -3+8，观察指令数量不变但栈中的操作数和返回值变化。', hint: '字节码描述操作，不把参数值写死在指令中。', success: '能逐条说出两个 iload、iadd 和 ireturn 对栈的影响。', requirements: [{ id: 'positive', label: 'a=7 · b=5', when: { left: 7, right: 5 } }, { id: 'mixed', label: 'a=-3 · b=8', when: { left: -3, right: 8 } }] },
    quiz: [quiz('iadd 执行时需要什么？', ['从操作数栈弹出两个 int，再压入结果', '直接修改 Class 文件', '创建两个新线程'], 0, 'iadd 从当前栈帧的操作数栈取得两个 int，并把和压回栈。'), quiz('字节码是否就是特定 CPU 的机器码？', ['是', '不是，JVM 解释或编译字节码', '只有 Windows 上是'], 1, 'Class 字节码是 JVM 指令，解释器和 JIT 再将其映射到具体机器执行。')],
    boundary: '只演示一个静态 int 加法方法，不模拟常量池解析、异常表、对象引用、宽类型槽位或 JIT 编译。',
    source: 'https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-2.html',
  }),
  lesson({
    id: 'jvm-classloading', title: '类加载与双亲委派', short: '02 · 类加载', icon: 'Network', tag: '类加载机制', number: 'J02', phase: '字节码与类加载',
    summary: '观察加载请求如何向父加载器委派，以及定义、链接和初始化的边界。',
    defaults: { target: 'java.lang.String', custom: true },
    fields: [{ key: 'target', label: '目标类', type: 'select', options: [['java.lang.String', 'java.lang.String'], ['com.example.OrderService', 'OrderService']] }, { key: 'custom', label: '经过自定义加载器', type: 'toggle' }],
    metrics: [['delegated', '委派次数', ''], ['defined', '已定义类', ''], ['verified', '已验证', ''], ['initialized', '已初始化', '']],
    nodes: [['request', '加载请求', 'loadClass()', 'Send', 'blue'], ['parent', '父级委派', 'Custom / Extension', 'Network', 'yellow'], ['bootstrap', 'Bootstrap', 'JDK core classes', 'Archive', 'green'], ['application', 'Application', 'application classes', 'Boxes', 'pink']],
    edges: [['request', 'parent', '向上委派'], ['parent', 'bootstrap', 'parent first'], ['bootstrap', 'application', '未找到时返回']],
    code: [
      '// 类加载与双亲委派演示：委派链日志、自定义加载器 defineClass、类身份与初始化时机',
      '// 运行：javac ClassLoadingDemo.java && java ClassLoadingDemo   （JDK 17，无第三方依赖）',
      'import java.io.ByteArrayOutputStream;',
      'import java.io.IOException;',
      'import java.io.InputStream;',
      'import java.lang.reflect.Constructor;',
      'import java.lang.reflect.Method;',
      '',
      'public class ClassLoadingDemo {',
      '',
      '    /** 仅用于演示的自定义加载器：记录委派过程，并自己定义 OrderService。 */',
      '    static final class TracingClassLoader extends ClassLoader {',
      '',
      '        TracingClassLoader() {',
      '            super(ClassLoadingDemo.class.getClassLoader());',
      '        }',
      '',
      '        @Override',
      '        protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {',
      '            System.out.printf("request  : Custom 接到加载请求 %s%n", name);',
      '            if (name.startsWith("java.")) {',
      '                Class<?> loaded = super.loadClass(name, resolve);',
      '                System.out.printf("delegated: %s 由 %s 定义%n", name, describe(loaded.getClassLoader()));',
      '                return loaded;',
      '            }',
      '            Class<?> defined = findLoadedClass(name);',
      '            if (defined == null && "OrderService".equals(name)) {',
      '                try {',
      '                    byte[] bytes = readClassBytes(name);',
      '                    defined = defineClass(name, bytes, 0, bytes.length);',
      '                } catch (IOException e) {',
      '                    throw new ClassNotFoundException(name, e);',
      '                }',
      '                System.out.printf("defined  : %s 由 Custom 定义%n", name);',
      '            }',
      '            if (defined == null) {',
      '                return super.loadClass(name, resolve);',
      '            }',
      '            if (resolve) {',
      '                resolveClass(defined);',
      '            }',
      '            return defined;',
      '        }',
      '',
      '        private byte[] readClassBytes(String name) throws IOException {',
      '            try (InputStream in = ClassLoadingDemo.class.getResourceAsStream(name + ".class")) {',
      '                if (in == null) {',
      '                    throw new IOException("找不到类的字节：" + name);',
      '                }',
      '                ByteArrayOutputStream out = new ByteArrayOutputStream();',
      '                byte[] buffer = new byte[4096];',
      '                for (int read = in.read(buffer); read != -1; read = in.read(buffer)) {',
      '                    out.write(buffer, 0, read);',
      '                }',
      '                return out.toByteArray();',
      '            }',
      '        }',
      '    }',
      '',
      '    private static String describe(ClassLoader loader) {',
      '        return loader == null ? "Bootstrap（ClassLoader 为 null）" : loader.getClass().getSimpleName();',
      '    }',
      '',
      '    public static void main(String[] args) throws Exception {',
      '        TracingClassLoader custom = new TracingClassLoader();',
      '',
      '        System.out.println("--- 场景 1：加载 JDK 核心类 java.lang.String（父加载器优先）---");',
      '        Class<?> stringType = custom.loadClass("java.lang.String");',
      '        System.out.printf("结果：String 的加载器 = %s；自定义加载器没有重复定义核心类%n",',
      '                describe(stringType.getClassLoader()));',
      '',
      '        System.out.println("--- 场景 2：加载应用类 OrderService（由自定义加载器定义）---");',
      '        Class<?> lazyType = Class.forName("OrderService", false, custom);',
      '        System.out.println("链接：验证字节码 → 准备静态字段默认值（<clinit> 尚未执行）");',
      '        Class<?> eagerType = Class.forName("OrderService", true, custom);',
      '        Constructor<?> constructor = eagerType.getDeclaredConstructor();',
      '        constructor.setAccessible(true);',
      '        Object service = constructor.newInstance();',
      '        Method describe = eagerType.getDeclaredMethod("describe");',
      '        describe.setAccessible(true);',
      '        describe.invoke(service);',
      '',
      '        Class<?> appLoaderType = Class.forName("OrderService", false, ClassLoadingDemo.class.getClassLoader());',
      '        System.out.printf("类身份：同名类由不同加载器定义即不同类型 → Custom 版 == Application 版？%b%n",',
      '                lazyType == appLoaderType);',
      '        System.out.printf("类身份：两次经 Custom 加载复用同一个 Class 对象？%b%n", lazyType == eagerType);',
      '    }',
      '}',
      '',
      '/** 演示类：由自定义加载器从字节定义，<clinit> 在首次主动使用时执行。 */',
      'class OrderService {',
      '',
      '    static {',
      '        System.out.println("init     : OrderService <clinit> 执行（首次主动使用触发）");',
      '    }',
      '',
      '    /** 由自定义加载器定义的那一份实例方法。 */',
      '    void describe() {',
      '        System.out.printf("instance : OrderService 实例方法被调用，类由 %s 定义%n",',
      '                getClass().getClassLoader().getClass().getSimpleName());',
      '    }',
      '}',
    ],
    theory: [['类身份', '类名 + 定义它的 ClassLoader', '同名字节码由不同加载器定义，JVM 中仍可能是不同类型。'], ['双亲委派', '先请求父加载器', '核心类优先由受信任的加载器定义，减少重复并保护基础类型身份。'], ['初始化时机', '加载不等于初始化', '首次主动使用通常触发 <clinit>，仅获得 Class 对象不一定初始化。']],
    goals: ['区分加载、链接与初始化', '解释父加载器优先查找的方向', '理解 Bootstrap 返回 null 并不表示没有加载器'],
    challenge: { task: '分别加载 java.lang.String 和 OrderService，比较最终定义类的加载器。', hint: '请求会向上走，但定义者取决于哪个加载器找到类。', success: '能解释为什么自定义加载器不应重新定义 java.lang.String。', requirements: [{ id: 'jdk', label: 'String · 自定义加载器开启', when: { target: 'java.lang.String', custom: true } }, { id: 'app', label: 'OrderService · 自定义加载器开启', when: { target: 'com.example.OrderService', custom: true } }] },
    quiz: [quiz('双亲委派的查找方向通常是什么？', ['先父后子', '先子后父且不可改变', '随机选择'], 0, 'loadClass 通常先委派父加载器，父级找不到才由当前加载器尝试。'), quiz('ClassLoader 为 null 的 JDK 核心类通常由谁加载？', ['没有被加载', 'Bootstrap ClassLoader', '业务线程'], 1, 'Java API 用 null 表示 Bootstrap ClassLoader。')],
    boundary: '采用 JDK 8 常见的 Bootstrap、Extension、Application 命名；现代 JDK 使用 Platform ClassLoader。未模拟模块系统、并行加载和自定义破坏委派。',
    source: 'https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-5.html',
  }),
  lesson({
    id: 'jvm-memory', title: 'JVM 运行时数据区域', short: '03 · 运行时内存区', icon: 'MemoryStick', tag: '内存结构', number: 'J03', phase: '内存与对象',
    summary: '同时改变线程、递归深度、对象和类数量，区分线程私有区域与共享区域。',
    defaults: { threads: 2, depth: 4, objects: 6, classes: 3 },
    fields: [{ key: 'threads', label: '线程数量', min: 1, max: 5, unit: '个' }, { key: 'depth', label: '调用深度', min: 1, max: 8, unit: '层' }, { key: 'objects', label: '堆对象', min: 1, max: 16, unit: '个' }, { key: 'classes', label: '加载类数', min: 1, max: 10, unit: '个' }],
    metrics: [['threads', '线程数', ''], ['stackFrames', '栈帧数', ''], ['heapObjects', '堆对象', ''], ['loadedClasses', '类元数据', '']],
    nodes: [['threads', 'Java 线程', 'thread-private state', 'Workflow', 'blue'], ['stacks', 'PC 与 Java 栈', 'frames per thread', 'Layers', 'green'], ['heap', 'Java 堆', 'shared objects', 'Boxes', 'yellow'], ['metadata', '方法区实现', 'class metadata', 'Archive', 'pink']],
    edges: [['threads', 'stacks', '每线程一份'], ['stacks', 'heap', '引用共享对象'], ['heap', 'metadata', '对象属于类']],
    code: [
      '// JVM 运行时数据区域演示：线程私有（PC / Java 栈）与线程共享（堆 / 方法区）的可观测差异',
      '// 运行：javac RuntimeAreasDemo.java && java RuntimeAreasDemo [线程数] [深度] [对象数] [类数]',
      'import java.lang.management.ClassLoadingMXBean;',
      'import java.lang.management.ManagementFactory;',
      'import java.lang.management.MemoryMXBean;',
      'import java.util.ArrayList;',
      'import java.util.List;',
      '',
      'public class RuntimeAreasDemo {',
      '',
      '    private static final int DEFAULT_THREADS = 2;',
      '    private static final int DEFAULT_DEPTH = 4;',
      '    private static final int DEFAULT_OBJECTS = 6;',
      '    private static final int DEFAULT_CLASSES = 3;',
      '    private static final int OBJECT_UNIT_BYTES = 1024;',
      '    /** 静态引用让对象保持可达：验证“仍被引用的堆对象不会随栈帧退出而消失”。 */',
      '    private static final List<byte[]> RETAINED = new ArrayList<>();',
      '    /** 刻意选择尚未被主流程加载的类：加载后已加载类计数会增长。 */',
      '    private static final String[] CLASS_POOL = {',
      '            "java.util.concurrent.atomic.AtomicLong",',
      '            "java.util.zip.Deflater",',
      '            "java.time.format.DateTimeFormatter",',
      '            "java.security.MessageDigest",',
      '    };',
      '',
      '    /** 线程私有：每层递归调用形成一个 Java 栈帧，返回值即该线程实际使用的栈帧数。 */',
      '    private static int descend(int depth) {',
      '        if (depth <= 1) {',
      '            return 1;',
      '        }',
      '        return 1 + descend(depth - 1);',
      '    }',
      '',
      '    /** 线程共享：对象实例分配在堆上，与创建它的线程无关。 */',
      '    private static void allocateObjects(int count, int unitBytes) {',
      '        for (int i = 0; i < count; i++) {',
      '            RETAINED.add(new byte[unitBytes]);',
      '        }',
      '    }',
      '',
      '    /** 方法区语义：类的元数据（含运行时常量池）随加载进入元空间实现。 */',
      '    private static void loadClasses(int count) throws ClassNotFoundException {',
      '        for (int i = 0; i < count; i++) {',
      '            Class.forName(CLASS_POOL[i % CLASS_POOL.length]);',
      '        }',
      '    }',
      '',
      '    public static void main(String[] args) throws Exception {',
      '        int threads = args.length > 0 ? Integer.parseInt(args[0]) : DEFAULT_THREADS;',
      '        int depth = args.length > 1 ? Integer.parseInt(args[1]) : DEFAULT_DEPTH;',
      '        int objects = args.length > 2 ? Integer.parseInt(args[2]) : DEFAULT_OBJECTS;',
      '        int classes = args.length > 3 ? Integer.parseInt(args[3]) : DEFAULT_CLASSES;',
      '',
      '        MemoryMXBean memoryBean = ManagementFactory.getMemoryMXBean();',
      '        ClassLoadingMXBean classBean = ManagementFactory.getClassLoadingMXBean();',
      '',
      '        Thread[] workers = new Thread[threads];',
      '        int[] frameCounts = new int[threads];',
      '        for (int i = 0; i < threads; i++) {',
      '            int index = i;',
      '            workers[i] = new Thread(() -> frameCounts[index] = descend(depth), "worker-" + i);',
      '        }',
      '        for (Thread worker : workers) {',
      '            worker.start();',
      '        }',
      '        for (Thread worker : workers) {',
      '            worker.join();',
      '        }',
      '        int totalFrames = 0;',
      '        for (int count : frameCounts) {',
      '            totalFrames += count;',
      '        }',
      '        System.out.printf("线程：%d 个线程各自拥有独立 PC 与 Java 栈（活动线程含 JVM 管理线程：%d）%n",',
      '                threads, Thread.activeCount());',
      '',
      '        System.gc();',
      '        // HotSpot 在 GC 时刷新 used 计数：先取快照再对比，读数才有意义',
      '        long heapBefore = memoryBean.getHeapMemoryUsage().getUsed();',
      '        allocateObjects(objects, OBJECT_UNIT_BYTES);',
      '        System.gc();',
      '        long heapAfter = memoryBean.getHeapMemoryUsage().getUsed();',
      '        System.out.printf("堆：%d 个对象（每个 %d 字节，共 %d KB）保持可达；堆使用 %d → %d 字节%n",',
      '                objects, OBJECT_UNIT_BYTES, objects * OBJECT_UNIT_BYTES / 1024, heapBefore, heapAfter);',
      '',
      '        int classesBefore = classBean.getLoadedClassCount();',
      '        loadClasses(classes);',
      '        System.out.printf("方法区：加载 %d 个目标类后，已加载类计数 %d → %d（元数据进入方法区实现）%n",',
      '                classes, classesBefore, classBean.getLoadedClassCount());',
      '',
      '        System.out.printf("栈帧：每线程递归 %d 层 = %d 个栈帧，已随线程退出销毁%n", depth, totalFrames);',
      '        System.out.println("结论：栈帧随线程退出而销毁，堆对象由所有线程共享且保持可达——StackOverflowError 与 OutOfMemoryError 因此来自不同区域。");',
      '    }',
      '}',
    ],
    theory: [['线程私有', 'PC、Java 虚拟机栈、本地方法栈', '增加线程会增加独立栈空间，不会复制整个 Java 堆。'], ['线程共享', 'Heap 与方法区', '对象实例主要位于堆；类结构、运行时常量池等属于方法区语义。'], ['异常映射', 'StackOverflowError / OutOfMemoryError', '递归过深与堆对象过多是不同故障路径，排查指标也不同。']],
    goals: ['区分线程私有与线程共享区域', '解释局部引用和引用对象可能位于不同区域', '把典型内存异常映射到可能区域'],
    challenge: { task: '保持对象和类数量不变，把线程数从 1 调到 3，比较栈帧与堆对象数量。', hint: '线程数乘以调用深度决定教学模型中的栈帧数。', success: '能说明为什么增加线程主要增加栈等线程私有开销。', requirements: [{ id: 'one', label: '1 线程 · 深度 4', when: { threads: 1, depth: 4, objects: 6, classes: 3 } }, { id: 'three', label: '3 线程 · 深度 4', when: { threads: 3, depth: 4, objects: 6, classes: 3 } }] },
    quiz: [quiz('Java 堆通常由谁共享？', ['同一 JVM 内的线程', '只有 main 线程', '每个方法独占'], 0, '同一 JVM 的线程共享堆，而每个线程拥有自己的 PC 和栈。'), quiz('局部变量引用和它指向的对象一定在同一区域吗？', ['一定', '不一定，引用可在栈帧，对象通常在堆', '对象只能在 Class 文件'], 1, '变量槽位和对象实例是不同概念。')],
    boundary: '展示 JVMS 逻辑区域，不等于具体 HotSpot 内存布局。未展示直接内存、代码缓存、压缩类空间、TLAB 和栈上分配。',
    source: 'https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-2.html#jvms-2.5',
  }),
  lesson({
    id: 'jvm-allocation', title: '对象分配与 TLAB', short: '04 · 对象分配', icon: 'Boxes', tag: '对象生命周期', number: 'J04', phase: '内存与对象',
    summary: '比较线程本地分配缓冲区与共享堆分配路径，观察 TLAB 补充成本。',
    defaults: { objects: 12, size: 8, tlab: true, tlabCapacity: 32 },
    fields: [{ key: 'objects', label: '对象数量', min: 2, max: 20, unit: '个' }, { key: 'size', label: '对象单位大小', min: 4, max: 32, step: 4, unit: '' }, { key: 'tlab', label: '启用 TLAB', type: 'toggle' }, { key: 'tlabCapacity', label: 'TLAB 容量', min: 16, max: 64, step: 16, unit: '' }],
    metrics: [['allocated', '已分配', ''], ['bytes', '分配单位', ''], ['fastPath', '本地快路径', ''], ['slowPath', '共享/补充路径', '']],
    nodes: [['new', 'new 指令', 'allocation request', 'CodeXml', 'blue'], ['tlab', '线程 TLAB', 'bump pointer', 'Cpu', 'green'], ['heap', '共享堆路径', 'synchronized reserve', 'MemoryStick', 'yellow'], ['result', '对象初始化', 'header + fields', 'Box', 'pink']],
    edges: [['new', 'tlab', '优先尝试'], ['tlab', 'heap', '空间不足'], ['heap', 'result', '分配完成']],
    code: [
      '// 对象分配与 TLAB 演示：JOL 实测对象布局 → 线程本地 bump-the-pointer → 逐线程分配量核算',
      '// 运行：javac -cp "lib/*" TlabAllocationDemo.java',
      '//       java -Djdk.attach.allowAttachSelf=true -cp "build;lib/*" TlabAllocationDemo',
      '// 依赖：org.openjdk.jol:jol-core:0.17（读取真实对象头与实例大小）',
      '// TLAB 明细：java -Xlog:gc+tlab=trace TlabAllocationDemo（观察 refill 与 waste 行）',
      'import com.sun.management.HotSpotDiagnosticMXBean;',
      'import com.sun.management.ThreadMXBean;',
      'import java.lang.management.ManagementFactory;',
      'import java.util.ArrayList;',
      'import java.util.Collections;',
      'import java.util.List;',
      'import org.openjdk.jol.info.ClassLayout;',
      '',
      'public class TlabAllocationDemo {',
      '',
      '    private static final int DEFAULT_OBJECTS = 12;',
      '    private static final int WORKER_THREADS = 3;',
      '    private static final int LARGE_OBJECT_BYTES = 256 * 1024;',
      '    /** 保留引用让对象保持存活：否则 JIT 可能直接消除分配，记账结果失真；预分配容量避免扩容数组混入逐线程核算。 */',
      '    private static final List<Sample> RETAINED = Collections.synchronizedList(new ArrayList<>(256));',
      '    private static final List<byte[]> RETAINED_LARGE = new ArrayList<>();',
      '',
      '    static final class Sample {',
      '        private final long value;',
      '',
      '        Sample(long value) {',
      '            this.value = value;',
      '        }',
      '    }',
      '',
      '    /** 线程本地分配：优先在自己的 TLAB 内移动指针（bump-the-pointer），用尽时申请新的 TLAB（refill）。 */',
      '    private static long allocateBatch(int count) {',
      '        ThreadMXBean threadBean = (ThreadMXBean) ManagementFactory.getThreadMXBean();',
      '        long threadId = Thread.currentThread().getId();',
      '        long before = threadBean.getThreadAllocatedBytes(threadId);',
      '        for (int i = 0; i < count; i++) {',
      '            RETAINED.add(new Sample(i));',
      '        }',
      '        return threadBean.getThreadAllocatedBytes(threadId) - before;',
      '    }',
      '',
      '    public static void main(String[] args) throws Exception {',
      '        int objectCount = args.length > 0 ? Integer.parseInt(args[0]) : DEFAULT_OBJECTS;',
      '        ThreadMXBean threadBean = (ThreadMXBean) ManagementFactory.getThreadMXBean();',
      '',
      '        HotSpotDiagnosticMXBean diagBean = ManagementFactory.getPlatformMXBean(HotSpotDiagnosticMXBean.class);',
      '        System.out.printf("TLAB 开关：UseTLAB=%s，TLABSize=%s（0 表示由 JVM 自适应决定）%n",',
      '                diagBean.getVMOption("UseTLAB").getValue(),',
      '                diagBean.getVMOption("TLABSize").getValue());',
      '',
      '        ClassLayout layout = ClassLayout.parseInstance(new Sample(0));',
      '        System.out.printf("分配计划：%d 个 Sample 对象；单对象真实大小 %d 字节（对象头 + 字段 + 对齐）%n",',
      '                objectCount, layout.instanceSize());',
      '        System.out.println(layout.toPrintable());',
      '',
      '        Thread[] workers = new Thread[WORKER_THREADS];',
      '        long[] allocatedPerThread = new long[WORKER_THREADS];',
      '        for (int i = 0; i < WORKER_THREADS; i++) {',
      '            int index = i;',
      '            int share = objectCount / WORKER_THREADS + (i < objectCount % WORKER_THREADS ? 1 : 0);',
      '            workers[i] = new Thread(() -> allocatedPerThread[index] = allocateBatch(share), "alloc-" + i);',
      '        }',
      '        for (Thread worker : workers) {',
      '            worker.start();',
      '        }',
      '        for (Thread worker : workers) {',
      '            worker.join();',
      '        }',
      '',
      '        long mainThreadId = Thread.currentThread().getId();',
      '        long largeBefore = threadBean.getThreadAllocatedBytes(mainThreadId);',
      '        RETAINED_LARGE.add(new byte[LARGE_OBJECT_BYTES]);',
      '        long largeAllocated = threadBean.getThreadAllocatedBytes(mainThreadId) - largeBefore;',
      '',
      '        long fastPathBytes = 0;',
      '        for (int i = 0; i < WORKER_THREADS; i++) {',
      '            fastPathBytes += allocatedPerThread[i];',
      '            System.out.printf("线程 alloc-%d：TLAB 内分配核算 %d 字节（约 %d 个对象）%n",',
      '                    i, allocatedPerThread[i], allocatedPerThread[i] / layout.instanceSize());',
      '        }',
      '        System.out.printf("分配核算：快路径 %d 个对象共 %d 字节；共享/补充路径 1 次（%d 字节大对象绕过 TLAB）；"',
      '                        + "TLAB 自身补充用 -Xlog:gc+tlab=trace 观察%n",',
      '                objectCount, fastPathBytes, largeAllocated);',
      '        System.out.println("结论：小对象先在每线程私有的 TLAB 内移动指针分配，互不争抢；大对象与 TLAB 补充仍走共享堆路径。");',
      '    }',
      '}',
    ],
    theory: [['TLAB', 'Thread Local Allocation Buffer', '线程在预留区域内移动指针分配，减少共享堆顶竞争。'], ['慢路径', 'TLAB refill / shared allocation', 'TLAB 用尽、大对象或策略限制时进入更重的路径。'], ['分配不等于构造', '内存预留 → 零值 → 对象头 → <init>', '看到 new 源码不能把所有步骤简化为只调用构造器。']],
    goals: ['解释 TLAB 为什么能降低分配竞争', '区分快速分配、TLAB 补充和共享路径', '理解对象内存分配先于构造方法执行'],
    challenge: { task: '保持 12 个、大小 8，分别开启和关闭 TLAB，对比快路径与共享/补充路径。', hint: 'TLAB 也需要周期性从共享堆申请新的区域。', success: '能解释启用 TLAB 后慢路径没有完全变为零。', requirements: [{ id: 'tlab', label: '12 对象 · TLAB 开启', when: { objects: 12, size: 8, tlab: true, tlabCapacity: 32 } }, { id: 'shared', label: '12 对象 · TLAB 关闭', when: { objects: 12, size: 8, tlab: false, tlabCapacity: 32 } }] },
    quiz: [quiz('TLAB 的主要目的是什么？', ['减少线程间分配指针竞争', '让对象永远不被 GC', '存放 Class 文件'], 0, '线程在自己的预留缓冲区内快速移动指针。'), quiz('启用 TLAB 后是否完全没有共享路径？', ['是', '否，补充 TLAB 等仍需协调', '仅 String 没有'], 1, 'TLAB 本身来自共享堆，补充和特殊分配仍可能进入慢路径。')],
    boundary: '使用固定单位大小和简单容量计算，不表示真实对象字节布局、对齐、逃逸分析、标量替换或大对象阈值。',
    source: 'https://docs.oracle.com/en/java/javase/21/gctuning/garbage-collector-implementation.html',
  }),
  lesson({
    id: 'jvm-roots', title: 'GC Roots 与可达性分析', short: '05 · 可达性分析', icon: 'Network', tag: '垃圾判定', number: 'J05', phase: '垃圾回收',
    summary: '从 GC Roots 标记对象图，并验证相互引用但不可达的循环仍可回收。',
    defaults: { objects: 8, roots: 2, cycle: true },
    fields: [{ key: 'objects', label: '堆对象数量', min: 4, max: 14, unit: '个' }, { key: 'roots', label: 'Root 数量', min: 1, max: 5, unit: '个' }, { key: 'cycle', label: '构造不可达循环', type: 'toggle' }],
    metrics: [['objects', '对象总数', ''], ['roots', 'GC Roots', ''], ['reachable', '可达对象', ''], ['reclaimed', '可回收对象', '']],
    nodes: [['objects', '堆对象图', 'references', 'Network', 'blue'], ['roots', 'GC Roots', 'stack / static / JNI', 'LocateFixed', 'green'], ['mark', '可达性标记', 'transitive closure', 'Workflow', 'yellow'], ['sweep', '回收候选', 'unreachable', 'Recycle', 'pink']],
    edges: [['roots', 'mark', '从根遍历'], ['objects', 'mark', '引用边'], ['mark', 'sweep', '未标记']],
    code: [
      '// GC Roots 与可达性分析演示：栈 / 静态根 → 传递可达链 → 不可达循环仍可回收',
      '// 运行：javac GcRootsDemo.java && java GcRootsDemo   （JDK 17，无第三方依赖）',
      'import java.lang.ref.Reference;',
      'import java.lang.ref.ReferenceQueue;',
      'import java.lang.ref.WeakReference;',
      'import java.util.ArrayList;',
      'import java.util.List;',
      '',
      'public class GcRootsDemo {',
      '',
      '    /** 静态 Root：类静态字段引用的对象始终可达。 */',
      '    private static final List<Node> STATIC_ROOT = new ArrayList<>();',
      '    /** 弱引用不影响可达性判定，只用来观测对象是否被回收。 */',
      '    private static final ReferenceQueue<Node> QUEUE = new ReferenceQueue<>();',
      '',
      '    static final class Node {',
      '        private final String name;',
      '        private Node peer;',
      '',
      '        Node(String name) {',
      '            this.name = name;',
      '        }',
      '',
      '        void link(Node other) {',
      '            this.peer = other;',
      '        }',
      '    }',
      '',
      '    private static String state(WeakReference<Node> reference) {',
      '        return reference.get() != null ? "存活" : "已回收";',
      '    }',
      '',
      '    public static void main(String[] args) throws InterruptedException {',
      '        Node rootA = new Node("A");',
      '        Node rootB = new Node("B");',
      '        Node child = new Node("child");',
      '        Node leaf = new Node("leaf");',
      '        Node cycleLeft = new Node("X");',
      '        Node cycleRight = new Node("Y");',
      '        rootA.link(child);',
      '        child.link(leaf);',
      '        cycleLeft.link(cycleRight);',
      '        cycleRight.link(cycleLeft);',
      '        STATIC_ROOT.add(rootB);',
      '',
      '        WeakReference<Node> weakChild = new WeakReference<>(child, QUEUE);',
      '        WeakReference<Node> weakLeaf = new WeakReference<>(leaf, QUEUE);',
      '        WeakReference<Node> weakCycle = new WeakReference<>(cycleLeft, QUEUE);',
      '        child = null;',
      '        leaf = null;',
      '        cycleLeft = null;',
      '        cycleRight = null;',
      '',
      '        System.out.println("对象图：6 个对象 · 2 个 GC Root（局部变量 A、静态引用 B）");',
      '        System.out.println("标记：Root A → child → leaf 沿引用链传递可达；X ↔ Y 互相引用但无 Root 路径");',
      '        System.gc();',
      '        Reference.reachabilityFence(rootA);',
      '        Reference<?> reclaimed = QUEUE.remove(5000);',
      '        System.out.printf("结果：weakChild=%s · weakLeaf=%s（传递可达，保留）%n", state(weakChild), state(weakLeaf));',
      '        System.out.printf("结果：weakCycle=%s（回收通知：%s）%n", state(weakCycle), reclaimed != null ? "已收到" : "未收到");',
      '        System.out.println("结论：决定存活的是从 GC Roots 的传递可达性，而不是对象之间是否互相引用。");',
      '    }',
      '}',
    ],
    theory: [['GC Roots', '遍历的起点集合', '活动线程栈中的引用、静态引用、JNI 引用等可成为根。'], ['传递可达', 'Root → A → B', '对象不必直接被 Root 引用，只要沿引用链可到达就存活。'], ['循环不等于存活', 'A ↔ B 且无 Root 路径', '可达性分析不会因对象互相引用就永久保留它们。']],
    goals: ['列举常见 GC Roots 来源', '手工判断对象图中的传递可达对象', '解释不可达循环为什么可以回收'],
    challenge: { task: '保持 8 个对象和 2 个 Root，分别开启和关闭不可达循环，观察可回收数不因循环增加而减少。', hint: '决定存活的是从根可达，不是引用计数。', success: '能判断一个环是否有从 Roots 进入的路径。', requirements: [{ id: 'cycle', label: '8 对象 · 2 Roots · 有循环', when: { objects: 8, roots: 2, cycle: true } }, { id: 'no-cycle', label: '8 对象 · 2 Roots · 无循环', when: { objects: 8, roots: 2, cycle: false } }] },
    quiz: [quiz('两个对象互相引用但都不可从 GC Roots 到达，会怎样？', ['永远存活', '仍可被回收', '自动变成静态变量'], 1, '可达性分析不依赖简单引用计数。'), quiz('对象 B 被可达对象 A 引用时，B 是否可达？', ['是，沿引用链可达', '否，必须直接是 Root', '仅数组中可达'], 0, '可达性是传递关系。')],
    boundary: '每个 Root 固定连接一个直接对象和一个子对象，仅用于解释算法。未模拟软/弱/虚引用、finalization、并发标记和引用处理阶段。',
    source: 'https://docs.oracle.com/en/java/javase/21/gctuning/other-considerations.html',
  }),
  lesson({
    id: 'jvm', title: '分代回收与对象晋升', short: '06 · 分代回收', icon: 'Recycle', tag: '垃圾回收', number: 'J06', phase: '垃圾回收',
    summary: '跟随对象从 Eden 分配到 Young GC、回收和存活对象晋升。',
    defaults: { eden: 4, allocations: 12, survival: 50 },
    fields: [{ key: 'eden', label: 'Eden 容量', min: 2, max: 8, unit: '对象' }, { key: 'allocations', label: '分配对象数', min: 1, max: 20, unit: '个' }, { key: 'survival', label: '每轮存活比例', min: 0, max: 100, step: 25, unit: '%' }],
    metrics: [['allocated', '已分配', ''], ['collections', 'Young GC', '次'], ['reclaimed', '已回收', ''], ['promoted', '已晋升', '']],
    nodes: [['allocation', '对象分配', 'new Object()', 'Box', 'blue'], ['eden', 'Eden 区', 'Young generation', 'MemoryStick', 'green'], ['gc', 'Young GC', 'reachability', 'Recycle', 'yellow'], ['old', '老年代', 'Old generation', 'Archive', 'pink']],
    edges: [['allocation', 'eden', '分配'], ['eden', 'gc', 'Eden 满'], ['gc', 'old', '存活晋升']],
    code: [
      '// 分代回收演示：Eden 分配 → Young GC 与老年代增长（GC MXBean 实测，非模拟数值）',
      '// 运行：javac GenerationalGC.java',
      '//       java -Xms64m -Xmx64m -Xmn16m -XX:+UseSerialGC GenerationalGC [总分配数] [保留间隔]',
      'import java.lang.management.GarbageCollectorMXBean;',
      'import java.lang.management.ManagementFactory;',
      'import java.lang.management.MemoryPoolMXBean;',
      'import java.util.ArrayList;',
      'import java.util.List;',
      '',
      'public class GenerationalGC {',
      '',
      '    private static final int OBJECT_BYTES = 512 * 1024;',
      '    private static final int DEFAULT_ALLOCATIONS = 96;',
      '    /** 每 8 个对象保留 1 个：模拟低存活率，其余在 Young GC 中回收。 */',
      '    private static final int DEFAULT_PROMOTION_INTERVAL = 8;',
      '    private static final List<byte[]> SURVIVORS = new ArrayList<>();',
      '',
      '    private static MemoryPoolMXBean findPool(String... keywords) {',
      '        for (MemoryPoolMXBean pool : ManagementFactory.getMemoryPoolMXBeans()) {',
      '            String name = pool.getName().toLowerCase();',
      '            for (String keyword : keywords) {',
      '                if (name.contains(keyword)) {',
      '                    return pool;',
      '                }',
      '            }',
      '        }',
      '        throw new IllegalStateException("未找到内存池：" + String.join("/", keywords));',
      '    }',
      '',
      '    private static long countYoungCollections() {',
      '        long total = 0;',
      '        for (GarbageCollectorMXBean bean : ManagementFactory.getGarbageCollectorMXBeans()) {',
      '            String name = bean.getName();',
      '            if (name.contains("Young") || name.contains("Copy") || name.contains("Scavenge")) {',
      '                total += bean.getCollectionCount();',
      '            }',
      '        }',
      '        return total;',
      '    }',
      '',
      '    public static void main(String[] args) {',
      '        int totalAllocations = args.length > 0 ? Integer.parseInt(args[0]) : DEFAULT_ALLOCATIONS;',
      '        int promotionInterval = args.length > 1 ? Integer.parseInt(args[1]) : DEFAULT_PROMOTION_INTERVAL;',
      '',
      '        MemoryPoolMXBean edenPool = findPool("eden");',
      '        MemoryPoolMXBean oldPool = findPool("old", "tenured");',
      '        long youngBefore = countYoungCollections();',
      '        long oldUsedBefore = oldPool.getUsage().getUsed();',
      '',
      '        for (int i = 1; i <= totalAllocations; i++) {',
      '            byte[] obj = new byte[OBJECT_BYTES];',
      '            if (i % promotionInterval == 0) {',
      '                SURVIVORS.add(obj);',
      '            }',
      '        }',
      '',
      '        long youngGcCount = countYoungCollections() - youngBefore;',
      '        long oldUsedAfter = oldPool.getUsage().getUsed();',
      '        System.out.printf("分配：%d 个对象 × %d KB；Eden 当前使用 %d KB（容量 %d KB）%n",',
      '                totalAllocations, OBJECT_BYTES / 1024,',
      '                edenPool.getUsage().getUsed() / 1024, edenPool.getUsage().getMax() / 1024);',
      '        System.out.printf("Young GC：期间发生 %d 次；老年代使用 %d → %d KB（存活对象经复制后晋升 %d 个）%n",',
      '                youngGcCount, oldUsedBefore / 1024, oldUsedAfter / 1024,',
      '                Math.max(0, oldUsedAfter - oldUsedBefore) / OBJECT_BYTES);',
      '        for (GarbageCollectorMXBean bean : ManagementFactory.getGarbageCollectorMXBeans()) {',
      '            System.out.printf("收集器 %s：累计次数 %d · 累计耗时 %d ms%n",',
      '                    bean.getName(), bean.getCollectionCount(), bean.getCollectionTime());',
      '        }',
      '        System.out.println("结论：对象先在 Eden 分配，Young GC 批量回收朝生夕灭对象，多次存活者晋升老年代——分代假设由此成立。");',
      '    }',
      '}',
    ],
    theory: [['弱分代假说', '多数对象朝生夕灭', '年轻代集中处理短命对象，以较低成本回收大量空间。'], ['Young GC', '存活对象复制或转移', '具体算法和区域取决于收集器，不能把所有 JVM 都理解成同一种布局。'], ['晋升条件', '年龄、空间担保与收集器策略', '存活一次不必然直接进入老年代。']],
    goals: ['解释分代设计针对的对象生命周期假设', '区分分配、存活、回收和晋升', '知道 Young GC 不等同于 Full GC'],
    challenge: { task: '固定 Eden 4、分配 12，比较 25% 和 75% 存活率对回收与晋升的影响。', hint: '存活率越高，年轻代每次能释放的空间越少。', success: '能解释高存活率为何可能增加复制和老年代压力。', requirements: [{ id: 'low', label: '存活率 25%', when: { eden: 4, allocations: 12, survival: 25 } }, { id: 'high', label: '存活率 75%', when: { eden: 4, allocations: 12, survival: 75 } }] },
    quiz: [quiz('Young GC 是否只回收“没有年龄”的对象？', ['是', '不是，它判断年轻代对象可达性并处理存活者', '只回收 Class'], 1, '年龄影响晋升，但垃圾判定仍基于可达性。'), quiz('存活率提高通常会带来什么？', ['每次释放更多空间', '复制/晋升压力可能增加', '保证不发生 GC'], 1, '更多对象存活意味着更少回收空间和更多存活处理成本。')],
    boundary: '存活比例由参数直接给定，存活对象直接晋升。省略 Survivor、年龄阈值、空间担保、老年代容量和具体收集器差异。',
    source: 'https://docs.oracle.com/en/java/javase/21/gctuning/garbage-collector-implementation.html',
  }),
  lesson({
    id: 'jvm-collectors', title: 'Serial、Parallel 与 G1 收集器对比', short: '07 · 收集器对比', icon: 'Recycle', tag: '收集器选择', number: 'J07', phase: '性能与诊断', milestone: 'diagnostics',
    summary: '在相同年轻代负载下，对比单线程停顿、并行停顿和区域化并发工作的差异。',
    defaults: { collector: 'serial', youngMb: 128, livePercent: 50, gcThreads: 4 },
    fields: [{ key: 'collector', label: '收集器模型', type: 'select', options: [['serial', 'Serial'], ['parallel', 'Parallel'], ['g1', 'G1']] }, { key: 'youngMb', label: '年轻代负载', min: 64, max: 256, step: 32, unit: 'MB' }, { key: 'livePercent', label: '对象存活率', min: 25, max: 75, step: 25, unit: '%' }, { key: 'gcThreads', label: '可用 GC 线程', min: 1, max: 8, unit: '个' }],
    metrics: [['pauseWork', '停顿工作量', '单位'], ['workers', '停顿工作线程', ''], ['concurrentWork', '并发工作量', '单位'], ['reclaimedMb', '本轮回收', 'MB']],
    nodes: [['workload', '年轻代负载', 'allocation pressure', 'Boxes', 'blue'], ['mark', '存活对象识别', 'roots and marking', 'Network', 'green'], ['pause', '应用停顿阶段', 'stop-the-world work', 'Pause', 'yellow'], ['workers', 'GC 工作线程', 'serial or parallel', 'Cpu', 'pink'], ['reclaim', '空间回收', 'reclaim / evacuate', 'Recycle', 'green']],
    edges: [['workload', 'mark', '触发收集'], ['mark', 'pause', '进入停顿'], ['pause', 'workers', '执行工作'], ['workers', 'reclaim', '释放空间']],
    code: [
      '// Serial / Parallel / G1 收集器对比演示：同一负载下实测收集器名称、GC 次数与停顿时间',
      '// 运行：javac CollectorCompareDemo.java',
      '//       java -XX:+UseSerialGC   CollectorCompareDemo [年轻代 MB] [存活率%]',
      '//       java -XX:+UseParallelGC CollectorCompareDemo [年轻代 MB] [存活率%]',
      '//       java -XX:+UseG1GC       CollectorCompareDemo [年轻代 MB] [存活率%]（JDK 17 默认 G1）',
      'import com.sun.management.HotSpotDiagnosticMXBean;',
      'import java.lang.management.GarbageCollectorMXBean;',
      'import java.lang.management.ManagementFactory;',
      'import java.util.ArrayList;',
      'import java.util.List;',
      '',
      'public class CollectorCompareDemo {',
      '',
      '    private static final int CHUNK_BYTES = 1024 * 1024;',
      '    private static final int DEFAULT_YOUNG_MB = 128;',
      '    private static final int DEFAULT_LIVE_PERCENT = 50;',
      '    private static final List<byte[]> RETAINED = new ArrayList<>();',
      '',
      '    private static long totalCollectionCount(List<GarbageCollectorMXBean> collectors) {',
      '        long total = 0;',
      '        for (GarbageCollectorMXBean bean : collectors) {',
      '            total += bean.getCollectionCount();',
      '        }',
      '        return total;',
      '    }',
      '',
      '    private static long totalCollectionTimeMillis(List<GarbageCollectorMXBean> collectors) {',
      '        long total = 0;',
      '        for (GarbageCollectorMXBean bean : collectors) {',
      '            total += bean.getCollectionTime();',
      '        }',
      '        return total;',
      '    }',
      '',
      '    public static void main(String[] args) {',
      '        int youngMb = args.length > 0 ? Integer.parseInt(args[0]) : DEFAULT_YOUNG_MB;',
      '        int livePercent = args.length > 1 ? Integer.parseInt(args[1]) : DEFAULT_LIVE_PERCENT;',
      '        int retainInterval = Math.max(1, 100 / livePercent);',
      '',
      '        List<GarbageCollectorMXBean> collectors = ManagementFactory.getGarbageCollectorMXBeans();',
      '        StringBuilder names = new StringBuilder();',
      '        for (GarbageCollectorMXBean bean : collectors) {',
      '            if (names.length() > 0) {',
      '                names.append(" + ");',
      '            }',
      '            names.append(bean.getName());',
      '        }',
      '        HotSpotDiagnosticMXBean diagBean = ManagementFactory.getPlatformMXBean(HotSpotDiagnosticMXBean.class);',
      '        System.out.printf("当前生效收集器：%s（由 -XX:+UseSerialGC / UseParallelGC / UseG1GC 启动参数决定）%n", names);',
      '        System.out.printf("可用 CPU：%d · ParallelGCThreads=%s（0 表示自适应）· 年轻代负载 %d MB · 存活率 %d%%%n",',
      '                Runtime.getRuntime().availableProcessors(),',
      '                diagBean.getVMOption("ParallelGCThreads").getValue(), youngMb, livePercent);',
      '',
      '        long countBefore = totalCollectionCount(collectors);',
      '        long pauseMillisBefore = totalCollectionTimeMillis(collectors);',
      '',
      '        for (int i = 0; i < youngMb; i++) {',
      '            byte[] chunk = new byte[CHUNK_BYTES];',
      '            if (i % retainInterval == 0) {',
      '                RETAINED.add(chunk);',
      '            }',
      '        }',
      '',
      '        long gcCount = totalCollectionCount(collectors) - countBefore;',
      '        long pauseMillis = totalCollectionTimeMillis(collectors) - pauseMillisBefore;',
      '        long reclaimedMb = youngMb - RETAINED.size();',
      '        System.out.printf("回收结果：分配 %d MB · 保留 %d MB · 回收 %d MB · GC 次数 +%d · GC 总时间 +%d ms%n",',
      '                youngMb, RETAINED.size(), reclaimedMb, gcCount, pauseMillis);',
      '        System.out.println("结论：三次运行的回收量相同，差异在停顿由单线程还是多线程承担、以及多少工作可并发——换启动参数重跑本程序即可复现。");',
      '    }',
      '}',
    ],
    theory: [['Serial', '单个 GC 工作线程执行停顿阶段', '实现简单、额外协调少，适合小堆或资源受限场景，但停顿工作不能由多个 GC 线程分担。'], ['Parallel', '多个 GC 工作线程换取吞吐量', '仍会 Stop-The-World，重点是缩短批量回收所需墙钟时间并提高吞吐，而不是消除停顿。'], ['G1', 'Region 化布局 + 并发标记 + 可预测停顿目标', '按收益选择 Region 并把部分工作并发化；停顿目标是调度目标，不是硬实时承诺。']],
    goals: ['区分单线程停顿、并行停顿与并发阶段', '解释吞吐优先和停顿目标不是同一个优化方向', '根据堆规模、延迟目标和 CPU 预算提出收集器选择证据'],
    challenge: { task: '固定年轻代负载 128 MB、存活率 50%、GC 线程 4，依次运行 Serial、Parallel 和 G1，比较工作分布。', hint: '三次回收量相同；差异在停顿工作由多少线程承担，以及多少工作可进入并发阶段。', success: '能说明模型工作单位不是毫秒，也不能据此宣称某收集器在生产环境一定更快。', requirements: [{ id: 'serial', label: 'Serial · 128 MB · 存活率 50%', when: { collector: 'serial', youngMb: 128, livePercent: 50, gcThreads: 4 } }, { id: 'parallel', label: 'Parallel · 128 MB · 存活率 50%', when: { collector: 'parallel', youngMb: 128, livePercent: 50, gcThreads: 4 } }, { id: 'g1', label: 'G1 · 128 MB · 存活率 50%', when: { collector: 'g1', youngMb: 128, livePercent: 50, gcThreads: 4 } }] },
    quiz: [quiz('Parallel GC 使用多个工作线程主要为了什么？', ['提高吞吐并缩短批量停顿工作', '彻底消除 Stop-The-World', '让对象不再进入老年代'], 0, 'Parallel GC 仍存在 Stop-The-World，多个线程主要用于并行完成回收工作。'), quiz('G1 的 MaxGCPauseMillis 表示什么？', ['每次停顿绝不会超过该值', '收集器用于选择回收集合的软目标', '应用线程的超时时间'], 1, '停顿目标用于启发式调度，不是硬实时上限。')],
    boundary: '使用 MB 与抽象工作单位构造确定性对照，不模拟真实对象图、Region 记忆集、混合回收、并发失败、操作系统调度或实际毫秒停顿，不能作为收集器性能基准。',
    source: 'https://docs.oracle.com/en/java/javase/21/gctuning/available-collectors.html',
  }),
  lesson({
    id: 'jvm-jit', title: 'JIT 热点编译与内联', short: '08 · JIT 热点编译', icon: 'Cpu', tag: '执行引擎', number: 'J08', phase: '性能与诊断', milestone: 'diagnostics',
    summary: '让同一方法反复执行越过阈值，观察解释执行 → C1 快速编译 → C2 深度优化的分级过程；再演示内联如何消除调用点开销、逃逸分析如何把未逃逸对象替换成标量；最后用编译参数对比提前编译与保持解释的取舍。',
    defaults: { mode: 'tiered', calls: 600, threshold: 200, inline: true, escape: true },
    fields: [{ key: 'mode', label: '实验场景', type: 'select', options: [['tiered', '① 分级编译 · 阈值与热度'], ['inline', '② 内联与逃逸分析'], ['flags', '③ 编译参数 · 门槛对比']] }, { key: 'calls', label: '调用次数', min: 100, max: 1000, step: 100, unit: '次' }, { key: 'threshold', label: '编译阈值', min: 100, max: 1000, step: 100, unit: '次' }, { key: 'inline', label: '启用内联', type: 'toggle' }, { key: 'escape', label: '启用逃逸分析', type: 'toggle' }],
    metrics: [['interpreted', '解释执行', '次'], ['c1', 'C1 段执行', '次'], ['c2', 'C2 段执行', '次'], ['inlined', '内联调用点', ''], ['escapes', '标量替换', '个']],
    nodes: [['call', '方法调用', 'invocation counter', 'Send', 'blue'], ['interp', '解释执行', 'profile 采集', 'CodeXml', 'green'], ['c1', 'C1 编译', 'quick compile', 'Cpu', 'yellow'], ['c2', 'C2 深度编译', 'profile-guided', 'Cpu', 'pink'], ['inline', '内联展开', 'call-site elimination', 'Waypoints', 'yellow'], ['alloc', '标量替换', 'no heap object', 'Box', 'green']],
    edges: [['call', 'interp', '计数未达阈值'], ['interp', 'c1', '越过 C1 阈值'], ['c1', 'c2', '持续热点'], ['call', 'inline', 'native 入口'], ['inline', 'alloc', '对象未逃逸'], ['c2', 'inline', '深度优化']],
    code: [
      '// JIT 热点编译演示：调用计数触发编译的耗时趋势 + 内联/逃逸分析的分配核算（零分配 vs 堆分配）',
      '// 运行：javac JitCompileDemo.java && java JitCompileDemo [调用次数]',
      '// 编译日志：java -XX:+PrintCompilation JitCompileDemo（观察 hotMethod 等的真实编译行）',
      '// 内联日志：java -XX:+UnlockDiagnosticVMOptions -XX:+PrintInlining JitCompileDemo',
      'import com.sun.management.HotSpotDiagnosticMXBean;',
      'import com.sun.management.ThreadMXBean;',
      'import java.lang.management.CompilationMXBean;',
      'import java.lang.management.ManagementFactory;',
      'import java.util.ArrayList;',
      'import java.util.List;',
      '',
      'public class JitCompileDemo {',
      '',
      '    private static final int DEFAULT_CALLS = 600;',
      '    private static final int SAMPLE_ROUNDS = 100;',
      '    private static final int ESCAPE_CALLS = 10_000;',
      '    private static final int WARMUP_ROUNDS = 2;',
      '    /** 逃逸对象的存放处：对象一旦写入这里，就无法被标量替换。 */',
      '    private static final List<Order> ESCAPED = new ArrayList<>(64 * 1024);',
      '',
      '    static final class Order {',
      '        private final int id;',
      '        private final int quantity;',
      '',
      '        Order(int id, int quantity) {',
      '            this.id = id;',
      '            this.quantity = quantity;',
      '        }',
      '',
      '        int price() {',
      '            return id * quantity + 1;',
      '        }',
      '    }',
      '',
      '    /** 热点方法：足够短小，容易被 C1/C2 编译并内联。 */',
      '    private static int hotMethod(int value) {',
      '        return value * 31 + 7;',
      '    }',
      '',
      '    /** 未逃逸对象：只在方法内使用，C2 可标量替换，不产生堆分配。 */',
      '    private static int orderTotal(int id) {',
      '        Order order = new Order(id, id + 1);              // 未逃逸：C2 标量替换后为零堆分配',
      '        return order.price();',
      '    }',
      '',
      '    /** 逃逸对象：写入静态列表后被外部引用，只能堆分配。 */',
      '    private static int escapedTotal(int id) {',
      '        Order order = new Order(id, id + 1);              // 逃逸：写入静态列表，无法标量替换',
      '        int price = order.price();',
      '        ESCAPED.add(order);',
      '        return price;',
      '    }',
      '',
      '    public static void main(String[] args) {',
      '        int calls = args.length > 0 ? Integer.parseInt(args[0]) : DEFAULT_CALLS;',
      '        HotSpotDiagnosticMXBean diagBean = ManagementFactory.getPlatformMXBean(HotSpotDiagnosticMXBean.class);',
      '        CompilationMXBean compileBean = ManagementFactory.getCompilationMXBean();',
      '        ThreadMXBean threadBean = (ThreadMXBean) ManagementFactory.getThreadMXBean();',
      '        long threadId = Thread.currentThread().getId();',
      '',
      '        System.out.println("--- 阶段 ①：分级编译（解释 → C1 → C2），编译日志用 -XX:+PrintCompilation 运行 ---");',
      '        long sum = 0;',
      '        long interpretedNanos = 0;',
      '        for (int i = 1; i <= calls; i++) {',
      '            long start = System.nanoTime();',
      '            sum += hotMethod(i);                          // 解释执行 + profile 采样',
      '            if (i <= SAMPLE_ROUNDS) {',
      '                interpretedNanos += System.nanoTime() - start;',
      '            }',
      '        }',
      '        String compileThreshold = diagBean.getVMOption("CompileThreshold").getValue();',
      '        long compiledNanos = 0;',
      '        for (int i = 1; i <= calls; i++) {',
      '            long start = System.nanoTime();',
      '            sum += hotMethod(i);                          // 编译入口：C1 快速编译 / C2 深度优化代码',
      '            if (i <= SAMPLE_ROUNDS) {',
      '                compiledNanos += System.nanoTime() - start;',
      '            }',
      '        }',
      '        System.out.printf("结果：sum=%d；前 %d 次采样 %d ns → 编译后 %d ns（单次采样含计时开销，仅看趋势）%n",',
      '                sum, SAMPLE_ROUNDS, interpretedNanos, compiledNanos);',
      '        System.out.printf("CompileThreshold=%s（分级编译下门槛为 Tier3/Tier4 调用阈值）· CompilationMXBean 累计编译耗时 %d ms%n",',
      '                compileThreshold, compileBean.getTotalCompilationTime());',
      '',
      '        System.out.println("--- 阶段 ②：内联与逃逸分析（分配量由 ThreadMXBean 实测）---");',
      '        for (int round = 0; round < WARMUP_ROUNDS; round++) {',
      '            for (int i = 0; i < ESCAPE_CALLS; i++) {',
      '                orderTotal(i);',
      '                escapedTotal(i);',
      '            }',
      '        }',
      '        long beforeHot = threadBean.getThreadAllocatedBytes(threadId);',
      '        long nonEscapedSum = 0;',
      '        for (int i = 0; i < ESCAPE_CALLS; i++) {',
      '            nonEscapedSum += orderTotal(i);',
      '        }',
      '        long nonEscapedBytes = threadBean.getThreadAllocatedBytes(threadId) - beforeHot;',
      '        long beforeEscape = threadBean.getThreadAllocatedBytes(threadId);',
      '        long escapedSum = 0;',
      '        for (int i = 0; i < ESCAPE_CALLS; i++) {',
      '            escapedSum += escapedTotal(i);',
      '        }',
      '        long escapedBytes = threadBean.getThreadAllocatedBytes(threadId) - beforeEscape;',
      '        System.out.printf("未逃逸：%d 次调用合计 %d，分配 %d 字节 → 标量替换生效时接近 0%n",',
      '                ESCAPE_CALLS, nonEscapedSum, nonEscapedBytes);',
      '        System.out.printf("逃逸　：%d 次调用合计 %d，分配 %d 字节 ≈ 每次 %d 字节堆分配%n",',
      '                ESCAPE_CALLS, escapedSum, escapedBytes, escapedBytes / ESCAPE_CALLS);',
      '',
      '        System.out.println("--- 阶段 ③：编译参数（阈值决定编译时机）---");',
      '        System.out.println("提前编译对照：java -XX:-TieredCompilation -XX:CompileThreshold=100 JitCompileDemo");',
      '        System.out.println("观察编译过程：java -XX:+PrintCompilation JitCompileDemo（越过阈值的调用边界之后出现编译行）");',
      '        System.out.println("运行结束：解释与编译的分界由阈值与热度决定——内联与标量替换都发生在编译后的代码里。");',
      '    }',
      '}',
    ],
    theory: [['分层编译', '解释 → C1 → C2', '解释器先运行并收集 profile；越过 C1 阈值得到快速编译版本，热度更高再交给 C2 深度优化，代价与收益逐级增加。'], ['内联', '编译期展开调用点', '把短小高频方法的调用点直接展开为被调方代码，减少调用与栈帧开销；是否内联由方法大小、热度与调用场景决定。'], ['逃逸分析与标量替换', '对象未逃逸时的优化', '对象若只在方法内使用且不逃逸，C2 可以拆开字段直接放到寄存器或栈上，既消除堆分配，也常顺带消除锁。']],
    goals: ['区分解释执行、C1 快速编译与 C2 深度优化', '解释调用次数、编译阈值与分层策略的关系', '说明内联与逃逸分析只在画像成立时生效'],
    challenge: { task: '分别在调用 600 与 1000 次时观察 C1/C2 分段；再进入内联场景对比开关内联与逃逸分析；最后用编译参数场景对比默认门槛与调低门槛。', hint: '编译发生在越过阈值的下一次调用边界；逃逸分析只消除未逃逸对象的堆分配。', success: '能说明为什么调低编译阈值不一定让峰值更快。', requirements: [{ id: 't600', label: '分级 · 600 次', when: { mode: 'tiered', calls: 600 } }, { id: 't1000', label: '分级 · 1000 次', when: { mode: 'tiered', calls: 1000 } }, { id: 'inline', label: '内联 · 内联与逃逸开启', when: { mode: 'inline', inline: true, escape: true } }, { id: 'flags', label: '参数 · 阈值 200', when: { mode: 'flags', threshold: 200 } }] },
    quiz: [quiz('方法调用次数越过阈值后，HotSpot 通常先做什么？', ['先由 C1 快速编译，热度足够再交 C2', '直接进行 C2 深度优化', '永远保持解释执行'], 0, '分层编译先做低成本的 C1 编译，持续热点才触发 C2 深度优化。'), quiz('完全未逃逸出方法的对象，C2 可能如何处理？', ['标量替换，不产生堆分配', '强制晋升到老年代', '禁止对该方法内联'], 0, '未逃逸对象可以被拆分为标量放在寄存器或栈上，甚至完全不分配。')],
    boundary: '使用抽象调用计数与固定阈值演示分层模型，不读取 CompilationMXBean，不修改网关启动参数，不代表真实 C1/C2 代码质量、OSR、去优化与具体 JDK 版本差异。',
    source: 'https://docs.oracle.com/en/java/javase/21/vm/java-hotspot-virtual-machine-performance-enhancements.html',
  }),
];
