const quiz = (prompt, choices, answer, explanation) => ({ prompt, choices, answer, explanation });
const lesson = config => ({ group: 'JVM 专题', module: 'JVM', milestone: 'foundation', ...config });

export const jvmLabs = [
  lesson({
    id: 'jvm-bytecode', title: 'Class 文件与字节码执行', short: '01 · 字节码执行', icon: 'CodeXml', tag: '执行引擎', number: 'J01', phase: '字节码与类加载',
    summary: '跟随 add 方法的 iload、iadd 与 ireturn，观察局部变量表和操作数栈。',
    defaults: { left: 7, right: 5 },
    fields: [{ key: 'left', label: '参数 a', min: -10, max: 20, unit: '' }, { key: 'right', label: '参数 b', min: -10, max: 20, unit: '' }],
    metrics: [['pc', '程序计数', ''], ['stackDepth', '栈深度', ''], ['localVariables', '局部变量', ''], ['result', '返回结果', '']],
    nodes: [['classfile', 'Class 文件', 'method bytecode', 'FileCheck2', 'blue'], ['locals', '局部变量表', 'slot 0 / slot 1', 'Table2', 'green'], ['stack', '操作数栈', 'operand stack', 'Layers', 'yellow'], ['return', '方法返回', 'ireturn', 'CornerDownLeft', 'pink']],
    edges: [['classfile', 'locals', '读取指令'], ['locals', 'stack', 'load / store'], ['stack', 'return', 'return value']],
    code: ['static int add(int a, int b) {', '  // iload_0', '  // iload_1', '  // iadd', '  return a + b; // ireturn', '}'],
    theory: [['栈帧', '每次方法调用创建一个栈帧', '局部变量表、操作数栈和返回信息属于当前调用。'], ['基于栈执行', 'iload → iadd → ireturn', '指令通过压栈和出栈传递中间值，而不是直接命名 CPU 寄存器。'], ['类型化指令', 'iadd 只处理 int 类值', 'long、float、double 等类型使用不同指令族。']],
    goals: ['读懂简单方法的局部变量槽位和操作数栈变化', '解释 iadd 为什么先弹出两个操作数', '区分 Java 源码、Class 字节码与机器码'],
    challenge: { task: '分别运行 7+5 与 -3+8，观察指令数量不变但栈中的操作数和返回值变化。', hint: '字节码描述操作，不把参数值写死在指令中。', success: '能逐条说出两个 iload、iadd 和 ireturn 对栈的影响。', requirements: [{ id: 'positive', label: 'a=7 · b=5', when: { left: 7, right: 5 } }, { id: 'mixed', label: 'a=-3 · b=8', when: { left: -3, right: 8 } }] },
    quiz: [quiz('iadd 执行时需要什么？', ['从操作数栈弹出两个 int，再压入结果', '直接修改 Class 文件', '创建两个新线程'], 0, 'iadd 从当前栈帧的操作数栈取得两个 int，并把和压回栈。'), quiz('字节码是否就是特定 CPU 的机器码？', ['是', '不是，JVM 解释或编译字节码', '只有 Windows 上是'], 1, 'Class 字节码是 JVM 指令，解释器和 JIT 再将其映射到具体机器执行。')],
    boundary: '只演示一个静态 int 加法方法，不模拟常量池解析、异常表、对象引用、宽类型槽位或 JIT 编译。',
    source: 'https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-2.html',
  }),
  lesson({
    id: 'jvm-classloading', title: '类加载与双亲委派', short: '02 · 类加载', icon: 'Network', tag: '类加载机制', number: 'J02', phase: '字节码与类加载',
    summary: '观察加载请求如何向父加载器委派，以及定义、链接和初始化的边界。',
    defaults: { target: 'java.lang.String', custom: true },
    fields: [{ key: 'target', label: '目标类', type: 'select', options: [['java.lang.String', 'java.lang.String'], ['com.example.OrderService', 'OrderService']] }, { key: 'custom', label: '经过自定义加载器', type: 'toggle' }],
    metrics: [['delegated', '委派次数', ''], ['defined', '已定义类', ''], ['verified', '已验证', ''], ['initialized', '已初始化', '']],
    nodes: [['request', '加载请求', 'loadClass()', 'Send', 'blue'], ['parent', '父级委派', 'Custom / Extension', 'Network', 'yellow'], ['bootstrap', 'Bootstrap', 'JDK core classes', 'Archive', 'green'], ['application', 'Application', 'application classes', 'Boxes', 'pink']],
    edges: [['request', 'parent', '向上委派'], ['parent', 'bootstrap', 'parent first'], ['bootstrap', 'application', '未找到时返回']],
    code: ['Class<?> type = loader.loadClass(name);', '// loading: locate bytes and define Class', '// linking: verify, prepare, optionally resolve', '// initialization: execute <clinit> on active use'],
    theory: [['类身份', '类名 + 定义它的 ClassLoader', '同名字节码由不同加载器定义，JVM 中仍可能是不同类型。'], ['双亲委派', '先请求父加载器', '核心类优先由受信任的加载器定义，减少重复并保护基础类型身份。'], ['初始化时机', '加载不等于初始化', '首次主动使用通常触发 <clinit>，仅获得 Class 对象不一定初始化。']],
    goals: ['区分加载、链接与初始化', '解释父加载器优先查找的方向', '理解 Bootstrap 返回 null 并不表示没有加载器'],
    challenge: { task: '分别加载 java.lang.String 和 OrderService，比较最终定义类的加载器。', hint: '请求会向上走，但定义者取决于哪个加载器找到类。', success: '能解释为什么自定义加载器不应重新定义 java.lang.String。', requirements: [{ id: 'jdk', label: 'String · 自定义加载器开启', when: { target: 'java.lang.String', custom: true } }, { id: 'app', label: 'OrderService · 自定义加载器开启', when: { target: 'com.example.OrderService', custom: true } }] },
    quiz: [quiz('双亲委派的查找方向通常是什么？', ['先父后子', '先子后父且不可改变', '随机选择'], 0, 'loadClass 通常先委派父加载器，父级找不到才由当前加载器尝试。'), quiz('ClassLoader 为 null 的 JDK 核心类通常由谁加载？', ['没有被加载', 'Bootstrap ClassLoader', '业务线程'], 1, 'Java API 用 null 表示 Bootstrap ClassLoader。')],
    boundary: '采用 JDK 8 常见的 Bootstrap、Extension、Application 命名；现代 JDK 使用 Platform ClassLoader。未模拟模块系统、并行加载和自定义破坏委派。',
    source: 'https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-5.html',
  }),
  lesson({
    id: 'jvm-memory', title: 'JVM 运行时数据区域', short: '03 · 运行时内存区', icon: 'MemoryStick', tag: '内存结构', number: 'J03', phase: '内存与对象',
    summary: '同时改变线程、递归深度、对象和类数量，区分线程私有区域与共享区域。',
    defaults: { threads: 2, depth: 4, objects: 6, classes: 3 },
    fields: [{ key: 'threads', label: '线程数量', min: 1, max: 5, unit: '个' }, { key: 'depth', label: '调用深度', min: 1, max: 8, unit: '层' }, { key: 'objects', label: '堆对象', min: 1, max: 16, unit: '个' }, { key: 'classes', label: '加载类数', min: 1, max: 10, unit: '个' }],
    metrics: [['threads', '线程数', ''], ['stackFrames', '栈帧数', ''], ['heapObjects', '堆对象', ''], ['loadedClasses', '类元数据', '']],
    nodes: [['threads', 'Java 线程', 'thread-private state', 'Workflow', 'blue'], ['stacks', 'PC 与 Java 栈', 'frames per thread', 'Layers', 'green'], ['heap', 'Java 堆', 'shared objects', 'Boxes', 'yellow'], ['metadata', '方法区实现', 'class metadata', 'Archive', 'pink']],
    edges: [['threads', 'stacks', '每线程一份'], ['stacks', 'heap', '引用共享对象'], ['heap', 'metadata', '对象属于类']],
    code: ['void handle(Request request) {', '  Order order = new Order(); // heap', '  int retry = 0;           // current frame', '  service.process(order);  // another frame', '}'],
    theory: [['线程私有', 'PC、Java 虚拟机栈、本地方法栈', '增加线程会增加独立栈空间，不会复制整个 Java 堆。'], ['线程共享', 'Heap 与方法区', '对象实例主要位于堆；类结构、运行时常量池等属于方法区语义。'], ['异常映射', 'StackOverflowError / OutOfMemoryError', '递归过深与堆对象过多是不同故障路径，排查指标也不同。']],
    goals: ['区分线程私有与线程共享区域', '解释局部引用和引用对象可能位于不同区域', '把典型内存异常映射到可能区域'],
    challenge: { task: '保持对象和类数量不变，把线程数从 1 调到 3，比较栈帧与堆对象数量。', hint: '线程数乘以调用深度决定教学模型中的栈帧数。', success: '能说明为什么增加线程主要增加栈等线程私有开销。', requirements: [{ id: 'one', label: '1 线程 · 深度 4', when: { threads: 1, depth: 4, objects: 6, classes: 3 } }, { id: 'three', label: '3 线程 · 深度 4', when: { threads: 3, depth: 4, objects: 6, classes: 3 } }] },
    quiz: [quiz('Java 堆通常由谁共享？', ['同一 JVM 内的线程', '只有 main 线程', '每个方法独占'], 0, '同一 JVM 的线程共享堆，而每个线程拥有自己的 PC 和栈。'), quiz('局部变量引用和它指向的对象一定在同一区域吗？', ['一定', '不一定，引用可在栈帧，对象通常在堆', '对象只能在 Class 文件'], 1, '变量槽位和对象实例是不同概念。')],
    boundary: '展示 JVMS 逻辑区域，不等于具体 HotSpot 内存布局。未展示直接内存、代码缓存、压缩类空间、TLAB 和栈上分配。',
    source: 'https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-2.html#jvms-2.5',
  }),
  lesson({
    id: 'jvm-allocation', title: '对象分配与 TLAB', short: '04 · 对象分配', icon: 'Boxes', tag: '对象生命周期', number: 'J04', phase: '内存与对象',
    summary: '比较线程本地分配缓冲区与共享堆分配路径，观察 TLAB 补充成本。',
    defaults: { objects: 12, size: 8, tlab: true, tlabCapacity: 32 },
    fields: [{ key: 'objects', label: '对象数量', min: 2, max: 20, unit: '个' }, { key: 'size', label: '对象单位大小', min: 4, max: 32, step: 4, unit: '' }, { key: 'tlab', label: '启用 TLAB', type: 'toggle' }, { key: 'tlabCapacity', label: 'TLAB 容量', min: 16, max: 64, step: 16, unit: '' }],
    metrics: [['allocated', '已分配', ''], ['bytes', '分配单位', ''], ['fastPath', '本地快路径', ''], ['slowPath', '共享/补充路径', '']],
    nodes: [['new', 'new 指令', 'allocation request', 'CodeXml', 'blue'], ['tlab', '线程 TLAB', 'bump pointer', 'Cpu', 'green'], ['heap', '共享堆路径', 'synchronized reserve', 'MemoryStick', 'yellow'], ['result', '对象初始化', 'header + fields', 'Box', 'pink']],
    edges: [['new', 'tlab', '优先尝试'], ['tlab', 'heap', '空间不足'], ['heap', 'result', '分配完成']],
    code: ['Order order = new Order();', '// fast path: reserve bytes from current thread TLAB', '// refill or shared allocation when TLAB lacks space', '// initialize object header and fields', '// constructor then runs on the allocated object'],
    theory: [['TLAB', 'Thread Local Allocation Buffer', '线程在预留区域内移动指针分配，减少共享堆顶竞争。'], ['慢路径', 'TLAB refill / shared allocation', 'TLAB 用尽、大对象或策略限制时进入更重的路径。'], ['分配不等于构造', '内存预留 → 零值 → 对象头 → <init>', '看到 new 源码不能把所有步骤简化为只调用构造器。']],
    goals: ['解释 TLAB 为什么能降低分配竞争', '区分快速分配、TLAB 补充和共享路径', '理解对象内存分配先于构造方法执行'],
    challenge: { task: '保持 12 个、大小 8，分别开启和关闭 TLAB，对比快路径与共享/补充路径。', hint: 'TLAB 也需要周期性从共享堆申请新的区域。', success: '能解释启用 TLAB 后慢路径没有完全变为零。', requirements: [{ id: 'tlab', label: '12 对象 · TLAB 开启', when: { objects: 12, size: 8, tlab: true, tlabCapacity: 32 } }, { id: 'shared', label: '12 对象 · TLAB 关闭', when: { objects: 12, size: 8, tlab: false, tlabCapacity: 32 } }] },
    quiz: [quiz('TLAB 的主要目的是什么？', ['减少线程间分配指针竞争', '让对象永远不被 GC', '存放 Class 文件'], 0, '线程在自己的预留缓冲区内快速移动指针。'), quiz('启用 TLAB 后是否完全没有共享路径？', ['是', '否，补充 TLAB 等仍需协调', '仅 String 没有'], 1, 'TLAB 本身来自共享堆，补充和特殊分配仍可能进入慢路径。')],
    boundary: '使用固定单位大小和简单容量计算，不表示真实对象字节布局、对齐、逃逸分析、标量替换或大对象阈值。',
    source: 'https://docs.oracle.com/en/java/javase/21/gctuning/garbage-collector-implementation.html',
  }),
  lesson({
    id: 'jvm-roots', title: 'GC Roots 与可达性分析', short: '05 · 可达性分析', icon: 'Network', tag: '垃圾判定', number: 'J05', phase: '垃圾回收',
    summary: '从 GC Roots 标记对象图，并验证相互引用但不可达的循环仍可回收。',
    defaults: { objects: 8, roots: 2, cycle: true },
    fields: [{ key: 'objects', label: '堆对象数量', min: 4, max: 14, unit: '个' }, { key: 'roots', label: 'Root 数量', min: 1, max: 5, unit: '个' }, { key: 'cycle', label: '构造不可达循环', type: 'toggle' }],
    metrics: [['objects', '对象总数', ''], ['roots', 'GC Roots', ''], ['reachable', '可达对象', ''], ['reclaimed', '可回收对象', '']],
    nodes: [['objects', '堆对象图', 'references', 'Network', 'blue'], ['roots', 'GC Roots', 'stack / static / JNI', 'LocateFixed', 'green'], ['mark', '可达性标记', 'transitive closure', 'Workflow', 'yellow'], ['sweep', '回收候选', 'unreachable', 'Recycle', 'pink']],
    edges: [['roots', 'mark', '从根遍历'], ['objects', 'mark', '引用边'], ['mark', 'sweep', '未标记']],
    code: ['Object a = new Object();', 'Object b = new Object();', '// a and b can reference each other', 'a = null; b = null;', '// an unreachable cycle is still collectible'],
    theory: [['GC Roots', '遍历的起点集合', '活动线程栈中的引用、静态引用、JNI 引用等可成为根。'], ['传递可达', 'Root → A → B', '对象不必直接被 Root 引用，只要沿引用链可到达就存活。'], ['循环不等于存活', 'A ↔ B 且无 Root 路径', '可达性分析不会因对象互相引用就永久保留它们。']],
    goals: ['列举常见 GC Roots 来源', '手工判断对象图中的传递可达对象', '解释不可达循环为什么可以回收'],
    challenge: { task: '保持 8 个对象和 2 个 Root，分别开启和关闭不可达循环，观察可回收数不因循环增加而减少。', hint: '决定存活的是从根可达，不是引用计数。', success: '能判断一个环是否有从 Roots 进入的路径。', requirements: [{ id: 'cycle', label: '8 对象 · 2 Roots · 有循环', when: { objects: 8, roots: 2, cycle: true } }, { id: 'no-cycle', label: '8 对象 · 2 Roots · 无循环', when: { objects: 8, roots: 2, cycle: false } }] },
    quiz: [quiz('两个对象互相引用但都不可从 GC Roots 到达，会怎样？', ['永远存活', '仍可被回收', '自动变成静态变量'], 1, '可达性分析不依赖简单引用计数。'), quiz('对象 B 被可达对象 A 引用时，B 是否可达？', ['是，沿引用链可达', '否，必须直接是 Root', '仅数组中可达'], 0, '可达性是传递关系。')],
    boundary: '每个 Root 固定连接一个直接对象和一个子对象，仅用于解释算法。未模拟软/弱/虚引用、finalization、并发标记和引用处理阶段。',
    source: 'https://docs.oracle.com/en/java/javase/21/gctuning/other-considerations.html',
  }),
  lesson({
    id: 'jvm', title: '分代回收与对象晋升', short: '06 · 分代回收', icon: 'Recycle', tag: '垃圾回收', number: 'J06', phase: '垃圾回收',
    summary: '跟随对象从 Eden 分配到 Young GC、回收和存活对象晋升。',
    defaults: { eden: 4, allocations: 12, survival: 50 },
    fields: [{ key: 'eden', label: 'Eden 容量', min: 2, max: 8, unit: '对象' }, { key: 'allocations', label: '分配对象数', min: 1, max: 20, unit: '个' }, { key: 'survival', label: '每轮存活比例', min: 0, max: 100, step: 25, unit: '%' }],
    metrics: [['allocated', '已分配', ''], ['collections', 'Young GC', '次'], ['reclaimed', '已回收', ''], ['promoted', '已晋升', '']],
    nodes: [['allocation', '对象分配', 'new Object()', 'Box', 'blue'], ['eden', 'Eden 区', 'Young generation', 'MemoryStick', 'green'], ['gc', 'Young GC', 'reachability', 'Recycle', 'yellow'], ['old', '老年代', 'Old generation', 'Archive', 'pink']],
    edges: [['allocation', 'eden', '分配'], ['eden', 'gc', 'Eden 满'], ['gc', 'old', '存活晋升']],
    code: ['// Simplified generational teaching model', 'eden.allocate(new Object());', 'if (eden.isFull()) youngGc();', 'promote(survivingObjects);'],
    theory: [['弱分代假说', '多数对象朝生夕灭', '年轻代集中处理短命对象，以较低成本回收大量空间。'], ['Young GC', '存活对象复制或转移', '具体算法和区域取决于收集器，不能把所有 JVM 都理解成同一种布局。'], ['晋升条件', '年龄、空间担保与收集器策略', '存活一次不必然直接进入老年代。']],
    goals: ['解释分代设计针对的对象生命周期假设', '区分分配、存活、回收和晋升', '知道 Young GC 不等同于 Full GC'],
    challenge: { task: '固定 Eden 4、分配 12，比较 25% 和 75% 存活率对回收与晋升的影响。', hint: '存活率越高，年轻代每次能释放的空间越少。', success: '能解释高存活率为何可能增加复制和老年代压力。', requirements: [{ id: 'low', label: '存活率 25%', when: { eden: 4, allocations: 12, survival: 25 } }, { id: 'high', label: '存活率 75%', when: { eden: 4, allocations: 12, survival: 75 } }] },
    quiz: [quiz('Young GC 是否只回收“没有年龄”的对象？', ['是', '不是，它判断年轻代对象可达性并处理存活者', '只回收 Class'], 1, '年龄影响晋升，但垃圾判定仍基于可达性。'), quiz('存活率提高通常会带来什么？', ['每次释放更多空间', '复制/晋升压力可能增加', '保证不发生 GC'], 1, '更多对象存活意味着更少回收空间和更多存活处理成本。')],
    boundary: '存活比例由参数直接给定，存活对象直接晋升。省略 Survivor、年龄阈值、空间担保、老年代容量和具体收集器差异。',
    source: 'https://docs.oracle.com/en/java/javase/21/gctuning/garbage-collector-implementation.html',
  }),
  lesson({
    id: 'jvm-collectors', title: 'Serial、Parallel 与 G1 收集器对比', short: '07 · 收集器对比', icon: 'Recycle', tag: '收集器选择', number: 'J07', phase: '性能与诊断', milestone: 'diagnostics',
    summary: '在相同年轻代负载下，对比单线程停顿、并行停顿和区域化并发工作的差异。',
    defaults: { collector: 'serial', youngMb: 128, livePercent: 50, gcThreads: 4 },
    fields: [{ key: 'collector', label: '收集器模型', type: 'select', options: [['serial', 'Serial'], ['parallel', 'Parallel'], ['g1', 'G1']] }, { key: 'youngMb', label: '年轻代负载', min: 64, max: 256, step: 32, unit: 'MB' }, { key: 'livePercent', label: '对象存活率', min: 25, max: 75, step: 25, unit: '%' }, { key: 'gcThreads', label: '可用 GC 线程', min: 1, max: 8, unit: '个' }],
    metrics: [['pauseWork', '停顿工作量', '单位'], ['workers', '停顿工作线程', ''], ['concurrentWork', '并发工作量', '单位'], ['reclaimedMb', '本轮回收', 'MB']],
    nodes: [['workload', '年轻代负载', 'allocation pressure', 'Boxes', 'blue'], ['mark', '存活对象识别', 'roots and marking', 'Network', 'green'], ['pause', '应用停顿阶段', 'stop-the-world work', 'Pause', 'yellow'], ['workers', 'GC 工作线程', 'serial or parallel', 'Cpu', 'pink'], ['reclaim', '空间回收', 'reclaim / evacuate', 'Recycle', 'green']],
    edges: [['workload', 'mark', '触发收集'], ['mark', 'pause', '进入停顿'], ['pause', 'workers', '执行工作'], ['workers', 'reclaim', '释放空间']],
    code: ['// Deterministic teaching model, not a benchmark', 'CollectorPlan plan = choose(serialOrParallelOrG1);', 'LiveSet live = traceRoots(youngGeneration);', 'plan.runStopTheWorldWorkers(live);', 'heap.reclaimOrEvacuate(deadObjects);'],
    theory: [['Serial', '单个 GC 工作线程执行停顿阶段', '实现简单、额外协调少，适合小堆或资源受限场景，但停顿工作不能由多个 GC 线程分担。'], ['Parallel', '多个 GC 工作线程换取吞吐量', '仍会 Stop-The-World，重点是缩短批量回收所需墙钟时间并提高吞吐，而不是消除停顿。'], ['G1', 'Region 化布局 + 并发标记 + 可预测停顿目标', '按收益选择 Region 并把部分工作并发化；停顿目标是调度目标，不是硬实时承诺。']],
    goals: ['区分单线程停顿、并行停顿与并发阶段', '解释吞吐优先和停顿目标不是同一个优化方向', '根据堆规模、延迟目标和 CPU 预算提出收集器选择证据'],
    challenge: { task: '固定年轻代负载 128 MB、存活率 50%、GC 线程 4，依次运行 Serial、Parallel 和 G1，比较工作分布。', hint: '三次回收量相同；差异在停顿工作由多少线程承担，以及多少工作可进入并发阶段。', success: '能说明模型工作单位不是毫秒，也不能据此宣称某收集器在生产环境一定更快。', requirements: [{ id: 'serial', label: 'Serial · 128 MB · 存活率 50%', when: { collector: 'serial', youngMb: 128, livePercent: 50, gcThreads: 4 } }, { id: 'parallel', label: 'Parallel · 128 MB · 存活率 50%', when: { collector: 'parallel', youngMb: 128, livePercent: 50, gcThreads: 4 } }, { id: 'g1', label: 'G1 · 128 MB · 存活率 50%', when: { collector: 'g1', youngMb: 128, livePercent: 50, gcThreads: 4 } }] },
    quiz: [quiz('Parallel GC 使用多个工作线程主要为了什么？', ['提高吞吐并缩短批量停顿工作', '彻底消除 Stop-The-World', '让对象不再进入老年代'], 0, 'Parallel GC 仍存在 Stop-The-World，多个线程主要用于并行完成回收工作。'), quiz('G1 的 MaxGCPauseMillis 表示什么？', ['每次停顿绝不会超过该值', '收集器用于选择回收集合的软目标', '应用线程的超时时间'], 1, '停顿目标用于启发式调度，不是硬实时上限。')],
    boundary: '使用 MB 与抽象工作单位构造确定性对照，不模拟真实对象图、Region 记忆集、混合回收、并发失败、操作系统调度或实际毫秒停顿，不能作为收集器性能基准。',
    source: 'https://docs.oracle.com/en/java/javase/21/gctuning/available-collectors.html',
  }),
  lesson({
    id: 'jvm-jit', title: 'JIT 热点编译与内联', short: '08 · JIT 热点编译', icon: 'Cpu', tag: '执行引擎', number: 'J08', phase: '性能与诊断', milestone: 'diagnostics',
    summary: '让同一方法反复执行越过阈值，观察解释执行 → C1 快速编译 → C2 深度优化的分级过程；再演示内联如何消除调用点开销、逃逸分析如何把未逃逸对象替换成标量；最后用编译参数对比提前编译与保持解释的取舍。',
    defaults: { mode: 'tiered', calls: 600, threshold: 200, inline: true, escape: true },
    fields: [{ key: 'mode', label: '实验场景', type: 'select', options: [['tiered', '① 分级编译 · 阈值与热度'], ['inline', '② 内联与逃逸分析'], ['flags', '③ 编译参数 · 门槛对比']] }, { key: 'calls', label: '调用次数', min: 100, max: 1000, step: 100, unit: '次' }, { key: 'threshold', label: '编译阈值', min: 100, max: 1000, step: 100, unit: '次' }, { key: 'inline', label: '启用内联', type: 'toggle' }, { key: 'escape', label: '启用逃逸分析', type: 'toggle' }],
    metrics: [['interpreted', '解释执行', '次'], ['c1', 'C1 段执行', '次'], ['c2', 'C2 段执行', '次'], ['inlined', '内联调用点', ''], ['escapes', '标量替换', '个']],
    nodes: [['call', '方法调用', 'invocation counter', 'Send', 'blue'], ['interp', '解释执行', 'profile 采集', 'CodeXml', 'green'], ['c1', 'C1 编译', 'quick compile', 'Cpu', 'yellow'], ['c2', 'C2 深度编译', 'profile-guided', 'Cpu', 'pink'], ['inline', '内联展开', 'call-site elimination', 'Waypoints', 'yellow'], ['alloc', '标量替换', 'no heap object', 'Box', 'green']],
    edges: [['call', 'interp', '计数未达阈值'], ['interp', 'c1', '越过 C1 阈值'], ['c1', 'c2', '持续热点'], ['call', 'inline', 'native 入口'], ['inline', 'alloc', '对象未逃逸'], ['c2', 'inline', '深度优化']],
    code: ['int sum = 0;', 'for (int i = 0; i < calls; i++) {', '  if (++invocationCounter == c1Threshold) compileLevel(c1);', '  if (invocationCounter == c2Threshold) compileLevel(c2);', '  sum += hotMethod(i); // interpreter -> compiled entry', '}'],
    theory: [['分层编译', '解释 → C1 → C2', '解释器先运行并收集 profile；越过 C1 阈值得到快速编译版本，热度更高再交给 C2 深度优化，代价与收益逐级增加。'], ['内联', '编译期展开调用点', '把短小高频方法的调用点直接展开为被调方代码，减少调用与栈帧开销；是否内联由方法大小、热度与调用场景决定。'], ['逃逸分析与标量替换', '对象未逃逸时的优化', '对象若只在方法内使用且不逃逸，C2 可以拆开字段直接放到寄存器或栈上，既消除堆分配，也常顺带消除锁。']],
    goals: ['区分解释执行、C1 快速编译与 C2 深度优化', '解释调用次数、编译阈值与分层策略的关系', '说明内联与逃逸分析只在画像成立时生效'],
    challenge: { task: '分别在调用 600 与 1000 次时观察 C1/C2 分段；再进入内联场景对比开关内联与逃逸分析；最后用编译参数场景对比默认门槛与调低门槛。', hint: '编译发生在越过阈值的下一次调用边界；逃逸分析只消除未逃逸对象的堆分配。', success: '能说明为什么调低编译阈值不一定让峰值更快。', requirements: [{ id: 't600', label: '分级 · 600 次', when: { mode: 'tiered', calls: 600 } }, { id: 't1000', label: '分级 · 1000 次', when: { mode: 'tiered', calls: 1000 } }, { id: 'inline', label: '内联 · 内联与逃逸开启', when: { mode: 'inline', inline: true, escape: true } }, { id: 'flags', label: '参数 · 阈值 200', when: { mode: 'flags', threshold: 200 } }] },
    quiz: [quiz('方法调用次数越过阈值后，HotSpot 通常先做什么？', ['先由 C1 快速编译，热度足够再交 C2', '直接进行 C2 深度优化', '永远保持解释执行'], 0, '分层编译先做低成本的 C1 编译，持续热点才触发 C2 深度优化。'), quiz('完全未逃逸出方法的对象，C2 可能如何处理？', ['标量替换，不产生堆分配', '强制晋升到老年代', '禁止对该方法内联'], 0, '未逃逸对象可以被拆分为标量放在寄存器或栈上，甚至完全不分配。')],
    boundary: '使用抽象调用计数与固定阈值演示分层模型，不读取 CompilationMXBean，不修改网关启动参数，不代表真实 C1/C2 代码质量、OSR、去优化与具体 JDK 版本差异。',
    source: 'https://docs.oracle.com/en/java/javase/21/vm/java-hotspot-virtual-machine-performance-enhancements.html',
  }),
];
