export const jvmDeepDives = {
  'jvm-bytecode': {
    question: '同一段 add 源码，JVM 到底怎样把两个参数变成一个返回值？',
    scenario: '调用静态方法 add(7, 5) 时，javap 显示 iload_0、iload_1、iadd、ireturn。参数变化不会改写这四条指令，只会改变当前栈帧中的数据。',
    chain: [
      ['方法调用先建立栈帧', '静态方法没有 this，参数 a、b 通常进入局部变量表 slot 0 和 slot 1。程序计数器指向当前线程下一条待执行的字节码指令。'],
      ['指令通过操作数栈传值', '两个 iload 依次把局部变量压入操作数栈。iadd 弹出两个 int，计算后把结果压回；它不会直接修改局部变量槽位。'],
      ['字节码还不是最终机器码', '解释器可逐条执行字节码，热点方法也可能由 JIT 编译成本机机器码。javap 证明 Class 中的指令，不证明运行时一定逐条解释。'],
    ],
    headers: ['观测证据', '能够确认', '不能直接确认'],
    rows: [['javap 出现 iload_0', '读取局部变量 slot 0 的 int', '该指令最终执行了多少次'], ['iadd 后栈深度为 1', '两个操作数被消费并压入结果', 'CPU 使用了哪一个寄存器'], ['ireturn 返回 12', '当前输入的计算结果', '方法没有经过 JIT 编译'] ],
    misconception: '“字节码就是跨平台的汇编，所以 JVM 会永远逐条解释”不成立。Class 指令集与具体 CPU 解耦，但执行引擎可以解释，也可以 JIT 编译。',
    transfer: '线上火焰图显示一个简单方法占用很高。仅凭 javap 的四条指令，能否断定它的机器指令成本很低？还需要什么证据？',
    answer: '不能。还要确认调用次数、是否内联、参数类型与装箱、编译层级、生成机器码及采样偏差。字节码适合解释语义，运行成本要结合 JIT 日志、JFR 或性能剖析。',
    links: [['JVMS 运行时数据区', 'https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-2.html'], ['JVMS 指令集', 'https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-6.html']],
  },
  'jvm-classloading': {
    question: '加载请求明明从自定义 ClassLoader 发起，为什么 String 仍由 Bootstrap 定义？',
    scenario: '应用加载 java.lang.String 与 OrderService。请求都可以经过应用加载器，但最终定义者不同；Class.getClassLoader() 对 String 返回 null。',
    chain: [
      ['loadClass 先查已加载结果', '标准实现先避免重复定义，再把请求委派给父加载器。父级能找到核心类时，子加载器不会再次定义同名核心类型。'],
      ['请求路径不等于定义身份', '某个加载器收到请求，并不代表它最终调用 defineClass。类的运行时身份由二进制类名和定义它的 ClassLoader 共同决定。'],
      ['加载、链接、初始化分阶段', '找到字节并定义 Class 后还要验证、准备和可选解析；首次主动使用通常才触发 <clinit>。仅取得 Class 对象不能笼统推断初始化已发生。'],
    ],
    headers: ['现象', '正确解释', '常见误判'],
    rows: [['String 的加载器为 null', '由 Bootstrap 表示', '这个类没有加载器'], ['OrderService 由 AppClassLoader 定义', '父级未找到后由应用加载器定义', '请求没有向父级委派'], ['获得 Class 对象', '类至少已加载', '静态初始化一定执行完毕']],
    misconception: '“双亲委派是 JVM 强制且绝不可改变的规则”不准确。它是 ClassLoader.loadClass 的常见实现约定；容器、插件和模块化系统可以采用受控的不同策略。',
    transfer: '插件目录里存在一份与主应用同名的 DTO，反射打印的全限定类名完全相同，但强制转换失败。你先检查什么？',
    answer: '同时打印两个 Class 对象及其定义 ClassLoader、父链和加载来源。若由不同加载器定义，它们是不同运行时类型；应统一共享 API 的加载器边界，避免插件私自携带重复接口类。',
    links: [['JVMS 加载、链接与初始化', 'https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-5.html'], ['ClassLoader API', 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/ClassLoader.html']],
  },
  'jvm-memory': {
    question: '线程、栈帧、对象和类元数据增加时，为什么不能都归因于“堆变大”？',
    scenario: '把线程从 1 增到 3，递归深度保持 4，教学模型中的栈帧从 4 增至 12；堆对象和已加载类数不随线程数自动复制。',
    chain: [
      ['先按线程私有与共享划分', '每个线程拥有自己的程序计数器和 Java 虚拟机栈；堆和方法区语义由同一 JVM 内线程共享。线程增长通常会增加独立栈及本地线程资源。'],
      ['变量槽位与对象分开观察', '方法局部引用可保存在栈帧槽位中，被引用的对象通常位于堆。引用消失可能让对象不可达，但不会等价于立即释放内存。'],
      ['逻辑规范与 HotSpot 实现分层', 'JVMS 定义运行时区域的职责，HotSpot 再用具体内存结构实现。Metaspace、Code Cache 和直接内存不能简单都叫作 Java 堆。'],
    ],
    headers: ['变化', '主要关注区域', '典型证据'],
    rows: [['线程数持续上升', '线程栈与本地线程资源', '线程转储、-Xss、进程线程数'], ['对象保留持续上升', 'Java 堆', '堆使用量、对象直方图、堆转储'], ['动态生成类持续上升', '类元数据区域', '已加载类数、Metaspace 内存池']],
    misconception: '“进程内存减去 Java 堆就是泄漏”不成立。线程栈、直接内存、代码缓存、JVM 本地结构和映射文件都可能占用进程地址空间。',
    transfer: '服务增加线程池上限后，堆曲线基本不变，但容器 RSS 上升并最终被系统终止。排查顺序是什么？',
    answer: '先核对线程数量与 -Xss，再区分堆、Metaspace、Code Cache、直接内存和本地分配；结合线程转储、MemoryPoolMXBean、Native Memory Tracking 与容器限制，不能只看堆 GC 指标。',
    links: [['JVMS 运行时数据区', 'https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-2.html#jvms-2.5'], ['MemoryPoolMXBean', 'https://docs.oracle.com/en/java/javase/21/docs/api/java.management/java/lang/management/MemoryPoolMXBean.html']],
  },
  'jvm-allocation': {
    question: 'TLAB 开启后对象仍在堆里，为什么分配却能更少竞争？',
    scenario: '同样分配 12 个教学对象，开启 TLAB 时多数请求走线程本地指针移动；关闭后每次都进入共享路径。TLAB 用尽时仍要补充。',
    chain: [
      ['先为线程预留一段堆空间', 'TLAB 是线程在 Eden 等分配区域中的私有缓冲。对象仍属于 Java 堆，只是当前线程可以在已预留范围内快速移动顶指针。'],
      ['快速路径有明确边界', '剩余空间不足、对象不适合进入 TLAB 或策略限制时，需要补充 TLAB 或走共享分配路径。开启 TLAB 不等于慢路径归零。'],
      ['内存预留早于构造执行', 'new 对应的过程包括分配、零值初始化、对象头设置和构造调用。构造方法抛异常，不表示此前完全没有发生分配工作。'],
    ],
    headers: ['场景', '可能路径', '不能据此推断'],
    rows: [['小对象且 TLAB 空间充足', '线程本地指针碰撞', '对象分配在 Java 堆之外'], ['TLAB 剩余空间不足', '补充 TLAB 或共享路径', '一定立即触发 GC'], ['线程分配字节增长', '该线程发生了受统计的分配', '这些对象现在仍然存活']],
    misconception: '“逃逸分析会把所有不逃逸对象都放到栈上”过度简化。HotSpot 常通过标量替换消除对象分配；具体结果取决于 JIT 编译与优化条件。',
    transfer: '接口优化后吞吐提高，但线程分配字节仍很高。你如何判断是短命对象成本、对象保留，还是测量口径问题？',
    answer: '用 JFR 或分配剖析定位热点类型与调用点，再结合 GC 分配速率、存活率和堆转储判断保留；核对采样窗口、预热和 JIT 状态。分配量高不自动等于内存泄漏。',
    links: [['HotSpot 存储管理', 'https://openjdk.org/groups/hotspot/docs/StorageManagement.html'], ['Oracle GC 实现概览', 'https://docs.oracle.com/en/java/javase/21/gctuning/garbage-collector-implementation.html']],
  },
  'jvm-roots': {
    question: '两个对象互相引用，为什么 GC 仍然能把它们一起回收？',
    scenario: '对象 A 与 B 构成循环，但活动线程栈、静态字段和 JNI 引用都无法到达它们。模型将整个环标记为不可达，而不是等待引用计数降到零。',
    chain: [
      ['从有限的 Roots 集合出发', '活动栈帧中的引用、已加载类的静态引用、JNI 引用等可成为遍历起点。Root 本身的枚举依赖 JVM 在安全点或并发阶段维护的元数据。'],
      ['沿引用边计算传递闭包', 'Root 直接引用 A，A 再引用 B，则 A 和 B 都可达。对象入度高或彼此成环，都不能替代从 Root 出发的路径判断。'],
      ['引用类型改变保留语义', '强、软、弱、虚引用进入不同处理流程。WeakReference 在 GC 判定后可能被清除并入队，但 System.gc() 不保证立即发生这件事。'],
    ],
    headers: ['对象关系', '可达性结论', '原因'],
    rows: [['Root → A → B', 'A、B 可达', '存在从 Root 出发的路径'], ['A ↔ B，无 Root 路径', 'A、B 均不可达', '循环本身不是 Root'], ['WeakReference → C，无强路径', 'C 可能被清除', '弱引用不提供强可达性']],
    misconception: '“把变量设为 null 就会立即回收对象”不成立。它只移除一条引用；对象可能仍由其他路径可达，即使不可达，实际回收时机也由收集器决定。',
    transfer: '缓存使用 WeakReference 后命中率突然下降。一次探针中引用仍未清除，能否证明设计可靠？应该怎样验证？',
    answer: '不能。建立可重复的内存压力与业务访问场景，观察 ReferenceQueue、命中率和重建成本；同时确认没有其他强引用。弱引用回收时机不确定，不能作为需要稳定保留的数据缓存策略。',
    links: [['WeakReference API', 'https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/ref/WeakReference.html'], ['Oracle GC 其他考虑', 'https://docs.oracle.com/en/java/javase/21/gctuning/other-considerations.html']],
  },
  jvm: {
    question: '年轻代存活率升高时，为什么一次 GC 释放的空间反而可能更少？',
    scenario: 'Eden 容量和分配数量固定，存活率从 25% 提高到 75%。触发次数可能相近，但每轮需要处理、复制或晋升的存活对象更多。',
    chain: [
      ['分代来自生命周期假设', '多数新对象很快不可达，因此把新对象集中到年轻代，可以用较小范围的收集换回大量空间。这是经验假设，不是每个负载都成立。'],
      ['收集器决定具体布局和动作', 'Eden、Survivor、年龄阈值是常见 HotSpot 教学模型，不应套用到所有收集器。Young GC 也不等同于一次全堆 Full GC。'],
      ['高存活率改变复制与晋升压力', '本轮死亡对象减少，释放空间变少；存活者需要复制、重新定位或晋升。持续高存活可能增加老年代占用和后续回收压力。'],
    ],
    headers: ['观测', '合理判断', '不能单独断定'],
    rows: [['Young GC count 增长', '年轻代收集事件发生', '每次停顿都很长'], ['存活率升高', '存活处理与晋升压力可能增加', '一定马上触发 Full GC'], ['累计 GC time 增长', 'MXBean 统计窗口内总耗时增加', '最近一次停顿就是该数值']],
    misconception: '“选择低延迟收集器后就不会有停顿”不成立。不同收集器改变工作并发方式与停顿目标，但应用线程仍可能在某些阶段暂停，目标也不是硬实时保证。',
    transfer: '发布后 Young GC 次数变化不大，但老年代增长加快。你会比较哪些指标与业务变化？',
    answer: '比较分配速率、每轮存活量、晋升量、对象年龄、老年代占用和停顿分位数，并关联缓存、批处理或请求对象生命周期变化。先确认收集器与日志字段，再判断是高存活还是容量配置问题。',
    links: [['Oracle 分代 GC 实现', 'https://docs.oracle.com/en/java/javase/21/gctuning/garbage-collector-implementation.html'], ['GarbageCollectorMXBean', 'https://docs.oracle.com/en/java/javase/21/docs/api/java.management/java/lang/management/GarbageCollectorMXBean.html']],
  },
  'jvm-collectors': {
    question: 'Serial、Parallel 和 G1 都能回收垃圾，为什么不能只选“看起来停顿最短”的那个？',
    scenario: '同一轮 128 MB 年轻代负载中有 64 MB 存活对象。三种模型回收的死亡对象相同，但停顿内工作线程数、并发工作量和额外协调成本不同。',
    chain: [
      ['先确定服务目标和资源边界', '批处理通常优先吞吐，交互服务更关注停顿分位数；堆大小、CPU 配额、容器限额和对象存活率都会改变结果。脱离负载谈“最佳收集器”没有可验证含义。'],
      ['区分并行与并发', 'Parallel 指多个 GC 线程同时执行停顿内工作，应用线程仍暂停；并发表示部分 GC 工作与应用线程重叠。两者都可能消耗更多 CPU，也都不等于零停顿。'],
      ['理解 G1 的 Region 与停顿目标', 'G1 通过并发标记识别老年代存活情况，再按收益选择 Region 组成回收集合。停顿目标影响启发式选择，但受存活对象、记忆集和疏散空间约束，不是硬上限。'],
    ],
    headers: ['选择方向', '主要收益', '需要付出的代价'],
    rows: [['Serial', '实现与协调简单，资源占用较低', '停顿工作由单个 GC 线程承担'], ['Parallel', '利用多核提高批量回收吞吐', '停顿仍存在，并与应用争夺 CPU'], ['G1', 'Region 化回收并提供停顿目标', '并发标记、记忆集和疏散需要额外资源']],
    misconception: '“G1 一定比 Parallel 快”不成立。快必须先定义为吞吐、平均延迟还是尾停顿；小堆、CPU 受限和高存活率场景可能得到完全不同的结果。',
    transfer: '一个 4 核、2 GB 堆的订单接口要求 P99 延迟稳定；夜间报表任务只要求一小时内完成。你会怎样分别建立收集器选择证据？',
    answer: '订单接口用接近生产的流量和对象生命周期比较停顿 P95/P99、吞吐、CPU、分配与晋升率，并检查容器限额；报表任务优先比较总完成时间和 CPU 利用率。两者都要固定 JDK、堆参数、预热和数据集，多轮运行后再决策。',
    links: [['Oracle 可用收集器', 'https://docs.oracle.com/en/java/javase/21/gctuning/available-collectors.html'], ['Oracle G1 调优', 'https://docs.oracle.com/en/java/javase/21/gctuning/garbage-first-garbage-collector-tuning.html']],
  },
};
