const quiz = (prompt, choices, answer, explanation) => ({ prompt, choices, answer, explanation });
const lesson = config => ({ group: 'Redis 专题', module: 'Redis', ...config });

export const redisLabs = [
  lesson({
    id: 'redis', title: 'Cache-Aside 缓存读写', short: '01 · 缓存读写', icon: 'DatabaseZap', tag: '基础原理', number: 'R01', phase: '基础原理', layout: 'wide',
    summary: '跟随一次请求，观察缓存命中、数据库回源、缓存回填与 LRU 淘汰。',
    defaults: { capacity: 3, requests: 6, cache: true, key: 'user:1001' },
    fields: [{ key: 'key', label: '请求 Key', type: 'text' }, { key: 'capacity', label: '缓存容量', min: 1, max: 6, unit: '条' }, { key: 'requests', label: '请求数量', min: 1, max: 12, unit: '次' }, { key: 'cache', label: '启用缓存', type: 'toggle' }],
    metrics: [['requests', '请求次数', ''], ['hits', '缓存命中', ''], ['misses', '数据库读取', ''], ['rate', '命中率', '%']],
    nodes: [['client', '客户端', 'HTTP Client', 'Monitor', 'blue'], ['app', 'Java 应用', 'Spring Boot Service', 'Coffee', 'green'], ['cache', 'Redis 缓存', 'In-memory cache', 'DatabaseZap', 'pink'], ['db', 'MySQL 数据库', 'Persistent storage', 'Database', 'yellow']],
    edges: [['client', 'app', '① 请求 / 响应'], ['app', 'cache', '② GET / SET'], ['app', 'db', '③ SELECT']],
    code: ['public User getUser(String key) {', '  User user = redis.get(key);', '  if (user != null) return user;', '  user = repository.findById(key);', '  redis.set(key, user);', '  return user;', '}'],
    theory: [['读取策略', 'Cache → Database → Cache', '先查缓存；未命中时回源，并把结果写回缓存。'], ['命中率', 'hits / requests', '复用越集中、工作集越能装入缓存，命中率通常越高。'], ['内存淘汰', 'maxmemory-policy', '达到内存上限后，是否淘汰以及淘汰谁由策略决定。']],
    goals: ['解释一次缓存命中和未命中的完整调用链', '区分缓存容量、工作集与命中率的关系', '知道 LRU 是淘汰策略，不是过期删除策略'],
    challenge: { task: '把缓存容量依次设为 1 和 3，运行相同的 6 次请求，对比最终命中率与数据库读取次数。', hint: '容量 1 无法容纳这组请求的工作集。', success: '能够解释为什么请求数相同，容量变化却改变了回源次数。', requirements: [{ id: 'small', label: '容量 1 · 运行 6 次请求', when: { capacity: 1, requests: 6, cache: true } }, { id: 'normal', label: '容量 3 · 运行 6 次请求', when: { capacity: 3, requests: 6, cache: true } }] },
    quiz: [
      quiz('Cache-Aside 读取缓存未命中后，下一步通常是什么？', ['直接返回空值', '查询数据库并回填缓存', '删除数据库记录'], 1, 'Cache-Aside 在缓存未命中时读取数据源，成功后将结果回填缓存。'),
      quiz('把缓存容量调大，命中率是否一定提高？', ['一定提高', '不一定，还取决于访问分布和工作集', '一定降低'], 1, '容量只是因素之一；几乎不重复的访问即使容量更大也可能没有命中。'),
    ],
    boundary: '浏览器内教学模拟，使用精确 LRU；Redis 实际 LRU 为近似采样。未连接真实服务，未模拟网络延迟、TTL 与并发一致性。',
    source: 'https://redis.io/docs/latest/develop/reference/eviction/',
  }),
  lesson({
    id: 'redis-types', title: '数据类型与访问模型', short: '02 · 数据类型', icon: 'Boxes', tag: '基础原理', number: 'R02', phase: '基础原理',
    summary: '用相同数据对比 String、Hash、List、Set 与 Sorted Set 的存储语义。',
    defaults: { type: 'set', items: 8, duplicateEvery: 2 },
    fields: [{ key: 'type', label: '数据类型', type: 'select', options: [['string', 'String'], ['hash', 'Hash'], ['list', 'List'], ['set', 'Set'], ['zset', 'Sorted Set']] }, { key: 'items', label: '写入次数', min: 2, max: 12, unit: '次' }, { key: 'duplicateEvery', label: '重复间隔', min: 0, max: 4, unit: '次' }],
    metrics: [['commands', '命令次数', ''], ['stored', '实际条目', ''], ['duplicates', '重复忽略', ''], ['result', '结果数量', '']],
    nodes: [['client', '业务场景', 'Access pattern', 'Monitor', 'blue'], ['command', 'Redis 命令', 'SET / HSET / SADD', 'CodeXml', 'green'], ['structure', '内部结构', 'Encoding varies', 'Boxes', 'yellow'], ['result', '读取结果', 'Semantic result', 'FileCheck2', 'pink']],
    edges: [['client', 'command', '选择命令'], ['command', 'structure', '更新数据'], ['structure', 'result', '读取结果']],
    code: ['// Choose a type by access pattern', 'redis.opsForList().rightPush(key, value);', 'redis.opsForSet().add(key, value);', 'redis.opsForZSet().add(key, value, score);', 'redis.opsForHash().put(key, field, value);'],
    theory: [['List 与 Set', '顺序 / 重复语义不同', 'List 保留插入与重复；Set 保证成员唯一。'], ['Sorted Set', 'member + score', '成员唯一并按分值排序，适合排行榜和延时队列索引。'], ['编码会变化', '类型 ≠ 固定底层结构', 'Redis 会按元素数量和大小选择紧凑或通用编码。']],
    goals: ['根据访问方式而不是字段名称选择数据类型', '解释 List、Set、Sorted Set 的重复和排序语义', '理解 Redis 类型与底层编码不是一一固定对应'],
    challenge: { task: '分别选择 List 和 Set，保持 8 次写入与重复间隔 2，比较“实际条目”和“重复忽略”。', hint: '关注集合是否允许相同 member。', success: '能够为队列、标签集合、排行榜分别选出合适类型。', requirements: [{ id: 'list', label: 'List · 8 次写入 · 重复间隔 2', when: { type: 'list', items: 8, duplicateEvery: 2 } }, { id: 'set', label: 'Set · 8 次写入 · 重复间隔 2', when: { type: 'set', items: 8, duplicateEvery: 2 } }] },
    quiz: [
      quiz('需要按分数实时查询排行榜，应优先选择哪种类型？', ['List', 'Hash', 'Sorted Set'], 2, 'Sorted Set 同时维护唯一成员和 score 排序。'),
      quiz('Redis 的 String 是否意味着底层永远是字符数组？', ['是', '否，编码可能按值变化', '仅集群模式不是'], 1, 'Redis 对象的逻辑类型和内部编码是两个层次。'),
    ],
    boundary: '演示数据类型的外部语义，不复刻 listpack、hashtable、quicklist、skiplist 等真实编码阈值与内存布局。',
    source: 'https://redis.io/docs/latest/develop/data-types/',
  }),
  lesson({
    id: 'redis-expiry', title: 'TTL、过期删除与内存淘汰', short: '03 · TTL 与淘汰', icon: 'Recycle', tag: '基础原理', number: 'R03', phase: '基础原理',
    summary: '区分 Key 到期与 maxmemory 淘汰，观察 noeviction 和 allkeys-lru 的不同结果。',
    defaults: { keys: 8, memory: 4, ttl: 3, jitter: false, policy: 'allkeys-lru' },
    fields: [{ key: 'keys', label: '写入 Key 数', min: 2, max: 12, unit: '个' }, { key: 'memory', label: '内存容量', min: 2, max: 8, unit: '个' }, { key: 'ttl', label: '基础 TTL', min: 1, max: 6, unit: '秒' }, { key: 'jitter', label: 'TTL 增加随机量', type: 'toggle' }, { key: 'policy', label: '内存策略', type: 'select', options: [['noeviction', 'noeviction'], ['allkeys-lru', 'allkeys-lru']] }],
    metrics: [['alive', '存活 Key', ''], ['expired', '过期删除', ''], ['evicted', '内存淘汰', ''], ['denied', '拒绝写入', '']],
    nodes: [['writer', '写入命令', 'SET key EX ttl', 'Send', 'blue'], ['memory', '键空间', 'Keyspace + expires', 'DatabaseZap', 'green'], ['policy', '内存策略', 'maxmemory-policy', 'ShieldAlert', 'yellow'], ['expiry', '过期周期', 'Passive + active', 'Recycle', 'pink']],
    edges: [['writer', 'memory', '写入'], ['memory', 'policy', '达到上限'], ['memory', 'expiry', 'TTL 到期']],
    code: ['redis.set(key, value, SetArgs.Builder.ex(ttl));', 'if (usedMemory > maxmemory) applyEvictionPolicy();', '// Expired keys are removed passively and actively', '// noeviction rejects memory-growing writes'],
    theory: [['两套机制', 'expiration ≠ eviction', '过期由 TTL 决定；淘汰由 maxmemory 与策略决定。'], ['过期删除', '惰性访问 + 主动周期采样', 'Redis 不为每个 Key 单独创建定时器。'], ['noeviction', '达到上限后拒绝增量写入', '它不会自动删除任意 Key 来为新写入腾空间。']],
    goals: ['区分 TTL 到期和内存淘汰的触发条件', '解释 Redis 为什么组合使用惰性与主动过期', '预测 noeviction 和 allkeys-lru 的写入结果'],
    challenge: { task: '固定写入 8 个 Key、内存容量 4，比较 noeviction 与 allkeys-lru 的拒绝和淘汰数量。', hint: '两种策略都遇到相同内存上限，但处理新写入的方式不同。', success: '能准确区分 expired、evicted 和 denied 三个指标。', requirements: [{ id: 'deny', label: 'noeviction · 8 Key · 容量 4', when: { keys: 8, memory: 4, policy: 'noeviction' } }, { id: 'lru', label: 'allkeys-lru · 8 Key · 容量 4', when: { keys: 8, memory: 4, policy: 'allkeys-lru' } }] },
    quiz: [
      quiz('Key 的 TTL 到期与 maxmemory 淘汰是什么关系？', ['同一机制', '两个独立触发机制', '只有主从模式才不同'], 1, 'TTL 到期是过期删除；内存达到上限才考虑淘汰策略。'),
      quiz('noeviction 达到内存上限后的典型行为是什么？', ['淘汰最旧 Key', '清空数据库', '拒绝会增加内存的写命令'], 2, 'noeviction 保留现有数据并让增量写入失败。'),
    ],
    boundary: '以“每个 Key 占一个容量单位”离散模拟；真实 Redis 按字节统计内存，LRU 为近似采样，过期周期受配置和负载影响。',
    source: 'https://redis.io/docs/latest/develop/reference/eviction/',
  }),
  lesson({
    id: 'redis-penetration', title: '缓存穿透与不存在的 Key', short: '04 · 缓存穿透', icon: 'ShieldAlert', tag: '缓存治理', number: 'R04', phase: '缓存治理',
    summary: '制造大量不存在的 Key，对比无保护、空值缓存与布隆过滤器的数据库压力。',
    defaults: { requests: 12, distinct: 12, bloom: false, nullCache: true },
    fields: [{ key: 'requests', label: '请求数量', min: 2, max: 24, unit: '次' }, { key: 'distinct', label: '不同 Key 数', min: 1, max: 24, unit: '个' }, { key: 'bloom', label: '启用布隆过滤器', type: 'toggle' }, { key: 'nullCache', label: '缓存空值', type: 'toggle' }],
    metrics: [['requests', '请求数', ''], ['dbQueries', '数据库查询', ''], ['blocked', '过滤器拦截', ''], ['nullHits', '空值命中', '']],
    nodes: [['client', '异常请求', 'Missing IDs', 'Monitor', 'blue'], ['guard', '布隆过滤器', 'Definitely absent?', 'Binary', 'green'], ['cache', '空值缓存', 'Short TTL', 'DatabaseZap', 'yellow'], ['db', '数据库', 'Source of truth', 'Database', 'pink']],
    edges: [['client', 'guard', '校验存在性'], ['guard', 'cache', '可能存在'], ['cache', 'db', '未命中']],
    code: ['if (!bloom.mightContain(id)) return NOT_FOUND;', 'Product value = redis.get(id);', 'if (value == NULL_SENTINEL) return NOT_FOUND;', 'value = repository.find(id);', 'redis.setex(id, shortTtl, value == null ? NULL_SENTINEL : value);'],
    theory: [['穿透定义', '缓存与数据库都不存在', '请求每次绕过缓存并落到数据库。'], ['空值缓存', '重复不存在 Key 有效', '随机且几乎不重复的 Key 会产生大量空占位，效果有限。'], ['布隆过滤器', '一定不存在 / 可能存在', '允许假阳性，不允许把真实存在元素判定为一定不存在。']],
    goals: ['区分缓存穿透与普通缓存未命中', '比较空值缓存和布隆过滤器的适用边界', '理解布隆过滤器假阳性的含义'],
    challenge: { task: '先用 12 个不同 Key 测试空值缓存，再把不同 Key 数改为 2；最后启用布隆过滤器。', hint: '空值缓存依赖后续请求重复命中相同的不存在 Key。', success: '能根据攻击 Key 是否重复选择治理方案。', requirements: [{ id: 'unique-null', label: '空值缓存 · 12 个不同 Key', when: { requests: 12, distinct: 12, bloom: false, nullCache: true } }, { id: 'repeat-null', label: '空值缓存 · 2 个不同 Key', when: { requests: 12, distinct: 2, bloom: false, nullCache: true } }, { id: 'bloom', label: '布隆过滤器 · 12 个不同 Key', when: { requests: 12, distinct: 12, bloom: true } }] },
    quiz: [
      quiz('空值缓存为什么难以处理每次都不同的随机不存在 Key？', ['没有机会复用已缓存的空值', 'Redis 不支持空值', '数据库会自动删除空值'], 0, '空值缓存只有再次请求同一个 Key 时才产生收益。'),
      quiz('布隆过滤器说“可能存在”意味着什么？', ['一定存在', '仍需继续查缓存或数据源', '一定不存在'], 1, '布隆过滤器可能假阳性，“可能存在”不能替代真实查询。'),
    ],
    boundary: '所有请求均针对不存在数据；布隆过滤器在模型中无假阳性。真实系统要处理过滤器同步、容量估算、误判率和空值 TTL。',
    source: 'https://redis.io/docs/latest/develop/data-types/probabilistic/bloom-filter/',
  }),
  lesson({
    id: 'redis-breakdown', title: '缓存击穿与热点重建', short: '05 · 缓存击穿', icon: 'Workflow', tag: '缓存治理', number: 'R05', phase: '缓存治理',
    summary: '让一个热点 Key 突然失效，对比并发回源、互斥重建与逻辑过期。',
    defaults: { concurrent: 20, strategy: 'mutex' },
    fields: [{ key: 'concurrent', label: '并发请求数', min: 2, max: 40, unit: '个' }, { key: 'strategy', label: '重建策略', type: 'select', options: [['none', '无保护'], ['mutex', '互斥重建'], ['logical', '逻辑过期']] }],
    metrics: [['requests', '并发请求', ''], ['dbQueries', '数据库查询', ''], ['waiting', '等待请求', ''], ['stale', '旧值响应', '']],
    nodes: [['hotkey', '热点 Key', 'Expired at t0', 'DatabaseZap', 'blue'], ['lock', '重建协调', 'Mutex / lease', 'ShieldAlert', 'green'], ['cache', '缓存值', 'Fresh or stale', 'Boxes', 'yellow'], ['db', '数据库', 'Rebuild source', 'Database', 'pink']],
    edges: [['hotkey', 'lock', '并发请求'], ['lock', 'db', '单线程重建'], ['db', 'cache', '写回']],
    code: ['Value value = redis.get(key);', 'if (value != null && !logicallyExpired(value)) return value;', 'if (tryLock(key)) rebuildFromDatabase();', 'else return staleValueOrRetry();', 'unlockWithToken(key);'],
    theory: [['击穿定义', '单个热点 Key 失效', '大量并发同时回源，数据库瞬时压力升高。'], ['互斥重建', '一个重建，其余等待', '保证新鲜度，但等待和锁超时会增加尾延迟。'], ['逻辑过期', '先返回旧值，后台更新', '牺牲短暂新鲜度换取稳定延迟。']],
    goals: ['区分击穿、穿透和雪崩', '解释互斥重建为何减少数据库查询', '理解逻辑过期以一致性换可用性的代价'],
    challenge: { task: '固定 20 个并发请求，依次运行无保护、互斥重建和逻辑过期，对比数据库查询、等待和旧值响应。', hint: '没有单一策略同时让等待为 0、旧值为 0、回源也只有 1 次。', success: '能根据业务对新鲜度和延迟的要求选择策略。', requirements: [{ id: 'none', label: '无保护 · 并发 20', when: { concurrent: 20, strategy: 'none' } }, { id: 'mutex', label: '互斥重建 · 并发 20', when: { concurrent: 20, strategy: 'mutex' } }, { id: 'logical', label: '逻辑过期 · 并发 20', when: { concurrent: 20, strategy: 'logical' } }] },
    quiz: [
      quiz('逻辑过期在热点重建期间通常返回什么？', ['旧值', 'HTTP 500', '数据库锁'], 0, '逻辑过期允许返回旧值，并由一个线程在后台重建。'),
      quiz('互斥重建最直接的收益是什么？', ['消除所有延迟', '把并发回源合并为一次', '保证 Redis 永不故障'], 1, '同一个 Key 只有持锁者查询数据库，其余请求等待或重试。'),
    ],
    boundary: '把并发请求视为同一时刻到达，省略真实线程调度、锁等待超时、数据库延迟和失败重试。逻辑过期旧值始终可用。',
    source: 'https://redis.io/docs/latest/develop/use/patterns/distributed-locks/',
  }),
  lesson({
    id: 'redis-avalanche', title: '缓存雪崩与流量整形', short: '06 · 缓存雪崩', icon: 'Layers', tag: '缓存治理', number: 'R06', phase: '缓存治理',
    summary: '让一批 Key 集中过期，观察 TTL 抖动和限流如何改变数据库峰值。',
    defaults: { keys: 24, window: 6, jitter: false, dbCapacity: 8, rateLimit: false },
    fields: [{ key: 'keys', label: '到期 Key 数', min: 6, max: 60, unit: '个' }, { key: 'window', label: '抖动窗口', min: 1, max: 10, unit: '秒' }, { key: 'jitter', label: '启用 TTL 抖动', type: 'toggle' }, { key: 'dbCapacity', label: '数据库容量', min: 2, max: 20, unit: '/秒' }, { key: 'rateLimit', label: '启用入口限流', type: 'toggle' }],
    metrics: [['expired', '已失效 Key', ''], ['peakDb', '回源峰值', '/s'], ['overloaded', '过载时间片', ''], ['rejected', '限流拒绝', '']],
    nodes: [['clock', 'TTL 时间轴', 'Same time or jitter', 'ListOrdered', 'blue'], ['cache', '批量失效', 'Many cache misses', 'DatabaseZap', 'yellow'], ['guard', '流量保护', 'Rate limit', 'ShieldAlert', 'green'], ['db', '数据库', 'Finite capacity', 'Database', 'pink']],
    edges: [['clock', 'cache', 'Key 到期'], ['cache', 'guard', '回源流量'], ['guard', 'db', '放行']],
    code: ['long ttl = baseTtl + random.nextLong(jitterWindow);', 'redis.setex(key, ttl, value);', 'if (!rateLimiter.tryAcquire()) return FALLBACK;', 'return repository.findById(id);'],
    theory: [['雪崩定义', '大量 Key 集中失效或缓存整体不可用', '大量请求在短时间内同时落向数据源。'], ['TTL 抖动', 'baseTTL + random(0, window)', '把失效事件摊开，降低峰值但不减少总回源。'], ['入口保护', '限流 / 降级 / 熔断', '保护数据库时必须接受一部分请求失败或返回降级数据。']],
    goals: ['通过峰值而不是总量识别雪崩风险', '解释 TTL 抖动为何降低峰值但不减少总回源', '理解限流以牺牲部分请求保护系统'],
    challenge: { task: '先让 24 个 Key 同时失效，再打开 TTL 抖动；最后关闭抖动并启用限流，对比峰值、过载和拒绝数。', hint: '抖动改变时间分布，限流改变数据库实际接收量。', success: '能组合预防措施与故障时保护措施。', requirements: [{ id: 'same-time', label: '24 Key 同时失效', when: { keys: 24, jitter: false, rateLimit: false } }, { id: 'jitter', label: '24 Key · 开启 TTL 抖动', when: { keys: 24, jitter: true, rateLimit: false } }, { id: 'limited', label: '同时失效 · 开启限流', when: { keys: 24, jitter: false, rateLimit: true } }] },
    quiz: [
      quiz('TTL 抖动主要改变哪个指标？', ['总 Key 数', '失效时间分布与回源峰值', '数据库表结构'], 1, '抖动把相同 TTL 分散到时间窗口，从而削峰。'),
      quiz('限流保护数据库的直接代价是什么？', ['部分请求被拒绝或降级', '缓存容量翻倍', '所有请求更快'], 0, '容量有限时，保护下游意味着不能让所有请求继续回源。'),
    ],
    boundary: '每个失效 Key 产生一次回源，按整秒时间片统计；真实系统还受热点程度、请求合并、连接池和重试风暴影响。',
    source: 'https://redis.io/docs/latest/develop/reference/eviction/',
  }),
  lesson({
    id: 'redis-consistency', title: '缓存与数据库一致性', short: '07 · 缓存一致性', icon: 'RefreshCw', tag: '并发正确性', number: 'R07', phase: '并发正确性',
    summary: '重放并发读写时序，比较先删缓存、更新后删除与延迟双删。',
    defaults: { strategy: 'dbFirst', concurrentRead: true },
    fields: [{ key: 'strategy', label: '更新策略', type: 'select', options: [['deleteFirst', '先删缓存再更新 DB'], ['dbFirst', '更新 DB 后删除缓存'], ['doubleDelete', '延迟双删']] }, { key: 'concurrentRead', label: '注入并发读', type: 'toggle' }],
    metrics: [['dbVersion', '数据库版本', ''], ['cacheVersion', '缓存版本', ''], ['staleReads', '短暂旧读', ''], ['consistent', '最终一致', '']],
    nodes: [['writer', '写请求', 'Update v1 → v2', 'Send', 'blue'], ['reader', '并发读', 'Race window', 'Monitor', 'yellow'], ['cache', 'Redis 缓存', 'Versioned value', 'DatabaseZap', 'green'], ['db', '数据库', 'Source of truth', 'Database', 'pink']],
    edges: [['writer', 'db', '更新'], ['reader', 'cache', '读取 / 回填'], ['writer', 'cache', '删除缓存']],
    code: ['@Transactional', 'repository.update(entity);', '// delete only after the DB transaction commits', 'redis.delete(cacheKey);', '// optional: outbox / CDC retries deletion failures'],
    theory: [['常见顺序', '更新数据库 → 删除缓存', '通常比“先删缓存”更容易收敛，但仍需处理删除失败。'], ['短暂旧读', '最终一致 ≠ 强一致', '删除动作前仍可能读到旧缓存，系统存在一致性窗口。'], ['可靠失效', '重试 / 消息 / CDC', '数据库提交后缓存删除失败时，需要可靠补偿。']],
    goals: ['画出先删缓存产生最终脏数据的竞态时序', '区分短暂旧读与最终缓存脏数据', '知道更新后删除仍需处理删除失败'],
    challenge: { task: '保持并发读开启，比较三种更新策略的缓存最终版本和短暂旧读次数。', hint: '最终 Cache 为空表示下一次读会从 DB v2 回填，不等于请求期间从未读到旧值。', success: '能说清推荐顺序的收益和它仍然没有解决的问题。', requirements: [{ id: 'delete-first', label: '先删缓存 · 注入并发读', when: { strategy: 'deleteFirst', concurrentRead: true } }, { id: 'db-first', label: '更新 DB 后删除 · 注入并发读', when: { strategy: 'dbFirst', concurrentRead: true } }, { id: 'double-delete', label: '延迟双删 · 注入并发读', when: { strategy: 'doubleDelete', concurrentRead: true } }] },
    quiz: [
      quiz('常见 Cache-Aside 写入顺序是什么？', ['先更新数据库，再删除缓存', '先写缓存，永不写数据库', '同时提交两个分布式事务'], 0, '更新数据库成功后删除缓存是常见做法，并需为删除失败设计补偿。'),
      quiz('最终缓存为空是否代表整个过程没有旧读？', ['代表', '不代表，删除前仍可能短暂命中旧值', '只在单机代表'], 1, '最终收敛与过程中的一致性窗口是两个不同问题。'),
    ],
    boundary: '固定重放一种典型竞态时序，不代表所有线程交错。数据库提交、缓存删除失败、事务回滚、重试和 CDC 需在生产设计中单独处理。',
    source: 'https://redis.io/docs/latest/develop/clients/client-side-caching/',
  }),
  lesson({
    id: 'redis-atomic', title: '原子命令、事务与 Lua', short: '08 · 原子性与事务', icon: 'CodeXml', tag: '并发正确性', number: 'R08', phase: '并发正确性',
    summary: '用库存扣减重放并发覆盖写，对比普通 GET/SET、WATCH 事务与 Lua 原子脚本。',
    defaults: { strategy: 'watch', clients: 8, stock: 5, demand: 1 },
    fields: [{ key: 'strategy', label: '并发策略', type: 'select', options: [['getSet', '普通 GET + SET'], ['watch', 'WATCH + MULTI/EXEC'], ['lua', 'Lua 原子脚本']] }, { key: 'clients', label: '并发客户端', min: 2, max: 16, unit: '个' }, { key: 'stock', label: '初始库存', min: 1, max: 12, unit: '件' }, { key: 'demand', label: '每单扣减', min: 1, max: 3, unit: '件' }],
    metrics: [['success', '成功订单', ''], ['finalStock', '最终库存', ''], ['oversold', '超卖订单', ''], ['retries', '事务重试', '']],
    nodes: [['request', '并发请求', 'Buy commands', 'Monitor', 'blue'], ['read', '读取库存', 'GET / WATCH', 'DatabaseZap', 'yellow'], ['guard', '并发校验', 'CAS or Lua', 'ShieldAlert', 'green'], ['write', '扣减库存', 'Atomic update', 'CodeXml', 'pink']],
    edges: [['request', 'read', '读取'], ['read', 'guard', '校验版本 / 库存'], ['guard', 'write', '提交扣减']],
    code: ['// Option 1: WATCH + optimistic transaction', 'WATCH stockKey', 'MULTI', 'DECRBY stockKey demand', 'EXEC  // null means conflict; read and retry', '// Option 2: Lua checks and decrements atomically', 'redis.eval(script, List.of(stockKey), List.of(demand));'],
    theory: [['单命令原子性', 'INCR / DECRBY / HINCRBY', '优先使用内建原子命令，避免把读改写拆成多个命令。'], ['Redis 事务', 'MULTI / EXEC 不自动回滚', 'WATCH 提供乐观锁；冲突时 EXEC 取消，需要客户端重试。'], ['Lua 脚本', '多个步骤作为一次原子执行', '脚本执行期间阻塞其他命令，应保持短小、确定且有超时治理。']],
    goals: ['复现 GET 后 SET 的丢失更新和超卖', '解释 WATCH 冲突为何需要客户端重试', '区分流水线、事务与 Lua 的作用'],
    challenge: { task: '保持库存 5、并发 8，依次运行普通 GET/SET、WATCH 事务和 Lua，比较超卖、最终库存与重试次数。', hint: '事务冲突重试是乐观并发控制的成本；Lua 没有网络往返中的竞态。', success: '能优先选择内建原子命令，并在多步条件更新时说明 WATCH 或 Lua 的取舍。', requirements: [{ id: 'get-set', label: '普通 GET/SET · 库存 5 · 并发 8', when: { strategy: 'getSet', clients: 8, stock: 5, demand: 1 } }, { id: 'watch', label: 'WATCH 事务 · 库存 5 · 并发 8', when: { strategy: 'watch', clients: 8, stock: 5, demand: 1 } }, { id: 'lua', label: 'Lua 脚本 · 库存 5 · 并发 8', when: { strategy: 'lua', clients: 8, stock: 5, demand: 1 } }] },
    quiz: [
      quiz('MULTI/EXEC 中某条命令运行时失败，Redis 是否自动回滚此前已执行命令？', ['会完整回滚', '不会自动回滚', '仅 Cluster 会回滚'], 1, 'Redis 事务不提供关系型数据库式回滚；命令错误的处理需区分入队错误与运行时错误。'),
      quiz('Pipeline 的主要作用是什么？', ['减少网络往返，不等同于事务原子性', '保证所有命令回滚', '自动获得分布式锁'], 0, 'Pipeline 批量发送命令以减少 RTT，但本身不保证一批命令不可被其他客户端穿插。'),
    ],
    boundary: '固定重放并发读改写竞态；WATCH 重试次数为教学计数，不代表真实调度。Lua 脚本在模型中总能成功执行，未模拟脚本超时与复制行为。',
    source: 'https://redis.io/docs/latest/develop/using-commands/transactions/',
  }),
  lesson({
    id: 'redis-lock', title: '分布式锁、租约与安全释放', short: '09 · 分布式锁', icon: 'ShieldAlert', tag: '并发正确性', number: 'R09', phase: '并发正确性',
    summary: '观察锁租约早于业务结束时的重叠执行，以及 token、Lua 和看门狗各自解决的问题。',
    defaults: { clients: 3, lease: 3, work: 8, watchdog: false, safeUnlock: true },
    fields: [{ key: 'clients', label: '竞争客户端', min: 1, max: 6, unit: '个' }, { key: 'lease', label: '锁租约', min: 1, max: 10, unit: '秒' }, { key: 'work', label: '业务耗时', min: 1, max: 15, unit: '秒' }, { key: 'watchdog', label: '自动续期', type: 'toggle' }, { key: 'safeUnlock', label: 'token + Lua 解锁', type: 'toggle' }],
    metrics: [['acquired', '成功加锁', ''], ['overlaps', '重叠执行', ''], ['renewals', '续期次数', ''], ['unsafeUnlocks', '误删他人锁', '']],
    nodes: [['client', '竞争客户端', 'Unique token', 'Monitor', 'blue'], ['lock', 'Redis 锁 Key', 'SET NX EX', 'DatabaseZap', 'green'], ['watchdog', '租约续期', 'Extend lease', 'RefreshCw', 'yellow'], ['release', '安全释放', 'Compare + DEL', 'CodeXml', 'pink']],
    edges: [['client', 'lock', 'SET NX EX'], ['lock', 'watchdog', '周期续期'], ['client', 'release', 'Lua 解锁']],
    code: ['String token = UUID.randomUUID().toString();', 'SET lockKey token NX PX leaseMillis', '// renew only while this token still owns the lock', 'if (GET lockKey == token) DEL lockKey  // execute as Lua', '// critical resources may also require fencing tokens'],
    theory: [['原子加锁', 'SET key token NX PX lease', 'NX 防止覆盖，PX 设置租约，token 标识锁的持有者。'], ['安全释放', '比较 token + DEL 必须原子执行', '直接 DEL 可能删除租约过期后由其他客户端取得的锁。'], ['租约边界', '锁 ≠ 业务绝对互斥证明', '进程暂停或续期失败仍可能重叠；关键资源可使用 fencing token。']],
    goals: ['解释为什么 SETNX 后再 EXPIRE 存在问题', '复现租约过期后的重叠执行和误删锁', '区分自动续期、唯一 token 与 fencing token 的作用'],
    challenge: { task: '令业务耗时大于锁租约，先关闭安全解锁和自动续期，再分别打开二者，观察重叠执行与误删指标。', hint: '安全解锁防止误删，但不会阻止租约已经过期造成的重叠执行。', success: '不再把“有 Redis 锁”误认为任何情况下都绝对互斥。', requirements: [{ id: 'unsafe', label: '租约 3s / 任务 8s · 直接 DEL', when: { lease: 3, work: 8, watchdog: false, safeUnlock: false } }, { id: 'safe-release', label: '租约 3s / 任务 8s · token + Lua', when: { lease: 3, work: 8, watchdog: false, safeUnlock: true } }, { id: 'renewed', label: '租约 3s / 任务 8s · 自动续期', when: { lease: 3, work: 8, watchdog: true, safeUnlock: true } }] },
    quiz: [
      quiz('为什么解锁要比较唯一 token 并用 Lua 原子删除？', ['为了压缩 Value', '防止旧持有者删除新持有者的锁', '为了增加 TTL'], 1, '租约可能已过期并被别人重新获得，旧客户端不能直接 DEL。'),
      quiz('自动续期能否彻底消除所有分布式锁正确性风险？', ['能', '不能，仍需考虑暂停、网络故障和 fencing', '仅 Redis Cluster 能'], 1, '看门狗降低租约过短风险，但不是外部资源的绝对互斥证明。'),
    ],
    boundary: '单 Redis 锁教学模型，不实现 Redlock 法定人数、真实时钟漂移、网络分区或进程暂停；看门狗在模型中总能续期成功。',
    source: 'https://redis.io/docs/latest/develop/use/patterns/distributed-locks/',
  }),
  lesson({
    id: 'redis-persistence', title: 'RDB、AOF 与崩溃恢复', short: '10 · 持久化', icon: 'Archive', tag: '可靠性', number: 'R10', phase: '可靠性与运维',
    summary: '在相同写入后制造崩溃，比较 RDB、AOF everysec 与 AOF always 的恢复窗口。',
    defaults: { mode: 'aofEverysec', writes: 11 },
    fields: [{ key: 'mode', label: '持久化模式', type: 'select', options: [['rdb', 'RDB 快照'], ['aofEverysec', 'AOF everysec'], ['aofAlways', 'AOF always']] }, { key: 'writes', label: '确认写入数', min: 5, max: 20, unit: '条' }],
    metrics: [['acknowledged', '已确认写入', ''], ['durable', '已持久化', ''], ['lost', '崩溃丢失', ''], ['fsyncs', '刷盘 / 快照', '次']],
    nodes: [['client', '写请求', 'Acknowledged writes', 'Send', 'blue'], ['memory', 'Redis 内存', 'Dataset', 'DatabaseZap', 'green'], ['disk', '持久化文件', 'RDB / AOF', 'Archive', 'yellow'], ['recover', '重启恢复', 'Load from disk', 'Recycle', 'pink']],
    edges: [['client', 'memory', '执行命令'], ['memory', 'disk', '持久化'], ['disk', 'recover', '加载']],
    code: ['appendonly yes', 'appendfsync everysec  // or always', 'save 60 1000            // RDB trigger example', '// Redis 7 uses multi-part AOF during rewrites', '// validate backups with restore drills'],
    theory: [['RDB', '时间点快照', '文件紧凑、恢复快，但两次快照之间的写入可能丢失。'], ['AOF', '记录写命令并重放', 'everysec 常在性能和约一秒丢失窗口之间折中。'], ['不是备份替代品', '持久化 ≠ 异地备份', '误删和逻辑错误也可能被持久化或复制。']],
    goals: ['解释 RDB 和 AOF 保存的对象不同', '比较 everysec 与 always 的持久性和开销', '理解持久化、复制与备份解决不同问题'],
    challenge: { task: '保持 11 条确认写入，切换三种模式，比较恢复条数、丢失窗口和刷盘次数。', hint: '更小的数据丢失窗口通常需要更频繁的同步。', success: '能根据 RPO、恢复时间和写入开销选择策略。', requirements: [{ id: 'rdb', label: 'RDB · 11 条写入', when: { mode: 'rdb', writes: 11 } }, { id: 'everysec', label: 'AOF everysec · 11 条写入', when: { mode: 'aofEverysec', writes: 11 } }, { id: 'always', label: 'AOF always · 11 条写入', when: { mode: 'aofAlways', writes: 11 } }] },
    quiz: [
      quiz('AOF everysec 的核心折中是什么？', ['可能丢失约一秒写入，减少每次写都 fsync 的开销', '永远不丢数据', '只保存 Key 名'], 0, 'everysec 通常每秒 fsync，在常见配置下可能损失最近约一秒数据。'),
      quiz('启用 RDB 或 AOF 后还需要备份吗？', ['不需要', '需要，持久化不能替代独立备份与恢复演练', '只有 String 需要'], 1, '误操作、逻辑错误、文件损坏和灾难恢复仍依赖独立备份。'),
    ],
    boundary: '每 5 次写入代表 AOF everysec 的一次刷盘窗口，每 6 次代表一次 RDB 快照，仅用于对比；实际丢失窗口按时间与系统行为决定。',
    source: 'https://redis.io/docs/latest/operate/oss_and_stack/management/persistence/',
  }),
  lesson({
    id: 'redis-ha', title: '复制、Sentinel 与 Cluster', short: '11 · 高可用与运维', icon: 'Network', tag: '可靠性', number: 'R11', phase: '可靠性与运维',
    summary: '制造主节点故障，观察异步复制落后、故障转移和未复制写入丢失。',
    defaults: { mode: 'sentinel', replicas: 2, writes: 10, lag: 2 },
    fields: [{ key: 'mode', label: '部署模式', type: 'select', options: [['sentinel', 'Sentinel 主从'], ['cluster', 'Redis Cluster']] }, { key: 'replicas', label: '副本数量', min: 0, max: 3, unit: '个' }, { key: 'writes', label: '主节点写入', min: 4, max: 16, unit: '条' }, { key: 'lag', label: '复制落后', min: 0, max: 4, unit: '条' }],
    metrics: [['writes', '主节点确认', ''], ['replicated', '副本收到', ''], ['lost', '故障丢失', ''], ['available', '服务状态', ''], ['shards', '逻辑分片', '']],
    nodes: [['client', '客户端', 'Topology-aware', 'Monitor', 'blue'], ['primary', '主节点', 'Accept writes', 'DatabaseZap', 'green'], ['replica', '异步副本', 'Replication offset', 'Layers', 'yellow'], ['failover', '故障转移', 'Promote replica', 'Workflow', 'pink']],
    edges: [['client', 'primary', '写请求'], ['primary', 'replica', '异步复制'], ['replica', 'failover', '选举提升']],
    code: ['// Sentinel: monitoring + automatic failover', '// Cluster: 16384 hash slots across primaries', 'WAIT replicas timeout  // improve, not guarantee, replication durability', '// clients must refresh topology after failover', '// test failover and backup restoration separately'],
    theory: [['异步复制', '主节点确认不等于副本已收到', '故障时未复制写入可能丢失。'], ['Sentinel', '单主数据集的监控与故障转移', '提供高可用，不提供水平分片。'], ['Cluster', '16384 hash slots', '通过分片扩展容量，每个分片仍要配置副本以容忍故障。']],
    goals: ['解释主节点确认写入仍可能在故障时丢失', '区分 Sentinel 高可用与 Cluster 分片', '知道客户端必须感知故障转移后的拓扑变化'],
    challenge: { task: '分别设置副本数 0 和 2，再调整复制落后量；比较故障后的服务状态与丢失写入。最后切换 Cluster 观察分片数。', hint: '副本解决可提升节点问题，但异步复制仍存在数据窗口。', success: '能把容量扩展、高可用和零数据丢失三个目标分开讨论。', requirements: [{ id: 'no-replica', label: 'Sentinel · 0 副本 · 落后 2', when: { mode: 'sentinel', replicas: 0, writes: 10, lag: 2 } }, { id: 'replicated', label: 'Sentinel · 2 副本 · 落后 2', when: { mode: 'sentinel', replicas: 2, writes: 10, lag: 2 } }, { id: 'cluster', label: 'Cluster · 2 副本 · 落后 2', when: { mode: 'cluster', replicas: 2, writes: 10, lag: 2 } }] },
    quiz: [
      quiz('Sentinel 与 Redis Cluster 最核心的区别之一是什么？', ['Sentinel 负责单主数据集高可用，Cluster 还提供分片', 'Sentinel 支持 SQL', 'Cluster 不支持副本'], 0, 'Sentinel 不做数据分片；Cluster 把 hash slots 分布到多个主节点。'),
      quiz('主节点已返回写入成功，故障时是否仍可能丢失？', ['不可能', '异步复制未赶上时可能', '只有 Hash 类型可能'], 1, '主节点确认和副本复制是两个进度，故障可能暴露复制落后窗口。'),
    ],
    boundary: '固定一次主节点故障和确定的复制落后量；不模拟 Sentinel 投票、Cluster gossip、slot 迁移、脑裂、WAIT 的真实超时与持久化组合。',
    source: 'https://redis.io/docs/latest/operate/oss_and_stack/management/replication/',
  }),
  lesson({
    id: 'redis-ops', title: '热 Key、大 Key 与线上诊断', short: '12 · 诊断实践', icon: 'Activity', tag: '运维实践', number: 'R12', phase: '可靠性与运维',
    summary: '从访问分布和内存占用两个维度识别热点 Key 与大 Key，并选择低风险处置方式。',
    defaults: { requests: 100, hotRatio: 80, valueKb: 1024 },
    fields: [{ key: 'requests', label: '采样请求数', min: 20, max: 200, step: 20, unit: '次' }, { key: 'hotRatio', label: '单 Key 流量占比', min: 10, max: 100, step: 10, unit: '%' }, { key: 'valueKb', label: 'Value 大小', min: 64, max: 2048, step: 64, unit: 'KB' }],
    metrics: [['hotKeys', '热点 Key', ''], ['bigKeys', '大 Key', ''], ['peakQps', '单 Key 请求', ''], ['valueKb', 'Value 大小', 'KB']],
    nodes: [['traffic', '流量采样', 'Key frequency', 'Activity', 'blue'], ['hotkey', '热点检测', '--hotkeys / metrics', 'Workflow', 'green'], ['memory', '内存测量', 'MEMORY USAGE', 'DatabaseZap', 'yellow'], ['scan', '渐进扫描', 'SCAN / --bigkeys', 'Search', 'pink']],
    edges: [['traffic', 'hotkey', '访问分布'], ['traffic', 'memory', '对象大小'], ['memory', 'scan', '定位处理']],
    code: ['redis-cli --hotkeys', 'MEMORY USAGE payload:1 SAMPLES 5', 'redis-cli --bigkeys', 'SCAN cursor MATCH prefix:* COUNT 100', 'UNLINK large:key  // asynchronous memory reclamation'],
    theory: [['热 Key', '请求集中在少数 Key', '可能打满单分片 CPU、网卡或连接，未必占用很多内存。'], ['大 Key', '单个 Value 占用或元素数量很大', '可能造成传输、删除、持久化和主从同步抖动。'], ['生产诊断', '优先指标与渐进命令', '避免直接 KEYS *、大范围 MONITOR 或同步 DEL 大对象。']],
    goals: ['区分热 Key 与大 Key，避免把二者混为一谈', '选择 MEMORY USAGE、SCAN、--bigkeys 等工具', '理解拆分、局部缓存、读副本和 UNLINK 的适用边界'],
    challenge: { task: '分别制造“热但不大”和“大但不热”的 Key，观察两类问题是否独立出现。', hint: '热度描述访问分布，大小描述对象占用，它们可以独立存在。', success: '能从 CPU/网络、延迟、内存三个方向提出诊断步骤。', requirements: [{ id: 'hot-only', label: '流量 80% · Value 64 KB', when: { hotRatio: 80, valueKb: 64 } }, { id: 'big-only', label: '流量 10% · Value 1024 KB', when: { hotRatio: 10, valueKb: 1024 } }] },
    quiz: [
      quiz('热 Key 和大 Key 是否是同一个概念？', ['是', '不是，访问频率与对象大小是两个维度', '只有 Cluster 中不同'], 1, '一个很小的 Key 也可能极热，一个很大的 Key 也可能很少访问。'),
      quiz('生产环境遍历大量 Key 时更合适的起点是什么？', ['KEYS *', '渐进式 SCAN 与指标采样', 'FLUSHALL'], 1, 'SCAN 是渐进迭代；KEYS * 可能长时间阻塞事件循环。'),
    ],
    boundary: '热点阈值固定为 50%，大 Key 教学阈值固定为 512 KB；真实阈值取决于实例规格、数据类型和延迟目标。redis-cli --hotkeys 依赖 LFU 策略提供的访问频率信息。',
    source: 'https://redis.io/docs/latest/develop/tools/cli/',
  }),
  lesson({
    id: 'redis-capstone', title: '商品缓存综合故障演练', short: '13 · 综合故障演练', icon: 'FlaskConical', tag: '综合实战', number: 'R13', phase: '综合实战',
    summary: '在一条商品详情链路中连续注入穿透、击穿、雪崩与缓存一致性故障。',
    defaults: { missing: 12, concurrent: 24, dbCapacity: 8, bloom: false, rebuild: 'none', jitter: false, safeWrite: false },
    fields: [{ key: 'missing', label: '不存在 Key 请求', min: 0, max: 24, unit: '次' }, { key: 'concurrent', label: '热点并发', min: 4, max: 40, unit: '个' }, { key: 'dbCapacity', label: '数据库容量', min: 4, max: 20, unit: '/秒' }, { key: 'bloom', label: '布隆过滤器', type: 'toggle' }, { key: 'rebuild', label: '热点重建', type: 'select', options: [['none', '无保护'], ['mutex', '互斥重建'], ['logical', '逻辑过期']] }, { key: 'jitter', label: 'TTL 抖动', type: 'toggle' }, { key: 'safeWrite', label: '更新后删除缓存', type: 'toggle' }],
    metrics: [['dbQueries', '数据库查询', ''], ['peakDb', '回源峰值', '/s'], ['stale', '旧值响应', ''], ['risks', '未治理风险', '类']],
    nodes: [['gateway', '商品接口', 'Product detail API', 'Monitor', 'blue'], ['protection', '保护层', 'Filter / rebuild', 'ShieldAlert', 'green'], ['cache', 'Redis 缓存', 'Product cache', 'DatabaseZap', 'yellow'], ['db', '商品数据库', 'Source of truth', 'Database', 'pink']],
    edges: [['gateway', 'protection', '请求治理'], ['protection', 'cache', '缓存访问'], ['cache', 'db', '受控回源']],
    code: ['if (!bloom.mightContain(id)) return NOT_FOUND;', 'Product value = redis.get(cacheKey);', 'if (value == null) value = rebuildWithMutex(id);', 'repository.update(product);', 'redis.delete(cacheKey);', 'long ttl = baseTtl + randomJitter();', '// monitor hit rate, hot keys, latency and DB load'],
    theory: [['风险不是孤立的', '穿透 + 击穿 + 雪崩 + 一致性', '真实故障常由多个薄弱点和重试流量共同放大。'], ['预防与保护', '过滤 / 分散 / 合并 / 限流', '预防降低发生概率，限流与降级在故障时保护容量边界。'], ['观测驱动', '命中率只是一个信号', '还要同时观察热 Key、回源峰值、尾延迟、错误率和数据库负载。']],
    goals: ['把四类缓存风险映射到同一条业务链路', '组合过滤、互斥重建、TTL 抖动与安全写入', '从风险数量、数据库查询和峰值解释治理效果'],
    challenge: { task: '先运行无保护基线，再启用布隆过滤器、互斥重建、TTL 抖动和更新后删除缓存，比较风险与数据库峰值。', hint: '完整保护不会消除所有数据库查询，它控制的是无效查询、并发放大与峰值。', success: '能够说明每个保护措施对应哪类风险，以及它没有解决什么。', requirements: [{ id: 'baseline', label: '无保护基线 · 四项保护关闭', when: { bloom: false, rebuild: 'none', jitter: false, safeWrite: false } }, { id: 'protected', label: '治理方案 · 过滤 + 互斥 + 抖动 + 安全写', when: { bloom: true, rebuild: 'mutex', jitter: true, safeWrite: true } }] },
    quiz: [
      quiz('完整治理后数据库查询为什么不一定变为 0？', ['有效缓存重建和批量到期仍可能需要访问数据源', '因为布隆过滤器失效', '因为 Redis 不支持读取'], 0, '缓存保护减少无效和放大的回源，数据首次加载、更新或正常重建仍需要访问数据源。'),
      quiz('面对缓存整体异常，最合理的观测组合是什么？', ['只看命中率', '只看 Redis 内存', '命中率、回源峰值、尾延迟、错误率和数据库负载'], 2, '单一指标无法区分访问分布、下游过载与请求失败，需要联合观察。'),
    ],
    boundary: '把四种风险依次发生并按确定流量计算，不模拟真实请求重叠、重试、连接池、数据库执行时间或部分故障。完整保护代表教学组合，不是通用生产配置。',
    source: 'https://redis.io/docs/latest/develop/clients/client-side-caching/',
  }),
];
