export const redisDeepDives = {
  redis: {
    question: 'Redis 缓存里没有商品，是不是就说明商品不存在？',
    scenario: '商品详情页读取 product:1。第一次 GET 返回 nil，应用读取数据库后把商品写入 Redis。随后数据库价格更新，缓存仍可能保存旧值。',
    chain: [
      ['先区分不存在与空内容', 'GET 返回 nil 只说明这个 Key 此刻不在缓存中。空字符串是一个真实存在的值，应在 Java 中使用 null 判断而不是 isEmpty 判断命中。'],
      ['把回源职责放在应用', 'Cache-Aside 没有 Redis 到 MySQL 的自动通道。应用负责查库、处理查无记录、回填缓存及失败策略。实验中的 SET 代表这次显式回填。'],
      ['缓存与数据库分别提交', '数据库提交与缓存失效不是一个原子事务。更新后删缓存是常见做法，但删除失败需要重试、消息或 CDC 等补偿机制。'],
    ],
    headers: ['看到的现象', '可以判断', '不能推断'],
    rows: [['GET → nil', 'Key 不存在', '数据库也没有记录'], ['GET → ""', 'Key 存在且值为空串', '这是缓存未命中'], ['SET → OK', '本次缓存写入被接受', '数据库提交成功或数据已落盘']],
    misconception: '“只要提高命中率，系统就更可靠”不成立。高命中率可能伴随长时间的脏缓存，应同时观察正确性、过期策略和回源失败。',
    transfer: '商品下架后，数据库已提交但 DEL 失败。你如何发现问题、补偿删除，并避免重试时错误覆盖新商品信息？',
    answer: '记录失效失败并做有界重试；重要链路可用事务 outbox 或 CDC 驱动失效。数据源保持权威，缓存用 TTL 限制陈旧时间。这个设计仍是最终一致，应明确允许的旧读窗口。',
    links: [['GET 返回语义', 'https://redis.io/docs/latest/commands/get/'], ['SET 选项', 'https://redis.io/docs/latest/commands/set/']],
  },
  'redis-types': {
    question: 'HSET 返回 0，为什么数据反而更新成功了？',
    scenario: '用户昵称需要局部更新，消息队列需要保留重复和顺序，标签要去重，榜单则按分值排序。选型必须从读写方式出发。',
    chain: [
      ['先选语义，再选命令', 'String 适合整体值；Hash 支持字段级更新；List 表达有序重复序列；Set 表达唯一成员；Sorted Set 增加分值排序。五种类型不能用同一套返回值规则判断。'],
      ['整数常表示计数，而非布尔成功', 'HSET 的 1/0 表示新增字段数，ZADD 默认表示新增成员数，RPUSH 表示最终长度，SADD 表示新增成员数。返回 0 可能是成功更新或没有新增。'],
      ['逻辑类型与内部编码分层', 'TYPE 返回 string、hash 等逻辑类型。具体编码随 Redis 版本、配置、值大小和元素数量变化，不能把 Hash 永远等同于哈希表。'],
    ],
    headers: ['需求', '优先考虑', '需要注意'],
    rows: [['用户资料局部更新', 'Hash', '字段更新返回新增数'], ['简单有序队列', 'List', '不自动提供可靠消费确认'], ['唯一标签集合', 'Set', '读取顺序不保证'], ['排行榜', 'Sorted Set', 'member 唯一，score 可更新'], ['整体 JSON 快照', 'String', '局部更新通常需重写整个值']],
    misconception: '“命令返回 0 就失败了”不成立。先读命令的返回语义，再检查实际数据；业务成功判定不能只看真假值。',
    transfer: '同一个榜单用户从 98 分升到 99 分，如何证明没有新增第二个用户，同时证明分数已改变？',
    answer: 'ZADD rank 99 alice 默认返回 0，说明未新增 member；ZRANGE rank 0 -1 WITHSCORES 返回唯一 alice 及 99 才证明更新结果。不能仅依赖 ZADD 的 0。',
    links: [['HSET', 'https://redis.io/docs/latest/commands/hset/'], ['ZADD', 'https://redis.io/docs/latest/commands/zadd/'], ['Redis 数据类型', 'https://redis.io/docs/latest/develop/data-types/']],
  },
  'redis-expiry': {
    question: '缓存写入时设置过 TTL，为什么更新一次后却永不过期了？',
    scenario: '登录态写入后有效期 120 秒。随后使用普通 SET 更新内容，却发现 TTL 返回 -1。另一条记录到期后 TTL 则返回 -2。',
    chain: [
      ['TTL 是 Key 的属性', 'EXPIRE 为已有 Key 设置截止时间。TTL 的正数单位为秒，PTTL 为毫秒；-1 表示无过期时间，-2 表示不存在。TTL=0 仍可能是即将到期的 Key。'],
      ['覆盖值与修改值的行为不同', '普通 SET 覆盖时清除原 TTL；SET KEEPTTL 可保留，SET EX/PX 可同时重新设定。INCR、HSET 等修改现有值的命令通常保留 Key 级 TTL，具体以命令文档为准。'],
      ['过期和淘汰是两回事', '过期按截止时间让数据失效；淘汰在内存压力下根据策略选择键。Redis 结合访问时检查和周期主动过期，不保证所有到期内存在同一瞬间释放。'],
    ],
    headers: ['返回或行为', '含义', '应用应如何处理'],
    rows: [['TTL = -2', 'Key 不存在', '视为未命中'], ['TTL = -1', 'Key 没有过期时间', '核对是否有意永久缓存'], ['TTL = 0', '即将过期', '不能据此认为已删除'], ['SET 后 TTL = -1', '原 TTL 被清除', '显式指定 EX/PX 或 KEEPTTL']],
    misconception: '“过期后一定立刻释放内存”不成立。读取语义上的不存在和后台实际释放时机不同。不要根据一次 TTL 推断内存回收性能。',
    transfer: '把 SET 和 EXPIRE 分成两次网络调用，进程在中间崩溃，会留下什么状态？如何避免？',
    answer: 'SET 成功但 EXPIRE 未执行，Key 可能永久保留。用 SET key value EX seconds 把值与过期时间放在同一个原子命令内。它解决这个窗口，但不自动解决数据库与缓存的一致性。',
    links: [['TTL', 'https://redis.io/docs/latest/commands/ttl/'], ['EXPIRE', 'https://redis.io/docs/latest/commands/expire/'], ['SET 的 KEEPTTL', 'https://redis.io/docs/latest/commands/set/']],
  },
  'redis-atomic': {
    question: 'DECR 是原子操作，为什么秒杀库存仍会变成负数？',
    scenario: '库存初始为 2。连续三次 DECR 返回 1、0、-1。没有一次写入丢失，业务却已经接受了超出库存的扣减。',
    chain: [
      ['原子性保证一个操作不可被穿插', 'Redis 执行单条 DECR 时不会让另一条命令插入它的读取与写回中。但 DECR 的规则只有减一，不包含“库存必须大于零”。'],
      ['业务不变量需要原子条件更新', '先 GET 判断再 DECR 是两条命令，其他客户端可在中间改变库存。使用 WATCH 检测版本变化并重试，或短 Lua 脚本把检查与扣减合为一次执行。'],
      ['原子性不能替代幂等与持久性', '超时后客户端不知道扣减是否成功，盲目重试可能重复扣减。订单 ID 幂等、防重复请求、持久化和后续数据库提交仍需单独设计。'],
    ],
    headers: ['方式', '解决什么', '没有自动解决'],
    rows: [['DECR', '单次减一原子执行', '不能扣为负数的业务条件'], ['Pipeline', '减少网络往返', '多步原子性和回滚'], ['WATCH + MULTI/EXEC', '检测竞争修改后取消提交', '客户端重试、运行时回滚'], ['短 Lua 脚本', '检查和修改原子执行', '跨系统事务、请求幂等']],
    misconception: '“Redis 事务等同于数据库事务”不成立。MULTI/EXEC 不提供关系型数据库式的运行时错误回滚，使用前要区分排队错误和执行错误。',
    transfer: '服务调用扣减命令后超时，没有收到响应。能否直接再执行一次 DECR？为什么？',
    answer: '不能仅凭超时认定未执行。应以唯一业务请求 ID 记录处理结果，在原子逻辑内去重，再返回既有结果；同时设计 Redis 与订单数据库之间的补偿和对账。',
    links: [['DECR', 'https://redis.io/docs/latest/commands/decr/'], ['事务语义', 'https://redis.io/docs/latest/develop/using-commands/transactions/'], ['脚本原子性', 'https://redis.io/docs/latest/develop/programmability/eval-intro/']],
  },
};
